### ISSUE TITLE
CML : unload cml_rt1011_rt5682 results in reboot

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#1425] opened 2019-11-01 23:49 UTC
This issue we discovered during stress testing loading and unloading of machine driver for some other issue debug.

I checked with CML_007_drop_stable release and see 1 change was missing in the machine driver:
ASoC: intel: sof_rt5682: add remove function to disable jack.

I made same change to the cml_rt1011_rt5682 machine driver and see that the unload is still an issue.

Any other changes required ?

**Comment by keyonjie** [comment] 2019-11-01 23:55
we might need dmesg log for the issue.

**Comment by ranj063** [comment] 2019-11-02 02:45
@sathyap-chrome can you please try with this suggestion from @plbossart https://github.com/thesofproject/linux/issues/1424#issuecomment-548963773

**Comment by sathyap-chrome** [comment] 2019-11-02 05:51
Sure. will try and let u know

**Comment by plbossart** [comment] 2019-11-05 01:51
see PR #1431

**Comment by sathyap-chrome** [comment] 2019-11-05 01:57
thanks @plbossart . Since we are on v4.19 there are some dependencies to pick this change, i'm checking and revert back once i try.

**Comment by plbossart** [comment] 2019-11-05 01:58
@sathyap-chrome what prevents you from testing with the mainline kernel first?

**Comment by sathyap-chrome** [comment] 2019-11-05 02:00
i will do that as well.
We are actually helping stress test team with a script to load / unload for checking a stress test failure on i2c.  Since that team will look to stay with chrome kernel, i was trying to get it working on v4.19

I should be able to test on mainline by tomorrow.

**Comment by aiChaoSONG** [comment] 2019-11-18 06:22
tried module reload stress test with keyword_detect + cml-007-drop-stable, not reproduced this issue, but see "page fault"

**Comment by sathyap-chrome** [comment] 2019-11-18 06:30
Can you share dmesg ?

**Comment by aiChaoSONG** [comment] 2019-11-18 06:43
@sathyap-chrome This is a very early bug exist on keyword_detect branch, please refer to https://github.com/thesofproject/linux/issues/1106,  this may help to resolve #1425.

Can you try backport PR#1147 to Chrome kernel and see if it can fix this issue?

**Comment by aiChaoSONG** [comment] 2019-11-20 07:39
@mengdonglin @sathyap-chrome @keyonjie 
I have reproduced this issue on ChromeOS, and I have done some investigations to root cause this issue:
- I tried sof-dev+master on two Chromebooks with Ubuntu OS, neither reproduced this issue.
- I tried keyword_detect + 007 branch, neither reproduced this issue, but saw #1106

our kernel branch has no such a module named cml_rt1011_rt5682, I think that's the reason we can't reproduce the issue on Ubuntu.

Therefore, I compiled Chrome's kernel with our kconfig, and install it on ubuntu,  and do module unload, the machine not reboot, but I saw "Kernel NULL pointer" as in #1106.

So, I guess Chrome OS may has some fallback mechanism, which will force HW reset or reboot once kernel oops/panic/warning happened. Before we continue, I think chrome team need to port the patch(#1147) for #1106 to chrome kernel.

@sathyap-chrome BTW, I saw snd_soc_skl in chrome kernel with `lsmod`, which was considered deprecated, please blacklist this module, or i am wrong?

**Comment by sathyap-chrome** [comment] 2019-11-20 16:42
@aiChaoSONG  Thanks for analysis. we  can close this and i can get back for any issue once i pull on the fixes mentioned.

**Comment by aiChaoSONG** [comment] 2019-11-22 03:12
any further issue please submit a new issue, let close this for now

**Closed as completed by aiChaoSONG** 2019-11-22 03:12 UTC
Labels: bug, P1, CML
