### ISSUE TITLE
Random hangs on Coffeelake/ThinkCentre M920t

### ISSUE THREAD

**Issue by CendioOssman** [thesofproject/linux#2066] opened 2020-04-29 08:20 UTC
We're experiencing random hangs on several identical ThinkCenter M920t here running Fedora 31. Originally reported to Red Hat here with lots of details:

https://bugzilla.redhat.com/show_bug.cgi?id=1817368

If we revert to the old driver (using `options snd-intel-dspcfg dsp_driver=1`) then the hangs go away, so we're fairly sure the new driver is to blame.

**Comment by ranj063** [comment] 2020-04-29 16:07
@CendioOssman I'm going through the logs but one of the errors pointed out: "Mar 26 09:56:01 aleta kernel: sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0" has been solved with.
"8354d9b44530b ("ASoC: SOF: Intel: hda-loader: clear the IPC ack bit 
after FW_PURGE done")

This was harmless in the first place and should not cause system hangs

**Comment by ranj063** [comment] 2020-04-29 16:09
"Jan 15 11:16:45 ossman.lkpg.cendio.se kernel: sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2"

This error suggests that the firmware file is missing. The sof-cfl.ri file should be in the /lib/firmware/intel directory

**Comment by plbossart** [comment] 2020-04-29 16:14
> "Jan 15 11:16:45 ossman.lkpg.cendio.se kernel: sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2"
> 
> This error suggests that the firmware file is missing. The sof-cfl.ri file should be in the /lib/firmware/intel directory

The sof-cfl.ri file should be in the /lib/firmware/intel/sof directory

**Comment by CendioOssman** [comment] 2020-05-01 10:07
> This was harmless in the first place and should not cause system hangs

That's a shame as that is the only message we reliably find in the logs. :/

> This error suggests that the firmware file is missing. The sof-cfl.ri file should be in the /lib/firmware/intel directory

That error is very old and was simply because the alsa-firmware package wasn't installed. At that point there were no hangs, but also no audio.

**Comment by plbossart** [comment] 2020-05-01 12:49
@CendioOssman there are known issues with hangs that should hopefully be gone with the 1.4.3  and 1.5 release - likely next week.

**Comment by CendioOssman** [comment] 2020-05-04 10:44
That's good news. :)

Is this just new firmware or does the kernel also need changes? I'm wondering if we can fix this by just adding those firmware files to our system with the standard Fedora kernel.

**Comment by plbossart** [comment] 2020-05-04 15:31
Usually @perexg takes the releases and adds them to Fedora, so you should see this without delay.
For other distros it's an uphill battle to find someone who can help package those binaries in the various packages formats.

**Comment by kv2019i** [comment] 2020-05-13 10:49
v1.5 firmware is now available for testing:
https://github.com/thesofproject/sof-bin/tree/stable-v1.5

**Comment by plbossart** [comment] 2020-05-27 16:52
@CendioOssman all hangs seem to be fixed with v1.5, can you give it a try?

**Comment by perexg** [comment] 2020-05-27 16:55
I am not able to update the Fedora SOF firmware package because I found a serious regression in v1.5 - https://github.com/thesofproject/sof/issues/2937 .

**Comment by plbossart** [comment] 2020-05-27 17:13
> I am not able to update the Fedora SOF firmware package because I found a serious regression in v1.5 - [thesofproject/sof#2937](https://github.com/thesofproject/sof/issues/2937) .

we should probably split firmware and topology packages then...@lgirdwood FYI.

**Comment by perexg** [comment] 2020-05-27 18:54
I don't think that the split is required. They all depend on each other. Just release the updated files ASAP so we can prepare packages for distros.

**Comment by kv2019i** [comment] 2020-06-03 13:02
@CendioOssman @perexg This issue is also fixed in 1.4.3: 
https://github.com/thesofproject/sof-bin/tree/stable-v1.4.3/lib/firmware/intel/sof/v1.4.3

1.5 release also has a fix, but as @perexg commented above, there's another regression and we need to wait until 1.5.1 release (pending still).

**Comment by perexg** [comment] 2020-06-03 13:14
I already released v1.5 for Fedora. It contains updated topology files - the DMIC control name fix plus the DMIC 20dB equalizer fix for the HDA platforms. I have first reports that the driver / DSP is more stable now. But anyway, it would be nice to have 1.5.1, so we (package maintainers) are not forced to do this dancing ;-)

**Comment by juimonen** [comment] 2020-06-03 13:30
@perexg 1.5.1 should be on its way to signing this week, tests looks ok so far. Apologies still for this, as said the dmic automatic testing is difficult all the way up to user space, we've taken measures for this not to happen again...

**Comment by kv2019i** [comment] 2020-06-03 14:29
Thanks @perexg (again)!

@CendioOssman Are you able to verify this?

**Comment by CendioOssman** [comment] 2020-06-04 07:34
Yes, with the updated Fedora package we are no longer seeing hangs here.

**Comment by kv2019i** [comment] 2020-06-04 13:43
Thanks @CendioOssman , closing!

**Closed as completed by kv2019i** 2020-06-04 13:43 UTC
Labels: bug, HDA
