### ISSUE TITLE
runtime suspend/resume doesn't work when no hdmi pipelines defined in tplg file(with idisp BEs defined in machine driver).

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#234] opened 2018-10-31 09:20 UTC
it can't enter suspend as hdmi codec driver is always waiting for hdmi codec probing.

**Comment by plbossart** [comment] 2018-10-31 22:41
@keyonjie thanks for report. Can you please add more details so that people can reproduce your finding?

**Comment by plbossart** [comment] 2019-03-24 18:30
@keyonjie this issue has not been updated since October 31, 2018, there is no description of the issue. Should it be closed or is this still open?

**Comment by stripes416** [comment] 2019-04-10 23:16
@keyonjie I've tested this on my up2 board to see if this is still an issue (per @ranj063 recommendations) I'm not seeing the issue you mentioned, but full disclosure, I couldn't replicate the issue as described either.

I tested sof-apl-pcm512x.tplg from latest topic/sof-dev built with and without HDA.

I've included two files - each containing data from one of the runs:
dmesg logs + the output from `'cat /proc/asound/pcm'` + the output of alias
pcm_status="`cat /sys/bus/pci/devices/0000\:00\:0e.0/power/runtime_status`"

[pcm_dmesg_with-HDA.txt](https://github.com/thesofproject/linux/files/3066218/pcm_dmesg_with-HDA.txt)
[pcm_dmesg_no-HDA.txt](https://github.com/thesofproject/linux/files/3066219/pcm_dmesg_no-HDA.txt)

**Comment by keyonjie** [comment] 2019-04-11 10:38
@stripes416 @zhuyingjiang the issue happened at when there is no hdmi/idisp pcm defined in tplg file, it was firstly found by @bardliao iirc, Bard and Libin did some work on that, I am not sure if it is already fixed in the latest code base, Can you comment out these in sof-apl-pcm512.m4 and retry if you can enter suspend?

```
# Low Latency playback pipeline 2 on PCM 1 using max 2 channels of s32le.
# Schedule 48 frames per 1000us deadline on core 0 with priority 0
PIPELINE_PCM_ADD(sof/pipe-volume-playback.m4,
        2, 1, 2, s32le,
        48, 1000, 0, 0)

# Low Latency playback pipeline 3 on PCM 2 using max 2 channels of s32le.
# Schedule 48 frames per 1000us deadline on core 0 with priority 0
PIPELINE_PCM_ADD(sof/pipe-volume-playback.m4,
        3, 2, 2, s32le,
        48, 1000, 0, 0)

# Low Latency playback pipeline 4 on PCM 3 using max 2 channels of s32le.
# Schedule 48 frames per 1000us deadline on core 0 with priority 0
PIPELINE_PCM_ADD(sof/pipe-volume-playback.m4,
        4, 3, 2, s32le,
        48, 1000, 0, 0)

```

**Comment by zhuyingjiang** [comment] 2019-04-11 11:12
I verified on Up2 with sof-apl-pcm512x-nohdmi.tplg, the Up2 can normally do suspend/resume. So we can close this issue.

**Closed as completed by zhuyingjiang** 2019-04-11 11:12 UTC
Labels: enhancement

**Comment by keyonjie** [comment] 2019-04-11 11:14
good, thanks @zhuyingjiang and @stripes416

**Comment by stripes416** [comment] 2019-04-11 17:35
@zhuyingjiang & @keyonjie Thanks!
