### ISSUE TITLE
[BUG] No update in sound-setting upon headset hotplug after long time idle

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#909] opened 2019-05-07 06:22 UTC
**Describe the bug**
Sound setting will always no update when Plug in/out headset after boot up/long time idle,  however status can update as soon as music is played.  

**To Reproduce**
1. Reboot system. 
2. Open sound setting of laptop
3. Plug in headset, then plug out, check.

**Expected behavior**
Status in sound setting should update as soon as plugged in/out

**Actual result**
Status won't update until music is play.
More info: 
Headset plug status is also not update in amixer when error reproduce
```
test@test-Inspiron-5490:~$ amixer cget numid=34,iface=CARD,name='Headphone Mic Jack'
numid=34,iface=CARD,name='Headphone Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```

**Environment**
platform: CML laptop with ALC3204 codec
Rander UCM https://github.com/RanderWang/intel-UCM   
Kernel repo：c99938c https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Firmware repo: 47fcac2  https://github.com/thesofproject/sof/commits/master |  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

[plug2sDelay_dmesg.log](https://github.com/thesofproject/linux/files/3151064/plug2sDelay_dmesg.log)
[plug2sdelay_logger.log](https://github.com/thesofproject/linux/files/3151065/plug2sdelay_logger.log)

**Comment by RanderWang** [comment] 2019-05-07 07:05
In this case, codec driver doesn't update jack status. Please dispatch it to codec vendor for help.

**Comment by wenqingfu** [comment] 2019-05-08 02:48
likely a jack update bug from codec driver. @mengdonglin to follow up

**Comment by mengdonglin** [comment] 2019-05-09 02:21
I will request Realtek to fix this codec issue on jack detection failure.

**Comment by KailangYang** [comment] 2019-05-10 11:09
@bardliao 
Could I test it on legacy HDA driver?

@mengdonglin 
Could Hui Wang join this github?

**Comment by bardliao** [comment] 2019-05-13 01:06
@kailangyang I don't see the issue on my laptop with ALC3254 codec. Neither SOF driver nor legacy HDA driver. @ClarexZhou Could you check it on your laptop with legacy HDA driver?
Please run ``echo 1 > /sys/module/snd_hda_intel/parameters/power_save`` as root before testing.

**Comment by KailangYang** [comment] 2019-05-16 12:34
@bardliao @mengdonglin 
I test it with Mantis(ALC3204) with Canonical OS with SOF. This issue will be reproduce.
But I test it under legacy HDA driver. It's not has this issue.
I think SOF was fail on handle unsolicited event.

**Comment by KailangYang** [comment] 2019-05-17 05:45
@ClarexZhou 
Hi,
You post a wrong message. below was the Headphone Mic Jack. It's not Headset Mic Jack.

test@test-Inspiron-5490:~$ amixer cget numid=34,iface=CARD,name='Headphone Mic Jack'
numid=34,iface=CARD,name='Headphone Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off

**Comment by ClarexZhou** [comment] 2019-05-17 05:50
@kailangyang ,Only one phantom jack for headset.  numid=35,iface=CARD,name='Headset Mic Phantom Jack'.
Now UCM is using 'Headphone Mic Jack' for headset detection.
@RanderWang please comment more details once needed.

**Comment by ClarexZhou** [comment] 2019-05-17 06:38
Error still seen with Realtek commit ALSA: hda/realtek - Check headset type by unplug and resume https://github.com/thesofproject/linux/commit/df06e42c0153e720ef413e42ba12e8f58e71e358 

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM/tree/hdmi
Kernel repo: df06e42 https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: b73b9a6 https://github.com/thesofproject/sof/commits/debug-ipc-timeout
Topology: https://github.com/thesofproject/sof/commits/debug-ipc-timeout. Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg
platform: CML laptop with ALC3204 codec

**Comment by KailangYang** [comment] 2019-05-17 06:56
@ClarexZhou , Why?

Headphone MIC was comon link to headphone. So, we call that Headphone MIC.
It's the pure Mic for 3 ring jack.
The headset was include Mic. It had headphone and headset Mic for 4 ring jack.
So, "UCM is using 'Headphone Mic Jack' for headset detection" is wrong.

**Comment by RanderWang** [comment] 2019-05-17 07:21
@kailangyang  Do you remember I sent a email to you about this issue. This is our discussion

````
I sent:
We get an issue on a xxx notebook. Pulse audio needs to detect Headset Mic by Jack for it.
But we find there is only “Headset Mic Phantom Jack”.  On our platform with ALC700, there is “Mic Jack”
For microphone and it will change when mic inserted or not. Could you help to debug this issue ?

your reply:
xxx was use Headset mode in driver. (This was xxx request us)
It will integrate with pulse audio. If you plug headset or headphone or pure MIC,
It will pop a menu icon for you to select what device is.
This was not a bug.
````

**Comment by KailangYang** [comment] 2019-05-17 07:54
@RanderWang @mengdonglin 

I just check “Headset Mic Phantom Jack” in Dell platform vs  “Mic Jack” in your platform.
That difference is one use software headset mode and yours use codec auto headset mode.
So, I reply you the difference. Maybe I don't understand what you mean.

**Comment by RanderWang** [comment] 2019-05-17 08:05
@kailangyang  thanks, I got your idea. I didn't want to query "Headphone Mic Jack" for Headset Mic, but
this is a workaround for gnome-settings-daemon and gnome-control-center issue

**Comment by KailangYang** [comment] 2019-05-17 08:08
How to test easily?
Modify /etc/modprobe.d/alsa-base.conf ....
add  below to the end line.
options snd-hda-codec-realtek dyndbg

You could check dmesg for headset plug and unplug message.

**Comment by KailangYang** [comment] 2019-05-17 08:14
@RanderWang 
What do you want to do?
Plug headset ... show pop menu. Right?

**Comment by KailangYang** [comment] 2019-05-20 07:41
@jason77-wang
Could you help to test this issue for legacy HDA driver on Mantis?
I add option as below.

Modify /etc/modprobe.d/alsa-base.conf
add below to the end line.
options snd-hda-codec-realtek dyndbg

You could check dmesg for headset plug and unplug message.

**Comment by jason77-wang** [comment] 2019-05-20 10:40
I can firm that this issue doesn't happen on legacy hda driver,
This issue can happen on sof driver.  Just like Kailang mentioned earlier, looks like the sof driver interrupt doesn't handle the jack plug/unplug unsol event.

**Comment by bardliao** [comment] 2019-05-21 12:35
@RanderWang @ClarexZhou Could you test with [sof-skl_hda_card.zip](https://github.com/thesofproject/linux/files/3202493/sof-skl_hda_card.zip) ucm file?
I can see the issue with https://github.com/RanderWang/intel-UCM/tree/hdmi, but don't see it with the attached ucm file

**Comment by YvonneYang2** [comment] 2019-05-22 05:01
Test with sof-skl_hda_card.zip ucm files, issue not reproduced whether boot up or idle long time.

**Test recipe**
Firmware: 5fa2426 https://github.com/thesofproject/sof/tree/master
Kernel: b58f448 https://github.com/thesofproject/linux/tree/release/sof-v5.0
Topology: file: tools/topology/sof-hda-generic.tplg, sof-hda-generic-2ch.tplg same as firmware
Kconfig: https://sof-ci-storage.sh.intel.com/daily/20190521/release/linux/topic/sof-dev/901cd2a5-2/config-daily-hda-20190521.txt
platform ：CML laptop

**Comment by RanderWang** [comment] 2019-05-23 05:24
Debug sof code and checked all the power setting in sof. I didn't found any hint. Now try to debug hda library.

**Comment by RanderWang** [comment] 2019-05-23 09:42
I debugged the legacy hda and found hda controller didn't suspend on my device, but hda codec did suspend. If hda controller doesn't suspend, all the resource will not be released, so headphone jack works.
Now I have to make it suspend to debug.

**Comment by RanderWang** [comment] 2019-05-24 09:56
Found resume function in legacy hda is invoked by acpi, but how to ?
And we need to implement runtime pm for hdac_hda.c, now we miss this for jack detection.
I also talked with kernel team about pm, but only found they can't help us for they didn't know more than us. So we have to fix it by our own

**Comment by plbossart** [comment] 2019-05-24 13:41
On 5/24/19 4:56 AM, RanderWang wrote:
> Found resume function in legacy hda is invoked by acpi, but how to ?
> And we need to implement runtime pm for hdac_hda.c, now we miss this for 
> jack detection.
> I also talked with kernel team about pm, but only found they can't help 
> us for they didn't know more than us. So we have to fix it by our own

Can we please try to have subject lines shorter than a line? How can you 
possibly expect people to care about such issues if you can't sum-up things?

**Comment by RanderWang** [comment] 2019-05-25 01:02
yes， I find it：https://github.com/torvalds/linux/commit/7d4f606c50ffaaa3ac60b7faf770dc6e84af3207
ALSA: hda - WAKEEN feature enabling for runtime pm

**Comment by RanderWang** [comment] 2019-05-25 01:31
> On 5/24/19 4:56 AM, RanderWang wrote:
>  Found resume function in legacy hda is invoked by acpi, but how to ?
>  And we need to implement runtime pm for hdac_hda.c, now we miss this for
>  jack detection.
>  I also talked with kernel team about pm, but only found they can't help
>  us for they didn't know more than us. So we have to fix it by our own
> Can we please try to have subject lines shorter than a line? How can you
> possibly expect people to care about such issues if you can't sum-up things?

Thanks Pierre.  In Chinese , I talked with kernel team smoothly. But In English, I may make thing in mess.
I need to study from Pierre and I often heared someone in china team said Pierre introduced a new word in a email.

**Comment by YvonneYang2** [comment] 2019-05-28 11:15
**Issue not reproduced after long time idle with scenario below**:

1. Make sure no headset is connected and sound setting is closed.
2. Idle 5 mins
3. Hot plug headset, then open sound setting to check.(result: headset hotplug status will update)

**Issue still reproduced with the scenario below**:

1. Make sure no headset is connected and sound setting is open.
2. Idle 5 mins
3. Hot plug headset and check the sound setting headset status.(result:headset hotplug status will not update)

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM/commits/hdmi
Firmware: c916fd7 https://github.com/bardliao/sof/tree/dell-test
Kernel: 0e0111f4 https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Topology: file: tools/topology/sof-hda-generic.tplg, sof-hda-generic-2ch.tplg same as firmware
platform ：CML laptop

**Comment by RanderWang** [comment] 2019-05-29 10:15
yes,  I have an idea suggested by keyon to fix this issue now.
But Kai wants to keep codec active when SOF is active and this idea also could fix this issue.

**Comment by ranj063** [comment] 2019-06-06 05:37
@ClarexZhou @mengdonglin 
I have just recently pushed a new PR to fix the IPC timeouts issues with MSI. This combined with Rander's PR #983, the canonical patch for jack detection in S3 and reverted commit to switch to legacy IRQ fixes this issue for me.
My branch https://github.com/ranj063/linux/tree/release/5.0 has all the above changes. Can you please verify if this works?

**Comment by libinyang** [comment] 2019-06-06 06:02
@ranj063 
I made a patchset just now: https://github.com/libinyang/linux/tree/v5.0-ipc_timeout_2, which works on my machine. I have test my patchset for about one hour. The patchset is a little similar with yours :)

**Comment by ClarexZhou** [comment] 2019-06-06 09:32
@ranj063 
Run stress test on https://github.com/ranj063/linux/tree/release/5.0.

No ipc timed out occurred. 

Only reproduce system response very slow issue during playback (aplay –d 1) stress test: Response very slow from 709th time. Then headset selection query pops up. But no ipc timed out. After that it always take several minutes for  aplay –d 1  

[aplayResponseslow_709_dmesg.log](https://github.com/thesofproject/linux/files/3260938/aplayResponseslow_709_dmesg.log)
[aplayResponseslow_709_soflogger.log](https://github.com/thesofproject/linux/files/3260939/aplayResponseslow_709_soflogger.log)

**Comment by ClarexZhou** [comment] 2019-06-12 10:07
Reopen for original issue isn't fully fixed #983 ,still waiting other PRs.
@RanderWang please add all PRs

**Comment by RanderWang** [comment] 2019-06-14 05:18
only https://github.com/thesofproject/linux/pull/1003 is not merged

**Comment by YvonneYang2** [comment] 2019-06-17 02:52
Issue not reproduced though #1003 is now merged by https://github.com/thesofproject/linux/tree/release/sof-v5.0. So close the bug.

**Closed as completed by YvonneYang2** 2019-06-17 02:52 UTC
Labels: bug, won't fix, CML, HDA, codec

**Comment by Hao-Sheng** [comment] 2019-06-19 09:36
[dmesg.log](https://github.com/thesofproject/linux/files/3305429/dmesg.log)
Found external mic cannot record sound
