### ISSUE TITLE
[HDA] Pop noise when starting/stopping HDA analog playback

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#1331] opened 2019-10-17 09:11 UTC
***Describe the bug***
This issue happens when starting/stopping playback, this is more like a codec driver issue. 

***To reproduce***
1. aplay -Dhw:0,0 -f dat -c 2 test.wav

***Expected behavior***
no pop noise when starting/stopping playback.

***Impact***
Pop noise

***Test env***
Firmware: c8bc4b2 https://github.com/thesofproject/sof/commits/tgl-002-drop-stable
Kernel: intel-next kernel, tag intel-5.4-rc2-2019-10-10, commit id: fc2de5669533
tplg: sof-hda-generic.m4
platform: TGL RVP with onboard ALC711 in HD-A mode. Connected an external monitor via microHDMI port.

I will try to capture the pop noise next.

**Comment by plbossart** [comment] 2019-10-17 15:12
@keqiaozhang again why are we using intel-next instead of topic/sof-dev? You should be able to test HDaudio functionality without other dependencies we don't care about.

**Comment by keqiaozhang** [comment] 2019-10-18 06:44
@plbossart 
i915 is not ready on sof-dev, but we need to test HDMI for TGL, so we chose intel-next for the release branch.

**Comment by plbossart** [comment] 2019-10-18 11:30
On 10/18/19 1:44 AM, Keqiao Zhang wrote:
> @plbossart <https://github.com/plbossart>
> i915 is not ready on sof-dev, but we need to test HDMI for TGL, so we 
> chose intel-next for the release branch.

If you report a bug on HDaudio, you should be testing with topic/sof-dev.

**Comment by sinahuang** [comment] 2019-11-05 03:31
This issue can be reproduced with kernel sof-dev on CML-S RVP with onboard ALC711 in HDA mode..

Test recipe:

Kernel: https://github.com/thesofproject/linux/commits/topic/sof-dev commit: 4e76b4a1
FW: https://github.com/thesofproject/sof/commits/master commit: 0e8cf66
Tplg: master e5fe2ca sof-hda-generic-4ch.tplg
Platform: CML-S RVP with onboard ALC711 in HDA mode.

**Comment by mengdonglin** [comment] 2019-11-07 03:18
@xiulipan It seems to be ALC711 specific. Can you please involve Realtek to check?

**Comment by xiulipan** [comment] 2019-11-07 04:30
@ClarexZhou @sinahuang Could you try:
-  legacy HDA to check if this is codec specific
-  to use some external sound card to record some pop-noise?

**Comment by sinahuang** [comment] 2019-11-07 08:18
> @ClarexZhou @sinahuang Could you try:
> 
> * legacy HDA to check if this is codec specific

Check on legacy HDA, issue can't be reproduced.
Test on CML laptop with codec ALC3204 in HDA mode, issue can't be reproduced 
Test on CFL-S RVP with codec ALC700 in HDA mode, issue can't be reproduced.

> * to use some external sound card to record some pop-noise?

Pop noise wav files as below:
[POP wav files.zip](https://github.com/thesofproject/linux/files/3818473/POP.wav.files.zip)

 External sound card to record display as below:
Pop noise at starting:
<img width="576" alt="pop1" src="https://user-images.githubusercontent.com/56706782/68371181-1dbfc880-0179-11ea-84a5-73aa658b96d3.png">
<img width="576" alt="333" src="https://user-images.githubusercontent.com/56706782/68371348-7e4f0580-0179-11ea-96e7-174b08ddc226.png">

Pop noise at ending:
![end pop details](https://user-images.githubusercontent.com/56706782/68374419-db4dba00-017f-11ea-996a-6142a1ac1b79.png)
![end pop](https://user-images.githubusercontent.com/56706782/68374433-e0ab0480-017f-11ea-9202-8333938de1e2.png)

**Comment by plbossart** [comment] 2019-11-07 16:15
@sinahuang you'd need to test with an RT711 in HDaudio mode, those are available on unmodified TGL RVPs

**Comment by sinahuang** [comment] 2019-11-08 03:11
Currently only TGL and CML-S have RT711 in HDA mode. On both platforms , this issue can be reproduced with SOF, while cannot with legacy HDA driver

**Comment by Liviali155** [comment] 2019-12-17 09:06
Issue can be reproduced when HDA Analog playback
Pop noise also can output on headset when starting/stopping HDA Analog capture on TGL-U RVP with onboard ALC711 in HD-A mode
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev   commit:c5e4a391
Firmware:https://github.com/thesofproject/sof/commits/master  commit: 85e462ad
sof-hda-generic-4ch.tplg   commit: 85e462ad

[dmesg20191217.log](https://github.com/thesofproject/linux/files/3972353/dmesg20191217.log)
[sof_trace1217.log](https://github.com/thesofproject/linux/files/3972355/sof_trace1217.log)

**Comment by Liviali155** [comment] 2020-01-10 04:10
Issue can reproduced on legacy HDA after suspend runtime PM use below method:
echo auto > /sys/bus/pci/devices/0000:00:1f:3/power/control
echo 1 > /sys/module/snd_hda_intel/parameters/power_save

**Comment by lgirdwood** [comment] 2020-01-10 11:03
@Liviali155 @mengdonglin legacy mode may not be fixable for some codecs but @singalsu has potential fix for any codec running in DSP mode.

**Comment by Liviali155** [comment] 2020-04-08 03:21
Tried with #1897 ,issue still can be reproduced

**Comment by Liviali155** [comment] 2020-04-13 07:25
This issue also can be reproduced on sof v1.5-rc1 when starting/stopping HDA analog playback and capture
Kernel:4b4681eb Sof-dev
fw:5f7d4e2 https://github.com/thesofproject/sof/releases/tag/v1.5-rc1

**Comment by plbossart** [comment] 2020-06-09 19:13
@Liviali155 I wonder if the issue is due to the power_save.

Could you re-try with SOF and legacy drivers and provide the information on /sys/module/snd_hda_intel/parameters/power_save while the drivers are suspended.

I'd like to understand if there is a difference in how we suspend the codec. @kv2019i FYI, this is odd.

**Comment by Liviali155** [comment] 2020-06-10 01:51
On sof:
cat /sys/module/snd_hda_intel/parameters/power_save when suspended,the value is 0
On legacy HDA:
cat /sys/module/snd_hda_intel/parameters/power_save when suspended,the value is 1

**Comment by Liviali155** [comment] 2020-06-10 02:03
This issue only occured when runtime PM status changed  from  active to suspend or changed from suspend to active

**Comment by kv2019i** [comment] 2020-06-11 19:16
@plbossart wrote:
>I'd like to understand if there is a difference in how we suspend the codec. @kv2019i FYI, this is odd.
@Liviali155 wrote:
> On legacy HDA:
> cat /sys/module/snd_hda_intel/parameters/power_save when suspended,the value is 1

So it would indeed seem that legacy driver is putting the codec to runtime PM as well. We share most of the per-codec logic (depop delays, power-up fixups, etc) and the controller resume/suspend looks the same, but obviously we go through ASoC flows so there can be differences. I'll try to see if I can reproduce on this some setup.

**Comment by RanderWang** [comment] 2020-08-13 05:52
I can reproduce it on RKL

**Comment by mengdonglin** [comment] 2020-08-13 06:21
Thank you @RanderWang @kv2019i This seems to be a common issue for ALC711 codec in HD-Audio mode. And legacy HD-Audio driver can also reproduce the pop noise. So close it as won't fix.

**Comment by RanderWang** [comment] 2020-08-13 06:21
I agree with @kv2019i . It is very likely a codec issue

**Closed as completed by mengdonglin** 2020-08-13 06:21 UTC
Labels: bug, won't fix, P2, CML, HDA, codec, TGL, RKL
