### ISSUE TITLE
sof 2.2.6 does not work with kernel 6.4.3 (error) and 6.1.38 (no output) on Dell XPS 9320

### ISSUE THREAD

**Issue by telmich** [thesofproject/linux#4476] opened 2023-07-15 06:40 UTC
Hello,

I installed sof 2.2.6 on Alpine Linux using the package manager (package `sof-firmware`).  When loading snd_sof_pci_intel_tgl I get the following error and no sound card seen:

```
sun:~# dmesg 
[69877.731551] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[69877.731566] sof-audio-pci-intel-tgl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[69877.731718] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[69877.731783] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_exit [i915])
[69877.738954] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[69877.749411] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
[69877.749535] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[69877.749536] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
[69877.749537] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[69877.866147] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[69877.866149] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:23:0
[69877.873826] soundwire sdw:0:025d:0714:01: Bus clash detected before INT mask is enabled
[69881.349827] soundwire sdw-master-0: clock stop prep/de-prep failed slave:15
[69881.349831] soundwire_intel soundwire_intel.link.0: prepare clock stop failed -110
[69881.349832] soundwire_intel soundwire_intel.link.0: intel_stop_bus: cannot stop clock: -110
```

With kernel linux-lts-6.1.38 the module loads and the card shows 3x HDMI out, but no speaker/microphone are detected.

The card in the 9320 is the following:

```
Audio:
  Device-1: Intel vendor: Dell driver: N/A bus-ID: 00:05.0 chip-ID: 8086:a75d
    class-ID: 0480
  Device-2: Intel vendor: Dell driver: sof-audio-pci-intel-tgl
    bus-ID: 00:1f.3 chip-ID: 8086:51ca class-ID: 0401
  API: ALSA v: k6.4.3-0-edge status: kernel-api
    tools: alsactl,alsamixer,amixer
  Server-1: JACK v: 1.9.22 status: off tools: jack_control
  Server-2: PulseAudio v: 16.1 status: off tools: pacat,pactl
```

**Comment by marc-hb** [comment] 2023-07-15 07:46
> `[69877.873826] soundwire sdw:0:025d:0714:01: Bus clash detected before INT mask is enabled`

This does not look good... @bardliao , @plbossart ?

**Comment by bardliao** [comment] 2023-07-17 05:48
@telmich Can you share the dmesg log? And does Dell XPS 9320 work with previous SOF version?

**Comment by telmich** [comment] 2023-07-24 16:45
@bardliao The only version in which sound works is on an older Ubuntu Kernel, using 5.19.0.

I have uploaded various supporting files also on https://www.nico.schottelius.org/temp/xps-9320/.

dmesgs are attached. 

[alpine-6.4.3-1-edge-dmesg.txt](https://github.com/thesofproject/linux/files/12148131/alpine-6.4.3-1-edge-dmesg.txt)
[alpine-6.1.38-5-lts-dmesg.txt](https://github.com/thesofproject/linux/files/12148132/alpine-6.1.38-5-lts-dmesg.txt)
[alpine-6.1.38-3-dmesg.txt](https://github.com/thesofproject/linux/files/12148133/alpine-6.1.38-3-dmesg.txt)
[alpine-6.1.38-2-lts-dmesg.txt](https://github.com/thesofproject/linux/files/12148134/alpine-6.1.38-2-lts-dmesg.txt)
[dmesg-ubuntu-5.19.0-32-generic.txt](https://github.com/thesofproject/linux/files/12148135/dmesg-ubuntu-5.19.0-32-generic.txt)

**Comment by bardliao** [comment] 2023-07-25 09:41
@telmich Can you add [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/12159551/sof-dyndbg.conf.txt) in the
/etc/modprobe.d/ folder and rename to sof-dyndbg.conf and reboot?
Then get the dmesg log again and it will show more debug log.

**Comment by telmich** [comment] 2023-07-25 10:58
@bardliao absolutely. As the device is currently in the office, I will do it tomorrow.
Do you have a preference of seeing the result with 6.1.38 or 6.4.3? In either case, I will try to stick to sof firmware 2.2.6.

**Comment by plbossart** [comment] 2023-07-25 10:59
6.4.3 is better for us, thanks @telmich

**Comment by plbossart** [comment] 2023-07-25 12:29
actually let me change my mind @telmich, we need dynamic debug for both 6.1.38 and 6.4 to see the difference and why the card is not detected.

**Comment by bardliao** [comment] 2023-07-26 05:47
> actually let me change my mind @telmich, we need dynamic debug for both 6.1.38 and 6.4 to see the difference and why the card is not detected.

@plbossart I think the only working kernel version is 5.19. @telmich Please also get the log from 5.19 kernel, thanks.

**Comment by telmich** [comment] 2023-07-26 11:34
Hello @plbossart - attached are the ones from Alpine Linux, now upgraded to 6.1.41 and 6.4.4, errors are still the same.

[dmesg-6.1.41-0-lts-dyndbg.txt](https://github.com/thesofproject/linux/files/12171839/dmesg-6.1.41-0-lts-dyndbg.txt)
[dmesg-6.4.4-0-edge-dyndbg.txt](https://github.com/thesofproject/linux/files/12171841/dmesg-6.4.4-0-edge-dyndbg.txt)

**Comment by telmich** [comment] 2023-07-26 11:37
@bardliao In regards to 5.19, I used an ubuntu live image for testing. What would be the best way to inject all the module parameters from the dyndbg before booting?

Afair, the ubuntu image is an ISO on a USB stick, so not that easy to edit without rebuilding the whole OS

**Comment by plbossart** [comment] 2023-07-26 16:21
@telmich I don't know what distro you use but dynamic debug is not enabled in the 'edge' version

````
[    6.872536] dyndbg param is supported only in CONFIG_DYNAMIC_DEBUG builds
````

We have no other means to help you out, so please switch to a different kernel where this configuration is enabled.

For the 6.1 version, it seems that the kernel does not support your configuration:

````
[   10.027825] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: ACPI reports 4 SDW Link devices
[   10.027850] snd_intel_sdw_acpi:sdw_intel_scan_controller: acpi PRP00001:00: Link 3 not selected in firmware
[   10.027856] soundwire_intel:sdw_intel_probe_controller: acpi PRP00001:00: Creating 4 SDW Link devices

[   10.042418] snd_soc_rt1316_sdw:rt1316_sdw_init: rt1316-sdca sdw:1:025d:1316:01: rt1316_sdw_init
[   10.042432] snd_soc_rt1316_sdw:rt1316_read_prop: rt1316-sdca sdw:1:025d:1316:01: rt1316_read_prop
[   10.042616] snd_soc_rt1316_sdw:rt1316_sdw_init: rt1316-sdca sdw:2:025d:1316:01: rt1316_sdw_init
[   10.042621] snd_soc_rt1316_sdw:rt1316_read_prop: rt1316-sdca sdw:2:025d:1316:01: rt1316_read_prop
[   10.050235] snd_sof:sof_set_fw_state: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 0 -> 1
[   10.050253] snd_sof_intel_hda_common:link_slaves_found: sof-audio-pci-intel-tgl 0000:00:1f.3: Slave 711 not found
````

Can you run 'sudo dmidecode | grep SKU' and report the value?

**Comment by bardliao** [comment] 2023-07-27 10:55
> Can you run 'sudo dmidecode | grep SKU' and report the value?

@plbossart I can find the SKU from alsainfo.
System SKU:        0C10

And we do support this SKU. https://github.com/thesofproject/linux/commit/1a55a34146b45

**Comment by telmich** [comment] 2023-08-07 07:58
@plbossart Sorry for the late reply, seems the github notifications don't work for me anymore.
Below is the SKU:

```
#  dmidecode | grep SKU
	SKU Number: 0C10
	SKU Number: Notebook
		Consumer SKU
```

**Comment by plbossart** [comment] 2023-08-07 14:32
@telmich Could this be a duplicate of https://github.com/thesofproject/linux/issues/4493 where the problem is that somehow someone decided that the SOF modules would be built-in?

We only support modules.

**Comment by telmich** [comment] 2023-08-07 15:30
[Uploading 6.1.43-0-lts-config.txt…]()
@plbossart I'm not sure if I follow. The modules are loaded as kernel modules, not compiled in if that is the question?

I just upgraded to 6.1.43-0-lts including dyndbg and the lsmod output, maybe that clarifies the situation.

[6.1.43-0-lts-alsainfo.txt](https://github.com/thesofproject/linux/files/12282071/6.1.43-0-lts-alsainfo.txt)
[6.1.43-0-lts-aplay-l.txt](https://github.com/thesofproject/linux/files/12282072/6.1.43-0-lts-aplay-l.txt)
[6.1.43-0-lts-dmesg.txt](https://github.com/thesofproject/linux/files/12282073/6.1.43-0-lts-dmesg.txt)
[6.1.43-0-lts-lsmod.txt](https://github.com/thesofproject/linux/files/12282074/6.1.43-0-lts-lsmod.txt)
[6.1.43-0-lts-lspci-kk.txt](https://github.com/thesofproject/linux/files/12282075/6.1.43-0-lts-lspci-kk.txt)

**Comment by telmich** [comment] 2023-08-07 15:52
And for comparison 6.4.8, unfortunately without dyndbg. Note that in 6.4.8 the soundcard is completely unavailable, whereas in 6.1.43 the hdmi outputs are visible.

[6.4.8-0-edge-dmesg.txt](https://github.com/thesofproject/linux/files/12282456/6.4.8-0-edge-dmesg.txt)
[6.4.8-0-edge-lsmod.txt](https://github.com/thesofproject/linux/files/12282457/6.4.8-0-edge-lsmod.txt)
[6.4.8-0-edge-lspci-kk.txt](https://github.com/thesofproject/linux/files/12282458/6.4.8-0-edge-lspci-kk.txt)


[6.4.8-0-edge-alsainfo.txt](https://github.com/thesofproject/linux/files/12282453/6.4.8-0-edge-alsainfo.txt)
[6.4.8-0-edge-aplay-l.txt](https://github.com/thesofproject/linux/files/12282454/6.4.8-0-edge-aplay-l.txt)
[6.4.8-0-edge-config.txt](https://github.com/thesofproject/linux/files/12282455/6.4.8-0-edge-config.txt)

**Comment by plbossart** [comment] 2023-08-07 16:26
well the point is that the SKU 0C10 is reported as working in the other issue, so there's clearly something specific to your distro...

can you try another distro with a USB key? Fedora is typically the most reliable for SOF support.

**Comment by telmich** [comment] 2023-08-08 19:40
@plbossart It does work (see https://github.com/thesofproject/linux/issues/4476#issuecomment-1648256840) on ubuntu, kernel 5.19.

I did take some time with other Alpine Linux developers to figure out what the difference is between the kernels and we enabled virtually all SOF / soundwire related options in linux-lts, however without any apparent change, which is why I opened this issue.

I am not saying the kernel config of Alpine with 6.1.43 is correct, but I would like to fix what is wrong. The problem so far has been that it is not clear what the error is nor how to fix it.

So yes, there might be something wrong, but can you point me in the right direction for fixing it so I can push it upstream to Alpine Linux?

**Comment by plbossart** [comment] 2023-08-08 19:54
like I said, try with a distro that has a recent kernel and start reporting the success. It's very very hard for us to even think of what a downstream distribution might have done.

Honestly the simplest would be to recompile your own kernel, it's not that hard and it's the only way to progress logically without adding newer variables in the equation.

**Comment by telmich** [comment] 2023-08-10 17:10
I followed two new approaches, unfortunately both without sucess:

1) I tried to use the ubuntu kernel 5.19.0 that works on ubuntu

Booting the same kernel that works on ubuntu and regenerating the initramfs on alpine linux using `mkinitfs 5.19.0-50-generic` results in the same behaviour as always, only dummy outputs seen

2) I diffed the two kernel configs of alpine linux -lts and the ubuntu kernel, one of the things that jumped at me was that ubuntu had `CONFIG_DRM_I915_PXP=y` set, but alpine's -lts (6.1.44 now) does not.

Booting a modified kernel with CONFIG_DRM_I915_PXP=y results in the same pattern, only the dummy output is visible.

**Comment by telmich** [comment] 2023-08-10 17:12
[5.19.0-50-generic-on-alpine-alsainfo.txt](https://github.com/thesofproject/linux/files/12315522/5.19.0-50-generic-on-alpine-alsainfo.txt)
[Uploading 5.19.0-50-generic-on-alpine-alsainfo.txt…]()
[5.19.0-50-generic-on-alpine-lsmod.txt](https://github.com/thesofproject/linux/files/12315523/5.19.0-50-generic-on-alpine-lsmod.txt)
[5.19.0-50-generic-on-alpine-aplay-l.txt](https://github.com/thesofproject/linux/files/12315524/5.19.0-50-generic-on-alpine-aplay-l.txt)
[5.19.0-50-generic-on-alpine-dmesg.txt](https://github.com/thesofproject/linux/files/12315525/5.19.0-50-generic-on-alpine-dmesg.txt)
[5.19.0-50-generic-on-alpine-lspci-kk.txt](https://github.com/thesofproject/linux/files/12315526/5.19.0-50-generic-on-alpine-lspci-kk.txt)

Log from 5.19.0-50 as booted on alpine w/ alpine adjusted initramfs

**Comment by telmich** [comment] 2023-08-10 17:14
[6.1.44-1-lts-pxp-alsainfo.txt](https://github.com/thesofproject/linux/files/12315550/6.1.44-1-lts-pxp-alsainfo.txt)
[6.1.44-1-lts-pxp-lsmod.txt](https://github.com/thesofproject/linux/files/12315551/6.1.44-1-lts-pxp-lsmod.txt)
[6.1.44-1-lts-pxp-aplay-l.txt](https://github.com/thesofproject/linux/files/12315552/6.1.44-1-lts-pxp-aplay-l.txt)
[6.1.44-1-lts-pxp-dmesg.txt](https://github.com/thesofproject/linux/files/12315553/6.1.44-1-lts-pxp-dmesg.txt)
[6.1.44-1-lts-pxp-lspci-kk.txt](https://github.com/thesofproject/linux/files/12315554/6.1.44-1-lts-pxp-lspci-kk.txt)

6.1.44 with PXP enabled

**Comment by telmich** [comment] 2023-08-10 17:18
@plbossart Usually when a kernel module can be loaded, my expectation is that "it works", such as a SCSI driver or similar. It seems in the case of snd-hda-intel/soundwire that is not necessarily the case.

From above tests it seems that the initramfs of ubuntu does something different that alpine does not do. Are there any cross dependencies that need to be fulfilled for the driver to function? i.e. loading something specific prior to soundwire_intel?

**Comment by plbossart** [comment] 2023-08-10 17:37
I don't really have any suggestions other than find a recent kernel that works, and then downgrade until we see a root cause. Starting with a distribution I've never used or raising conjectures on hypothetical differences is unlikely to help make progress.

Like I said, the easiest is to take the latest Ubuntu or Fedora with kernel 6.2+, install on a USB key, boot from the USB key and see what happens. If it's broken then we can remove the 'unknown distribution' from the variables.

**Comment by telmich** [comment] 2023-08-10 21:33
@plbossart I am puzzled. Ubuntu using kernel 5.19.0-50 does work. Alpine using 6.1.38 to 6.1.44 nor 6.4.8 does not work. Alpine using the exact same Ubuntu kernel that does work, but with a freshly generated initramfs does not work.

If I was to downgrading from 5.19.0, how would that help?

**Comment by bardliao** [comment] 2023-08-11 06:21
Again, you have to set CONFIG_DYNAMIC_DEBUG=y in kconfig, otherwise, we can't get any debug log.
"dyndbg param is supported only in CONFIG_DYNAMIC_DEBUG builds"
If you want to debug the issue, you have to build kernel by your self instead of installing a prebuilt kernel.
So that you can check if https://github.com/thesofproject/linux/pull/3978/commits is in your kernel or not. I think this PR is the key why your sound card is not created.
The Ubuntu kernel works may because they have the required patches which landed in upstream kernel later.
BTW, you can try our kernel: https://github.com/thesofproject/linux/ and use https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh to generate the kconfig.

**Comment by telmich** [comment] 2023-08-15 09:48
Good morning @bardliao !

I just built the latest kernel (6.5.0) from above sources, used the kconfig-sof-default.sh, but that kernel seems not to have dm crypt support, so it cannot load the rootfs. Now investigating which .config options are missing to make it bootable, starting with DM_CRYPT=y - will follow up as soon as I have something that can boot into xorg.

**Comment by telmich** [comment] 2023-08-15 09:51
For the record, I get at the boot: `device mapper: reload ioctl on root (252:0) failed: No such file or directory`

**Comment by telmich** [comment] 2023-08-15 11:13
I can confirm that using above linux sources and the following config, sound on the Dell XPS 9320 does actually work under Linux 6.5.0-rc5-g925a9e721de0.

If you don't mind keeping this issue open for one more week or so, I'll dive into the .config differences between this kernel and linux-lts to document which config option was the required one.

Attached are the usual debug files.

[6.5.0-rc5-g925a9e721de0-alsainfo.txt](https://github.com/thesofproject/linux/files/12343575/6.5.0-rc5-g925a9e721de0-alsainfo.txt)
[6.5.0-rc5-g925a9e721de0-lsmod.txt](https://github.com/thesofproject/linux/files/12343576/6.5.0-rc5-g925a9e721de0-lsmod.txt)
[6.5.0-rc5-g925a9e721de0-aplay-l.txt](https://github.com/thesofproject/linux/files/12343577/6.5.0-rc5-g925a9e721de0-aplay-l.txt)
[6.5.0-rc5-g925a9e721de0-dmesg.txt](https://github.com/thesofproject/linux/files/12343578/6.5.0-rc5-g925a9e721de0-dmesg.txt)
[6.5.0-rc5-g925a9e721de0-lspci-kk.txt](https://github.com/thesofproject/linux/files/12343579/6.5.0-rc5-g925a9e721de0-lspci-kk.txt)
[6.5.0-rc5-g925a9e721de0-config.txt](https://github.com/thesofproject/linux/files/12343583/6.5.0-rc5-g925a9e721de0-config.txt)

**Comment by plbossart** [comment] 2023-08-15 13:53
start with the "SOF" Kconfigs and see that everything looks similar.
We typically don't work with entire configs but instead add the 'fragments' that we need with kconfig-sof-default.sh, it's a lot more manageable to understand what parts we need to recommend.

What you can do is also to extend the existing distro with the recommended SOF additions, we have a dedicated script for it, see https://github.com/thesofproject/kconfig/blob/master/kconfig-distro-sof-update.sh. That would avoid the issues with DM_CRYPT.

**Comment by telmich** [comment] 2023-08-18 07:43
@plbossart Much appreciated, will give that a try and see what the diff is.

**Comment by ujfalusi** [comment] 2023-09-07 12:59
@telmich, did you managed to narrow down on the config difference?

**Comment by plbossart** [comment] 2024-04-04 19:46
No feedback, closing.

**Closed as completed by plbossart** 2024-04-04 19:46 UTC
Labels: bug, SDW, ADL, sof v2.2.x
