### ISSUE TITLE
[Bug] [cml&CFL]sof-cnl.ri still need to be rename to cml or cfl fw to use

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#2013] opened 2020-04-15 06:18 UTC
**Describe the bug**
sof-cnl.ri still need be renamed to sof-cml.ri for CML or sof-cfl.ri for CFL to use.

**To Reproduce**
1. Delete sof-cml.ri from /lib/firmware/intel/sof/ and put only sof-cnl.ri
2. sudo reboot to boot up system 

**Reproduction Rate**
3/3

**Expected behavior**
Should fallback to using sof-cnl.ri, if not find sof-cml.ri  for CML or sof-cfl.ri for CFL

**Impact**
SOF firmware isn't loaded

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: topic/sof-dev, commit 73187435
    * SOF: Master, commit 3808dfec
2) Name of the topology file
    * Topology: sof-hda-generic-2ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: CFL Laptop with ALC3254 in HDA mode and CML laptop with  ALC3204 in HDA mode.

Dmesg on the CFL laptop:
```
	Line 889: [    3.939974] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
	Line 895: [    3.941556] sof-audio-pci 0000:00:1f.3: skipping SoundWire, no links enabled
	Line 896: [    3.941668] sof-audio-pci 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0295
	Line 899: [    3.967084] sof-audio-pci 0000:00:1f.3: HDA codec #2 probed OK: response: 8086280b
	Line 902: [    3.990433] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
	Line 903: [    3.990439] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
	Line 904: [    3.994607] sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 2
	Line 905: [    3.994639] sof-audio-pci 0000:00:1f.3: loading firmware
	Line 906: [    3.998551] sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2
	Line 906: [    3.998551] sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2
	Line 906: [    3.998551] sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cfl.ri failed with error -2
	Line 907: [    3.998559] sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cfl.ri failed err: -2
	Line 907: [    3.998559] sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cfl.ri failed err: -2
	Line 907: [    3.998559] sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cfl.ri failed err: -2
	Line 908: [    3.998570] sof-audio-pci 0000:00:1f.3: error: failed to load DSP firmware -2
	Line 909: [    3.999655] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
	Line 910: [    3.999700] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
	Line 911: [    3.999709] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
	Line 912: [    4.000006] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -2
	Line 912: [    4.000006] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -2
``` 
[dmesg.txt](https://github.com/thesofproject/linux/files/4479415/dmesg.txt)

**Comment by ClarexZhou** [comment] 2020-04-15 06:18
Error also seen with stable linux 5.5.9 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.9, commit 81b6e04c4b..

**Comment by mengdonglin** [comment] 2020-04-15 07:02
@kv2019i @plbossart @lgirdwood  can we allow driver to
-  fallback to sof-cnl.ri if sof-cml.ri is not available for CML
-  fallback to sof-cnl.ri if sof-cfl.ri is not available for CFL ?

For SOF v1.4.2 release, @jajanusz confirmed that a single cn-cnl.ri (PV bit set in manifest) can be shared for all cAVS 1.8 platforms: https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2/intel-signed

I think SOF v1.5 and future releases, there will also be only one  cn-cnl.ri

**Comment by Liviali155** [comment] 2020-04-15 07:33
Add Dmesg log for the CML laptop:

<details>
 <summary>dmesg_error.log</summary>

````
[    2.576013] sof-audio-pci 0000:00:1f.3: hda codecs found, mask 5
[    2.576014] sof-audio-pci 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    2.576121] sof-audio-pci 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    2.576191] iwlwifi 0000:00:14.3: base HW address: 04:ea:56:6d:c2:9d
[    2.576290] sof-audio-pci 0000:00:1f.3: Direct firmware load for intel/sof/sof-cml.ri failed with error -2
[    2.576292] sof-audio-pci 0000:00:1f.3: error: request firmware intel/sof/sof-cml.ri failed err: -2
[    2.576374] sof-audio-pci 0000:00:1f.3: error: failed to load DSP firmware -2
[    2.589161] thermal thermal_zone5: failed to read out thermal zone (-61)
[    2.589466] systemd[1]: Starting Load/Save RF Kill Switch Status...
[    2.591266] iwlwifi 0000:00:14.3 wlp0s20f3: renamed from wlan0
[    2.594423] systemd[1]: Started Load/Save RF Kill Switch Status.
[    2.599403] systemd[1]: Finished Load/Save Screen Backlight Brightness of backlight:intel_backlight.
[    2.607263] sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -2
[    2.612542] systemd[1]: Started Journal Service.
[    2.616174] systemd-journald[244]: Received client request to flush runtime journal.
[    3.250816] random: crng init done
[    4.065237] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[    6.335246] FAT-fs (sda1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    6.471781] rfkill: input handler disabled
````
</details>


[dmesg-4015.log](https://github.com/thesofproject/linux/files/4479700/dmesg-4015.log)

**Comment by kv2019i** [comment] 2020-04-15 08:19
@ClarexZhou @mengdonglin The driver will not try multiple files, so the firmware package will need to install symlinks (so that sof-cml.ri is always there).

**Comment by mengdonglin** [comment] 2020-04-15 09:53
@kv2019i Okay. We'll communicate to OS vendors. 

You''re right, the driver will not try multiple files: https://github.com/thesofproject/linux/blob/73187435bdb760e706e04d8fbb32aaba7e9f00d1/sound/soc/sof/sof-pci-dev.c#L137

And since SOF v1.3 used different FW binaries for CML and CFL, we cannot change the default default_fw_filename for them in driver. Closed this issue as won't fix.

**Closed as completed by mengdonglin** 2020-04-15 09:53 UTC
Labels: bug, won't fix, P1, CML, HDA, CFL
