### ISSUE TITLE
[WHL] HDMI/DP doesn't work

### ISSUE THREAD

**Issue by ghost** [thesofproject/linux#313] opened 2018-11-26 14:03 UTC
linux: sof-dev/af44aa9
soft: master/ad3f3e4 tplg file: sof-whl-hda.m4 -> /lib/firmware/intel/sof-hda-generic.tplg
sof: whl-001-drop-stable/33e4b99

For above configuration HDA 48k, 16b, stereo works fine

HDMI/DP doesn't work for all 3 iDisp configuration:
`aplay -vv -Dhw:0,3 file_sound.wav`

![image](https://user-images.githubusercontent.com/22911148/49018411-a70a0500-f18b-11e8-82a2-be9bd0036f08.png)

![image](https://user-images.githubusercontent.com/22911148/49018417-aa9d8c00-f18b-11e8-9c60-740807bc8768.png)

**Comment by plbossart** [comment] 2018-11-26 15:32
@echudy Not an SOF issue, this is a configuration issue, you need to set the controls correctly. Typically this is done by checking which pin is connected, then setting the Pin5/6/7-Port0 Mux to 1 (for HDMI1 path), 2 (for HDMI2 path) and 3 (for HDMI3 path).
The same requirement applies to the cAVS/SST driver, this is not SOF specific....

**Comment by xiulipan** [comment] 2018-11-27 03:39
@echudy 
`-19` means either you did not connect a HDMI monitor to the device or you have wrong set in alsamixer

![image](https://user-images.githubusercontent.com/37825714/49056896-76cc7000-f238-11e8-8e95-41ffd560ba88.png)

A working hdmi setting is look like above.

Notice here only port 6 is connection to a monitor so I can see below message in dmesg
```
[    3.984807] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[    3.985075] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
```

Which means I can only have port6 thus `HDMI 2` working.
So after you have a monitor connected, you need to check the dmesg to determine which card to use.

**Comment by emilchudzik** [comment] 2018-11-27 09:31
Ok, i did this steps:
- connect monitor with HDMI and restart due to catch dmesg notification. I see the same as you:
```
[    5.152543] sof-audio sof-audio: tplg: load pcm HDMI1 3
[    5.152545] sof-audio sof-audio: tplg: load pcm HDMI2 4
[    5.152547] sof-audio sof-audio: tplg: load pcm HDMI3 5
[    5.162688] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[    5.163424] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
[    5.234380] sof-audio sof-audio: creating new PCM HDMI1
[    5.234385] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI1 3 mapping ok
[    5.234392] sof-audio sof-audio: creating new PCM HDMI2
[    5.234397] skl_hda_dsp_generic skl_hda_dsp_generic: snd-soc-dummy-dai <-> HDMI2 4 mapping ok
[    5.234404] sof-audio sof-audio: creating new PCM HDMI3

```
- so i set alsamixer to pin 6: **cvt3**
![image](https://user-images.githubusercontent.com/41113230/49071946-6368d700-f22f-11e8-99a9-a4c37c26e22b.png)

- pin6 is HDMI2, so I use command to play:
`aplay -vv -Dhw:0,4 file_sound.wav`
![image](https://user-images.githubusercontent.com/41113230/49071981-7aa7c480-f22f-11e8-8ac4-f4c039439e74.png)

in dmesg I still see code -19:
```
[  361.469883] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi2 hw params: -19
[  361.469894]  iDisp2: ASoC: hw_params BE failed -19
[  361.469899]  HDMI2: ASoC: hw_params BE failed -19

```

**Comment by xiulipan** [comment] 2018-11-27 09:37
@bardliao 
I remember there is a hdac-hdmi codec driver patch to enable HDMI playback on WHL for sod-dev?
If that patch is merged now?

**Comment by xiulipan** [comment] 2018-11-27 10:06
@emilchudzik 
Confirmed with bard, please check if you have https://github.com/thesofproject/linux/commit/441b4b0374200744131f8c03fb225a2be42d88f1
In you kernel repo.
I can see from af44aa9 there is no this patch, please cherry-pick it.

**Comment by emilchudzik** [comment] 2018-11-27 13:59
Still the same, HDMI doesn't work.
Error -19 disappeared.

After play using HDMI2 (hw0,4) I have only this in dmesg:
```
audiodsp@lab201:~$ dmesg
[  414.479628] sof-audio sof-audio: pcm: open stream 4 dir 0
[  414.479635] sof-audio sof-audio: period min 192 max 16384 bytes
[  414.479639] sof-audio sof-audio: period count 2 max 16
[  414.479643] sof-audio sof-audio: buffer max 65536 bytes
[  414.479839] sof-audio sof-audio: pcm: close stream 4 dir 0

```

**Comment by plbossart** [comment] 2018-11-27 20:12
@emilchudzik please add ccflags-y += -DDEBUG to the Makefiles in sound/soc/sof/ sound/soc/sof/intel sound/soc/codecs sound/soc/intel/boards and submit the full dmesg log as attachment

**Comment by bardliao** [comment] 2018-11-28 01:23
@emilchudzik Same branch/commit works on my WHL RVP. But there is only one DP port on my HWL RVP which is pin 5. 
```
[    3.440683] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[    3.440982] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
```
So my command is  aplay -Dhw:0,3 48k32bitCalifornia_Dreaming.wav -vv.
```
Playing WAVE '48k32bitCalifornia_Dreaming.wav' : Signed 32 bit Little Endian, Rate 48000 Hz, Stereo
Hardware PCM card 0 'sof-skl_hda_card' device 3 subdevice 0
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : S32_LE
  subformat    : STD
  channels     : 2
  rate         : 48000
  exact rate   : 48000 (48000/1)
  msbits       : 32
  buffer_size  : 8064
  period_size  : 1920
  period_time  : 40000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1920
  period_event : 0
  start_threshold  : 8064
  stop_threshold   : 8064
  silence_threshold: 0
  silence_size : 0
  boundary     : 9079256848778919936
  appl_ptr     : 0
  hw_ptr       : 0
```

**Comment by emilchudzik** [comment] 2018-11-30 10:02
It seems like a monitor issue.
- IIyama X2472HD:
available only HDMI and JACK output - screen is visible, but unable to play using aplay

- Dell U2414Hb:
available DP and HDMI and JACK output - on both HDMI and DP can play and sound on stereo JACK works.

**Closed as completed** 2018-11-30 10:38 UTC
Labels: bug, P1, WHL
