### ISSUE TITLE
HDMI misleading report on Up2

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#227] opened 2018-10-30 00:08 UTC
Dmesg provides a misleading report even when HDMI can work.
[    4.093970] sof-audio-pci 0000:00:0e.0: no HDMI audio devices found
[dmesg.log](https://github.com/thesofproject/linux/files/2527483/dmesg.log)

**Comment by markyang** [comment] 2018-11-01 09:15
**Summary:**
This issue can be reproduced on UP2.
[    6.061752] sof-audio-pci 0000:00:0e.0: no HDMI audio devices found

**Test env:**
sof master: 43da1696
sof tool: 4ac9248
kernel debug/v4.19-backport: 925637e3
tplg: sof-apl-pcm512x.tplg-4ac9248

[dmesg-apl-hdmi.txt](https://github.com/thesofproject/linux/files/2537852/dmesg-apl-hdmi.txt)

**Comment by plbossart** [comment] 2018-11-06 21:47
This was introduced w/ the patch 89bef7af66b5 ('ASoC: SOF: Intel HDA: continue probe if no HDMI devices found');

@lgirdwood why was the error control removed? if you've compiled in HDMI support and can't init the i915 parts then something is just very wrong.

**Comment by lgirdwood** [comment] 2018-11-07 14:25
@plbossart so the initial code from @RanderWang printed the error and returned an error if no monitor was connected (meaning SOF would not probe on devices with no monitors connected).
@RanderWang should this error be visible when no monitors are connected or does it mean something more fatal perhaps unrecoverable has happened ?

**Comment by plbossart** [comment] 2018-11-08 02:12
@lgirdwood the connection state (plugged/unplugged) is irrelevant. Even when there is nothing connected you can establish the link with the iDISP codec. With HDaudio you can even stream audio out with nothing connected. So this error really means the link with the graphics IP is not working, and that is non-recoverable, so we should fail big-time and early rather than try to continue.

**Comment by lgirdwood** [comment] 2018-11-08 11:56
@plbossart ok, the initial error message made it seem like a codec was not detected and non fatal.

**Comment by lgirdwood** [comment] 2018-11-09 16:34
Updated to HEAD 3277edc9, regarding above this error should only be fatal if HDMI based topologies are loaded. 

```
    4.708781] sof-audio-pci 0000:00:0e.0: PCI DSP detected
[    4.709115] sof-audio-pci 0000:00:0e.0: No matching ASoC machine driver found - using nocodec
[    4.711206] sof-audio sof-audio: probing SOF DSP device....
[    4.711211] sof-audio sof-audio: using platform alias (null)
[    4.711294] sof-audio sof-audio: checking for capabilities at offset 0xc00
[    4.711296] sof-audio sof-audio: found ML capability at 0xc00
[    4.711299] sof-audio sof-audio: checking for capabilities at offset 0x800
[    4.711301] sof-audio sof-audio: found DSP capability at 0x800
[    4.711304] sof-audio sof-audio: checking for capabilities at offset 0x500
[    4.711305] sof-audio sof-audio: found GTS capability at 0x500
[    4.711308] sof-audio sof-audio: checking for capabilities at offset 0x1f00
[    4.711310] sof-audio sof-audio: found DRSM capability at 0x1f00
[    4.711313] sof-audio sof-audio: checking for capabilities at offset 0x700
[    4.711315] sof-audio sof-audio: found SPIB capability at 0x700
[    4.711323] sof-audio-pci 0000:00:0e.0: DMA mask is 64 bit
[    4.711327] sof-audio sof-audio: hda global caps = 0x1006701
[    4.711329] sof-audio sof-audio: detected 6 playback and 7 capture streams
[    4.711364] sof-audio sof-audio: use msi interrupt mode
[    4.711366] sof-audio sof-audio: using HDA IRQ 25
[    4.719986] sof-audio sof-audio: using IPC IRQ 25
[    4.725178] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[    4.725183] sof-audio-pci 0000:00:0e.0: PP capability, will probe DSP later.
[    4.725189] sof-audio-pci 0000:00:0e.0: no HDMI audio devices found
[    4.727934] sof-audio sof-audio: error: failed to probe DSP -19
```

**Comment by lgirdwood** [comment] 2018-11-09 16:37
@plbossart same error on Leafhill too. My only thoughts are if you are not seeing this then a Kconfig option is breaking this (and it should be non fatal).

**Comment by lgirdwood** [comment] 2018-11-09 16:47
Ok, @RanderWang the SOF HDMI support depends on the Intel display driver. Can you add such a rule in Kconfig otherwise we get this error.

**Comment by plbossart** [comment] 2018-11-09 17:12
All machine drivers which support HDMI should select HDAC_HDMI. This is not the case today.
That said, we will need to make the select conditional as well to build without HDMI when SOF_HDA is not selected. Kconfig mess again.

**Comment by plbossart** [comment] 2018-11-09 17:14
@lgirdwood actually if you are using nocodec you should not have HDMI enabled, not sure how you reached this point?

**Comment by libinyang** [comment] 2018-11-14 09:09
@lgirdwood 
@plbossart 
After checking the code, I mainly knows why this bug happens and what's the design in SOF for HDMI.
Actually, the code is somehow copy from HDA. But the copier missed one point, in HDA we will return error directly in some cases. These cases are the controller is only for HDMI/DP audio. This means we never need initialize the HDA audio controller after we met the i915 init fails (no other codec is connected to this controller). And the copier copied this solution for all controller. This is wrong. Because in SOF, the controller will connect both to HDMI/DP codec and to other codecs. So we should still init the SOF even i915 init fails. So Rander/Liam made a patch for it (There is a little defect in the patch. We should only logout "no HDMI" info only init i915 fails).

The right solution is: after init i915 fails, we logout the information and set a flag. And in the later code, we will skip all HDMI/DP operations.

What's your opinion? If it is OK for you, I will make a patch.

**Comment by keyonjie** [comment] 2018-11-14 09:41
@libinyang we have same logic with sst skl.c, but I agree with your point that we should make HDA processing possible even i915_init fails or HDMI codec is unavailable.

Back to the issue initiated by Pierre, I believe if we select and load all dependencies(sof_hda, hdac_hdmi, hdac_hda, drm_i915, snd_hda_core,... there may be more...), we should not fail at hda_codec_i915_init() on skl+ platforms. Because this probing is before topology loading, so it has no relationship with tplg files, but machine driver which may require/introduce dependencies to those HDA/HDMI Kconfigs.

So I think the issues is that we should clean up Kconfig items, which should be done with nocodec/hda_generic/normal machine drivers probing refinement(which @bardliao is working) together.

**Comment by libinyang** [comment] 2018-11-14 14:07
> @libinyang we have same logic with sst skl.c, but I agree with your point that we should make HDA processing possible even i915_init fails or HDMI codec is unavailable.
> 
> Back to the issue initiated by Pierre, I believe if we select and load all dependencies(sof_hda, hdac_hdmi, hdac_hda, drm_i915, snd_hda_core,... there may be more...), we should not fail at hda_codec_i915_init() on skl+ platforms. Because this probing is before topology loading, so it has no relationship with tplg files, but machine driver which may require/introduce dependencies to those HDA/HDMI Kconfigs.
> 
> So I think the issues is that we should clean up Kconfig items, which should be done with nocodec/hda_generic/normal machine drivers probing refinement(which @bardliao is working) together.

Agree with that we should clean up the Kconfig.

However, this bug should be another issue from Kconfig. 
Firstly, this bug is directly is caused by mistaken of the code, the right code should be:
+    if (ret)
+        dev_dbg(...);

Secondly, As we can see, i915 init is handling graphic related issues. So this is a error handling topic. What if it failed on SKL+ (something wrong in i915 driver). The correct behavior is that we should set the flag and will not operate i915 later as you can't say what will happen if i915 is initialized wrong.

**Comment by plbossart** [comment] 2018-11-14 17:52
@libinyang I am not able to follow your explanations, can you submit a PR if you believe something is not correct.

**Comment by libinyang** [comment] 2018-11-15 03:43
> @libinyang I am not able to follow your explanations, can you submit a PR if you believe something is not correct.

Sure. I will submit a patch.

**Comment by libinyang** [comment] 2018-11-16 08:36
@plbossart 
@lgirdwood 

Patch submitted: https://github.com/thesofproject/linux/pull/295.
Please help review.

**Comment by libinyang** [comment] 2018-11-19 08:43
The latest sof-dev branch should have already fixed this issue. Should I porting the patch to debug/v4.19-backport? code is like:
ret = hda_codec_i915_init(sdev);
if (ret < 0) {
     dev_err(&pci->dev, "no HDMI audio devices found\n");
     return ret;
}

**Comment by plbossart** [comment] 2018-11-19 14:33
On 11/19/18 2:43 AM, Libin Yang wrote:
>
> The latest sof-dev branch should have already fixed this issue. Should 
> I porting the patch to debug/v4.19-backport? code is like:
>
No one should be using debug/v4.19-backport, I will push it to the 
archives. All the 4.19 code is now in topic/sof-dev, the debug branches 
are temporary to check for bugs or missing features during transitions.
>

**Comment by libinyang** [comment] 2018-11-20 01:51
> one should be using debug/v4.19-backport, I will push it to the archives. All the 4.1


> No one should be using debug/v4.19-backport, I will push it to the archives. All the 4.19 code is now in topic/sof-dev, the debug branches are temporary to check for bugs or missing features during transitions.

Got it.

**Comment by mengdonglin** [comment] 2018-11-20 15:14
@libinyang @plbossart  Can we close this issue if "the latest sof-dev branch should have already fixed this issue"?

**Comment by libinyang** [comment] 2018-11-21 01:34
i think so

**Comment by RanderWang** [comment] 2018-11-21 03:17
sorry, I am late.
Now the error message has been removed after I refine the algorithm of HDA codec detection.
So, It could be closed.

**Closed as completed** 2018-11-21 06:51 UTC
Labels: bug, P2, APL
