### ISSUE TITLE
[GLK][BUG]"ipc timed out for 0x80010000 size 216" occurred when do suspend/resume stress test.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2212] opened 2020-06-18 16:18 UTC
**Describe the bug**
"ipc timed out for 0x80010000 size 216" occurred when do suspend/resume stress test. After issue occurred runtime PM status will keep active but all pipline can work well.

**To Reproduce**
1.Boot up system.
2. sudo su
3.Echo s2idle>/sys/power/mem_sleep
 4.cd sof-test
5.cd test-case
6.export TPLG=/lib/firmware/intel/sof-glk-da7219.tplg
7../check-suspend-resume.sh -l 50(https://github.com/thesofproject/sof-test/blob/master/test-case/check-suspend-resume.sh)

**Reproduce rate**
First round test for 50 times, pass
2nd round test for 50 times, pass
3rd round test for 50 times, failed at 3th time
4th round test for 500 times, pass
5th round test for 50 times, failed at 4th time.

**Expected result**
No error should occurred when do suspend/resume stress test.

**Actual result**
"ipc timed out for 0x80010000 size 216" occurred when do suspend/resume stress test.
dmesg log:
```
[ 6438.043822] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x30030000: GLB_TPLG_MSG: COMP_CONNECT
[ 6438.043832] sof-audio-pci 0000:00:0e.0: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[ 6438.544629] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x80010000 size 216
[ 6438.544632] sof-audio-pci 0000:00:0e.0: info: preventing DSP entering D3 state to preserve context
[ 6438.544650] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[ 6438.544708] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[ 6438.544716] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[ 6438.544718] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 6438.544735] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 6438.544737] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
[ 6438.544741] sof-audio-pci 0000:00:0e.0: error: failed to set dai config for SSP1-Codec
[ 6438.544744] sof-audio-pci 0000:00:0e.0: error: failed to restore pipeline after resume -110
[ 6438.544765] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x20140000 successful
[ 6438.544786] sof-audio-pci 0000:00:0e.0: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[ 6439.048611] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x40010000 size 76
[ 6439.048614] sof-audio-pci 0000:00:0e.0: info: preventing DSP entering D3 state to preserve context
[ 6439.048618] sof-audio-pci 0000:00:0e.0: status: fw entered - code 00000005
[ 6439.048663] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[ 6439.048669] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
[ 6439.048671] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 6439.048676] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 6439.048679] sof-audio-pci 0000:00:0e.0: ctx_save ipc error -110, proceeding with suspend
[ 6439.048750] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x1010303 successful
[ 6439.048754] sof-audio-pci 0000:00:0e.0: FW Poll Status: reg=0x303 successful
[ 6439.048758] sof-audio-pci 0000:00:0e.0: DSP core(s) enabled? 0 : core_mask 3
[ 6439.048777] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000010 at  00000044
[ 6439.048782] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power 0
[ 6439.048784] sof-audio-pci 0000:00:0e.0: display power disable
```
Terminal output:
```

020-05-15 07:34:40 UTC Sub-Test: [INFO] Check for the kernel log status
2020-05-15 07:34:40 UTC [ERROR] Caught dmesg error
===========================>>
[ 6438.544629] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x80010000 size 216
[ 6438.544708] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[ 6438.544716] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000001 rirb 00
[ 6438.544718] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 6438.544735] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 6438.544737] sof-audio-pci 0000:00:0e.0: error: waking up any trace sleepers
[ 6438.544741] sof-audio-pci 0000:00:0e.0: error: failed to set dai config for SSP1-Codec
[ 6438.544744] sof-audio-pci 0000:00:0e.0: error: failed to restore pipeline after resume -110
[ 6439.048611] sof-audio-pci 0000:00:0e.0: error: ipc timed out for 0x40010000 size 76
[ 6439.048663] sof-audio-pci 0000:00:0e.0: error: unexpected fault 0x00000000 trace 0x00004000
[ 6439.048669] sof-audio-pci 0000:00:0e.0: error: hda irq intsts 0x00000000 intlctl 0xc0000000 rirb 00
[ 6439.048671] sof-audio-pci 0000:00:0e.0: error: dsp irq ppsts 0x00000000 adspis 0x00000000
[ 6439.048676] sof-audio-pci 0000:00:0e.0: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 6439.048679] sof-audio-pci 0000:00:0e.0: ctx_save ipc error -110, proceeding with suspend
<<===========================
2020-05-15 07:34:40 UTC Sub-Test: [ERROR] Catch error in dmesg
2020-05-15 07:34:40 UTC Sub-Test: [INFO] Test Result: FAIL!
```

**Environment**
    Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit: 7b2f053d9
    * SOF:https://github.com/thesofproject/sof/commits/master commit: f06da5
2) Name of the topology file
    * Topology: {sof-glk-da7219.tplg}
3) Name of the platform(s) on which the bug is observed.
    * Platform: {GLK Chrome with onboard codec DA7219 in I2S mode}

[sof&kernel log.zip](https://github.com/thesofproject/linux/files/4799787/sof.kernel.log.zip)

**Comment by plbossart** [comment] 2020-07-22 20:58
@sinahuang can you check if this still happens with the latest kernel/firmware/topology code? We need to make progress here, it's been 5+ weeks without progress

**Comment by Liviali155** [comment] 2020-07-27 06:23
Issue still can be reproduced with latest sof-dev (b31892bc) +master(1c53b8e9) when run suspend/resume stress test
<img width="379" alt="Capture" src="https://user-images.githubusercontent.com/56707932/88509975-b1da0480-d014-11ea-99ec-5cddc60381f7.PNG">

First round: Failed at 45/50
2nd round:Passed 50/50
3rd round:Passed 50/50
4th round :Passed 50/50
5th round:Passed 500/500
[sof-logger0720.log](https://github.com/thesofproject/linux/files/4980285/sof-logger0720.log)
[dmesg0720.log](https://github.com/thesofproject/linux/files/4980286/dmesg0720.log)

**Comment by keyonjie** [comment] 2020-08-24 02:46
Not seeing this recently with CI daily.

**Comment by keqiaozhang** [comment] 2020-09-02 01:39
Checked with today's code base and passed 500 iterations. Since this issue also not seeing in recently CI test. so let's close this issue.
Kernel: sof-dev /33fd4f99da78
SOF: master/78202631e766

**Closed as completed by keqiaozhang** 2020-09-02 01:39 UTC
Labels: bug, P2, GLK, I2S
