### ISSUE TITLE
[SDW] [Volteer] arecord -i does not work

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2730] opened 2021-02-03 00:25 UTC
Before we go in complicated tests, I tried to record from the echo reference without any playback, and get different results depending on whether the arecord -i option is used or not.

````
root@jf-tglu-volt-sdw-1:~# arecord -Dhw:0,3 -c2 -r48000 -fS16_LE -d 10 
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
RIFF$LWAVEfmt ���dataLroot@jf-tglu-volt-sdw-1:~# arecord -i -Dhw:0,3 -c2 -r48000 -fS16_LE -d 10 
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
RIFF$LWAVEfmt ���dataLstdout: Resource temporarily unavailable
````

**Comment by plbossart** [comment] 2021-02-03 00:35
Ironically 'aplay -vi -Dhw:0,2 -c2 -r48000 -fS16_LE /dev/zero' works fine and I can't seem to break it. This doesn't impact the recording of hw:0,3 in parallel.

**Comment by plbossart** [comment] 2021-02-04 16:41
@aiChaoSONG can you look into this? I don't understand how we can run complicated tests and my basic test fails.

**Comment by aiChaoSONG** [comment] 2021-02-05 02:14
@plbossart  If the output file is specified, both arecord commands with/without -i work well.  I have the same behavior with you if output file is not specified. I also try some other record pipelines on different platforms(SDW-sku0a32/I2S-helios), I get the same result. Seems we have to specify the output file for arecord.

**Comment by aiChaoSONG** [comment] 2021-02-05 02:32
@plbossart I guess you are debugging https://github.com/thesofproject/sof/issues/3714. To reproduce the issue faster, change 
line 58 in multiple-pause-resume.sh from `func_pipeline_export "$tplg" "type:any"` to `func_pipeline_export "$tplg" "type:any & smart_amp:any"`

PS: we don't have issue in running `aplay -Dhw:0,2` and `arecord -Dhw:0,3`  in parallel, we have issue in doing pause/release to  them in parallel. Manually reproducing this issue is hard, because only one terminal can have focus, your pause-release(press space) can only send to one of them.  you can run `aplay` in local terminal, and `arecord` in a remote terminal, and send pause-release from host and local keyboard simultaneously.

**Comment by plbossart** [comment] 2021-02-05 02:46
> @plbossart If the output file is specified, both arecord commands with/without -i work well. I have the same behavior with you if output file is not specified. I also try some other record pipelines on different platforms(SDW-sku0a32/I2S-helios), I get the same result. Seems we have to specify the output file for arecord.

Humm, I recall copy/pasting the command from CI tests and not seeing a good result either.
Maybe I made a mistake, but to clear this can you clarify what command works for you?

**Comment by plbossart** [comment] 2021-02-05 02:52
> @plbossart I guess you are debugging [thesofproject/sof#3714](https://github.com/thesofproject/sof/issues/3714). To reproduce the issue faster, change
> line 58 in multiple-pause-resume.sh from `func_pipeline_export "$tplg" "type:any"` to `func_pipeline_export "$tplg" "type:any & smart_amp:any"`
> 
> PS: we don't have issue in running `aplay -Dhw:0,2` and `arecord -Dhw:0,3` in parallel, we have issue in doing pause/release to them in parallel. Manually reproducing this issue is hard, because only one terminal can have focus, your pause-release(press space) can only send to one of them. you can run `aplay` in local terminal, and `arecord` in a remote terminal, and send pause-release from host and local keyboard simultaneously.

You have two pipelines and two states each, that's 4 combinations where you can test the state machine.
My take is that conceptually things are already broken because we have a component with two sources and another one with two sinks.

If we have timing issues with transitions on each pipeline tripping on each other that's a different problem.

**Comment by aiChaoSONG** [comment] 2021-02-05 03:09
> but to clear this can you clarify what command works for you?

```
aplay -Dhw:0,2 -c2 -r48000 -f S16_LE -i -vvv /dev/zero
arecord -Dhw:0,3 -c2 -r48000 -f S16_LE -i -vvv ./recorded.wav
```
@plbossart Above two commands work for me, and can be run in parallel.

**Comment by aiChaoSONG** [comment] 2021-02-05 03:11
@plbossart This is my previous finding, may give some hint?
> The commit thesofproject/linux@2dbd71d increase the possibility to reproduce the issue. Before this, issue never reproduced in our CI.

**Comment by keyonjie** [comment] 2021-02-22 03:25
so @plbossart this is not a valid issue? shall we close it?

**Comment by keyonjie** [comment] 2021-03-01 02:41
@plbossart let's close it, please reopen if needed.

**Closed as completed by keyonjie** 2021-03-01 02:41 UTC
Labels: SDW
