### ISSUE TITLE
[BUG] cl_dsp_init: timeout for HIPCIE done

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1472] opened 2019-11-13 05:52 UTC
**Bug Description**
run `sudo rtcwake -s 5 -m mem`, after the machine sleep back, check dmesg, you can see *cl_dsp_init: timeout for HIPCIE done* error

**To Reproduce**
1. reboot 
2. run `sudo rtcwake -s 5 -m mem`

**Reproduction Rate**
5/5

**Impact**
no functional impact, just error messages

**Platform & Environment**
Kernel: topic/sof-dev: `f55db62e`
SOF: master: `835d876b`
Tplg: sof-cml-rt1011-rt5682
Platform: ASUS CML Chromebook with RT5682 codec

```
[  112.521166] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0e0e successful
[  112.521173] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0e0e successful
[  112.521174] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[  112.521176] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[  113.021457] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
[  113.021461] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout for HIPCIE done
[  113.021468] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  113.021472] sof-audio-pci 0000:00:1f.3: error: status = 0xffffffff panic = 0xffffffff
[  113.021476] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  113.021482] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[  113.021487] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  113.021491] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[  113.021495] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
[  113.021498] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
[  113.021502] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[  113.021511] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0e successful
[  113.021514] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[  113.021519] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
```
[sof_trace.log](https://github.com/thesofproject/linux/files/3839590/sof_trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3839591/dmesg.log)

**Comment by ranj063** [comment] 2019-11-13 06:08
@aiChaoSONG Can you please check if this problem is solved by reverting 0e1a9616

**Comment by aiChaoSONG** [comment] 2019-11-13 06:24
@ranj063 reverting 0e1a961 helps with this issue.  @keyonjie we may need to rethink, and deal with code_loading beautifully.

**Comment by dengyangchao** [comment] 2019-11-13 07:14
Issue also can reproduce on CML Chrome with onboard codec RT5682 in I2S mode when run ```Soix_test.sh```.

Firmware: 835d876b https://github.com/thesofproject/sof/commits/master
Kernel: f55db62e https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-cml-rt5682-max98357a.tplg same as firmware

```
[  150.682581] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  150.714112] sd 1:0:0:0: [sda] Synchronizing SCSI cache
[  150.714792] sd 1:0:0:0: [sda] Stopping disk
[  151.011104] ACPI: EC: interrupt blocked
[  154.750672] ACPI: EC: interrupt unblocked
[  154.778797] sd 1:0:0:0: [sda] Starting disk
[  155.012978] sof-audio-pci 0000:00:1f.3: loading firmware
[  155.012992] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000002 at  00000048
[  155.012999] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000000 at  00000048
[  155.013008] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[  155.013014] sof-audio-pci 0000:00:1f.3: Debug PCIW: 00000004 at  00000044
[  155.013017] sof-audio-pci 0000:00:1f.3: booting DSP firmware
[  155.013116] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  155.013141] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  155.013150] sof-audio-pci 0000:00:1f.3: period_bytes:0x0
[  155.013153] sof-audio-pci 0000:00:1f.3: periods:1
[  155.013292] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0e0e successful
[  155.013304] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0e0e successful
[  155.013310] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[  155.013317] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[  155.083963] ata2: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
[  155.086036] ata2.00: configured for UDMA/133
[  155.513496] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
[  155.513501] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout for HIPCIE done
[  155.513511] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  155.513518] sof-audio-pci 0000:00:1f.3: error: status = 0xffffffff panic = 0xffffffff
[  155.513523] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[  155.513534] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[  155.513542] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  155.513548] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[  155.513555] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
[  155.513558] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
[  155.513565] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[  155.513578] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0e successful
[  155.513584] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[  155.513591] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
```


[test_0_fail.log](https://github.com/thesofproject/linux/files/3839796/test_0_fail.log)

**Comment by dengyangchao** [comment] 2019-11-13 07:29
Also can reproduce on 
ICL RVP with onboard codec ALC700 in HDA mode(s2idle)
GLK Chrome with onboard codec DA7219 in I2S mode(s2idle)

And checked on CFL-S RVP ALC700 in HDA mode(deep), issue can't reproduce 
so issue only can reproduce on **s2idle** mode, and related with #1387

**Comment by YvonneYang2** [comment] 2019-11-13 08:36
Issue can be reproduced on CML SDW Laptop with ALC711+ ALC1308+ ALC715 mode.

kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: fb40b85 + https://github.com/thesofproject/linux/pull/1451
FW: https://github.com/thesofproject/sof/commits/master  commit: 835d876
tplg: same path as FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by keyonjie** [comment] 2019-11-13 17:44
Thanks for reporting this, if we go through the dmesg log, we can find the 1st try in cl_dsp_init() failed and the subsequent try succeed, this is interesting @ranj063

**Comment by keyonjie** [comment] 2019-11-13 19:29
I root caused what happens there, will provide a update fix soon. @plbossart @ranj063

**Comment by keyonjie** [comment] 2019-11-13 19:53
@ranj063 @plbossart after applied the fix from PR https://github.com/thesofproject/linux/pull/1479, the issue is disappear even with commit 0e1a961 applied, that is consistent with what @dengyangchao observed, thank you.

@ranj063 @plbossart @aiChaoSONG I feel happy that the clean up commit actually helped us to export potential hidden issues. :-)

**Comment by dengyangchao** [comment] 2019-11-14 02:23
Reopen issue,  with #1477 merged, issue still exist.

Firmware: decd2064 https://github.com/thesofproject/sof/commits/master
Kernel: fd302303 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-cml-rt5682-max98357a.tplg same as firmware

```
[   90.530136] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[   90.530144] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   90.607326] ata2: SATA link up 6.0 Gbps (SStatus 133 SControl 300)
[   90.608963] ata2.00: configured for UDMA/133
[   91.030485] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
[   91.030490] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout for HIPCIE done
[   91.030500] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[   91.030508] sof-audio-pci 0000:00:1f.3: error: status = 0xffffffff panic = 0xffffffff
[   91.030514] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[   91.030525] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[   91.030533] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[   91.030540] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask f
[   91.030548] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
[   91.030551] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
[   91.030564] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0f successful
[   91.030578] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f0f0e successful
[   91.030584] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[   91.030591] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   91.031268] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x80000000 successful
```

[test_0_fail.log](https://github.com/thesofproject/linux/files/3844303/test_0_fail.log)

**Comment by sinahuang** [comment] 2019-11-14 02:32
Verified this issue with MSI mode on TGL RVP, issue still can be reproduced.

```
[   65.125294] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   65.625623] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x0 timedout
[   65.625626] sof-audio-pci 0000:00:1f.3: error: cl_dsp_init: timeout for HIPCIE done
[   65.625643] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[   65.625650] sof-audio-pci 0000:00:1f.3: error: status = 0xffffffff panic = 0xffffffff
[   65.625657] sof-audio-pci 0000:00:1f.3: unknown ROM status value ffffffff
[   65.625671] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010f0f successful
[   65.625685] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf000f0f successful
[   65.625689] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[   65.625697] sof-audio-pci 0000:00:1f.3: error: Error code=0xffffffff: FW status=0xffffffff
[   65.625698] sof-audio-pci 0000:00:1f.3: error: iteration 0 of Core En/ROM load failed: -110
[   65.626400] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010f0f successful
[   65.626444] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010f0e successful
[   65.626450] sof-audio-pci 0000:00:1f.3: unstall/run core: core_mask = 1
[   65.626475] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   65.627138] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x80000000 successful
[   65.627153] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010e0e successful
[   65.627284] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   65.692595] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x5000001 successful
[   65.708245] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x5 successful
[   65.708486] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[   65.708503] sof-audio-pci 0000:00:1f.3: Firmware download successful, booting...
[   65.717603] sof-audio-pci 0000:00:1f.3: ipc rx: 0x70000000: FW_READY


```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 413de1
FW: https://github.com/thesofproject/sof/commits/master commit: decd206
Tplg: Same with TGL FW branch commit: sof-tgl-rt711-rt1308-nohdmi.tplg rename to sof-tgl-rt711-rt1308.tplg
Platform:TGL RVP with onboard ACL711 in SDW mod and ALC1308 in I2S mode.

[dmesg.log](https://github.com/thesofproject/linux/files/3844322/dmesg.log)
[sof_error_trace.log](https://github.com/thesofproject/linux/files/3844323/sof_error_trace.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/3844325/sof_trace.log)

**Comment by dengyangchao** [comment] 2019-11-15 03:23
Tried PR #1479 on GLK Chrome with onboard codec DA7219 in I2S mode(**S2idle**)
Issue can't reproduce through below test:
1. Run stress test via```S0ix_test.sh``` 
2. Playing -> pause -> suspend -> wakeup -> resume
3. Suspend & Resume device during audio playback 

[test_99_pass.log](https://github.com/thesofproject/linux/files/3849659/test_99_pass.log)

**Comment by ranj063** [comment] 2019-11-20 03:32
@mengdonglin this issue should be assigned to @keyonjie. This was caused by his changes to the S0ix implementation and he's working on the fix.

**Comment by mengdonglin** [comment] 2019-11-22 01:22
Remove P1 label since there is  no functional impact, just error messages. And assigned to @keyonjie

**Comment by keyonjie** [comment] 2019-11-22 08:01
https://github.com/thesofproject/linux/pull/1524 will fix this.

**Comment by dengyangchao** [comment] 2019-12-04 10:11
Tried #1524 on ICL RVP with onboard codec ALC700 in HDA mode (s2idle) 
issue can't reproduce.
Tried two scenarios in s2idle:
1. suspend&resume via command"sudo rtcwake -m mem -s 10" without playback.
2. suspend&resume via command"sudo rtcwake -m mem -s 10" with playback.

[dmesg.log](https://github.com/thesofproject/linux/files/3921204/dmesg.log)

**Comment by mengdonglin** [comment] 2019-12-25 03:04
To be fixed by PR https://github.com/thesofproject/linux/pull/1631 by Ranjani

**Comment by YvonneYang2** [comment] 2019-12-25 04:26
Tested it with latest topic/sof-dev(7fde475) + #1631 , issue cannot be reproduced on CML laptop with HDA ALC3204.

**Comment by dengyangchao** [comment] 2019-12-25 08:18
Tested it with latest topic/sof-dev(7fde475) + #1631 , issue cannot be reproduced on
CML Chrome with I2S RT5682
GLK Chrome with I2S  DA7219

**Comment by sinahuang** [comment] 2019-12-25 08:19
Check this issue with latest sof-dev(7fde475) + #1631 on TGL-U RVP with codec ALC711 in HDA mode, issue can't be reproduced.

**Comment by xiulipan** [comment] 2019-12-26 04:48
@Bin-QA Please help to check if our test scripts can identify such issue.
@ranj063 @keyonjie If we have retry logic here, maybe we can change the logs into warning instead of error?

**Comment by Bin-QA** [comment] 2019-12-26 05:07
I think this PR can identify the issue like this: https://github.com/thesofproject/sof-test/pull/16

**Comment by dengyangchao** [comment] 2020-01-14 02:29
Since #1631 merged, issue can't be reproduced, close.

**Closed as completed by dengyangchao** 2020-01-14 02:29 UTC
Labels: bug, GLK, ICL, CML, CFL, TGL, suspend resume
