### ISSUE TITLE
[BUG]Cannot detect HDMI/DP unplugged status when no monitor/eDP is connected after unplug 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1440] opened 2019-11-06 09:57 UTC
If no monitor/eDP is connected after unplugging HDMI/DP, amixer contents cannot detect the unplugged status.

For example: 
1. Only connect HDMI external port(no eDP or DP connected), then boot up.
2. Check amixer contents, it can detect HDMI connected status(HDMI Jack value is on)
3. Unplug HDMI external port, then there is no monitor and eDP connected. Check amixer contents, it still shows HDMI Jack value is on.

Note:
If has monitor/eDP connected after unplugging HDMI/DP ecternal port, issue cannot be reproduced. 

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 313bb6e 
FW: https://github.com/thesofproject/sof/commits/master  commit: 9b6ad970
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

**Comment by dengyangchao** [comment] 2019-11-06 10:06
Issue also can reproduce on CFL-S RVP with onboard codec ALC700 in HDA mode

Environment
Firmware: 9b6ad970 https://github.com/thesofproject/sof/commits/master
Kernel: 4e76b4a1 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by Liviali155** [comment] 2019-11-06 10:14
issue can also be reproduced on apl up2 with codec  PCM512x in I2S mode
Environment
 Firmware: 9b6ad970 https://github.com/thesofproject/sof/commits/master
 Kernel: 4e76b4a https://github.com/thesofproject/linux/commits/topic/sof-dev
 Topology: file: tools/topology/sof-apl-pcm512x.tplg  same as firmware

**Comment by plbossart** [comment] 2019-11-12 00:07
@Liviali155 the best result would be to try Up2 w/ HDMI without any I2S code (w/ hda-generic-idisp mode)

**Comment by Liviali155** [comment] 2019-11-12 05:49
> @Liviali155 the best result would be to try Up2 w/ HDMI without any I2S code (w/ hda-generic-idisp mode)

I used sof-hda-generic-idisp.tplg to verify,issue can reproduce,details as below:
Firmware: b27b218a https://github.com/thesofproject/sof/commits/master
Kernel: 0e1a9616 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-idisp.tplg same as firmware

**Comment by kv2019i** [comment] 2019-11-18 12:56
I could not verify this on CFL RVP, but on Up2 this happened.

Based on logs, this looks like a i915 issue. The physical connector disconnect is detected just fine, but i915 never calls the eld notify callback in this case. If one boots up without HDMI connected, then behaviour is as expected, so something goes wrong if system is booted with the HDMI connected at boot. I will investigate a bit further and then move to i915 bugzilla.

**Comment by dengyangchao** [comment] 2020-02-13 07:17
@kv2019i Please help to check the DRM logs, tried on APL-UP2-PCM512X.
Connected with DP and HDMI, 
1.Unplug HDMI >dmesg1.log
2.Unplug DP > dmesg2.log
If it is I915 issue, can we close it?

[dmesg1.log](https://github.com/thesofproject/linux/files/4196952/dmesg1.log)
[dmesg2.log](https://github.com/thesofproject/linux/files/4196954/dmesg2.log)

**Comment by dengyangchao** [comment] 2020-02-14 08:41
Report and track on https://gitlab.freedesktop.org/drm/intel/issues/1215 
Close for not sof issue

**Closed as completed by dengyangchao** 2020-02-14 08:41 UTC
Labels: bug, P3, APL, ICL, CFL

**Comment by kv2019i** [comment] 2020-02-14 09:24
@dengyangchao Thanks for moving. As this has been lower in priority, I haven't had time to investigate this, but most probably this is an i915 problem. If/when I have to study this more, I'll add comments to the i915 gitlab item you filed.
