### ISSUE TITLE
[Feature][SDW]Should be able to detect headset unplug/plug-in status when sdw-master-0 pm status suspended.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1409] opened 2019-10-31 06:44 UTC
**Describe the bug**
Should support clock stop mode, can detect headset plug-in/unplug status when sdw-master-0 pm status is suspended.

**To Reproduce**
1. System boot up without headset.
2. Open sound setting.
3. Check the sdw-master-0 pm status is suspended via cat "/sys/bus/soundwire/devices/sdw-master-0/power/runtime_status"
4. Plug in headset and check headphone and headset mic jack detect status via "amixer contents"
 
**frequency**
100%

**Expected result**
Can detect headset is plugged in when sdw-master-0 pm status is suspended.

**Actual result**
Cannot detect headset is plugged in when sdw-master-0 pm status is suspended.
```
numid=60,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=61,iface=CARD,name='Headset Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 9f1bd5b 
FW: https://github.com/thesofproject/sof/commits/master  commit: 59c9338
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

[dmesg.log](https://github.com/thesofproject/linux/files/3792463/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3792464/logger.log)

**Comment by plbossart** [comment] 2019-10-31 13:55
Duplicate of https://github.com/thesofproject/linux/issues/1380

**Closed as completed by plbossart** 2019-10-31 13:55 UTC
Labels: bug, duplicate, enhancement, ICL, SDW
