### ISSUE TITLE
[Bug][UCM][CML]One time pop noise output via internal speaker when plug  headset during paplay

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1862] opened 2020-03-05 06:57 UTC
**Describe the bug**
One time pop noise output via internal speaker when plug in headset or unplug headset during paplay

Note: This pop noise is observed from PR#24 [split profile and enable source auto switch when plug in /unplug headset]. Error not seen without PR#24.  Error also seen with PR#28

**To Reproduce** 
Step1: paplay wav/music.wav -vvv
Step2: Plug in headset
Step3: Unplug headset
Step4: Repeat step2 and step3

**Reproduced rate**
90%
 
**Expected result**
No pop noise should be observed.

**Actual result**
One time pop noise output via internal speaker when plug in headset or unplug headset during paplay

**Environment**
Kernel:release/sdw_cml_hotfix, commit:38d0dcd
FW: commits/cml-010-hot-fix, commit: 0ed0dba
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg 
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode
ucm: https://github.com/thesofproject/alsa-ucm-conf.git+PR#24  or PR#28

**Comment by ClarexZhou** [comment] 2020-03-05 06:57
@libinyang please help to check first

**Comment by ClarexZhou** [comment] 2020-03-05 07:01
The pop noise sound like the pop noise in scenario #1376

**Comment by libinyang** [comment] 2020-03-05 07:32
This bug should not be related to UCM or pulseaudio.
It can easily be reproduced by aplay. Seems to be codec driver or fw or controller driver issue.

**Comment by bardliao** [comment] 2020-03-05 11:10
@ClarexZhou Could you use the following command to mute/unmute in playback and see if there is a pop when mute/unmute?
``amixer cset name='Speaker Switch' 0``
and
``amixer cset name='Speaker Switch' 1``

**Comment by ClarexZhou** [comment] 2020-03-05 11:31
@bardliao   no this pop noise if using above cset instead of headset plug.
Here is the amixer contents with and without headset with UCM PR#24
[24headset.txt](https://github.com/thesofproject/linux/files/4292732/24headset.txt)
[24speaker.txt](https://github.com/thesofproject/linux/files/4292734/24speaker.txt)

Here is the amixer contents with and without headset with UCM PR#28
[noheadset.txt](https://github.com/thesofproject/linux/files/4292685/noheadset.txt)
[headset.txt](https://github.com/thesofproject/linux/files/4292686/headset.txt)

**Comment by ClarexZhou** [comment] 2020-03-05 12:11
Error also can be reproduced with below steps:
1. paplay 1.wav -vvv
2. open system sound setting, select output source, to switch sources between Speaker and Headphone.

Error not seen on UCM without PR#24 or without PR#28.

**Comment by kv2019i** [comment] 2020-03-10 08:15
@mengdonglin This is missing an assignee -- P1 bug with no updates in 5 days

**Comment by ClarexZhou** [comment] 2020-03-16 07:26
Error not seen with kernel sof-dev, commit: 0f90705, contains PR #1887 + PR #1897  and FW: https://github.com/thesofproject/sof/tree/cml-010-hot-fix, commit https://github.com/thesofproject/sof/commit/0ed0dbae7a73f7d3a648199c0ad9f95944d8ec85 + commit thesofproject/sof@f73332e 

But still has slight noise on internal speaker with same kernel  sof-dev, commit: 0f90705, contains PR #1887 + PR #1897  and FW: Master, commit: thesofproject/sof@afd97708

**Comment by YvonneYang2** [comment] 2020-04-22 06:08
Since ucm2 issue https://github.com/thesofproject/linux/issues/1999, output source won't auto switch to headphone when plug in headphone. So tested it via switching to headphone manually, issue cannot be reproduced after #1897 merged.  Close the bug.

Test recipe:
Kernel: topic/sof-dev(8dc1789) 
FW: master(0befebb7)

**Closed as completed by YvonneYang2** 2020-04-22 06:08 UTC
Labels: bug, P1, CML, UCM
