### ISSUE TITLE
[FEATURE] Explicit clock control

### ISSUE THREAD

**Issue by brentlu** [thesofproject/linux#2907] opened 2021-05-10 03:26 UTC
Some codecs need external clock (mclk or bclk) to be ready in prepare stage or some function may broken.

To support those codec, we need to implement explicit clock control so machine driver could enable/disable the clock via DAPM supply widget or set_bias_level callback.

This feature has been implemented on SST FW running on Chrome KBL platforms. Following are the mailthread:
https://mailman.alsa-project.org/pipermail/alsa-devel/2017-November/127833.html
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-October/156161.html

**Comment by brentlu** [comment] 2021-05-10 03:27
same request in sof
https://github.com/thesofproject/sof/issues/4156

**Comment by plbossart** [comment] 2021-06-10 19:47
duplicate of https://github.com/thesofproject/linux/issues/314

let's close this one, we will work on this when we have multi-client support. for short-term it's enough to support early bitclk enablement.

**Closed as completed by plbossart** 2021-06-10 19:47 UTC
Labels: enhancement, P1
