### ISSUE TITLE
[Bug] [CML] Call Trace when using RT 711 headset playback/capture with UCM2 on ubuntu 20.04

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1979] opened 2020-04-03 10:43 UTC
**Describe the bug**
Call Trace when using RT 711 headset playback/capture with UCM2 on ubuntu 20.04

Error not seen with ubuntu 18.04 with UCM1.  

**To Reproduce**
1.  System os is 20.04 (get from cdimage.ubuntu.com/ubuntu/daily-live/current)
2. UCM2 https://github.com/thesofproject/alsa-ucm-conf/pull/29 is used and pulseaudio is enabled. 
3. Boot up system 
4. "aplay -Dhw:0,0 -f dat 1.wav -vv -i"

**Reproduction Rate**
4/5

**Expected behavior**
Headset playback should works normally

**Impact**
aplay stuck and Call Trace in dmesg then system freeze.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: {fce7f934} release/sof-dev
    * SOF: {d7ad0c13} Master
2) Name of the topology file
    * Topology: sof-cml-rt711-rt1308-mono-rt715.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: CML-U laptop with RT711 RT1308 and RT715 in SDW mode

<details>
 <summary>Dmesg</summary>
````
[  133.922848] sof-audio-pci 0000:00:1f.3: pcm: free stream 2 dir 0
[  133.923960] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  133.924155] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  133.924343] sof-audio-pci 0000:00:1f.3: pcm: close stream 2 dir 0
[  134.489386] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  134.489410] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  187.993298] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 0
[  187.993300] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[  187.993301] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[  187.993302] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[  187.998377] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  187.998542] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  187.998544] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 0
[  187.998546] sof-audio-pci 0000:00:1f.3: generating page table for 00000000d61e5ee2 size 0xffc0 pages 16
[  187.998550] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[  187.998563] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  187.998565] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[  187.998565] sof-audio-pci 0000:00:1f.3: periods:4
[  187.998574] sof-audio-pci 0000:00:1f.3: stream_tag 1
[  187.998578] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  187.998976] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  187.998977] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790528
[  187.998999] divide error: 0000 [#1] SMP NOPTI
[  187.999002] CPU: 3 PID: 2218 Comm: aplay Not tainted 5.6.0-rc6-daily-default-20200403 #1
[  187.999003] Hardware name: Dell Inc. Latitude 9510/, BIOS 0.1.3 10/01/2019
[  187.999006] RIP: 0010:sdw_compute_params+0x343/0x1000 [soundwire_generic_allocation]
[  187.999007] Code: 8c 00 00 00 41 8d 45 ff 4d 89 e1 48 89 c7 48 c1 e0 04 4c 8d 5c 06 10 48 89 f1 41 8b 31 31 d2 44 89 d0 48 83 c1 10 49 83 c1 04 <f7> f6 89 71 f0 89 41 f4 49 39 cb 75 e3 48 8b 04 24 48 8b 88 e8 00
[  187.999008] RSP: 0018:ffffab9b01283be0 EFLAGS: 00010282
[  187.999010] RAX: 0000000000b71b00 RBX: 0000000000000002 RCX: ffffa26c4fcf7550
[  187.999010] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000001
[  187.999011] RBP: 0000000000000001 R08: 0000000000000002 R09: ffffa26c7436c1ec
[  187.999012] R10: 0000000000b71b00 R11: ffffa26c4fcf7560 R12: ffffa26c7436c1e8
[  187.999012] R13: 0000000000000002 R14: ffffa26c9fdde118 R15: 000000000000bb80
[  187.999013] FS:  00007f778dc04440(0000) GS:ffffa26ca44c0000(0000) knlGS:0000000000000000
[  187.999014] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  187.999015] CR2: 00007ffd84548c50 CR3: 0000000287276003 CR4: 00000000003606e0
[  187.999016] Call Trace:
[  187.999020]  sdw_prepare_stream+0xfe/0x2e0 [soundwire_bus]
[  187.999022]  intel_prepare+0x103/0x150 [soundwire_intel]
[  187.999026]  soc_pcm_prepare+0xdc/0x200 [snd_soc_core]
[  187.999030]  dpcm_be_dai_prepare+0x9c/0x110 [snd_soc_core]
[  187.999032]  dpcm_fe_dai_prepare+0x8e/0x140 [snd_soc_core]
[  187.999036]  snd_pcm_do_prepare+0x1f/0x40 [snd_pcm]
[  187.999038]  snd_pcm_action_single+0x31/0x80 [snd_pcm]
[  187.999040]  snd_pcm_action_nonatomic+0x5c/0x60 [snd_pcm]
[  187.999042]  snd_pcm_common_ioctl+0x709/0x1020 [snd_pcm]
[  187.999045]  ? selinux_file_ioctl+0x143/0x200
[  187.999048]  snd_pcm_ioctl+0x25/0x30 [snd_pcm]
[  187.999050]  ksys_ioctl+0x8d/0xb0
[  187.999051]  __x64_sys_ioctl+0x11/0x20
[  187.999053]  do_syscall_64+0x43/0x160
[  187.999055]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  187.999057] RIP: 0033:0x7f778de713cb
[  187.999058] Code: 0f 1e fa 48 8b 05 c5 3a 0d 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 0f 1f 44 00 00 f3 0f 1e fa b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 95 3a 0d 00 f7 d8 64 89 01 48
[  187.999059] RSP: 002b:00007ffd8454b438 EFLAGS: 00000202 ORIG_RAX: 0000000000000010
[  187.999060] RAX: ffffffffffffffda RBX: 0000558bb5107e20 RCX: 00007f778de713cb
[  187.999061] RDX: 0000000000000000 RSI: 0000000000004140 RDI: 0000000000000004
[  187.999061] RBP: 0000558bb5107da0 R08: 0000000000000000 R09: 0000000000003ff0
[  187.999062] R10: 00007f778df81739 R11: 0000000000000202 R12: 00007ffd8454b510
[  187.999063] R13: 00007ffd8454b480 R14: 000000000000bb80 R15: 000000000000bb80
[  187.999064] Modules linked in: dell_wmi wmi_bmof snd_soc_rt711 snd_soc_rt1308_sdw snd_soc_rt715 snd_soc_sof_sdw snd_soc_hdac_hdmi snd_soc_rt700 regmap_sdw snd_soc_dmic dell_laptop dell_smbios dell_wmi_descriptor dcdbas x86_pkg_temp_thermal intel_powerclamp snd_hda_codec_hdmi snd_sof_pci snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_soc_acpi_intel_match snd_sof snd_sof_xtensa_dsp snd_soc_acpi snd_hda_ext_core ledtrig_audio snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation snd_soc_core snd_compress soundwire_cadence soundwire_bus snd_hda_codec snd_hwdep snd_hda_core snd_pcm snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq snd_seq_device snd_timer i915 iwlmvm snd i2c_algo_bit soundcore drm_kms_helper syscopyarea sysfillrect sysimgblt iwlwifi fb_sys_fops hid_multitouch processor_thermal_device intel_soc_dts_iosf mei_me mei wmi int3403_thermal int340x_thermal_zone int3400_thermal acpi_thermal_rel drm efivarfs intel_lpss_pci xhci_pci intel_lpss
[  187.999083]  mfd_core xhci_hcd i2c_hid
[  187.999094] ---[ end trace d8ea7fbe15d6bc38 ]---
[  187.999096] RIP: 0010:sdw_compute_params+0x343/0x1000 [soundwire_generic_allocation]
[  187.999097] Code: 8c 00 00 00 41 8d 45 ff 4d 89 e1 48 89 c7 48 c1 e0 04 4c 8d 5c 06 10 48 89 f1 41 8b 31 31 d2 44 89 d0 48 83 c1 10 49 83 c1 04 <f7> f6 89 71 f0 89 41 f4 49 39 cb 75 e3 48 8b 04 24 48 8b 88 e8 00
[  187.999098] RSP: 0018:ffffab9b01283be0 EFLAGS: 00010282
[  187.999098] RAX: 0000000000b71b00 RBX: 0000000000000002 RCX: ffffa26c4fcf7550
[  187.999099] RDX: 0000000000000000 RSI: 0000000000000000 RDI: 0000000000000001
[  187.999100] RBP: 0000000000000001 R08: 0000000000000002 R09: ffffa26c7436c1ec
[  187.999100] R10: 0000000000b71b00 R11: ffffa26c4fcf7560 R12: ffffa26c7436c1e8
[  187.999101] R13: 0000000000000002 R14: ffffa26c9fdde118 R15: 000000000000bb80
[  187.999102] FS:  00007f778dc04440(0000) GS:ffffa26ca44c0000(0000) knlGS:0000000000000000
[  187.999103] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  187.999103] CR2: 00007ffd84548c50 CR3: 0000000287276003 CR4: 00000000003606e0
[  188.989523] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  188.989553] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
````
</details>

[sof_logger_error.txt](https://github.com/thesofproject/linux/files/4426638/sof_logger_error.txt)
[sof_logger_full.txt](https://github.com/thesofproject/linux/files/4426639/sof_logger_full.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/4426640/dmesg.txt)

**Comment by plbossart** [comment] 2020-04-03 13:40
that looks bad, division by zero?

````
[  187.998999] divide error: 0000 [#1] SMP NOPTI
[  187.999002] CPU: 3 PID: 2218 Comm: aplay Not tainted 5.6.0-rc6-daily-default-20200403 #1
[  187.999006] RIP: 0010:sdw_compute_params+0x343/0x1000 [soundwire_generic_allocation]
````

**Comment by YvonneYang2** [comment] 2020-04-07 05:33
Close it since not issue not reproduced with latest sof-dev(commit:052e45d7) + master(commit:b4e8b1e) + ucm2 ( https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +PR#29 )

**Closed as completed by YvonneYang2** 2020-04-07 05:33 UTC
Labels: bug, P1, CML, SDW
