### ISSUE TITLE
[TGL][SDW][RT711] Initialization not complete, timed out in suspend-resume test

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#2599] opened 2020-12-04 02:19 UTC
**Description**
In daily report 962, several TGL device show below error message  in suspend-resume test case, include TGL_RVP_SDW,  TGLU_ANDR_SDCA and TGL_OLPMLK_RT715 and CML_OLP_RT711
```
[ 8611.896412] kernel: rt711 sdw:0:25d:711:0: Initialization not complete, timed out
[ 8611.896427] kernel: PM: dpm_run_callback(): rt711_dev_resume+0x0/0x90 [snd_soc_rt711] returns -110
[ 8611.896433] kernel: PM: Device sdw:0:25d:711:0 failed to resume: error -110
```

**Recipe**
Kernel Branch: topic/sof-dev
Kernel Commit:  25012df6
SOF Branch: master
SOF Commit:  cc1cd8a4af1b

[dmesg.txt](https://github.com/thesofproject/linux/files/5640169/dmesg.txt)

Reproduced in:
- https://sof-ci.01.org/softestpr/PR561/build521/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback (run-all-tests.sh not involved)

**Comment by plbossart** [comment] 2020-12-04 17:33
That's not good... Do we know what has changed since the last case that worked? We haven't seen those issues for weeks, it's surprising that they pop-up again.

@bardliao @RanderWang FYI.

**Comment by bardliao** [comment] 2020-12-07 12:33
I think we should firstly find a easier way to reproduce it. I can only see this issue in run-all-tests.sh. I can't see it if I run ./check-suspend-resume.sh only.

**Comment by plbossart** [comment] 2020-12-07 16:12
@bardliao it's reproduced in other CI tests.
I agree that it's not clear why that happens only when we run multiple tests, but the problem does exist :-)

**Comment by bardliao** [comment] 2020-12-08 01:58
@plbossart Yep, my point is that if we want to figure out when did the issue start from, we need a easier way to reproduce it. But you have fixed it by #2603 :)

**Comment by plbossart** [comment] 2020-12-08 03:42
I am not happy though, I'd really want to know what causes this test to fail in the sequence - something must interfere. it's very very odd that the suspend-resume tests work if there is nothing done prior.

**Comment by keyonjie** [comment] 2020-12-15 03:02
lower priority to P2 as it is not a usual end user scenario with kmod remove/install.

**Comment by bardliao** [comment] 2020-12-15 06:03
This only happens after https://github.com/thesofproject/linux/commit/d5dcce0c414fcbfe4c2037b66ac69ea5f9b3f75cand https://github.com/thesofproject/linux/commit/99aed9227073fb34ce2880cbc7063e04185a65e1 and two iterations of kmod test.

**Comment by plbossart** [comment] 2020-12-15 16:06
> lower priority to P2 as it is not a usual end user scenario with kmod remove/install.

No. This breaks our CI and needs to be fixed as P1. no exceptions, sorry. You are sending a really bad message here.

**Comment by marc-hb** [comment] 2020-12-17 23:40
> This only happens after d5dcce0 99aed92 and two iterations of kmod test.

@bardliao can you submit to sof-test a test change or test parameter/configuration that reproduces more easily? It doesn't have to be in CI if it takes long but it should be at least in nightly tests.

> Yep, my point is that if we want to figure out when did the issue start from, we need a easier way to reproduce it. But you have fixed it by #2603 :)

Reverting fixes locally is required to "test the test". If the reverts are too complicated then backtracking is another option.

**Comment by keyonjie** [comment] 2020-12-21 01:39
> > lower priority to P2 as it is not a usual end user scenario with kmod remove/install.
> 
> No. This breaks our CI and needs to be fixed as P1. no exceptions, sorry. You are sending a really bad message here.

Thanks for your feedback @plbossart . That was the decision from the bug scrub meeting. FWIW, I have no objection to mark it P1 since Bard and you who actually works on it agree. :)

**Comment by keyonjie** [comment] 2020-12-21 01:41
assign it to @bardliao who actually already work on it.

**Comment by keyonjie** [comment] 2020-12-21 02:49
will PR fix this issue: https://github.com/thesofproject/linux/pull/2635

**Comment by mengdonglin** [comment] 2020-12-22 02:14
Closing as PR #2635 was merged.

**Comment by marc-hb** [comment] 2021-01-04 23:27
> Closing as PR #2635 was merged.

I hope you meant "as #2635 was merged **and** the tests have been consistently passing" :-)

Either way, re-opening based on the most recent comments in #2635, more specifically: "we don't need this" and "please prepare a revert".

**Closed as completed** 2021-01-05 07:57 UTC
Labels: bug, P1, TGL, SDW
