### ISSUE TITLE
[BUG][BYT]error: resuming DSP -524

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/linux#1724] opened 2020-01-17 04:47 UTC
**Describe the bug**
SOF did not load correctly and no PCM shows on BYT.

**To Reproduce**
boot up

**Expected behavior**
aplay -l should show something.

**Environment**
FW Branch master
Commit: dbb70c84
kernel:
Branch:sof-dev
Commit: 0cf356c6

**dmesg**
```
[   20.449735] sof-audio-acpi 80860F28:01: firmware boot complete
[   20.449783] sof-audio-acpi 80860F28:01: generating page table for 00000000de7c6d6f size 0x10000 pages 16
[   20.449788] sof-audio-acpi 80860F28:01: dma_trace_pages: 16
[   20.449802] sof-audio-acpi 80860F28:01: stream_tag: 0
[   20.449806] sof-audio-acpi 80860F28:01: error: resuming DSP -524
[   20.449920] sof-audio-acpi 80860F28:01: error: can't set params for DMA for trace -524
[   20.450069] sof-audio-acpi 80860F28:01: warning: failed to initialize trace -524
[   20.450213] sof-nocodec sof-nocodec: info: override BE DAI link NoCodec-0
[   20.450218] sof-nocodec sof-nocodec: info: override BE DAI link NoCodec-1
[   20.450221] sof-nocodec sof-nocodec: info: override BE DAI link NoCodec-2
[   20.450358] sof-audio-acpi 80860F28:01: loading topology:intel/sof-tplg/sof-byt-nocodec.tplg
[   20.488414] sof-audio-acpi 80860F28:01: Topology: ABI 3:12:0 Kernel ABI 3:12:0
[   20.488465] sof-audio-acpi 80860F28:01: tplg: ready widget id 0 pipe 1 type 1 name : codec_out0 stream none
[   20.488470] sof-audio-acpi 80860F28:01: warning: widget type 1 name codec_out0 not handled
[   20.488479] sof-audio-acpi 80860F28:01: tplg: ready widget id 1 pipe 1 type 23 name : PCM0P stream Low Latency Playback 0
[   20.488485] sof-audio-acpi 80860F28:01: loaded host PCM0P
[   20.488489] sof-audio-acpi 80860F28:01:  config: periods snk 2 src 0 fmt 0
[   20.488494] sof-audio-acpi 80860F28:01: error: resuming DSP -524
[   20.488611] sof-audio-acpi 80860F28:01: error: DSP failed to add widget id 0 type 23 name : PCM0P stream Low Latency Playback 0 reply 0
[   20.488799] sof-audio-acpi 80860F28:01: ASoC: failed to load widget PCM0P
[   20.488908] sof-audio-acpi 80860F28:01: error: tplg component load failed -524
[   20.489286] sof-audio-acpi 80860F28:01: error: failed to load DSP topology -22
[   20.489408] sof-audio-acpi 80860F28:01: ASoC: failed to probe component -22
[   20.489564] sof-nocodec sof-nocodec: ASoC: failed to instantiate card -22
[   20.489782] sof-nocodec: probe of sof-nocodec failed with error -22
```

**Comment by xiulipan** [comment] 2020-01-17 04:48
@ClarexZhou @fredoh9 I also see BDW and BSW failed from daily test result. Could you confirm?

**Comment by ClarexZhou** [comment] 2020-01-17 04:52
Already do bi-sect on BYT-5682. Issue is caused by commit https://github.com/thesofproject/linux/commit/7764364794f24a05038f461768bc24bc3d0d626d

**Comment by ClarexZhou** [comment] 2020-01-17 04:55
@ranj063  Could you please check on this first?

**Comment by ClarexZhou** [comment] 2020-01-17 05:09
BDW failed for same issue.

**Comment by keyonjie** [comment] 2020-01-17 05:17
did we found the issue by CI before the PR was merged? or we didn't have chance to run that because of the power supply was cutting off?

**Comment by xiulipan** [comment] 2020-01-17 05:27
@keyonjie I re-check the test result for #1702 https://sof-ci.01.org/linuxpr/PR1702/build2894/devicetest/ All BYT/BSW is failed.

I think we missed a patch to replace the `sof_ipc_tx_message_no_pm` usage for BYT platforms

**Comment by keyonjie** [comment] 2020-01-17 05:40
> @keyonjie I re-check the test result for #1720 https://sof-ci.01.org/linuxpr/PR1702/build2894/devicetest/ All BYT/BSW is failed.
> 
> I think we missed a patch to replace the `sof_ipc_tx_message_no_pm` usage for BYT platforms

Thanks for the link, then we should have taken care about CI errors before merging, @plbossart @ranj063.

**Comment by xiulipan** [comment] 2020-01-17 06:06
@keyonjie @ClarexZhou Got a fix https://github.com/thesofproject/linux/pull/1725
Please help to review and test.

**Closed as completed** 2020-01-17 20:15 UTC
Labels: bug, P1, BYT, BDW, BSW
