### ISSUE TITLE
Enable SOF driver to support built-in mode

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#139] opened 2018-09-17 01:35 UTC
Currently SOF driver only support modular mode, but we have requirement to support built-in mode, the main gap currently is that rootfs may be unavailable yet during SOF driver loading stage.

**Comment by wenqingfu** [comment] 2019-04-01 22:51
Is this request still valid?  If so, any idea can throw on the table?

**Comment by plbossart** [comment] 2019-04-01 22:53
I think it could be done by baking the firmware and topology files inside of the kernel, otherwise the dependency with the filesystem remains.

**Comment by keyonjie** [comment] 2019-04-02 02:03
I initiated this with intention to reminding about trying to implement built-in driver support without built-in FW/tplg images using some retry(later) logic once request_firmware fails.

As we have implemented runtime suspend/resume now, it's possible to do this retry in runtime resume, though it fails at the first boot with built-in driver(need keep pci driver working at this fails), @plbossart what do you think about this?

**Comment by plbossart** [comment] 2019-04-02 15:06
@keyonjie I don't think we should try this. We need to verify all the boot flows immediately, not rely on some sort of retry. In other implementations such as Edison where everything was built-in, the firmware was embedded in the kernel and that's an acceptable restriction to me.

**Comment by keyonjie** [comment] 2019-04-03 09:39
OK, then let's close this item.

**Comment by plbossart** [comment] 2019-04-03 14:05
no, let's try with the firmware embedded in the kernel and close when it's verified.

**Comment by xiulipan** [comment] 2019-04-04 06:17
@plbossart 
Then it may not be easy to try with the CI. It will need the firmware inside the kernel build folder. And the kernel config set to include the binaries.

Maybe I can come up with some scripts to test it once a week. I will upload the scripts and the def-config to kconfig repo once I have done the test.

**Comment by caseorum** [comment] 2020-09-19 08:32
Anecdotally, I can confirm success with both built-in FW/tplg and in the initramfs on bdw-rt5677 (samus).
Kernel 5.9.0-rc5+ eb5f95f1593f7c22dac681b19e815828e2af3efd
FW/tplg latest release v1.5.1

**Comment by paulstelian97** [comment] 2020-09-21 08:21
NXP side (also anecdotal), we had used built in (with in-kernel-image firmware) as well (a while ago actually). A bit hacky but that's how we did it for a while. Had to do that because built-in SOF somehow loaded before the networked rootfs...

**Comment by keyonjie** [comment] 2020-09-21 08:41
Thanks for trying this out @caseorum and @paulstelian97. @lyakh FYI.

**Comment by dbaluta** [comment] 2020-09-21 09:58
I wonder if there's a de facto solution for having builtin modules which load the firmware from rootfs (to avoid building the firmware inside the kernel image).
When we tried this solution loading the firmware always failed because the rootfs wasn't available at that time.

**Comment by lyakh** [comment] 2020-09-21 11:43
> I wonder if there's a de facto solution for having builtin modules which load the firmware from rootfs (to avoid building the firmware inside the kernel image).

@dbaluta As mentioned in https://www.kernel.org/doc/html/latest/driver-api/firmware/direct-fs-lookup.html#firmware-and-initramfs 
> using a userspace fallback mechanism is currently the only viable solution as only userspace can know for sure when the real rootfs is ready and mounted.

**Comment by paulstelian97** [comment] 2020-09-21 12:53
> > I wonder if there's a de facto solution for having builtin modules which load the firmware from rootfs (to avoid building the firmware inside the kernel image).
> 
> @dbaluta As mentioned in https://www.kernel.org/doc/html/latest/driver-api/firmware/direct-fs-lookup.html#firmware-and-initramfs
> 
> > using a userspace fallback mechanism is currently the only viable solution as only userspace can know for sure when the real rootfs is ready and mounted.

Problem with that is that a weird cyclic dependency happens that prevents the rootfs from ever mounting (nfsroot comes after sof for some reason?).

Also AFAICT we at NXP do not use any initramfs at all.

**Comment by plbossart** [comment] 2021-06-10 19:52
let's close this, there are existing solutions and no real new development needed.

**Closed as completed by plbossart** 2021-06-10 19:52 UTC
Labels: enhancement

**Comment by marc-hb** [comment] 2021-06-22 04:51
Some references.

This problem is not specific to audio and there are security aspects:
http://lkml.iu.edu/hypermail/linux/kernel/1508.1/03428.html

Note not every device has the simple concept of "one rootfs".

ChromeOS had a generic workaround for a long time:
https://chromium-review.googlesource.com/q/system_running
... which has been NACKed upstream.
