### ISSUE TITLE
[BUG][JSL] SOF doesn't work after S3

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#1719] opened 2020-01-16 07:57 UTC
**Describe the bug**
Perform S3 test first, then do playback or capture, aplay/arecord will stuck there without output and process cannot be killed.
This issue only happens on HDA mode, on I2S mode, sof works well after S3.

**To Reproduce**
1. do S3 first
    rtcwake -m mem -s 5
2.  then run aplay/arecord
    aplay -Dhw:0,1 -f dat -c 2 -vvv /dev/zero

**Reproduction Rate**
100%

**Expected behavior**
SOF works well after S3

**Environment**
Branch jsl-001-drop-stable
Commit: 921fd951faf467c724fe35e8b724dd43ade39f7d
kernel:
Branch:sof-dev
Commit:  0e05b6e 

**dmesg**
```
[  142.672487] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  142.672515] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  143.172281] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  143.172312] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  318.752895] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5
[  323.762163] sof-audio-pci 0000:00:1f.3: pcm: open stream 1 dir 0
[  323.762169] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[  323.762172] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[  323.762175] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[  323.762910] sof-audio-pci 0000:00:1f.3: pcm: close stream 1 dir 0
[  434.210982] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  434.245658] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  434.245835] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  434.245912] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010303 successful
[  434.245917] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x303 successful
[  434.245921] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 3
[  434.245963] sof-audio-pci 0000:00:1f.3: Debug PCIR: 00000010 at  00000044
```

[dmesg_s3.txt](https://github.com/thesofproject/linux/files/4069790/dmesg_s3.txt)

**Comment by plbossart** [comment] 2020-01-17 00:17
@kv2019i does this ring a bell?

**Comment by kv2019i** [comment] 2020-01-17 06:29
@plbossart no, this looks like a new case. I wonder if graphics came back ok from S3. Only error in the log before the audio register sync error is this:
[  130.432125] [drm:intel_gt_verify_workarounds [i915]] *ERROR* GT workaround lost on init! (9524=0/0, expected 10000, mask=10000)

@keqiaozhang Would be interesting to check when this started happening? Perhaps a recent upstream merge?

**Comment by keqiaozhang** [comment] 2020-01-17 07:05
@kv2019i  We didn't do a regular test on JSL, because no JSL devices available in PRC now. We will get one next week.
I found this issue on COE's device with remote testing. So not sure if this is a regression.

**Comment by kv2019i** [comment] 2020-02-06 20:57
@keqiaozhang I believe this same bug as #1763 (now fixed in sof-dev) and is triggered by difference in BIOS settings for HDA link values versus hw defaults. This  happen on JSL/TGL/ICL/GLK platforms and newer.

**Comment by plbossart** [comment] 2020-03-03 21:03
@keqiaozhang is this bug still current? it's been going on for ~2 months now.

**Comment by keqiaozhang** [comment] 2020-03-04 08:22
@emilchudzik 
Could you help to verify this issue with latest sof-dev on your JSL device? Thanks .

**Comment by emilchudzik** [comment] 2020-03-05 13:58
Issue exists on my JSL (HDA mode).
kernel: 24d97816/sof-dev
FW: c35e1aa6/master

Steps:
- aplay works well before S3
- S3 works
- aplay don't start after S3, it seems like freeze after enter command. Even if I check: "aplay -l" this commant last about 20-30sec to display output.
In dmesg I see:
![image](https://user-images.githubusercontent.com/41113230/75988066-50908800-5ef1-11ea-9d49-5c2d270fcf99.png)


full dmesg: 
[dmesg_S3.txt](https://github.com/thesofproject/linux/files/4293264/dmesg_S3.txt)

**Comment by kv2019i** [comment] 2020-03-05 15:48
@emilchudzik Does HDMI work before S3 on this platform? The error:

[  714.317335] snd_hda_codec_hdmi ehdaudio0D2: Unable to sync register 0x2f8100. -5

.. is typically seen when the hardware is something our HDMI codec driver does not identify. We recently added one JSL variant more, but I wonder if there is still more, or there is an issue with your kernel config.

To debug this further, can you also share me output of "cat /proc/asound/card0/codec#2" before S3 is attempted

And also, please share the config file (.config) that was used to compile the kernel.

**Comment by emilchudzik** [comment] 2020-03-06 08:51
ok, I will check HDMI.

I just check dmesg and playback that I run yesterday (19h ago made S3) and playback currently keep working:
![image](https://user-images.githubusercontent.com/41113230/76067526-d2cf8980-5f8f-11ea-8d87-fae53b9dd587.png)

**Comment by emilchudzik** [comment] 2020-03-06 12:38
@kv2019i I haved just check issue again with headphones connected to monitor.
Playback works through HDMI2 after reboot and before entering S3.
After S3 playback doesn't work. Some time later it recover as I describe comments above.

Logs:
[proc_asound_card0_codec2.txt](https://github.com/thesofproject/linux/files/4298314/proc_asound_card0_codec2.txt)

[dmesg4_aplay_afterS3.txt](https://github.com/thesofproject/linux/files/4298323/dmesg4_aplay_afterS3.txt)

for building kernel I used: [kconfig-sof-default.sh](https://github.com/thesofproject/kconfig/blob/master/kconfig-sof-default.sh)
.config: [config.txt](https://github.com/thesofproject/linux/files/4298349/config.txt)

**Comment by kv2019i** [comment] 2020-03-06 13:17
Thanks @emilchudzik ! The kernel config is ok, as is the proc asound dump. This looks very close to #1763 but the fix for that is included in the kernel tree you quoted (24d97816ea7d731d32895bdc17c5c4af68a6e8f2 ), so it is not helping.

So it seem on audio side everything is as it should, but graphics side is not coming back alive after S3. Let's see if we could have other people reprouce this.

It would help if you could additionally take drm traces. Before going to S3 and back, run following as root:

echo 0x1f > /sys/module/drm/parameters/debug

You should see plenty of drm logs in dmesg.  There's so much traces, so you might overrun dmesg 
buffer, in which case you also need to add "log_buf_len=1M" to kernel cmdline.

This log would help to confirm whether graphics driver is programming the link correctly after S3.

@keqiaozhang @yongzhi1 Can you reproduce this on JSL?

**Comment by emilchudzik** [comment] 2020-03-09 13:54
after enter command for extend log buffer to 1M and
`echo 0x1f > /sys/module/drm/parameters/debug`
catched dmesg: [dmesg_drm_before_S3.txt](https://github.com/thesofproject/linux/files/4306973/dmesg_drm_before_S3.txt)

then I enter S3:
[dmesg_drm_after_S3.txt](https://github.com/thesofproject/linux/files/4306974/dmesg_drm_after_S3.txt)

then run aplay - which "freeze", doesn't work
[dmesg_drm_after_S3_and_aplay.txt](https://github.com/thesofproject/linux/files/4306975/dmesg_drm_after_S3_and_aplay.txt)

**Comment by kv2019i** [comment] 2020-03-09 14:14
Thanks @emilchudzik !

First thing that pops from the logs that you are missing i915 firmware on the test device:
[    3.502994] i915 0000:00:02.0: Direct firmware load for i915/icl_dmc_ver1_09.bin failed with error -2
[    3.503002] i915 0000:00:02.0: Failed to load DMC firmware i915/icl_dmc_ver1_09.bin. Disabling runtime power management.
[    3.503004] i915 0000:00:02.0: DMC firmware homepage: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

... you should fetch one from linux-firmware. Latest linux-firmware on Ubuntu 18.04LTS still doesn't have it, so you might need to manually fetch it from:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=51deca67a4eb5c1b1ab49d6d25dc759e8e27fe7b

The firmware update probably should be done first as the i915 logs don't seem quite right.

I would be expecting to see traces like below when aplay is used and/or when system resumes from S3:

[245682.136006] [drm:intel_power_well_enable [i915]] enabling power well 2
[245682.136058] [drm:intel_power_well_enable [i915]] enabling power well 3
[245682.136165] [drm:i915_audio_component_get_power [i915]] restored AUD_FREQ_CNTRL to 0x810

**Comment by emilchudzik** [comment] 2020-03-10 11:14
thanks @kv2019i  for hints, below logs:
[dmesg_i915_1_aplay_before_S3.txt](https://github.com/thesofproject/linux/files/4312034/dmesg_i915_1_aplay_before_S3.txt)
[dmesg_i915_2_after_S3.txt](https://github.com/thesofproject/linux/files/4312035/dmesg_i915_2_after_S3.txt)
[dmesg_i915_3_aplay_after_S3.txt](https://github.com/thesofproject/linux/files/4312033/dmesg_i915_3_aplay_after_S3.txt)


I can see now:
[  197.348161] [drm:intel_power_well_enable [i915]] enabling power well 4
[  197.348284] [drm:drm_atomic_state_init [drm]] Allocated atomic state 00000000b3def8e2
[  197.348313] [drm:drm_mode_object_get [drm]] OBJ ID: 236 (1)
[  197.348328] [drm:drm_mode_object_get [drm]] OBJ ID: 239 (2)
[  197.348341] [drm:drm_mode_object_get [drm]] OBJ ID: 239 (3)

but issue still exists, aplay doesn't work after wake up from S3.

**Comment by kv2019i** [comment] 2020-03-10 11:47
Thanks @emilchudzik ! After a bit more debug, it starts to seem this is a GFX problem. A peek at /sys/kernel/debug/dri/0/i915_capabilities shows that the i915 platform is ELK, not ICL, so I think there are some i915-side driver workarounds that are not yet applied on this platform. 

Let me put together a patch to verify.

**Comment by kv2019i** [comment] 2020-03-10 13:14
@emilchudzik Ok, I have a potential fix in PR1881 . Could you give it a try?

**Comment by keqiaozhang** [comment] 2020-03-11 05:32
@plbossart 
Sorry, we don't have a available JSL device(also checked with other teams) to verify this issue.  so let's keep this issue open until we get a proper device to check.

**Comment by kv2019i** [comment] 2020-03-11 08:09
@plbossart @keqiaozhang This is clearly a bug, no question about it. #1881 is a potential fix.

**Comment by emilchudzik** [comment] 2020-03-11 09:08
@kv2019i your patch fix this issue.
I have just checked kernel ac3abc565474/sof-dev + #1881 
and now aplay works after S3.
checked several reboots with several S3, each time aplay works after resume from S3.

**Comment by kv2019i** [comment] 2020-03-11 09:41
Excellent, that's great news, thanks @emilchudzik !

I'll post this patch to i915 driver. Once reviews pass and patch is merged to i915, we can backport it to sof-dev as otherwise it would take a looong time to get the patch back.

**Comment by kv2019i** [comment] 2020-03-13 08:52
Patch sent to intel-gfx list:
https://lists.freedesktop.org/archives/intel-gfx/2020-March/233419.html

**Comment by kv2019i** [comment] 2020-03-26 06:58
Still in review, not yet merged:
https://patchwork.freedesktop.org/series/74664/

**Comment by kv2019i** [comment] 2020-04-16 12:28
OK, now merged to upstream:
https://lists.freedesktop.org/archives/intel-gfx/2020-April/236415.html
A backport is already in sof-dev, so we can close this issue.

**Closed as completed** 2020-04-16 12:30 UTC
Labels: bug, P2, HDA, GFX, JSL, suspend resume
