### ISSUE TITLE
[SDW][RT711] calibration timed out

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2611] opened 2020-12-08 18:50 UTC
During kmod load/unload tests (Intel test 1025), we see this error

````
[ 1998.004550] rt711 sdw:0:25d:711:0: [rt711_sdw_read] 7558 85d8 9c58 acd8 => 0000f888
[ 1998.004563] rt711_calibration, calibration time-out!
[ 1998.004912] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 7520 85a0 7420 84a0 <= 006f 0583
[ 1998.005015] rt711 sdw:0:25d:711:0: [rt711_sdw_write] 3501 <= 0003
[ 1998.005024] rt711 sdw:0:25d:711:0: rt711_calibration calibration complete, ret=-110
````
[rt711-calibration-dmesg.txt](https://github.com/thesofproject/linux/files/5661194/rt711-calibration-dmesg.txt)

Opens:
a) is this really an error? the status of rt711_calibration() is not tested by anyone
b) is this really good to use the same function directly and with a workqueue? This code seems suspicious:
````c
	if (rt711->first_hw_init)
		rt711_calibration(rt711);
	else {
		INIT_DELAYED_WORK(&rt711->jack_detect_work,
			rt711_jack_detect_handler);
		INIT_DELAYED_WORK(&rt711->jack_btn_check_work,
			rt711_btn_check_handler);
		mutex_init(&rt711->calibrate_mutex);
		INIT_WORK(&rt711->calibration_work, rt711_calibration_work);
		schedule_work(&rt711->calibration_work);
	}
````
On init we use a work queue but later we call the function directly? 
Should we always rely on schedule_work(), so that during remove/suspend we wait for the calibration to be finished? If the calibration is handled directly it's not clear what happens?

**Comment by plbossart** [comment] 2020-12-08 18:51
@bardliao @shumingfan @RanderWang @jack-cy-yu FYI

**Comment by bardliao** [comment] 2020-12-09 01:23
I see below in the dmesg.
```
[ 1993.074141] rt711 sdw:0:25d:711:0: [rt711_sdw_read] 7558 85d8 9c58 acd8 => 0000f888
[ 1993.074974] rt711 sdw:0:25d:711:0: [rt711_sdw_read] b921 0000 => 80000000
[ 1993.075474] rt711 sdw:0:25d:711:0: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000800
[ 1993.076120] rt711 sdw:0:25d:711:0: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000030
[ 1993.076123] rt711 sdw:0:25d:711:0: in rt711_jack_detect_handler, jack_type=0x3
[ 1993.076125] rt711 sdw:0:25d:711:0: in rt711_jack_detect_handler, btn_type=0x0
[ 1993.085664] rt711 sdw:0:25d:711:0: [rt711_sdw_read] 7558 85d8 9c58 acd8 => 0000f888
```
Do we need to use mutex here?

**Comment by shumingfan** [comment] 2020-12-09 02:41
@plbossart @bardliao  I just want to save time for system boot, so I use the schedule_work() for the first time.
If the driver re-do the io_init after the system resumes, I want to make sure the calibration is done before the playback/capture operations.

I think this issue could be caused by the power state of the codec. The power state was changed to D3 in the put function of kcontrol.
Could you test again with the following patch?
```
@@ -544,9 +544,11 @@ static int rt711_set_amp_gain_put(struct snd_kcontrol *kcontrol,
                        break;
        }

+       mutex_lock(&rt711->calibrate_mutex);
        if (dapm->bias_level <= SND_SOC_BIAS_STANDBY)
                regmap_write(rt711->regmap,
                                RT711_SET_AUDIO_POWER_STATE, AC_PWRST_D3);
+       mutex_unlock(&rt711->calibrate_mutex);
        return 0;
 }
```

**Comment by plbossart** [comment] 2020-12-11 13:41
https://github.com/thesofproject/linux/pull/2626

**Comment by mengdonglin** [comment] 2020-12-14 08:44
@plbossart @bardliao Can we close this issue as #2626 got merged?

**Comment by bardliao** [comment] 2020-12-14 10:10
> @plbossart @bardliao Can we close this issue as #2626 got merged?

Let's check the test result for few more days. We can close the issue if we don't see it in our daily test.

**Comment by bardliao** [comment] 2020-12-17 08:12
Not reproduce in recent test report.

**Closed as completed by bardliao** 2020-12-17 08:12 UTC
Labels: bug, P1, CML, codec, SDW, fix submitted

**Comment by shumingfan** [comment] 2020-12-21 02:01
> Not reproduce in recent test report.

The patch was merged to the for-next branch.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=6108f990c0887d3e8f1db2d13c7012e40a061f28
