### ISSUE TITLE
make kernel failed on branch debug/v4.14-backport

### ISSUE THREAD

**Issue by DarrenxWang** [thesofproject/linux#230] opened 2018-10-30 07:57 UTC
@plbossart I tried with default configuration in your repo https://github.com/plbossart/kconfig
$make defconfig
$scripts/kconfig/merge_config.sh .config /kconfig/base-defconfig /kconfig/sof-defconfig

But we got building error. The kconfig and error log are attached.

[build-error-Pierre-def-sof-kconfig.txt](https://github.com/thesofproject/linux/files/2528926/build-error-Pierre-def-sof-kconfig.txt)

[Pierre-def-sof-kconfig.config.txt](https://github.com/thesofproject/linux/files/2528932/Pierre-def-sof-kconfig.config.txt)

**Comment by DarrenxWang** [comment] 2018-10-30 09:36
@plbossart I also tried with default configuration in your repo https://github.com/plbossart/kconfig
$make defconfig
$scripts/kconfig/merge_config.sh .config <PATH>/kconfig/base-defconfig <PATH>/kconfig/sof-defconfig

But we also got building error. The kconfig and error log are attached.

[build-error-Pierre-def-sof-kconfig.txt](https://github.com/thesofproject/linux/files/2528926/build-error-Pierre-def-sof-kconfig.txt)

[Pierre-def-sof-kconfig.config.txt](https://github.com/thesofproject/linux/files/2528932/Pierre-def-sof-kconfig.config.txt)

**Comment by plbossart** [comment] 2018-10-30 13:14
@DarrenxWang Thanks for the report. Indeed I missed a number of dependencies for rt274, pcm512 and topology header files. My backport script was not complete and I tested without SOF :-(
Please retry, all the fixes were pushed to github and I am able to compile both backport/v4.14-intel-audio and debug/￼v4.14-backport.

**Comment by plbossart** [comment] 2018-10-31 23:42
can we please close this?

**Comment by mengdonglin** [comment] 2018-11-01 07:50
Cannot reproduce on latest debug/￼v4.14-backport and so close this issue.

**Closed as completed by mengdonglin** 2018-11-01 07:50 UTC
Labels: bug, P1
