### ISSUE TITLE
[BUG] [MTL] sdw_prepare_stream: subdevice #0-Playback: inconsistent state state 3

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#4350] opened 2023-05-12 02:58 UTC
**Describe the bug**
CI observed this issue on MTL-SDW platform when testing multiple pause/resume. 
There're some sdw kernel errors:
```
[ 3112.638266] kernel:  SDW0-Playback: ASoC: error at snd_soc_link_prepare on SDW0-Playback: -22
[ 3112.638287] kernel:  SDW0-Playback: ASoC: error at __soc_pcm_prepare on SDW0-Playback: -22
[ 3112.638305] kernel:  Deepbuffer Jack Out: ASoC: error at dpcm_be_dai_prepare on Deepbuffer Jack Out: -22
[ 3112.638325] kernel:  Deepbuffer Jack Out: ASoC: error at dpcm_fe_dai_prepare on Deepbuffer Jack Out: -22
```
No obvious error in mtrace.

**To Reproduce**
 ~/sof-test/test-case/multiple-pause-resume.sh -r 50

**Reproduction Rate**
This issue is easy to reproduce. Almost 100%.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: [6694b85ddcea](https://github.com/thesofproject/linux/commit/6694b85ddcea)
    * SOF: {mtl-005-drop-stable}[36a7a817fb8b](https://github.com/thesofproject/sof/commit/36a7a817fb8b)
2) Name of the topology file
    * Topology: sof-mtl-rt711-4ch.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: MTL-SDW

[dmesg.txt](https://github.com/thesofproject/linux/files/11458475/dmesg.txt)

**Comment by bardliao** [comment] 2023-05-12 11:34
This issue is because somehow sdw_trigger SNDRV_PCM_TRIGGER_PAUSE_RELEASE is called right before sdw_prepare.
```
[ 2453.587208] snd_sof:sof_widget_setup_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: widget mixin.15.1 setup complete
[ 2453.587225] snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: bind copier.host.15.1:0 -> gain.15.1:0
[ 2453.587261] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x13000003|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[ 2453.597179] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x33000000|0x1: GLB_SET_PIPELINE_STATE
[ 2453.597244] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x13000003|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[ 2453.597270] Message payload: 00000000: 00000002 00000000 00000001
[ 2453.597287] bard: sdw_trigger subdevice #0, cmd 3
[ 2453.597485] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x45020004|0x20006: MOD_BIND
[ 2453.599289] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x65000000|0x20006: MOD_BIND
[ 2453.599613] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x45020004|0x20006: MOD_BIND
[ 2453.599636] snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: bind gain.15.1:0 -> mixin.15.1:0
[ 2453.599654] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x45020006|0x10002: MOD_BIND
[ 2453.601813] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x65000000|0x10002: MOD_BIND
[ 2453.602017] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x45020006|0x10002: MOD_BIND
[ 2453.602032] snd_sof:sof_ipc4_route_setup: sof-audio-pci-intel-mtl 0000:00:1f.3: bind mixin.15.1:0 -> mixout.1.1:1
[ 2453.602040] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x45010002|0x1000003: MOD_BIND
[ 2453.603111] bard: sdw_trigger subdevice #0, cmd 4
[ 2453.603709] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx reply: 0x65000000|0x1000003: MOD_BIND
[ 2453.603909] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx done : 0x45010002|0x1000003: MOD_BIND
[ 2453.603928] bard: sof_ipc4_pcm_hw_params subdevice #0
[ 2453.603976] bard: sdw_prepare subdevice #0
[ 2453.606455] snd_sof:sof_pcm_trigger: sof-audio-pci-intel-mtl 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 4
[ 2453.606464] bard: sof_ipc4_pcm_trigger subdevice #0: cmd 4
[ 2453.606469] snd_sof:sof_ipc4_trigger_pipelines: sof-audio-pci-intel-mtl 0000:00:1f.3: trigger cmd: 4 state: 4
[ 2453.606477] snd_sof:sof_ipc4_log_header: sof-audio-pci-intel-mtl 0000:00:1f.3: ipc tx      : 0x13000004|0x1: GLB_SET_PIPELINE_STATE [data size: 12]
[ 2453.606625] sdw_prepare_stream: subdevice #0-Playback: inconsistent state state 3
[ 2453.606656]  SDW0-Playback: ASoC: error at snd_soc_link_prepare on SDW0-Playback: -22
[ 2453.606678]  SDW0-Playback: ASoC: error at __soc_pcm_prepare on SDW0-Playback: -22
[ 2453.606696]  Deepbuffer Jack Out: ASoC: error at dpcm_be_dai_prepare on Deepbuffer Jack Out: -22
[ 2453.606717]  Deepbuffer Jack Out: ASoC: error at dpcm_fe_dai_prepare on Deepbuffer Jack Out: -22
```

The issue only happens with sof-mtl-005 firmware and not seen with main firmware. But I have no idea how firmware can affect the hw_params and trigger sequence. @ranj063 Do you have any thought?

**Comment by plbossart** [comment] 2023-05-12 15:13
wow, that's a big one. The prepare stage should really be complete before the trigger happens. I am glad we added this state machine check in the SoundWire stream handling!

**Comment by ranj063** [comment] 2023-05-12 15:47
> The issue only happens with sof-mtl-005 firmware and not seen with main firmware. But I have no idea how firmware can affect the hw_params and trigger sequence. @ranj063 Do you have any thought?

@bardliao I dont think the problem is that you have a trigger before prepare. Thats just not possible I think.On the other hand I think the problem is that we're trying to do a prepare for the deep buffer PCM while the regular PCM is already running.

**Comment by ranj063** [comment] 2023-05-12 16:00
@bardliao Can you please see if this helps?
```
diff --git a/sound/soc/soc-pcm.c b/sound/soc/soc-pcm.c
index adb69d7820a8..945952d2be48 100644
--- a/sound/soc/soc-pcm.c
+++ b/sound/soc/soc-pcm.c
@@ -2405,6 +2405,9 @@ int dpcm_be_dai_prepare(struct snd_soc_pcm_runtime *fe, int stream)
                if (!snd_soc_dpcm_be_can_update(fe, be, stream))
                        continue;
 
+               if (!snd_soc_dpcm_can_be_prepared(fe, be, stream);
+                       continue;
+
                if ((be->dpcm[stream].state != SND_SOC_DPCM_STATE_HW_PARAMS) &&
                    (be->dpcm[stream].state != SND_SOC_DPCM_STATE_STOP) &&
                    (be->dpcm[stream].state != SND_SOC_DPCM_STATE_SUSPEND) &&
@@ -3042,3 +3045,21 @@ int snd_soc_dpcm_can_be_params(struct snd_soc_pcm_runtime *fe,
        return snd_soc_dpcm_check_state(fe, be, stream, state, ARRAY_SIZE(state));
 }
 EXPORT_SYMBOL_GPL(snd_soc_dpcm_can_be_params);
+
+/*
+ * We can only prepare a BE DAI if any of it's FE are not prepared,
+ * running or paused for the specified stream direction.
+ */
+int snd_soc_dpcm_can_be_prepared(struct snd_soc_pcm_runtime *fe,
+                                struct snd_soc_pcm_runtime *be, int stream)
+{
+       const enum snd_soc_dpcm_state state[] = {
+               SND_SOC_DPCM_STATE_START,
+               SND_SOC_DPCM_STATE_PAUSED,
+               SND_SOC_DPCM_STATE_PREPARE,
+       };
+
+       return snd_soc_dpcm_check_state(fe, be, stream, state, ARRAY_SIZE(state));
+}
+EXPORT_SYMBOL_GPL(snd_soc_dpcm_can_be_prepared);
```

**Comment by plbossart** [comment] 2023-05-12 16:40
@bardliao it's not clear why we are seeing this problem now, we've enabled multiple streams for SoundWire for at least a year now. But @ranj063 is right that while we prevent multiple hw_params from happening when the BE is already running, we do no such thing for the prepare case. That's a miss IMHO and the patch above seems correct - even if it doesn't fix our problem.

One open is that the prepare takes time, with a bank switch to adjust the clock if required, so it's not clear if we have the proper locking and exclusion.

**Comment by bardliao** [comment] 2023-05-15 01:29
> @bardliao Can you please see if this helps?
> 
> ```
> diff --git a/sound/soc/soc-pcm.c b/sound/soc/soc-pcm.c
> index adb69d7820a8..945952d2be48 100644
> --- a/sound/soc/soc-pcm.c
> +++ b/sound/soc/soc-pcm.c
> @@ -2405,6 +2405,9 @@ int dpcm_be_dai_prepare(struct snd_soc_pcm_runtime *fe, int stream)
>                 if (!snd_soc_dpcm_be_can_update(fe, be, stream))
>                         continue;
>  
> +               if (!snd_soc_dpcm_can_be_prepared(fe, be, stream);
> +                       continue;
> +
>                 if ((be->dpcm[stream].state != SND_SOC_DPCM_STATE_HW_PARAMS) &&
>                     (be->dpcm[stream].state != SND_SOC_DPCM_STATE_STOP) &&
>                     (be->dpcm[stream].state != SND_SOC_DPCM_STATE_SUSPEND) &&
> @@ -3042,3 +3045,21 @@ int snd_soc_dpcm_can_be_params(struct snd_soc_pcm_runtime *fe,
>         return snd_soc_dpcm_check_state(fe, be, stream, state, ARRAY_SIZE(state));
>  }
>  EXPORT_SYMBOL_GPL(snd_soc_dpcm_can_be_params);
> +
> +/*
> + * We can only prepare a BE DAI if any of it's FE are not prepared,
> + * running or paused for the specified stream direction.
> + */
> +int snd_soc_dpcm_can_be_prepared(struct snd_soc_pcm_runtime *fe,
> +                                struct snd_soc_pcm_runtime *be, int stream)
> +{
> +       const enum snd_soc_dpcm_state state[] = {
> +               SND_SOC_DPCM_STATE_START,
> +               SND_SOC_DPCM_STATE_PAUSED,
> +               SND_SOC_DPCM_STATE_PREPARE,
> +       };
> +
> +       return snd_soc_dpcm_check_state(fe, be, stream, state, ARRAY_SIZE(state));
> +}
> +EXPORT_SYMBOL_GPL(snd_soc_dpcm_can_be_prepared);
> ```

@ranj063 @plbossart This change can fix the issue. I tested ~/sof-test/test-case/multiple-pause-resume.sh -r 50 about 10 times and all iterations are passed. It will fail in 2 iterations without the change.
@ranj063 Would you like to submit a PR? Or do you want me to do so?

**Comment by ranj063** [comment] 2023-05-15 03:26
> @ranj063 Would you like to submit a PR? Or do you want me to do so?

@bardliao please go ahead and submit the change. Thank you!

**Comment by bardliao** [comment] 2023-05-22 03:14
Fixed by https://github.com/thesofproject/linux/pull/4354

**Closed as completed by bardliao** 2023-05-22 03:14 UTC
Labels: P1, SDW, MTL, mtl-005
