### ISSUE TITLE
kernel panic on reboot after failed probe

### ISSUE THREAD

**Issue by lyakh** [thesofproject/linux#3235] opened 2021-10-25 11:46 UTC
I've seen this multiple times, when SOF fails to probe, e.g. because of an error in a development firmware version, when then rebooting the system, the kernel panics and the system has to be power-cycled. Observed on UP2 / APL.
![panic](https://user-images.githubusercontent.com/1363683/138689257-441f34ca-9f27-40ad-bcd0-76207fcaa1cf.png)

**Comment by plbossart** [comment] 2021-10-25 15:31
@lyakh it seems the panic occurs during the shutdown, no?

**Comment by lyakh** [comment] 2021-10-26 06:18
@plbossart yes, that's what I meant by "on reboot" - a reboot attempt after a failed probe fails with this panic.

**Comment by ujfalusi** [comment] 2022-01-05 15:09
@lyakh, do you know if this can be still reproduced? If I recall there were couple of fixes since then for HDA code.

**Comment by lyakh** [comment] 2022-01-06 07:13
@ujfalusi I think I've seen this last time relatively recently - in December or maybe in November, not sure what kernel version that was any more, sorry. But it should be relatively easy to verify too - just return a timeout when waiting for the firmware boot confirmation

**Comment by ujfalusi** [comment] 2022-01-07 12:46
I would not close this as I recall seeing similar crash in the past, but to note that I'm not able to reproduce it on UP2 with sof-hda-generic-idisp.tplg, sof-apl-pcm512x.tplg or sof-apl-nocodec.tplg, up-Xtreme i11 with sof-hda-generic.tplg.

I have simulated the boot failure in kernel and I have also made the firmware crash during it's boot.

**Comment by lyakh** [comment] 2022-06-30 06:06
@ujfalusi do we still need this open?

**Comment by ujfalusi** [comment] 2022-06-30 08:53
let's close. I have fixed it quite a while ago. Thanks for the report @lyakh !

**Closed as completed by ujfalusi** 2022-06-30 08:53 UTC
Labels: APL, Boot
