### ISSUE TITLE
[BUG][CML][UCM2]Output device will auto switch from speaker to other source when unplug HDMI external port or headphone.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#2126] opened 2020-05-18 08:28 UTC
**Describe the bug**
Output device will auto switch from speaker to other source when unplug HDMI external port or headphone.

Precondition:
1.Install ubuntu 20.04
2.Pulseaudio version: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tree/master (commit：36a4923f) + https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295 
3.UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit:12743d2)+#PR https://github.com/thesofproject/alsa-ucm-conf/pull/35 + #PR https://github.com/thesofproject/alsa-ucm-conf/pull/39

**To Reproduce**
1. Boot up system with headphone and HDMI external port both connected
2. Open sound setting and select speaker as output device.
3. Unplug HDMI external port.
4. Check the output device.

**Reproduce rate**
5/5

**Expected result**
Output source will stay in speaker.

**Actual result**
Output source will auto switch to headphone from speaker after unplugged HDMI external port.

**Test recipe**
Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:1697493f
FW: https://github.com/thesofproject/sof/commits/master commit: 83cecc95
Tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
Platform:CML-U Laptop with codec ALC711, RT1308, RT715 in SDW mode.

**Comment by sinahuang** [comment] 2020-05-18 09:30
Issue also can be reproduced on CML-H, and found a similar issue that output device will auto switch from A HDMI to B HDMI when unplug headphone. 
Scenario:
1.Boot up system with headphone,HDMI and DP externel port all connected
2.Open sound setting and select one HDMI/DP as output device.
3.Unplug headset ->output will auto switch to another HDMI/DP

**Comment by sinahuang** [comment] 2020-05-26 11:19
Original issue also can be reproduced on CML-H, but found another similar issue that output device will auto switch from speaker to HDMI2 when unplug HDMI1.
Scenario:
1.Boot up system ->open sound setting;
2. Plug in HDMI1 and then plug in HDMI2;
3.Select speaker as output source in sound setting;
4.Unplug HDMI1;

**Comment by ClarexZhou** [comment] 2020-05-29 04:59
Error not seen with https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295#note_512131, wait Pulseaudio update.

**Comment by mengdonglin** [comment] 2020-08-05 08:37
Close this issue because it cannot be reproduced with latest PulseAudio fix for SoundWire. @libinyang will file a separate bug to track HD-A configuration.

**Closed as completed by mengdonglin** 2020-08-05 08:37 UTC
Labels: bug, CML, SDW, UCM2, single-profile UCM + PA#295
