### ISSUE TITLE
No sound output if DSP enabled [IPL-EVT-C1][8086:a3f0]

### ISSUE THREAD

**Issue by prestige-wang** [thesofproject/linux#1444] opened 2019-11-07 07:45 UTC
Bug Description

On Impala platform, when BIOS enabled DSP, there is no sound output on Ubuntu.

To Reproduce
Boot in Ubuntu 18.04 SP1.

Reproduction Rate
100%

Environment
Platform: Impala 21.5 AIO (CML-S B460C PCH)
OS: Ubuntu 1804 SP1
Audio device: Intel Corporation Device a3f0 (prog-if 80)

**Comment by cooper-chiou** [comment] 2019-11-07 08:55
I provided test patch to OSV for validation since there is no audio pci device id for CML-S per checked.

**Comment by cooper-chiou** [comment] 2019-11-11 23:38
validated PASS on customer system, and patch has committed to upstream by https://patchwork.kernel.org/patch/11235833/, please review. Thanks,

**Comment by plbossart** [comment] 2019-11-12 00:05
@cooper-chiou is the DSP enabled on CML-S, and if yes shouldn't we enable it w/ SOF?

**Comment by cooper-chiou** [comment] 2019-11-12 00:13
@plbossart this customer's project (Impala) didn't have PCH-DMIC design, and BIOS enabled DSP to support Win APO feature per customer mentioned.

**Comment by plbossart** [comment] 2019-11-12 00:29
@cooper-chiou did you mean "BIOS did not enable DSP"?

**Comment by cooper-chiou** [comment] 2019-11-13 18:20
@plbossart I confirmed with ODM "It didn’t support PCH-DMIC, but BIOS enabled DSP for Windows APO feature"

**Comment by plbossart** [comment] 2019-11-13 19:52
"APO" usually means processing on the host. Are you saying that on Windows the DSP is used on this platform? If yes, we would need to add support for this platform in SOF as well. We may still use the legacy driver for now thanks to the auto detection, but if this platform has a DSP then SOF should support it.

**Comment by cooper-chiou** [comment] 2019-11-14 19:23
From Intel Smart Sound Technology Feature document, "CometLake-S" feature list claimed "Windows APO (in SW) Support for Pre- and Post-Processing Brands" = YES. That's why ODM BIOS enabled DSP to support Windows APO feature. (Btw, in Linux POR list Audio DSP - Pre/Post Processing is NO)

**Comment by plbossart** [comment] 2019-11-14 19:33
ok, let me try differently: can you provide the results of the following command on that device

````
more /sys/bus/pci/devices/0000\:00\:1f.3/class 
````

**Comment by cooper-chiou** [comment] 2019-11-15 04:54
@plbossart 
The result is here.
$ cat /sys/bus/pci/devices/0000\:00\:1f.3/class 
0x040380

**Comment by cooper-chiou** [comment] 2019-12-18 05:31
Patch "ALSA: hda: Add Cometlake-S PCI ID" has been added to 5.3-stable tree, please find the following commit id, then I think we can close this sighting when confirmed by issue submitter @prestige-wang .

    [ Upstream commit b73a58549ea37a44434c7afab3c7ad9af210cfd9 ]
    Link: https://lore.kernel.org/r/20191108071349.12840-1-cooper.chiou@intel.com

**Closed as completed** 2019-12-26 05:44 UTC
