### ISSUE TITLE
[Dell] CyborgL TGL platform single mic no function by Intel NHTL  bin file seeting

### ISSUE THREAD

**Issue by AndyLiao-wistron** [thesofproject/linux#2725] opened 2021-01-28 14:58 UTC
Intel TGL single mic NHTL bin file setting no function on Linux platform
Intel sighting number #00587508 
![TGL single mic setting 1](https://user-images.githubusercontent.com/78159159/106156095-193b6180-61bc-11eb-8415-56a3ad787a51.PNG)
![TGL single mic setting](https://user-images.githubusercontent.com/78159159/106156101-1b052500-61bc-11eb-9535-3657e10edad9.PNG)

**Comment by plbossart** [comment] 2021-01-29 21:29
@AndyLiao-wistron out of curiosity, what happens if you click on the 'Microphone Array' box shown in the first picture?

can you also provide the dmesg log for this issue with dynamic debug enabled? copy 
[ddebug.txt](https://github.com/thesofproject/linux/files/5896394/ddebug.txt) as /etc/modprobe.d/sof-dyndbg.conf.

Thanks!

**Comment by keyonjie** [comment] 2021-02-22 03:23
@AndyLiao-wistron @plbossart so do we expect the issue is fixed with the latest topic/sof-dev kernel?

**Comment by plbossart** [comment] 2021-02-22 15:55
@keyonjie there was no reply so I don't know if the patch fixed the issue

@AndyLiao-wistron should chime in here, if not let's close this issue

**Comment by keyonjie** [comment] 2021-03-01 02:31
let's close it since no reply for long time.

**Closed as completed** 2021-03-01 02:40 UTC
Labels: bug, P2, TGL, dmic
