### ISSUE TITLE
Sound does not work on Rooks County laptop LAPRC710 / Intel NUC M15 Alder Lake

### ISSUE THREAD

**Issue by eugenhu** [thesofproject/linux#4088] opened 2022-12-09 08:51 UTC
Similar laptop to https://github.com/thesofproject/linux/issues/3049 but the Alder Lake version with i7-1260p.

I've tried remapping _ADRs like in https://github.com/thesofproject/linux/issues/3049, and copying the quirks from the AlderLake devices entry:
https://github.com/thesofproject/linux/blob/3bdc36c2f22399de145ea4a03a8ee4be3fa8528f/sound/soc/intel/boards/sof_sdw.c#L236-L247

except matching my device instead:
```
.matches = { 
    DMI_MATCH(DMI_SYS_VENDOR, "Intel (R) Client Systems"), 
    DMI_MATCH(DMI_PRODUCT_NAME, "LAPRC"), 
}, 
```

Without these modifications, I get "no soundcards found" when running `aplay -l`. Using these modifications, I get a headphone jack, some HDMI outputs, but no internal speaker. The jack always shows up as unplugged in `pavucontrol`, so I can't play sound out of the laptop's headphone jack, but I can play sounds through a monitor connected to the laptop's HDMI port.

I don't know how to make any further progress, not really familiar with this kind of stuff.

I'm running Arch with `sof-firmware` 2.2.3.

Diagnostic info below:

`ls /sys/bus/soundwire/devices`:
```
sdw:0:025d:0711:01
sdw:2:025d:1316:01
sdw-master-0
sdw-master-1
```

`cat /sys/bus/acpi/devices/*/adr | grep 025d`:
```
0x000020025d071100
0x000120025d071100
```

[alsa-info.txt](https://github.com/thesofproject/linux/files/10193218/alsa-info.txt)

[dmesg.txt](https://github.com/thesofproject/linux/files/10193213/dmesg.txt)

From dmesg, only SDW0-Playback and SDW0-Capture dai links are created it seems, not sure if this relates to the absence of speakers.

**Comment by plbossart** [comment] 2022-12-09 14:01
Thanks @eugenhu for the report.

You will also need a quirk in drivers/soundwire/dmi_quirks.c, the address for the amplifier (1316) is incorrect, it's the wrong SoundWire version and likely the wrong link used. 


From the dmesg log, you have 
rt7111-scda on link0: 30025d071101
rt1316 (sdca as well) on link2 30025d131601

which seems to match the HP Omen1 quirk

https://github.com/thesofproject/linux/blob/f2a1d50df454105db86cd9abcfabf3758b24a266/drivers/soundwire/dmi-quirks.c#L62

**Comment by eugenhu** [comment] 2022-12-09 15:04
Thanks for the help.

Sorry, I forgot to mention I've currently got this adr_remap in dmi-quirks.c:
```
static const struct adr_remap intel_tgl_bios[] = {
	{
		0x000020025D071100ull,
		0x000030025D071101ull
	},
	{
		0x000120025D071100ull,
		0x000230025D131601ull
	},
	{}
};
```
And it looks like both 711 and 1316 are found:
```
[    7.968395] sof-audio-pci-intel-tgl 0000:00:1f.3: found 1316 at link 2
[    7.968398] sof-audio-pci-intel-tgl 0000:00:1f.3: Slave 714 not found
[    7.968399] sof-audio-pci-intel-tgl 0000:00:1f.3: Slave 711 not found
[    7.968401] sof-audio-pci-intel-tgl 0000:00:1f.3: found 711 at link 0
```
Checking on Windows devmgmt, 000030025D071101 and 000230025D131601 look like the right addresses, no 714 in devmgmt though, not sure that's coming from.

I've also tried using the quirk `RT711_JD2` instead of `RT711_JD2_100K` which gets rid of the
```
[   12.207145] rt711-sdca sdw:0:025d:0711:01: Wrong JD source
```
But the headphones still show up as unplugged.

**Comment by plbossart** [comment] 2022-12-09 15:39
@eugenhu try using the same quirks as other NUC laptops

````
		.driver_data = (void *)(SOF_SDW_TGL_HDMI |
					SOF_SDW_PCH_DMIC |
					RT711_JD1),
````

It could very well be that you only need RT711_JD1 as well, IIRC the other quirks are not really useful.

**Comment by eugenhu** [comment] 2022-12-09 16:05
I get this error with those quirks:
```
[   11.706954] sof-audio-pci-intel-tgl 0000:00:1f.3: loading topology:intel/sof-tplg/sof-adl-rt711-4ch.tplg
...
[   11.707887] sof-audio-pci-intel-tgl 0000:00:1f.3: error: can't connect DAI SSP2.OUT stream SSP2-BT
[   11.707893] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to add widget id 0 type 27 name : SSP2.OUT stream SSP2-BT
[   11.707898] sof_sdw sof_sdw: ASoC: failed to load widget SSP2.OUT
[   11.707902] sof_sdw sof_sdw: ASoC: topology: could not load header: -22
[   11.707926] sof-audio-pci-intel-tgl 0000:00:1f.3: error: tplg component load failed -22
[   11.707935] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to load DSP topology -22
[   11.707938] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_component_probe on 0000:00:1f.3: -22
[   11.707963] sof_sdw sof_sdw: ASoC: failed to instantiate card -22
[   11.708207] sof_sdw sof_sdw: snd_soc_register_card failed -22
[   11.708232] sof_sdw: probe of sof_sdw failed with error -22
```

Headphones still unplugged when switching `RT711_JD2` for `RT711_JD1` and using the other quirks from the original post.

[dmesg2.txt](https://github.com/thesofproject/linux/files/10196261/dmesg2.txt)

**Comment by plbossart** [comment] 2022-12-09 16:35
You can't use these SSP quirks on your platform. It's SoundWire + DMIC only.

 SOF_BT_OFFLOAD_SSP(2) | 
				SOF_SSP_BT_OFFLOAD_PRESENT),

**Comment by plbossart** [comment] 2022-12-09 16:37
And I also don't know why you are loading this sof-adl-rt711-4ch.tplg topology, this is not quite right either.

Bottom line: please provide a PR or GitHub changes I can comment on. I am lost with all your changes.

**Comment by eugenhu** [comment] 2022-12-09 16:41
Sorry, I'll make a PR with the original changes. Is there a way to load a specific topology? sof-adl-rt711-4ch.tplg was chosen automatically.

**Comment by plbossart** [comment] 2022-12-09 16:58
You may need a new entry in sound/soc/intel/common/soc-acpi-adl-match.c. We have this one, but the amplifier is on link3, you need link2 apparently.

````c
	{
		.link_mask = 0x9, /* 2 active links required */
		.links = adl_sdw_rt711_link0_rt1316_link3,
		.drv_name = "sof_sdw",
		.sof_tplg_filename = "sof-adl-rt711-l0-rt1316-l3.tplg",
	},
````

so that would be 

````c
	{
		.link_mask = 0x5, /* 2 active links required */
		.links = adl_sdw_rt711_link0_rt1316_link2,
		.drv_name = "sof_sdw",
		.sof_tplg_filename = "sof-adl-rt711-l0-rt1316-l2.tplg",
	},
````
Unzip these two files and copy them in /lib/firmware/intel/sof-tplg/

[sof-adl-rt711-l0-rt1316-l2-2ch.tplg.gz](https://github.com/thesofproject/linux/files/10196632/sof-adl-rt711-l0-rt1316-l2-2ch.tplg.gz)
[sof-adl-rt711-l0-rt1316-l2-4ch.tplg.gz](https://github.com/thesofproject/linux/files/10196633/sof-adl-rt711-l0-rt1316-l2-4ch.tplg.gz)

**Comment by eugenhu** [comment] 2022-12-09 18:53
The changes you suggested worked to get the internal speaker working, thanks. All changes are in PR https://github.com/thesofproject/linux/pull/4091.

However, the headphone jack is still not working, show as (unplugged) in pavucontrol. I've tried using `RT711_JD1` and `RT711_JD2_100K`, with no improvement.

Logs:
[dmesg3.txt](https://github.com/thesofproject/linux/files/10197318/dmesg3.txt)
[alsa-info2.txt](https://github.com/thesofproject/linux/files/10197320/alsa-info2.txt)

**Comment by plbossart** [comment] 2022-12-09 18:55
Thanks for testing @eugenhu, nice progress.

I'll have to add @shumingfan to help with jack detection. All NUC laptops used JD1 so far, not sure why it's not working this time or if another setting is required.

**Comment by plbossart** [comment] 2022-12-09 19:08
also @eugenhu please try at the amixer level to see if there are any changes

assuming the numid = 18 (Headphone Jack), you can use

amixer -Dhw:0 numid=18 cget 

and see if plugging the headphone has any effect. We need to make sure it works at that level before checking PulseAudio/PipeWire integration.

**Comment by eugenhu** [comment] 2022-12-09 19:31
Not too familiar with ALSA, but this is what I tried:
```
$ amixer cget -Dhw:0 numid=18
numid=18,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```
Same output when headphones are plugged in vs out.

**Comment by plbossart** [comment] 2022-12-09 19:47
Thanks @eugenhu, that points to a driver issue then. @shumingfan might be able to help next week.

**Comment by shumingfan** [comment] 2022-12-12 02:05
@eugenhu 
Could you dump registers while using RT711_JD1 and RT711_JD2 separately?
When the jack was plugged in, then dump the registers by the commands below.
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers

**Comment by eugenhu** [comment] 2022-12-12 09:02
Using RT711_JD1. After plugging in headphones and running
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump1.txt](https://github.com/thesofproject/linux/files/10206308/dump1.txt)
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq1.txt](https://github.com/thesofproject/linux/files/10206313/dump-sdw-mbq1.txt)

Using RT711_JD2,
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump2.txt](https://github.com/thesofproject/linux/files/10206314/dump2.txt)
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq2.txt](https://github.com/thesofproject/linux/files/10206316/dump-sdw-mbq2.txt)

**Comment by shumingfan** [comment] 2022-12-12 09:16
@eugenhu Sorry, I missed one thing.
To avoid the bus/codec driver suspending, please dump registers while the playback or recording.

**Comment by eugenhu** [comment] 2022-12-12 09:34
How should I do this? Can I run `speaker-test` to play a sound through the headphone jack? or just play it through the internal speakers.

I've tried dumping the registers again, with the laptop's mic unmuted, not sure if this is what you wanted:

Using RT711_JD1.
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump1.txt](https://github.com/thesofproject/linux/files/10206584/dump1.txt)
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq1.txt](https://github.com/thesofproject/linux/files/10206591/dump-sdw-mbq1.txt)

If this is what you need, I'll re-run using RT711_JD2.

**Comment by shumingfan** [comment] 2022-12-12 09:41
@eugenhu OK, please dump the registers using RT711_JD2.

**Comment by eugenhu** [comment] 2022-12-12 09:49
Using RT711_JD2,
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump2.txt](https://github.com/thesofproject/linux/files/10206714/dump2.txt)
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq2.txt](https://github.com/thesofproject/linux/files/10206715/dump-sdw-mbq2.txt)

**Comment by shumingfan** [comment] 2022-12-12 13:35
@eugenhu Could you share the information from the command 'dmidecode'?
Our HW engineer wants to check the HW ID.

**Comment by eugenhu** [comment] 2022-12-12 13:44
$ dmidecode
[dmidecode.txt](https://github.com/thesofproject/linux/files/10208512/dmidecode.txt)

Thanks.

**Comment by shumingfan** [comment] 2022-12-13 06:14
@eugenhu 
Could you try this patch (https://github.com/shumingfan/linux/commit/dd54f92fa9fca940ffd7400c7f1db7e21fb0b42a) and use RT711_JD2_100K to test?
And please dump the registers with the same method.

**Comment by eugenhu** [comment] 2022-12-13 07:08
Using RT711_JD2_100K,
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump3.txt](https://github.com/thesofproject/linux/files/10215304/dump3.txt)
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq3.txt](https://github.com/thesofproject/linux/files/10215306/dump-sdw-mbq3.txt)

The headphones now show up as (plugged-in) on pavucontrol. But when I tried to play sounds through it with `speaker-test`, I can't hear anything, I see the sound activity bar moving up and down in pavucontrol though. Sound activity bar is zero for the headphone mic also.

**Comment by shumingfan** [comment] 2022-12-13 07:18
@eugenhu 
Please share the information while playback.
$ amixer contents

and check DAPM status
$ cd /sys/kernel/debug/asoc/
$ grep -rn On ./

**Comment by eugenhu** [comment] 2022-12-13 07:25
$ amixer contents -Dhw:0
[amixer-contents.txt](https://github.com/thesofproject/linux/files/10215442/amixer-contents.txt)

\# cd /sys/kernel/debug/asoc/
\# grep -rn On ./
[dapm.txt](https://github.com/thesofproject/linux/files/10215450/dapm.txt)

**Comment by shumingfan** [comment] 2022-12-13 07:59
@eugenhu 
Please set the controls for recording below before the testing.
amixer cset name='rt711 ADC 22 Mux' 'MIC2'
amixer cset name='rt711 FU0F Capture Volume' 57
amixer cset name='rt711 FU0F Capture Switch' 1
amixer cset name='PGA2.0 2 Master Capture Volume' 80
amixer cset name='PGA2.0 2 Master Capture Switch' 1

Could you use the aplay or arecord command to test again?
$ aplay -Dplughw:0,0 filename.wav
$ arecord -Dhw:0,1 -f dat test.wav -vvv

**Comment by eugenhu** [comment] 2022-12-13 09:07
No sound out of the headphones still.

Recording seems to work, but there's a lot of noise and static, e.g.:
[headphones-mic.mp4](https://user-images.githubusercontent.com/16740189/207274111-5e6274c7-ee3c-4274-ba1d-9f677a670651.mp4)

There is not nearly as much static as when recording in Windows.

Compared to laptop built-in mic:
[laptop-mic.mp4](https://user-images.githubusercontent.com/16740189/207274444-60d6041b-902a-4898-a801-6714b5abc2e8.mp4)

**Comment by shumingfan** [comment] 2022-12-13 09:33
@eugenhu Based on this status, I want to loop back the playback data to the host.
$ cd /sys/kernel/debug/soundwire/master-0-0/intel-sdw/
$ echo 2 > cdns-pdi-loopback-target
$ echo 3 > cdns-pdi-loopback-source

After the settings above, please start playing a wav file, then record the playback data.
a) aplay -Dplughw:0,0 filename.wav
b) arecord -Dhw:0,1 -f dat test.wav -vvv

We could check test.wav whether it saves the playback data.

**Comment by eugenhu** [comment] 2022-12-13 16:01
Original file (from https://www2.cs.uic.edu/~i101/SoundFiles/):
[preamble10.mp4](https://user-images.githubusercontent.com/16740189/207382229-c537c5b2-37fc-4dd8-9fbc-fad6e9893c94.mp4)

Recorded file:
[test.mp4](https://user-images.githubusercontent.com/16740189/207382278-4dc3113c-1a82-46fc-8609-03b15cd8ea19.mp4)

**Comment by plbossart** [comment] 2022-12-14 14:28
The jack detection problem is still open.

**Comment by shumingfan** [comment] 2022-12-15 09:24
@eugenhu Could you dump registers when playback and recording separately again?
I will get the same machine the next Monday or Tuesday, then try to reproduce this issue.
If there is any further update, I will let you know.

**Comment by eugenhu** [comment] 2022-12-15 09:41
Here are the dumps without the looping back stuff.

While playing with `aplay`:
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump-play.txt](https://github.com/thesofproject/linux/files/10235729/dump-play.txt)

$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq-play.txt](https://github.com/thesofproject/linux/files/10235730/dump-sdw-mbq-play.txt)

While recording with `arecord`:
$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01/registers
[dump-record.txt](https://github.com/thesofproject/linux/files/10235739/dump-record.txt)

$ cat /sys/kernel/debug/regmap/sdw:0:025d:0711:01-sdw-mbq/registers
[dump-sdw-mbq-record.txt](https://github.com/thesofproject/linux/files/10235740/dump-sdw-mbq-record.txt)

Thanks a lot for the help. Should I finalize PR https://github.com/thesofproject/linux/pull/4091, or just leave it as is?

**Comment by shumingfan** [comment] 2022-12-20 10:55
@eugenhu I get the machine today and reproduce the no sound out of the headphone issue.
The settings of the codec look ok to me. I need the hardware engineer's help.
Our hardware engineer wants to check the schematic again. Please wait for him.

**Comment by shumingfan** [comment] 2022-12-22 07:30
@eugenhu I updated the patch (837353837876d62ab6f68c52eb8d6c6ae28d4496).
Please try to test it. Thanks.

**Comment by eugenhu** [comment] 2022-12-22 09:20
Great, I've just tried the new patch and I think everything is working now. Speakers, headphones, laptop mic, headphone mic all seem to be working. Thanks!

**Comment by plbossart** [comment] 2022-12-22 14:32
@eugenhu did you mean that you changed the quirk in sof_sdw.c to use JD2_100K ?
Not sure how the patch from @shumingfan would help otherwise.

If everything works well, can you update the PR https://github.com/thesofproject/linux/pull/4091 with comments and your Signed-off-by tag, and we'll send this upstream - likely next year since the merge window is not closed yet.

**Comment by eugenhu** [comment] 2022-12-22 16:34
@plbossart Yes, using RT711_JD2_100K. I'll update PR https://github.com/thesofproject/linux/pull/4091 accordingly and address the comments. Thank you for your help also.

**Comment by shumingfan** [comment] 2022-12-27 13:34
The "ASoC: rt711-sdca: add jack detection mode for JD2 100K" patch was applied already.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=51ea51b18904cd1a0fb244ce41dfd903c2ada628

**Comment by plbossart** [comment] 2023-01-05 21:08
closing, will send patches upstream. Thanks @eugenhu

**Closed as completed by plbossart** 2023-01-05 21:08 UTC
Labels: SDW, Community, ADL, NUC
