### ISSUE TITLE
[CML] ASoC: Both platform name/of_node are set

### ISSUE THREAD

**Issue by zhuyingjiang** [thesofproject/linux#515] opened 2019-01-09 07:19 UTC
When SOF start with load tplg, there will be a error with : " cml_rt5682 cml_rt5682: ASoC: Both platform name/of_node are set for SSP1-Codec", 
but after the kernel start, manually modprobe the module, the module can be load.
another way to make it auto load, is change the devm_kzalloc to kzalloc in snd_soc_init_platform.

**Comment by zhuyingjiang** [comment] 2019-01-09 07:20
log
[why_not_load_mod_2.txt](https://github.com/thesofproject/linux/files/2739744/why_not_load_mod_2.txt)
[why_not_load_mod.txt](https://github.com/thesofproject/linux/files/2739745/why_not_load_mod.txt)

**Comment by plbossart** [comment] 2019-01-09 14:42
On 1/9/19 1:19 AM, Zhu, Yingjiang wrote:
>
> When SOF start with load tplg, there will be a error with : " 
> cml_rt5682 cml_rt5682: ASoC: Both platform name/of_node are set for 
> SSP1-Codec",
>
This is odd. I've seen this message before and it's been discussed this 
week on the alsa mailing list, look for "[alsa-devel] [PATCH] ASoC: 
core: Fix deferral of machine drivers"


> but after the kernel start, manually modprobe the module, the module 
> can be load.
>
Loading the module driver manually will not execute the probe and create 
a card, so that's not a solution.
>
> another way to make it auto load, is change the devm_kzalloc to 
> kzalloc in snd_soc_init_platform.
>
why would that help?

**Comment by plbossart** [comment] 2019-01-09 16:43
@zhuyingjiang when you provide logs, it's good if their names are self-explanatory. "why_not_load_mod.txt" and "why_not_load_mod_2.txt" don't tell me what you are trying to do, and how they relate to your bug description

Also you may want to check why the codec is not registered in the first place:

[    3.366721] cml_rt5682 cml_rt5682: ASoC: CODEC DAI rt5682-aif1 not registered
[    3.381978] cml_rt5682 cml_rt5682: ASoC: CODEC DAI rt5682-aif1 not registered

Looks to me like you didn't look at the root cause: the machine driver was selected based on the presence of an ACPI ID but the codec driver didn't probe successfully, so things won't work at this point.

**Comment by bardliao** [comment] 2019-01-10 06:27
Thanks @plbossart for the information. I read [ASoC: core: Fix deferral of machine drivers](https://lore.kernel.org/patchwork/patch/1030024/). I think that is exactly what we meet now. I applied the patch manually and it solved the issue. 

>> another way to make it auto load, is change the devm_kzalloc to
>>kzalloc in snd_soc_init_platform.

>why would that help?

The root cause is the "platform" is dynamic allocated by devm_kzalloc() and it will be freed automatically on error. And It will not be freed automatically If we use kzalloc(). But it will not be freed at all if we don't add a appropriate kfree() for it.

**Comment by zhuyingjiang** [comment] 2019-01-10 07:33
@plbossart I am now report the issues first and I will go deep into the bugs, when the issues are reported.
And OK, I will change the filename and the descriptions.
 Bard said he still find this problem before. @bardliao Could you provide some comments?

**Comment by zhuyingjiang** [comment] 2019-01-11 11:13
@plbossart @bardliao Thanks, this fixed the issue, will wait when it merged , and verify again.

**Comment by mengdonglin** [comment] 2019-01-15 11:23
@plbossart could you help to merge  patch [ASoC: core: Fix deferral of machine drivers](https://lore.kernel.org/patchwork/patch/1030024/) to close this issue?

**Comment by bardliao** [comment] 2019-01-15 11:35
@mengdonglin It seems the patch has not been applied to upstream yet.

**Comment by plbossart** [comment] 2019-01-15 15:01
On 1/15/19 5:35 AM, Bard Liao wrote:
>
> @mengdonglin <https://github.com/mengdonglin> It seems the patch has 
> not been applied to upstream yet.
>
It's even worse, it creates issues with the way we use .platform_name in 
all machine drivers.

At any rate I don't get why we have this issue only on CML so I would 
err on the side of a mistake in the CML support.

**Comment by bardliao** [comment] 2019-01-16 00:58
@plbossart I can see this issue on ICL. APL, and BYT. An easy way to reproduce it is to use an invalid .codec_dai_name on any dai link. So bind dai link will get error, and it is easy to see the issue when the soc core retry to bind dai link.

**Comment by plbossart** [comment] 2019-01-16 01:15
@bardliao I have never seen this issue on APL/BYT so you will have to provide me with a configuration and log for me to believe it. My money is on a missing configuration of your machine driver. There are actually no usable logs for this issue, we'd need to progress on what the root cause before speculating further.

**Comment by bardliao** [comment] 2019-01-16 06:46
@plbossart attached the .config and dmesg. the specific config can reproduce the issue on Up2.
Which is made by ```scripts/kconfig/merge_config.sh .config <PATH>/kconfig/base-defconfig <PATH>/kconfig/sof-defconfig <PATH>/kconfig/hdaudio-codecs-defconfig```
with the following change.
```
# CONFIG_SND_HDA_INTEL is not set
+CONFIG_DEBUG_KMEMLEAK=y
+CONFIG_DEBUG_KMEMLEAK_EARLY_LOG_SIZE=4000
```
However I can't find a working for CNL. I am checking if there is anything wrong on machine driver.

[config.txt](https://github.com/thesofproject/linux/files/2762907/config.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/2762908/dmesg.txt)

**Comment by bardliao** [comment] 2019-01-16 10:15
@plbossart I think I get the reason why the issue is always seen with rt5682 codec. There are so many sleep in rt5682_i2c_probe(),  and snd_soc_register_component() will not called before dai link binding. So dai link binding won't success in the first try, and we will meet the issue in the second try. We don't see this issue on other platforms since we can bind dai link successfully at the first try and the issue can only be seen after second try of dai link binding.

**Comment by zhuyingjiang** [comment] 2019-01-16 10:34
> There are so many sleep in rt5682_i2c_probe(), and snd_soc_register_component() will not called before dai link binding.

@bardliao So this is a issue/bug of rt5682?

**Comment by bardliao** [comment] 2019-01-16 11:17
@zhuyingjiang No the sleep are necessary for rt5682. ASoC allows retry on dal link binding. The issue is as [ASoC: core: Fix deferral of machine drivers](https://lore.kernel.org/patchwork/patch/1030024/) says the "platform" is dynamic allocated by devm_kzalloc() and it will be freed automatically on error. So now we will see the "ASoC: Both platform name/of_node are set" error after second try in dai link binding.

**Comment by zhuyingjiang** [comment] 2019-01-16 11:39
@plbossart  Yes,  I have saw a illegal name of platform, why the name is set should be root cause
====plat name: ;ݱ\xffffffff\xffffffff\xffffffff\xffffffff02\xffffffb2\xffffffff\xffffffff\xffffffff\xffffffff====of_node (null)===

**Closed as completed** 2019-02-01 02:26 UTC
Labels: bug, CML
