### ISSUE TITLE
[BUG][TGL][SDW][CI] Volteer: Parity error detected

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#2533] opened 2020-10-26 08:48 UTC
In daily test report 594 on TGL SDW Chromebook, below message shows in suspend-resume test case:
```
[   38.453229] max98373 sdw:1:19f:8373:0:7: Parity error detected
[   38.454043] max98373 sdw:1:19f:8373:0:3: Parity error detected
```

**Recipe:**
Kernel: topic/sof-dev d0a335d
SOF : master e04610b1
TPLG: sof-tgl-sdw-max98373-rt5682-4ch.tplg
Platform: TGL Chrome book

**Comment by keyonjie** [comment] 2020-11-02 03:18
@naveen-manohar FYI.

**Comment by aiChaoSONG** [comment] 2020-11-13 02:01
Will monitor this issue for a week, if not reproduced, will close.

**Comment by RanderWang** [comment] 2020-11-17 09:06
@aiChaoSONG   I often get this parity error. According to @bardliao  we need to add a prop to 98373

**Comment by mengdonglin** [comment] 2020-11-18 10:06
@aiChaoSONG @RanderWang Is there any impact on audio functionality when you observe this parity error? Need this info to decide the proper priority

**Comment by RanderWang** [comment] 2020-11-19 09:08
> @aiChaoSONG @RanderWang Is there any impact on audio functionality when you observe this parity error? Need this info to decide the proper priority

Nothing but notify you command parity error

**Comment by aiChaoSONG** [comment] 2020-11-23 02:56
Not reproduced on: 2020/11/23 UTC+8

**Comment by plbossart** [comment] 2020-12-11 19:16
Reproduced w/ topic/sof-dev + timeout fixes:

````
kernel: [ 9630.149535] intel-sdw intel-sdw.0: intel_link_power_up: powering up all links
kernel: [ 9630.149536] intel-sdw intel-sdw.0: intel_link_power_up: first link up, programming SYNCPRD
kernel: [ 9630.149880] rt5682 sdw:0:25d:5682:0: sdw_modify_slave_status: initializing completion for Slave 1
kernel: [ 9630.150315] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
kernel: [ 9630.150325] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
kernel: [ 9630.150742] intel-sdw intel-sdw.0: Slave status change: 0x2
kernel: [ 9630.150747] soundwire sdw-master-0: Slave attached, programming device number
kernel: [ 9630.150937] soundwire sdw-master-0: SDW Slave Addr: 20025d568200
kernel: [ 9630.150939] soundwire sdw-master-0: SDW Slave class_id 0x00, mfg_id 0x025d, part_id 0x5682, unique_id 0x0, version 0x2
kernel: [ 9630.150940] soundwire sdw-master-0: Slave already registered, reusing dev_num:1
kernel: [ 9630.151178] intel-sdw intel-sdw.0: Msg ignored for Slave 0
kernel: [ 9630.151179] soundwire sdw-master-0: No more devices to enumerate
kernel: [ 9630.151203] intel-sdw intel-sdw.0: Slave status change: 0x21
kernel: [ 9630.151206] rt5682 sdw:0:25d:5682:0: sdw_modify_slave_status: signaling completion for Slave 1
kernel: [ 9630.162317] max98373 sdw:1:19f:8373:0:7: sdw_modify_slave_status: initializing completion for Slave 1
kernel: [ 9630.162319] max98373 sdw:1:19f:8373:0:3: sdw_modify_slave_status: initializing completion for Slave 2
kernel: [ 9630.163071] intel-sdw intel-sdw.1: Slave status change: 0x2
kernel: [ 9630.163075] soundwire sdw-master-1: Slave attached, programming device number
kernel: [ 9630.163241] soundwire sdw-master-1: SDW Slave Addr: 27019f837300
kernel: [ 9630.163241] soundwire sdw-master-1: SDW Slave class_id 0x00, mfg_id 0x019f, part_id 0x8373, unique_id 0x7, version 0x2
kernel: [ 9630.163242] soundwire sdw-master-1: Slave already registered, reusing dev_num:1
kernel: [ 9630.163470] soundwire sdw-master-1: SDW Slave Addr: 23019f837300
kernel: [ 9630.163470] soundwire sdw-master-1: SDW Slave class_id 0x00, mfg_id 0x019f, part_id 0x8373, unique_id 0x3, version 0x2
kernel: [ 9630.163471] soundwire sdw-master-1: Slave already registered, reusing dev_num:2
kernel: [ 9630.163704] intel-sdw intel-sdw.1: Msg ignored for Slave 0
kernel: [ 9630.163705] soundwire sdw-master-1: No more devices to enumerate
kernel: [ 9630.163731] intel-sdw intel-sdw.1: Slave status change: 0x221
kernel: [ 9630.163734] max98373 sdw:1:19f:8373:0:7: sdw_modify_slave_status: signaling completion for Slave 1
kernel: [ 9630.163927] max98373 sdw:1:19f:8373:0:3: sdw_modify_slave_status: signaling completion for Slave 2
kernel: [ 9630.164145] intel-sdw intel-sdw.1: Slave status change: 0x440
kernel: [ 9630.164427] max98373 sdw:1:19f:8373:0:7: Parity error detected
kernel: [ 9630.165301] max98373 sdw:1:19f:8373:0:3: Parity error detected
kernel: [ 9630.165704] intel-sdw intel-sdw.1: Slave status change: 0x220
````

A parity check will typically miss 50% of the cases. Here we have two separate devices who report the parity issue at the same time, this is statistically strongly correlated and does not appear random.

The problem did not appear in a test repetition, so it's not 100% reproducible. Will add more traces and keep checking.

@fredoh9 @RanderWang I would need your help to inspect the cases where this error appeared to see if this was with a specific test case:

If I look at the initial bug report above, I see that in Test 594 the parity error happened with 
check-suspend-resume-with-audio.sh -l 15 -m capture

When I reproduced the test, it was with 
check-suspend-resume-with-audio.sh -l 15 -m playback

Maybe it's a red-herring, but it's worth checking if we need to have audio streaming to see the issue, or if this happened also in the past with regular plain vanilla suspend-resume.

**Comment by RanderWang** [comment] 2020-12-14 07:36
@plbossart  yes,  I could always reproduce it with check-suspend-resume-with-audio.sh without any parameters. I didn't try -m options.

**Comment by plbossart** [comment] 2020-12-16 00:23
> @plbossart yes, I could always reproduce it with check-suspend-resume-with-audio.sh without any parameters. I didn't try -m options.

Thanks for sharing this info @RanderWang, that will help narrow the tests.

**Comment by plbossart** [comment] 2020-12-17 00:47
I was able to reproduce the issue with a much simpler test:

````bash
#!/usr/bin/bash

set -e

modprobe snd-sof-pci
TPLG=sof-tgl-sdw-max98373-rt5682.tplg ~/sof-test/test-case/check-kmod-load-unload.sh -l2
TPLG=sof-tgl-sdw-max98373-rt5682.tplg ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 200 -m playback
````

I am not even sure the kmod test is needed.

With additional traces, the parity error can be shown as happening exactly at the same time as the bus clash errors we chose to ignore a couple of weeks ago.

[dmesg3.txt](https://github.com/thesofproject/linux/files/5706274/dmesg3.txt)

At this point, it seems the devices don't seem to have any issues but somehow the bus clash/parity issues happen randomly. The best course of action is probably to ignore both bus clash and parity issue, will try to cook something.

**Comment by plbossart** [comment] 2020-12-18 16:06
Potential fix here: https://github.com/thesofproject/linux/pull/2645

Additional tests do confirm that the parity error is correlated with a bus clash error, the suggestion is to ignore both with a parity quirk at the master level.

**Comment by plbossart** [comment] 2021-01-22 00:17
closing since there's been no occurrence of this issue for 1+ month

**Closed as completed by plbossart** 2021-01-22 00:17 UTC
Labels: bug, P3, codec, TGL, SDW, MAX98373, Parity error
