### ISSUE TITLE
[FEATURE] Support for ES8336 on AMD

### ISSUE THREAD

**Issue by andreaconsole** [thesofproject/linux#3779] opened 2022-07-22 14:49 UTC
Hi everyone and thak you for your precious efforts.
I understand that it is a general issue with this audio card, but it also seems that ES8336 will be supported sooner on Intel chipsets than on AMD. I open this issue to make sure I get the information as soon as some support to AMD is available (even through a patch).
Regarding my personal situation, I own a Matebook D15 Ryzen 5500U, with Windows 11 (which I hope to remove soon) and Kubuntu 22.04 in dual boot. As many people highlighted, the audio card is not recognised for this kind of laptops.
So far, I unsuccessfully tried this approach: https://ubuntuhandbook.org/index.php/2022/07/fix-no-sound-issue-ubuntu-22-04-essx8336/
It is not specified, but since it did not work for me, I assume it is meant for Intel chipset.
By the way, the result of alsa-info command for my laptop is here: http://alsa-project.org/db/?f=b91cb314d1042018a232ab9b23ef3977e4512c8f
Thank you for any help you can provide!

PS:
I have no competence in writing drivers, but I own an AMD Ryzen 5 with es8336, Kubuntu and Windows 11 in dual boot. If anyone wants to try to develop the codec driver from scratch, I am available to contribute with tests and other activities, e.g. aimed at reverse engineering the Windows driver.

**Comment by vaurat** [comment] 2022-07-29 17:29
:+1: I'm waiting support since 22.04 for my _Honor Magicbook 14_ AKA _Huawei Matebook D14_ bought in oct. 2020.

**Comment by andreaconsole** [comment] 2022-08-02 15:03
UPDATE: as of today, the official answer of Huawei is still "we do not support the installation of Linux on laptops sold with Windows", meaning that they have no interest in contacting AMD/ES to find a solution. I sent a request for support to AMD and Everest Semiconductor, too (and I guess I am not the first), but I don't expect a better outcome.

**Comment by plbossart** [comment] 2022-08-08 09:12
duplicate of https://github.com/thesofproject/linux/issues?q=is%3Aissue+is%3Aopen+label%3A%22codec+ES8336%22

**Closed as completed by plbossart** 2022-08-08 09:12 UTC
Labels: Community, codec ES8336, AMD
