### ISSUE TITLE
[WHL] Unable to boot linux to UI with SOF enabled for 4.19 kernel

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#250] opened 2018-11-07 13:09 UTC
Builded kernel with default config - can boot to UI. 
Steps:

> git clone https://github.com/thesofproject/linux.git
> cd linux
> git status

branch: sof-dev
commit: af44aa9
>  make defconfig
>  make deb-pkg -j16 KCONFIG_CONFIG=.config

After install this image there is a possibility to boot linux to UI.

When I use config where is enabled SOF, HDA, CNL and codec for WHL (from RanderWang) there is an issue during boot.

branch: sof-dev
commit: af44aa9

>  cp ../Rander/hda_config ./.config
>  make menuconfig KCONFIG_CONFIG=.config -> check options: SOF, HDA, CNL, codec
>  make deb-pkg -j16 KCONFIG_CONFIG=.config

During boot I have this issue:
![image](https://user-images.githubusercontent.com/41113230/48132942-68241600-e295-11e8-879a-993a22950141.png)

**Comment by lgirdwood** [comment] 2018-11-07 14:02
@echudzi sorry, there is not much info realted to audio on the screenshot. Can you attached the output from dmesg so @RanderWang can check.

**Comment by RanderWang** [comment] 2018-11-07 14:12
l test this config on three whl ,no  such issue. and kernel config depends on  hw,  so  my config maybe not suitable for  yours.  lt boot failed  before loading sof.  l can't debug it

**Comment by emilchudzik** [comment] 2018-11-07 14:42
@lgirdwood there is no dmesg, I see only this screen after boot.
@RanderWang How did you generate your config? I know where SOF/HDA/CNL and codec enable. But I need stable base config.

**Comment by emilchudzik** [comment] 2018-11-07 14:58
I just make on commit af44aa9 (sof-dev branch):
> make defconfig

I can boot to UI, but there is an issue on dmesg:

```
[    2.805079] snd_hda_intel 0000:00:1f.3: enabling device (0000 -> 0002)
...
[    2.809040] ALSA device list:
[    2.809040]   No soundcards found.
...
[    2.984838] snd_hda_intel 0000:00:1f.3: bound 0000:00:02.0 (ops 0xffffffff8a298d00)
[    3.003333] hdaudio hdaudioC0D0: Unable to bind the codec
[    3.003502] hdaudio hdaudioC0D2: Unable to bind the codec
...
```

**Comment by emilchudzik** [comment] 2018-11-07 15:03
And this is the config file based on "make defconfig":
[config_af44aa9_def-hdaconfig.txt](https://github.com/thesofproject/linux/files/2557878/config_af44aa9_def-hdaconfig.txt)

@RanderWang could you check what is still to be done in the config? Maybe you will need to add the missing settings to the Wiki?

**Comment by plbossart** [comment] 2018-11-07 16:40
@RanderWang please submit a PR for the Kconfig repository (https://github.com/thesofproject/kconfig) 
so that we have your setup maintained and reproduced. It's not good practice to maintain your own config shared privately. 
we only want the deltas on top of defconfig, not the whole thing.
Thanks!

**Comment by plbossart** [comment] 2018-11-07 16:42
@echudzi you may want to use ktest to simplify the kernel updates. There is no need to use the Debian packages. See https://github.com/thesofproject/sof-docs/blob/master/getting_started/setup/setup_ktest_environment.rst

**Comment by RanderWang** [comment] 2018-11-08 07:26
> @RanderWang please submit a PR for the Kconfig repository (https://github.com/thesofproject/kconfig)
> so that we have your setup maintained and reproduced. It's not good practice to maintain your own config shared privately.
> we only want the deltas on top of defconfig, not the whole thing.
> Thanks!

Yes, I will do it

**Comment by RanderWang** [comment] 2018-11-08 07:53
@plbossart  @echudzi 

I try make defconfig to make a default config. And then I build a image without any change.  I get kernel crash. I tried your idea a few month ago on CNL, also failed.

![crash](https://user-images.githubusercontent.com/39945651/48185454-02588c80-e370-11e8-8ae9-40d0f0c06f56.jpg)


You may find hda info in this picture, but it is not related to it. I disabled audio driver and got another crash at different point.

make defconfig doesn't work on WHL. please see my wikipage to build kernel image. Please try it, I just first remove .config and make menuconfig (it will select almost all the items, more than make defconfig) then select SOF. It works well

**Comment by emilchudzik** [comment] 2018-11-08 10:20
@plbossart @RanderWang when I delete .config file from repository then command "make menuconfig" create new .config based on local machine where it will be built. 
In my case this is dev machine with linux (some market desktop). I think this is not good solution to use this config for WHL.
![image](https://user-images.githubusercontent.com/41113230/48192476-315b0800-e348-11e8-8a08-6b4184d841f9.png)

**Comment by emilchudzik** [comment] 2018-11-08 10:22
But with that config (based on my local dev machine from market) I can boot linux with HDA and SOF enabled to UI and playback/capture works well.

We can close issue, but for me this in to good way to prepare config for any platform.

**Comment by plbossart** [comment] 2018-11-08 14:12
@emilchudzik please use the recommended path of doing "make defconfig" then use merge_config.sh to add the needed options. We cannot reproduce any of your problems if you use a locally generated config based on a kernel that is 4 generations older than the one you are testing. 
There's a reason why I worked on these kconfig fragments... only use "make menuconfig" to alter a configuration, never to start from scratch. Thank you.

**Comment by emilchudzik** [comment] 2018-11-09 08:44
@plbossart your method in my WHL doesn't work, I still can't boot to UI, when I use "make defconfig" and then follow steps from https://github.com/thesofproject/kconfig.

when I use Rander method - I can boot to UI, but this steps I still think is not good idea:
rm .config
make menuconfig
It enable a lot of options in kernel, time of building is long, but it works. 
I try to explain it in ths topic, for me it is still not clear. 
If only I met this problems we can close this issue.

**Comment by plbossart** [comment] 2018-11-09 14:37
@xiulipan can you confirm if the configs on  https://github.com/thesofproject/kconfig work for WHL and if not work with @RanderWang to fix this? If @emilchudzik is right, we have a gap in our configs. Thanks!

**Comment by xiulipan** [comment] 2018-11-10 03:37
@plbossart 
Yes our config need some on device test.
Now the https://github.com/thesofproject/kconfig could not even boot on APL UP2 board.
I am doing the fix to have the kernel built with kconfig could run on every platform we have.
Now I found most gaps are in base-defconfig part, will send the PR once I did all the patch and test.

**Comment by plbossart** [comment] 2018-11-11 15:12
@xiulipan I use all the kconfig stuff on Up2 and have no problem at all. It's been working for at least 6 months. Did you mean the WHL board?

**Comment by plbossart** [comment] 2018-11-12 17:04
@emilchudzik I also just tried on a WHL device, things work just fine for me. I am able to boot to UI with make defconfig+ merge_config.sh .config base-defconfig. The only thing that doesn't work is the trackpad. 

As to the error on "Unable to bind codec" error, it's normal since we disable the legacy HDAudio in the base config to avoid conflicts with SOF or SST drivers. It's a feature, not a bug. I just pushed an additional kconfig fragment called hdaudio-legacy-defconfig that gives you legacy audio directly (incompatible and mutually exclusive with sof-defconfig and sst-defconfig of course).

**Comment by xiulipan** [comment] 2018-11-14 04:04
@plbossart 
Sorry about that. This seems to be the CI issue, I rechecked the kernel binary with kconfig on BYT, APL, CNL, WHL and all works find with UI.
Have no ICL platform. Will update status later.

**Comment by emilchudzik** [comment] 2018-11-14 09:22
@plbossart new repo kconfig and command below resolve issue, there is possibility to boot to UI.
`# cd <kernel_path>`
`# make defconfig`
`# /scripts/kconfig/merge_config.sh .config [kconfig_path]/kconfig/base-defconfig [kconfig_path]/kconfig/sof-defconfig [kconfig_path]/kconfig/hdaudio-codecs-defconfig`
`# make bindeb-pkg -j32`

This is config file created on above steps:
[_config.txt](https://github.com/thesofproject/linux/files/2580357/_config.txt)


But loading topology failed:
![image](https://user-images.githubusercontent.com/41113230/48477609-577a1f80-e802-11e8-8287-f6b64e244828.png)

for  HDA I need to use: /lib/firmware/intel/**sof-hda-generic.tplg**, not sof-cnl.tplg as in dmesg.
@RanderWang  could you look at this why driver forces loading **sof-cnl.tplg**

**Comment by plbossart** [comment] 2018-11-14 17:40
@emilchudzik you most likely have an ACPI ID that selects an I2S-based machine. You need to make sure your BIOS or ACPI initrd overrides don't have anything that prevents HDaudio from being selected. Can you run alsa-info.sh and paste the results somewhere.

**Comment by emilchudzik** [comment] 2018-11-15 09:27
Here is an alsa-info output when used Rander method (created config based on local machine config).
Status: playback and capture works.
[alsa-info.txt.dN7IBDWdtd_usingRanderMethod.txt](https://github.com/thesofproject/linux/files/2584532/alsa-info.txt.dN7IBDWdtd_usingRanderMethod.txt)

Here is an alsa-info output when used kconfig to prepare .config file.
Status: loaded sof-cnl.tplg instead of sof-hda-generic.tplg
[alsa-info.txt.kz4taOuHFc_usingKconfig.txt](https://github.com/thesofproject/linux/files/2584533/alsa-info.txt.kz4taOuHFc_usingKconfig.txt)

BIOS settings not changed - from the Rander Wiki

**Comment by plbossart** [comment] 2018-11-15 14:47
@emilchudzik the log does not include anything related to ACPI devices? 
the chunk of alsa-info.sh is this:
````bash
# Check for ACPI device status
if [ -d /sys/bus/acpi/devices ]; then
    for f in /sys/bus/acpi/devices/*/status; do
	ACPI_STATUS=$(cat $f 2>/dev/null);
	if [[ "$ACPI_STATUS" -ne 0 ]]; then
	    echo $f $'\t' $ACPI_STATUS >>$TEMPDIR/acpidevicestatus.tmp;
	fi
    done
fi
````

We need to figure out why you have an I2S-related ACPI ID. Chances are the config you use locally does not include anything but HDAudio support, while the generic one includes both HDaudio and I2S support for CNL-rt274, and the latter is likely selected. Keep in mind that HDaudio is selected as a fall-back when I2S devices are not detected.

**Comment by mengdonglin** [comment] 2018-11-25 03:01
@emilchudzik Closing this issue since Ubuntu can boot to UI now. Please file a new bug if you still see the proper HDaudio machine driver cannot be selected on you WHL RVP.

**Closed as completed by mengdonglin** 2018-11-25 03:01 UTC
Labels: bug, P2, WHL
