### ISSUE TITLE
[BUG][CML][UCM2]Speaker and headset has sound output at the same time after suspend-resume

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2014] opened 2020-04-15 10:32 UTC
***Describe the bug***
Speaker and headset has sound output at the same time after suspend-resume
Ctrl +c to stop paplay then paplay  Right now  again can not recovery,
Ctrl +c to stop paplay,wait about 20s,paplay again can recovery

**To Reproduce**
1.sudo reboot with headset connected
2.open sound settings
3.set Output Device as " Speaker-sof-hda-dsp"
4.set Input Device as "Headset Mono Microphone-sof-hda-dsp" or"Digital Microphone-sof-hda-dsp"
5.paplay wav/48California_Dreaming.wav -vv 
6."sudo rtcwake -m mem -s  10" to suspend
7.wait device to wake up
8.repeat step 6~7 2 times

**Reproduction Rate**
  Reproduction Rate >90% issues can be reproduced when repeating suspend and wakeup 3 times.

**Expected behavior**
Only speaker has sound output

**Actual result**
Speaker and headset has sound output at the same time

Amixer contents is below,there is no difference between them
[amixer_faile.txt](https://github.com/thesofproject/linux/files/4480876/amixer_faile.txt)
[amixer_pass.log](https://github.com/thesofproject/linux/files/4480877/amixer_pass.log)

Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: 5f7d4e2    https://github.com/thesofproject/sof/releases/tag/v1.5-rc1
Kernel: stable linux 5.5.9 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.9, commit 81b6e04c4b
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2:UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

[dmesg0415.log](https://github.com/thesofproject/linux/files/4480879/dmesg0415.log)
[sof-logger0415.log](https://github.com/thesofproject/linux/files/4480881/sof-logger0415.log)

**Comment by Liviali155** [comment] 2020-04-15 11:41
Issue can be  reproduced on sof/dev(commit:73187435)
Issue can be reproduced on 5.5.8 Kernel: [97453d9] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
Issue can be reproduced on 5.6.3 kernel:commit f9fb8575

**Comment by juimonen** [comment] 2020-04-15 14:11
yeah I can reproduce this. Can't think anything else that this has to be something in quite low level as we have alsamixer headphones muted, but still the sound is going there... so the actual codec and alsa mute are out of sync.

**Comment by juimonen** [comment] 2020-04-15 19:06
@mengdonglin @Liviali155 After debugging this I see that when waking up from suspend, snd_hda_codec_realtek is syncing the register 0x21b8000 to value 0x80. Per my debugging this should be the headphone path mute and the value 0x80 should mean muted. 

Why this is not muting the actual codec is a mystery to me. I see the same sequence with the forced "rtcwake" call and with just letting the codec go itself to suspend/wake. The difference is that user space pulseaudio doesn't go to its normal "suspend", the process is just frozen (I guess). So when pulseaudio process wakes up it doesn't do any twiddling of alsa parameters. And for some reason the register sync is not enough by itself.

I think we need to ask from realtek some info/clues about this.

**Comment by Liviali155** [comment] 2020-04-16 04:12
Issue can be reproduced after revert PR #1983

**Comment by juimonen** [comment] 2020-04-16 05:36
@bardliao can you point out this issue for realtek folks also for some comments? I'm little bit lost how to advance with this...

**Comment by ClarexZhou** [comment] 2020-04-16 09:38
Error not seen on Lenovo Yoga x1 ALC285 in HDA mode, with 1.4.2 fw. Tried withe 5.5.9 and 5.6.3 kernel.

**Comment by bardliao** [comment] 2020-04-16 10:25
> @bardliao can you point out this issue for realtek folks also for some comments? I'm little bit lost how to advance with this...

Sent email to @kailangyang.

**Comment by juimonen** [comment] 2020-04-16 10:29
@bardliao thank you!

**Comment by bardliao** [comment] 2020-04-16 10:30
@ClarexZhou @Liviali155 Can you check if below experiments can mute the headphone when you meet the issue?
1. amixer cset name='Headphone Playback Switch' 1 and amixer cset name='Headphone Playback Switch' 0
2. unplug and plug the headphone.
Please do the 2 experiment separately.

Thanks

**Comment by Liviali155** [comment] 2020-04-17 01:35
> @ClarexZhou @Liviali155 Can you check if below experiments can mute the headphone when you meet the issue?
> 
> 1. amixer cset name='Headphone Playback Switch' 1 and amixer cset name='Headphone Playback Switch' 0
> 2. unplug and plug the headphone.
>    Please do the 2 experiment separately.
> 
> Thanks
1.After amixer cset name='Headphone Playback Switch' 0 ,the headphone was muted,only has speaker has sound output
2.unplug and plug the headphone,Both of speaker and headset has no sound output,because the Output Device Changed to "Headphones-sof-hda-dsp",and Input Device Changed to "Headphones Stereo Microphone-sof-hda-dsp",At the same time if change
Output Device as " Speaker-sof-hda-dsp"  Input Device as "Headset Mono Microphone-sof-hda-dsp" again,only has speaker has sound output

**Comment by juimonen** [comment] 2020-04-17 06:05
attached alsainfo and codec dump after the issue happened:


[alsa_info.txt](https://github.com/thesofproject/linux/files/4491177/alsa_info.txt)
[codec_dump.txt](https://github.com/thesofproject/linux/files/4491178/codec_dump.txt)

**Comment by juimonen** [comment] 2020-04-17 06:38
new alsainfo after dump enabled:
[alsa_info3.txt](https://github.com/thesofproject/linux/files/4491293/alsa_info3.txt)

**Comment by juimonen** [comment] 2020-04-17 06:44
@Liviali155 @ClarexZhou 

I made https://github.com/alsa-project/alsa-ucm-conf/pull/21 to address the issue of wrong input when inserting headset. Not solving this issues, but related.

**Comment by juimonen** [comment] 2020-04-17 07:23
yet another try with alsa-info
[alsa_info4.txt](https://github.com/thesofproject/linux/files/4491532/alsa_info4.txt)

**Comment by KailangYang** [comment] 2020-04-17 08:11
I think this would be mixer layer issue.

Register and mixer didn’t sync. You could see below or dump file.
Register => unmute
Mixer => mute
I think mixer mute can’t access codec register.

Node 0x21 [Pin Complex] wcaps 0x40058d: Stereo Amp-Out
  Control: name="Headphone Playback Switch", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x00, nsteps=0x00, stepsize=0x00, mute=1
  Amp-Out vals:  [0x00 0x00]  =============================>> unmute
  Pincap 0x0001001c: OUT HP EAPD Detect
  EAPD 0x2: EAPD
  Pin Default 0x02211020: [Jack] HP Out at Ext Front
    Conn = 1/8, Color = Black
    DefAssociation = 0x2, Sequence = 0x0
  Pin-ctls: 0xc0: OUT HP
  Unsolicited: tag=01, enabled=1
  Power states:  D0 D1 D2 D3 EPSS
  Power: setting=D0, actual=D0
  Connection: 2
     0x02 0x03*

Simple mixer control 'Headphone',0
  Capabilities: pvolume pswitch
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 87
  Mono:
  Front Left: Playback 48 [55%] [-29.25dB] [off]  => mute
  Front Right: Playback 48 [55%] [-29.25dB] [off]  => mute

**Comment by juimonen** [comment] 2020-04-17 08:18
@kailangyang ok.

If I put debugs on in regmap:
"dmesg -w | grep 0x21b8000" (should be headphone mute other channels register)
When device wakes up I see : 
snd_hda_codec_realtek: Synced register 0x21b8000, value 0x80 (muted)

I understand the above so that it is syncing the headphone mute register to mute (which is correct)? But it is not reflected in the codec?

**Comment by KailangYang** [comment] 2020-04-17 08:34
@juimonen 
codec dump show register NID 0x21 Amp-Out vals:  [0x00 0x00].
This value was the current register value.
Could you use alsamixer to mute headphone?
Then to see the NID 0x21 Amp-Out vals. If value was 0x80.
It shows your verb command was wrong.

**Comment by juimonen** [comment] 2020-04-17 08:43
@kailangyang sorry I'm little bit lost here...

alsamixer shows "muted", but if I toggle it back and forth, it will have effect.

The thing here is that in this "wake up from suspend" case nothing is sent from user space and we are relying on driver resume to restore the settings. And as said, dmesg debug from regmap tells me after wake up that headphone mute is synced. But it is not reflected in the codec dump (and therefore i guess not in the codec). So the question for me is, why ins't the regmap sync going to the codec? it doesn't give me errors either?

**Comment by juimonen** [comment] 2020-04-17 10:16
@kailangyang @Liviali155

I see that the resume in mantis is going through patch_realtek.c alc269_resume. I also see that none of the possible "pop preventing" sleeps are called.

If I add forced 200ms sleep to alc269_resume before regmap sync, this issue will not happen. So I think @kailangyang theory that the codec has not properly started is correct. So even if the sync happens, it is not propagated as codec is not "ready".

I'm not sure what would be the proper place/way to fix this...? @kailangyang any idea?

**Comment by juimonen** [comment] 2020-04-22 10:03
@Liviali155 @mengdonglin we should add some label if this is related to only some codec/platform like mantis...

**Comment by YvonneYang2** [comment] 2020-04-23 02:05
Issue cannot be reproduced on cml-u laptop in ALC711 -RT1308, RT715 SDW mode or cml chrombook in I2S RT5682 mode.

**Comment by ClarexZhou** [comment] 2020-04-23 02:17
Error also can be reproduced on CFL ALC3254 HDA laptop. which also support headphone stere microphone and headset mono microphone.
UCM2: https://github.com/alsa-project/alsa-ucm-conf/UCM2 + https://github.com/alsa-project/alsa-ucm-conf/pull/21
Kernel: sof-dev 8dc1789e
Firmware & tplg: Master 0befebb7

**Comment by juimonen** [comment] 2020-04-29 12:20
@kailangyang ping. sorry to bother you with this also, would there be someone in realtek, who could see the best way to fix this. Seems there needs to be delay when syncing the codec register values in resume... this is the mantis hw.

**Comment by KailangYang** [comment] 2020-04-30 07:24
Please test it with legacy hda driver.
I think this issue didn't happen in legacy hda driver.
This maybe the integration issue with hda bus.

**Comment by juimonen** [comment] 2020-04-30 07:58
@Liviali155 so if testing with legacy, disable the pop-up. That will make the use case different as it sends the switch command again when selecting the device.

**Comment by Liviali155** [comment] 2020-04-30 08:03
> @Liviali155 so if testing with legacy, disable the pop-up. That will make the use case different as it sends the switch command again when selecting the device.

This comment should add in https://github.com/thesofproject/linux/issues/2025？
How to disable pop-up？

**Comment by juimonen** [comment] 2020-04-30 08:09
@Liviali155 hmm yeah I don't no that myself either.... @jason77-wang you have any simple trick how to prevent the pop-up from appearing? I think this is stock 20.04 ubuntu...

**Comment by Liviali155** [comment] 2020-04-30 08:29
> Please test it with legacy hda driver.
> I think this issue didn't happen in legacy hda driver.
> This maybe the integration issue with hda bus.

On matins changed to legacy HDA,runtime_status is always active
Tested 40 times, error not seen
after used “echo 1 > /sys/module/snd_hda_intel/parameters/power_save“ to enable pm runtime_status,it can enter susupend,then tested 30 times,error also not seen

**Comment by mengdonglin** [comment] 2020-08-05 08:33
It seems to be a codec issues, it need some delay before processing the verb correctly. Won't fix

**Closed as completed by mengdonglin** 2020-08-05 08:33 UTC
Labels: bug, won't fix, P2, CML, HDA, CFL, codec, UCM2, codec ALC3204, codec ALC3254, suspend resume
