### ISSUE TITLE
[BUG] dapm_find_widget Error when kmod-load-unload after aplay on GLK_BOB_DA7219

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3105] opened 2021-08-18 07:19 UTC
**Describe the bug**
In inner 5931, on model=GLK_BOB_DA7219 ,after playback and try kmod load unload , error happened when **dapm_find_widget** .
After that , kernel Oops and Call Trace happened

/I ran over 100 rounds, but haven't reproduced it though . Still trying

**To Reproduce**
 TPLG=/lib/firmware/intel/sof-tplg/sof-glk-da7219.tplg ~/sof-test/test-case/check-kmod-load-unload-after-playback.sh -l 5

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: 34fd0612
SOF Branch: main
SOF Commit: aeda0158b0df
Topology:sof-glk-da7219.tplg 
Platform:GLK_BOB_DA7219

**Screenshots or console output**
[dmesg]
```
[ 5643.214258] kernel: sof-audio-pci-intel-apl 0000:00:0e.0: FW Poll Status: reg[0x80]=0x20140000 successful
[ 5643.276064] kernel: general protection fault, probably for non-canonical address 0xdead0000000000f0: 0000 [#1] SMP PTI
[ 5643.276074] kernel: CPU: 1 PID: 90123 Comm: irq/96-da7219-a Not tainted 5.14.0-rc6-daily-default-20210817 #34fd0612
[ 5643.276079] kernel: Hardware name: Google Bobba/Bobba, BIOS Google_Bobba.11825.0.2019_03_06_2015 03/06/2019
[ 5643.276082] kernel: RIP: 0010:dapm_find_widget+0x71/0xd0 [snd_soc_core]
[ 5643.276115] kernel: Code: 00 48 89 e7 e8 80 01 1e e5 49 89 e7 48 8b 5d 18 45 31 ed 48 8b 83 00 04 00 00 48 81 c3 00 04 00 00 4c 8d 60 e8 48 39 c3 74 29 <49> 8b 7c 24 08 4c 89 fe e8 12 ac 1d e5 85 c0 75 0a 49 39 6c 24 28
[ 5643.276119] kernel: RSP: 0018:ffff9e8c40bffd80 EFLAGS: 00010202
[ 5643.276123] kernel: RAX: dead000000000100 RBX: ffffffffc0cac4e0 RCX: 0000000000000000
[ 5643.276126] kernel: RDX: 0000000000000069 RSI: ffffffffc05eda4d RDI: ffff9c9564018a40
[ 5643.276128] kernel: RBP: ffff9c9571cb3768 R08: 0000000000000001 R09: 0000000000000001
[ 5643.276130] kernel: R10: ffff9e8c40bffe38 R11: 0000000000000000 R12: dead0000000000e8
[ 5643.276133] kernel: R13: 0000000000000000 R14: 0000000000000001 R15: ffffffffc05eda4d
[ 5643.276135] kernel: FS:  0000000000000000(0000) GS:ffff9c96b7800000(0000) knlGS:0000000000000000
[ 5643.276138] kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 5643.276140] kernel: CR2: 00005623605491a0 CR3: 000000011161e000 CR4: 0000000000350ee0
[ 5643.276143] kernel: Call Trace:
[ 5643.276149] kernel:  ? __mutex_unlock_slowpath+0x40/0x2a0
[ 5643.276160] kernel:  ? snd_soc_dapm_disable_pin+0x1e/0x50 [snd_soc_core]
[ 5643.276185] kernel:  snd_soc_dapm_set_pin+0x18/0x90 [snd_soc_core]
[ 5643.276208] kernel:  snd_soc_dapm_disable_pin+0x2b/0x50 [snd_soc_core]
[ 5643.276231] kernel:  da7219_aad_irq_thread+0x24a/0x280 [snd_soc_da7219]
[ 5643.276239] kernel:  ? irq_thread+0x93/0x190
[ 5643.276244] kernel:  ? irq_forced_thread_fn+0x70/0x70
[ 5643.276247] kernel:  irq_thread_fn+0x18/0x60
[ 5643.276251] kernel:  irq_thread+0xdd/0x190
[ 5643.276254] kernel:  ? __kthread_parkme+0x38/0x90
[ 5643.276259] kernel:  ? wake_threads_waitq+0x30/0x30
[ 5643.276262] kernel:  ? irq_thread_dtor+0x80/0x80
[ 5643.276265] kernel:  kthread+0x141/0x170
[ 5643.276269] kernel:  ? set_kthread_struct+0x40/0x40
[ 5643.276272] kernel:  ret_from_fork+0x1f/0x30
[ 5643.276279] kernel: Modules linked in: snd_soc_sst_bxt_da7219_max98357a snd_soc_intel_hda_dsp_common snd_soc_hdac_hdmi snd_sof_pci_intel_tgl snd_sof_pci_intel_icl snd_sof_pci_intel_cnl snd_hda_codec_hdmi snd_soc_dmic snd_sof_pci_intel_apl(-) snd_sof_intel_hda_common soundwire_intel soundwire_generic_allocation soundwire_cadence snd_sof_intel_hda snd_soc_hdac_hda snd_hda_ext_core snd_hda_codec snd_hwdep snd_hda_core snd_sof_pci snd_sof_acpi_intel_bdw snd_sof_acpi_intel_byt snd_sof_intel_ipc snd_sof_acpi snd_sof_intel_atom snd_sof_xtensa_dsp snd_sof snd_soc_acpi_intel_match snd_soc_acpi snd_intel_dspcfg snd_intel_sdw_acpi snd_soc_rt1011 snd_soc_rt715 snd_soc_rt1308_sdw snd_soc_rt1308 snd_soc_rt711 snd_soc_rt700 snd_soc_max98373_sdw snd_soc_max98373_i2c snd_soc_max98373 snd_soc_max98090 snd_soc_max98357a snd_soc_wm8804_i2c snd_soc_wm8804 snd_soc_pcm512x_i2c snd_soc_pcm512x snd_soc_rt5682_sdw regmap_sdw soundwire_bus snd_soc_rt5682_i2c snd_soc_rt5682 snd_soc_rt5677 snd_soc_rt5677_spi snd_soc_rt5670
[ 5643.276336] kernel:  snd_soc_rt5660 snd_soc_rt5651 snd_soc_rt5645 snd_soc_rt5640 snd_soc_rl6231 snd_soc_rt298 snd_soc_rt286 snd_soc_rl6347a snd_soc_da7219 snd_soc_da7213 snd_soc_core snd_compress snd_pcm fuse ax88796b asix usbnet x86_pkg_temp_thermal intel_powerclamp snd_seq_midi snd_seq_midi_event snd_usbmidi_lib snd_rawmidi ledtrig_audio snd_soc_sst_ipc regmap_i2c snd_soc_sst_dsp snd_seq i915 i2c_algo_bit ttm snd_seq_device drm_kms_helper processor_thermal_device_pci_legacy processor_thermal_device processor_thermal_rfim processor_thermal_mbox intel_soc_dts_iosf snd_timer elan_i2c snd int3403_thermal int340x_thermal_zone soundcore int3400_thermal acpi_thermal_rel drm drm_panel_orientation_quirks efivarfs mmc_block spi_pxa2xx_platform sdhci_pci cqhci xhci_pci sdhci intel_lpss_pci xhci_hcd intel_lpss idma64 mfd_core [last unloaded: snd_sof_pci_intel_tng]
[ 5643.276404] kernel: ---[ end trace 1c10755ceb274e23 ]---
```

[glk_dmesg.txt](https://github.com/thesofproject/linux/files/7005307/glk_dmesg.txt)

**Comment by plbossart** [comment] 2021-08-18 13:35
duplicate of https://github.com/thesofproject/linux/issues/2676

**Closed as completed by plbossart** 2021-08-18 13:35 UTC
Labels: GLK, Intel Daily tests
