### ISSUE TITLE
Brya / Volteer : Soundwire: AMIC not working

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#2953] opened 2021-05-31 12:23 UTC
Intially, we saw on Brya Proto systems with SNDW card, AMIC is not working. There are no errors , but recording is blank.
When we cross checked with Volteer SNDW, we saw the same issue on latest build. We talked to @libinyang  and he suggested UCM change to suit the updated PCM.

VOLTEER:
With latest topology updated and UCM shared by @libinyang , AMIC recording is still blank.
This seems to be regression as it was working on images in March ( Not done a bisect on where it was introduced yet)

On latest build, i see that if there is playback happening on the headphones, recording is working.
[volteer_14003.zip](https://github.com/thesofproject/linux/files/6570171/volteer_14003.zip)
contains the recorded files, amixer dump and register dump in both cases.

@yongzhi1 please add more details as required

**Comment by plbossart** [comment] 2021-06-01 14:29
@sathya-nujella what do you mean my 'AMIC'? headset capture? If yes that should be an RT5682 problem, no?

**Comment by sathyap-chrome** [comment] 2021-06-01 14:47
@plbossart . Yes , its AMIC. I raised it since Settings provided by @libinyang didnt work and he agreed to take a look as its a regression. Also wanted to know if linux team is seeing same issue on latest builds on SNDW card of Volteer.
@yongzhi1 your thoughts ?

**Comment by yongzhi1** [comment] 2021-06-01 17:11
According to validation team, the amic recording works fine for WW11 TGL BKC, and from their RT5682 reg dump, the regression does not seem to be caused by the codec driver/mixer settings.

**Comment by libinyang** [comment] 2021-06-02 09:04
I did some debug and found it can only capture what is playback. This means it captured the loopback data. However, we didn't loopback the playback and capture.  So it should be either codec hw issue or register setting issue. I will co-debug with Realtek.

**Comment by oder-chiou** [comment] 2021-06-02 12:53
Hi ,
Please verify the patch, if it is OK, i will upstream it, thanks.
[0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset-unplu.zip](https://github.com/thesofproject/linux/files/6584648/0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset-unplu.zip)

**Comment by yongzhi1** [comment] 2021-06-02 13:57
Thanks @oder-chiou , in the dump shared by our validation, we have 0010: d04a in the old working BKC though:
[voltter_working_amic_reg.txt](https://github.com/thesofproject/linux/files/6584938/voltter_working_amic_reg.txt)

With your patch tested on TGL volteer board, good news is that the amic recording can pick up sound from Mic now, the bad news is that when playback running simultaneously, the recording can still capture the playback, not sure if I have a defect DB AIC.

**Comment by plbossart** [comment] 2021-06-02 13:59
@yongzhi1 can you check the mixer settings in case you have a loopback from playback to capture happening in the headset codec?

**Comment by yongzhi1** [comment] 2021-06-02 14:21
Thanks @plbossart , the RT5682 UCM settings haven't been touched for a while: 

https://chromium.googlesource.com/chromiumos/overlays/board-overlays/+/refs/heads/main/overlay-volteer/chromeos-base/chromeos-bsp-volteer/files/ucm-config/sof-soundwire/HiFi.conf#61

On top of above, dev numbers were updated to match current topology: 
https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/2925843

**Comment by mengdonglin** [comment] 2021-06-02 14:38
@plbossart @yongzhi1 @sathyap-chrome @oder-chiou Here is the investigation of @bardliao He found after reverting this rt5682 codec driver commit https://github.com/thesofproject/linux/commit/5a15cd7fce20b1fd4aece6a0240e2b58cd6a225d, AMIC can work except for the 1st recording after booting the device. So this issue seems to be a codec driver regression.

**Comment by sathyap-chrome** [comment] 2021-06-02 15:54
@yongzhi1 can you try the revert. if its good, we can try to keep it for time being

**Comment by yongzhi1** [comment] 2021-06-02 16:52
With 5a15cd7 reverted, on Brya P1 board, I can still repro the same as described at https://github.com/thesofproject/linux/issues/2953#issuecomment-853050795

**Comment by keqiaozhang** [comment] 2021-06-03 01:48
> Hi ,
> Please verify the patch, if it is OK, i will upstream it, thanks.
> [0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset-unplu.zip](https://github.com/thesofproject/linux/files/6584648/0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset-unplu.zip)


@oder-chiou , I think there're 2 issues here:
1. headset jack in cannot record any signals
2. headset jack in will capture the data from headset jack out without the physical loopback.

I tried your patch on Volteer, it can fix the issue2, but issue1 still exists. 

@yongzhi1, seems that I got the opposite result from you.

**Comment by libinyang** [comment] 2021-06-03 01:56
> With [5a15cd7](https://github.com/thesofproject/linux/commit/5a15cd7fce20b1fd4aece6a0240e2b58cd6a225d) reverted, on Brya P1 board, I can still repro the same as described at [#2953 (comment)](https://github.com/thesofproject/linux/issues/2953#issuecomment-853050795)

@yongzhi1 Can you try different type headset? There are 2 type headset, one is Nokia type, the other is iphone type. The interest thing is without @oder-chiou patch, my headset was detected as iphone type, and with the patch, my headset will be detected as nokia type. Maybe there is still another bug in the driver.

**Comment by libinyang** [comment] 2021-06-03 03:07
With 5a15cd7 reverted, I have a different result with @yongzhi1 . It works well here. And the headset is detected as iphone.

**Comment by oder-chiou** [comment] 2021-06-03 06:19
@libinyang Please help to test the patch on your side, thanks.

[0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset v2.zip](https://github.com/thesofproject/linux/files/6589354/0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset.v2.zip)

**Comment by libinyang** [comment] 2021-06-03 13:41
> @libinyang Please help to test the patch on your side, thanks.
> 
> [0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset v2.zip](https://github.com/thesofproject/linux/files/6589354/0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset.v2.zip)

@oder-chiou It works on my platform. @yongzhi1 Can you have a try on this patch?

**Comment by sathyap-chrome** [comment] 2021-06-03 13:43
@libinyang  / @oder-chiou  works for me too (tested on Volteer). But i see that recording is more noisier than when we revert the original commit. Do you observe the same ?

**Comment by sathyap-chrome** [comment] 2021-06-03 13:55
Here are some samples attached.
EXP1: Old kernel tip without the original commit.
EXP2: EXP1 + the commit in upstream ([5a15cd7](https://github.com/thesofproject/linux/commit/5a15cd7fce20b1fd4aece6a0240e2b58cd6a225d))
EXP3 : EXP2 + 0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset v2.zip

TEST1 : plain AMIC record
TEST2 : backgroup playback and then amic record.

Sample recordings: 
[amic_experiments.zip](https://github.com/thesofproject/linux/files/6592092/amic_experiments.zip)

Thanks Naveen for helping out with kernels for various exp on v5.4 (for volteer)
cc @libinyang / @oder-chiou / @yongzhi1

**Comment by yongzhi1** [comment] 2021-06-03 14:59
> > @libinyang Please help to test the patch on your side, thanks.
> > [0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset v2.zip](https://github.com/thesofproject/linux/files/6589354/0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset.v2.zip)
> 
> @oder-chiou It works on my platform. @yongzhi1 Can you have a try on this patch?

With OMTP headset:

TEST1 : plain AMIC record - this pass
TEST2 : backgroup playback and then amic record. - this fail

Procedure used for TEST2:
1. Insert headset
2. Start playback with youtube
3. Launch Mic Note, click recording, and notice the green bar moving up and down along with the playback volume
4. Pause youtube playback and observe the Mic Note recording again.

**Comment by libinyang** [comment] 2021-06-04 05:47
I checked the record again today. 
1. the noise is OK. Almost no noise with loopback record.
2. use headset playback & record, the record still can capture what is playback, with very low volume.

**Comment by bardliao** [comment] 2021-06-04 06:06
> 2. use headset playback & record, the record still can capture what is playback, with very low volume.

If the volume is very low, it is very likely a headset issue. Could you test the same scenario on a real product (eg. your cell phone) with the same headset?

**Comment by sathyap-chrome** [comment] 2021-06-04 06:20
@libinyang  @bardliao can we confirm 0001-ASoC-rt5682-Fix-the-fast-discharge-for-headset v2.zip works and @oder-chiou can post upstream ?

**Comment by libinyang** [comment] 2021-06-04 08:59
@bardliao You got it. It's the headset issue...
@sathyap-chrome The patch works well on my board now.

**Comment by plbossart** [comment] 2021-06-08 19:47
Can we close this now @sathyap-chrome @libinyang ?
 
@oder-chiou 's patch is upstream and in topic/sof-dev, not sure if anything else is needed now.

**Comment by keqiaozhang** [comment] 2021-06-09 01:53
Confirmed that this issue cannot be reproduced in latest topic/sof-dev/https://github.com/thesofproject/linux/commit/c2e9167423d0ad2f4f2c09f4ed537f694c02e28e

**Closed as completed by keqiaozhang** 2021-06-09 01:53 UTC
Labels: bug, codec, TGL, ADL
