### ISSUE TITLE
SoundWire: TGL: IO error in rt711_jack_detect_handler

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3459] opened 2022-02-25 16:49 UTC
@bardliao @shumingfan FYI, that's a new one.

https://sof-ci.01.org/linuxpr/PR3454/build7233/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-capture-5

````
[   29.522674] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
[   29.522680] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
[   29.522741] kernel: IO error in rt711_jack_detect_handler, ret -110
````

[dmesg.log](https://github.com/thesofproject/linux/files/8142866/dmesg.log)

**Comment by plbossart** [comment] 2022-02-25 16:50
not sure if this is related to https://github.com/thesofproject/linux/issues/3401

**Comment by plbossart** [comment] 2022-02-28 22:49
Not able to reproduce with short tests on Dell SKU 0A3E that uses RT711 on link1

````
TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg  ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 5 -m capture
````

@bardliao can you try to see if this bug can be reproduced on your TGL devices with IPC3?
Not sure why we see this consistently on TGLU_RVP_SDW now.

**Comment by bardliao** [comment] 2022-03-01 12:13
> Not able to reproduce with short tests on Dell SKU 0A3E that uses RT711 on link1
> 
> ```
> TPLG=/lib/firmware/intel/sof-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg  ~/sof-test/test-case/check-suspend-resume-with-audio.sh -l 5 -m capture
> ```
> 
> @bardliao can you try to see if this bug can be reproduced on your TGL devices with IPC3? Not sure why we see this consistently on TGLU_RVP_SDW now.

@plbossart I tested it on my Dell SKU 0A3E and it passed. I run the test twice and both iterations are passed.

**Comment by marc-hb** [comment] 2022-03-08 17:55
P1 because it's happening consistently:

https://sof-ci.01.org/sofpr/PR5485/build12238/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5
https://sof-ci.01.org/softestpr/PR871/build1005/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5
https://sof-ci.01.org/sofpr/PR5475/build12242/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5

These test failures happened on different units.

What changed recently? Big kernel merge?

Interesting that searching for something as specific as `rt711_jack_detect_handler` returns 11 entries no less (8 closed)
https://github.com/thesofproject/linux/issues?q=rt711_jack_detect_handler

**Comment by plbossart** [comment] 2022-03-09 01:31
@marc-hb can you help find the first report of a failure? I am down to a spurious pm_runtime resume after a system suspend, no sure what is happening.

**Comment by marc-hb** [comment] 2022-03-10 04:55
I think this came with 5.17, maybe with
- https://github.com/thesofproject/linux/pull/3461 ?

According to the TCR database, the very first check-suspend-playback/capture failure on TGLU_RVP_SDW happened on January 29th:

This was with
- linux/for-next/74cc53cf/linux-image-5.17.0-rc1-daily-default-20220128-0-13653-g74cc53cf59b6_5.17.0-rc1-linux-for-next-74cc53cf_amd64.deb
- sof/main/40d2f6688367/fw/debug/sof-tgl.ri



```
[2022-01-29T20:15:10.418Z] 2022-01-29 20:15:09 UTC Sub-Test: [REMOTE_COMMAND] Run the command: rtcwake -m mem -s 5
[2022-01-29T20:15:10.418Z] rtcwake: wakeup from "mem" using /dev/rtc0 at Sat Jan 29 20:15:15 2022
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:16 UTC Sub-Test: [REMOTE_COMMAND] sleep for 5
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC Sub-Test: [REMOTE_INFO] Check for the kernel log status
[2022-01-29T20:15:22.710Z] declare -- cmd="journalctl_cmd --since=@1643487301"
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC [ERROR] Caught kernel log error
[2022-01-29T20:15:22.710Z] ===========================>>
[2022-01-29T20:15:22.710Z] [ 8113.494143] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
[2022-01-29T20:15:22.710Z] [ 8113.494149] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
[2022-01-29T20:15:22.710Z] [ 8113.494221] kernel: IO error in rt711_jack_detect_handler, ret -110
[2022-01-29T20:15:22.710Z] <<===========================
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC Sub-Test: [REMOTE_ERROR] Caught error in kernel log
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC Sub-Test: [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC Sub-Test: [REMOTE_ERROR]  die()  @  /home/ubuntu/sof-test/test-case/../case-lib/lib.sh
[2022-01-29T20:15:22.710Z] 2022-01-29 20:15:21 UTC Sub-Test: [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-suspend-resume.sh:91
```

Starting from January 29th I see one of two daily-tests failing: PASS, FAIL, PASS, FAIL,... There's no branch information in the TCR database but it looks like the `topic/sof-dev` daily was the one passing and the `for-next` daily was the one failing.

From February 2nd to February 24th, daily tests are consistently passing again.

After February 24th, daily tests are consistently failing except this one (which was on 5.16):

- topic/sof-dev/96221091-2/linux-image-5.16.0-rc1-daily-default-20220227-0_5.16.0-rc1-topic-sof-dev-96221091-2_amd64.deb
- ab715d8e347f/fw/zephyr_debug_key/sof-tgl.ri

The first _SOF_ Pull Requests started failing these two tests on TGLU_RVP_SDW on March 1st and then they almost never passed. #3461 was merged on Feb 28th

**Comment by ujfalusi** [comment] 2022-03-10 08:59
@marc-hb, @bardliao, @plbossart, I think the reason for the error is:
https://sof-ci.01.org/linuxpr/PR3461/build7243/devicetest/?model=TGLU_RVP_SDW&testcase=check-suspend-resume-with-playback-5
When it works the log looks like this:
```
[ 1398.567313] kernel: rt711 sdw:0:025d:0711:00: rt711_calibration calibration complete, ret=0
[ 1398.568250] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_init enable
[ 1398.568332] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_write] 3501 <= 0003
[ 1398.568335] kernel: rt711 sdw:0:025d:0711:00: rt711_io_init hw_init complete
[ 1398.568337] kernel: rt711 sdw:0:025d:0711:00: sdw_handle_slave_status: signaling initialization completion for Slave 1
...
[ 1398.577647] kernel: rt711 sdw:0:025d:0711:00: rt711_interrupt_callback control_port_stat=4
[ 1398.577977] kernel: soundwire_intel soundwire_intel.link.0: Slave status change: 0x20
[ 1398.818037] kernel: soundwire_intel soundwire_intel.link.0: Slave status change: 0x40
[ 1398.818252] kernel: rt711 sdw:0:025d:0711:00: Slave impl defined interrupt
[ 1398.818254] kernel: rt711 sdw:0:025d:0711:00: rt711_interrupt_callback control_port_stat=4
[ 1398.818658] kernel: soundwire_intel soundwire_intel.link.0: Slave status change: 0x20
[ 1399.072288] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] b921 0000 => 80000000
[ 1399.073103] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000800
[ 1399.073916] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000030
[ 1399.073919] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_detect_handler, jack_type=0x3
[ 1399.073922] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_detect_handler, btn_type=0x0

[ 1401.551250] kernel: soundwire sdw-master-1: clock stop prep/de-prep done slave:15
[ 1401.966736] kernel: soundwire sdw-master-0: clock stop prep/de-prep done slave:15
[ 1401.966958] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_down: powering down all links
```
When it fails:
```
[ 1404.335718] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_init enable
[ 1404.335858] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_write] 3501 <= 0003
[ 1404.335863] kernel: rt711 sdw:0:025d:0711:00: rt711_io_init hw_init complete
[ 1404.335865] kernel: rt711 sdw:0:025d:0711:00: sdw_handle_slave_status: signaling initialization completion for Slave 1
[ 1404.336071] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_down: powering down all links
...
[ 1404.785030] kernel: ACPI: EC: interrupt blocked
[ 1409.162488] kernel: ACPI: EC: interrupt unblocked
[ 1409.316458] kernel: soundwire_intel soundwire_intel.link.0: IO transfer timed out, cmd 3 device 1 addr b921 len 1
[ 1409.316466] kernel: soundwire sdw-master-0: trf on Slave 1 failed:-110 write addr b921 count 0
[ 1409.316538] kernel: IO error in rt711_jack_detect_handler, ret -110

...

[ 1410.107908] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: powering up all links
[ 1410.107914] kernel: soundwire_intel soundwire_intel.link.0: intel_link_power_up: first link up, programming SYNCPRD
[ 1410.108260] kernel: rt711 sdw:0:025d:0711:00: sdw_modify_slave_status: initializing enumeration and init completion for Slave 1
[ 1410.109150] kernel: soundwire_intel soundwire_intel.link.0: Slave status change: 0x2
[ 1410.109156] kernel: soundwire sdw-master-0: Slave attached, programming device number
[ 1410.109384] kernel: soundwire sdw-master-0: SDW Slave Addr: 20025d071100
[ 1410.109385] kernel: soundwire sdw-master-0: SDW Slave class_id 0x00, mfg_id 0x025d, part_id 0x0711, unique_id 0x0, version 0x2
[ 1410.109387] kernel: soundwire sdw-master-0: Slave already registered, reusing dev_num:1
...
[ 1410.576437] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_init enable
[ 1410.576540] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_write] 3501 <= 0003
[ 1410.576542] kernel: rt711 sdw:0:025d:0711:00: rt711_io_init hw_init complete
[ 1410.576544] kernel: rt711 sdw:0:025d:0711:00: sdw_handle_slave_status: signaling initialization completion for Slave 1
...
[ 1410.586529] kernel: rt711 sdw:0:025d:0711:00: rt711_interrupt_callback control_port_stat=4
[ 1410.586872] kernel: soundwire_intel soundwire_intel.link.0: Slave status change: 0x20
[ 1410.606525] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 1410.606581] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 1410.814363] kernel: rt711 sdw:0:025d:0711:00: Slave impl defined interrupt
[ 1410.814366] kernel: rt711 sdw:0:025d:0711:00: rt711_interrupt_callback control_port_stat=4
[ 1411.069309] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] b921 0000 => 80000000
[ 1411.070401] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000800
[ 1411.071528] kernel: rt711 sdw:0:025d:0711:00: [rt711_sdw_read] 7520 85a0 9c20 aca0 => 00000030
[ 1411.071534] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_detect_handler, jack_type=0x3
[ 1411.071538] kernel: rt711 sdw:0:025d:0711:00: in rt711_jack_detect_handler, btn_type=0x0
[ 1414.140735] kernel: soundwire sdw-master-0: clock stop prep/de-prep done slave:15
[ 1414.140987] kernel: soundwire sdw-master-1: clock stop prep/de-prep done slave:15
[ 1414.141163] kernel: soundwire_intel soundwire_intel.link.1: intel_link_power_down: powering down all links
```
So in case of error print the `in rt711_jack_init enable` means that `jack_detect_work` is scheduled to run in ~250ms, the sdw core got power off and the `rt711_jack_detect_handler()` tries to read 0xb921 register, which is volatile, so it must reach out to the bus, but it is down, so we get -ETIMEDOUT back as error code.
Note that later on the jack detect works again when the sequence is correct (the sdw links are not powered down right away).

When there is no error we also receive interrupt, which is expected or not, I don't know.

We might be missing a cancel work calls in case the sdw is disabling the link or we need a check if the link is up at all?

**Comment by keqiaozhang** [comment] 2022-03-10 13:24
@plbossart @marc-hb @ujfalusi  It took me more than 6 hours to bisect this issue, lucky me, I found the bad commit:
https://github.com/thesofproject/linux/commit/e38f9ff63e6d403f8e52302d223e3c5c110872ee
```
diff --git a/drivers/acpi/scan.c b/drivers/acpi/scan.c
index 2c80765670bc..5991dddbc9ce 100644
--- a/drivers/acpi/scan.c
+++ b/drivers/acpi/scan.c
@@ -1340,11 +1340,11 @@ static void acpi_set_pnp_ids(acpi_handle handle, struct acpi_device_pnp *pnp,
                if (info->valid & ACPI_VALID_HID) {
                        acpi_add_id(pnp, info->hardware_id.string);
                        pnp->type.platform_id = 1;
-               }
-               if (info->valid & ACPI_VALID_CID) {
-                       cid_list = &info->compatible_id_list;
-                       for (i = 0; i < cid_list->count; i++)
-                               acpi_add_id(pnp, cid_list->ids[i].string);
+                       if (info->valid & ACPI_VALID_CID) {
+                               cid_list = &info->compatible_id_list;
+                               for (i = 0; i < cid_list->count; i++)
+                                       acpi_add_id(pnp, cid_list->ids[i].string);
```

I tried to revert this commit on tip of sof-dev and verified this issue again, 3*30 iterations passed, no reproductions.

**Comment by ujfalusi** [comment] 2022-03-10 13:49
@keqiaozhang, wow!

What I have found that the issue is really easy to reproduce on tglu-rvp-sdw:
```
aplay -Dplughw:0,2 -fdat /dev/urandom &
sleep 1
sudo rtcwake -m mem -s 5
```
Don't forget to `killall aplay`

```
# aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 0: Jack Out (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 2: Speaker (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 5: HDMI 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 6: HDMI 2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 7: HDMI 3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 8: HDMI 4 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
If you would try `plughw:0,0`, it never happens, only if you use a PCM which does not have the rt711 in path.

Can you see if this is working as well? For me this is 100% reproduction rate.

**Comment by keqiaozhang** [comment] 2022-03-10 14:12
@ujfalusi , I changed test script and only test hw:0,2 with suspend/resume.  I did a lot of test, no reproductions after reverting https://github.com/thesofproject/linux/commit/e38f9ff63e6d403f8e52302d223e3c5c110872ee. I'm pretty sure about the result.

**Comment by ujfalusi** [comment] 2022-03-10 14:14
@keqiaozhang, I have checked as well and indeed the kernel with revered https://github.com/thesofproject/linux/commit/e38f9ff63e6d403f8e52302d223e3c5c110872ee is fine.

Let me attach the two dmesg, which is recorded before executing the rtcwake.
sof-dev: [sof-dev.log](https://github.com/thesofproject/linux/files/8224056/sof-dev.log)
with revert: [e38f9ff63e6d403f8e52302d223e3c5c110872ee_reverted.log](https://github.com/thesofproject/linux/files/8224060/e38f9ff63e6d403f8e52302d223e3c5c110872ee_reverted.log)
 
@plbossart, @bardliao FYI.

Thanks @keqiaozhang !!

**Comment by plbossart** [comment] 2022-03-10 14:49
yes, the issue is when we are playing on the speakers while the jack out path controlled by rt711 is suspended.
And the problem is that we resume the jack path which is already suspended - still no idea why it's related to this CID patch.

**Comment by marc-hb** [comment] 2022-03-10 17:45
> still no idea why it's related to this CID patch.

https://en.wikipedia.org/wiki/Butterfly_effect
The double pendulum video is amazing.

**Comment by ujfalusi** [comment] 2022-03-10 19:53
@plbossart, #3509 will show what is _skipped_ after that patch, when the results are in just:
dmesg | grep acpi_set_pnp_ids

The patch should exclude some CIDs in case the HID is not set for the device, right? So those CIDs are not going to be `acpi_add_id()`.

The issue I think is that the rt711 got woken resumed without sdw resume. Later on I think it is a bit different since there sdw is resuming and then the rt711. Or not.

Let's wait for the results and check the dmesg, I hope it will give some hints.

Bdw: is this only happening with RVP? Do we have other device with rt711 (not the rt711-sdca)? Can it be broken ACPI table?

**Comment by marc-hb** [comment] 2022-03-10 20:15
> still no idea why it's related to this CID patch.

Is it worth comparing the output of acpidump with and without e38f9ff63e6d4 maybe? I diff-ed two acpidumps recently for a totally different reason and that wasn't too hard even with my ACPI ignorance.

https://wiki.ubuntu.com/Kernel/Reference/ACPITricksAndTips

**Comment by ujfalusi** [comment] 2022-03-10 20:22
We have a list on TGLU_RVP_SDW device:
```
[    0.578019] kernel: ACPI: acpi_set_pnp_ids: CID without HID for hardware_id.string: (null), count: 2
[    0.578020] kernel: ACPI: acpi_set_pnp_ids: CID #0: string: PRP00001
[    0.578021] kernel: ACPI: acpi_set_pnp_ids: CID #1: string: PNP0A05
[    0.585528] kernel: ACPI: acpi_set_pnp_ids: CID without HID for hardware_id.string: (null), count: 2
[    0.585529] kernel: ACPI: acpi_set_pnp_ids: CID #0: string: PRP00001
[    0.585530] kernel: ACPI: acpi_set_pnp_ids: CID #1: string: PNP0A05
```
These are _not_ `acpi_add_id()`-ed, but still not explaining what is going on as the same set is excluded on CML_RVP_SDW and there things are fine. We should also print out what _is_ added for clarity?

**Comment by plbossart** [comment] 2022-03-10 20:46
I think this is the problem, the only two devices on RVP that don't have an _HID are audio things (SoundWire and USB Audio offload).
I think the patch to reject those devices is invalid or needs to grand-father in such exceptions to the rule.

````
           Device (SNDW)
            {
                Name (_ADR, 0x40000000)  // _ADR: Address
                Name (_CID, Package (0x02)  // _CID: Compatible ID
                {
                    "PRP00001", 
                    "PNP0A05" /* Generic Container Device */
                })

     Device (UAOL)
            {
                Name (_ADR, 0x50000000)  // _ADR: Address
                Name (_CID, Package (0x02)  // _CID: Compatible ID
                {
                    "PRP00001", 
                    "PNP0A05" /* Generic Container Device */
                })
       
````

In theory it's not valid to have both _ADR and _CID, but that has been the practice for many moons already.

**Comment by plbossart** [comment] 2022-03-10 20:51
> These are _not_ `acpi_add_id()`-ed, but still not explaining what is going on as the same set is excluded on CML_RVP_SDW and there things are fine.

@ujfalusi things are fine because CML_RVP_SDW uses a different RT700 codec where we don't schedule a jack detection workqueue. It's a combination of 

a) doing a pm_runtime_resume before suspend (which is really not necessary if the codec is already pm_runtime suspended)
AND
b) the codec initialization scheduling a jack detection workqueue. This part is ONLY done for the RT711.

**Comment by plbossart** [comment] 2022-03-10 21:00
Here's the TGL_RVP_SDW DSDT for reference.

[dsdt.dsl.txt](https://github.com/thesofproject/linux/files/8227151/dsdt.dsl.txt)

**Comment by marc-hb** [comment] 2022-03-11 05:53
This failure has been impacting every single pull request and daily run for about 10 days. It's happening only for a specific test on a very specific product. While it seems far from resolution, its reproduction seems to be under control, it even has been bisected. Can we SKIP testing suspend/resume only on that particular product until this is fixed? We already know it keeps failing every time.

**Comment by ujfalusi** [comment] 2022-03-11 06:49
> > These are _not_ `acpi_add_id()`-ed, but still not explaining what is going on as the same set is excluded on CML_RVP_SDW and there things are fine.
> 
> @ujfalusi things are fine because CML_RVP_SDW uses a different RT700 codec where we don't schedule a jack detection workqueue.

Right, but there is ADLP_RVP_SDW, which have the exact rt711 and it schedules jack detection, yet it passes.

> It's a combination of
> 
> a) doing a pm_runtime_resume before suspend (which is really not necessary if the codec is already pm_runtime suspended)

Hmm, but the driver cancels the delayed works on suspend.
Hmm x2:
the driver cancels the works on suspend _if_ `rt711->hw_init` is **true**.
the `rt711_update_status()` sets `rt711->hw_init` to **false** if the status changes to SDW_SLAVE_UNATTACHED

What we see in the logs is that the hardware got initialized, jack is scheduled then all sdw links got disabled, there could be a runtime suspend after this, it is not visible, but it would leave the works in flight.

> AND
> b) the codec initialization scheduling a jack detection workqueue. This part is ONLY done for the RT711.

It is not that uncommon to try to detect the jack state after resume (the codec was off and the user could inserted / removed / changed the connected head*).

**Comment by ujfalusi** [comment] 2022-03-11 08:41
> Here's the TGL_RVP_SDW DSDT for reference.
> 
> [dsdt.dsl.txt](https://github.com/thesofproject/linux/files/8227151/dsdt.dsl.txt)

To make things a bit more interesting:
It turned out I have one SoundWire laptop (Dell Latitude 9520, i5-1145G7) which happens to have rt711 headset codec as the rvp.

The same devices are w/o HID:
[    0.388302] ACPI: acpi_set_pnp_ids: CID without HID
[    0.388303] ACPI: acpi_set_pnp_ids:   CID #0/2: string: PRP00001
[    0.388304] ACPI: acpi_set_pnp_ids:   CID #1/2: string: PNP0A05
[    0.391457] ACPI: acpi_set_pnp_ids: CID without HID
[    0.391458] ACPI: acpi_set_pnp_ids:   CID #0/2: string: PRP00001
[    0.391459] ACPI: acpi_set_pnp_ids:   CID #1/2: string: PNP0A05

The dsdt.dsl of the device is similar regarding to these.

and I can not reproduce the issue on it.

**Comment by keqiaozhang** [comment] 2022-03-21 01:50
https://github.com/thesofproject/linux/pull/3525 is merged, closing this issue.

**Closed as completed by keqiaozhang** 2022-03-21 01:50 UTC
Labels: P1, TGL, SDW, suspend resume
