### ISSUE TITLE
Feedback from RT1011 - channels are swapped at every session

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#1838] opened 2020-02-28 09:48 UTC
On CML platform, we have RT1011 smart amp providing feedback. we have 4 CH feedback ( from 4 individual speakers) enabled with attached Topology ( m4 is attached too)

Test procedure:
Play a known audio sample ( preferably sine tone) on Speakers
Record 4 ch data on Feedback PCM ( hw:0,10) for few seconds and make multiple recordings.
Each file shows feedback to be different - ideally they should be same for same input file.

TEST ENV:
CML device with RT1011 Amp.
SOF v0.8 backport release FW and topology changes attached on top.

[008_aec.zip](https://github.com/thesofproject/linux/files/4266370/008_aec.zip)

**Comment by sathyap-chrome** [comment] 2020-02-28 09:49
@keqiaozhang Please reproduce one time and then we can see how to proceed debug. Codec vendor informs that the codec side, there is no channel swap. 

cc @keyonjie @aiChaoSONG

**Comment by keyonjie** [comment] 2020-03-02 04:16
@sathyap-chrome can you help clarify:
1. you are playing *stereo*(2 channels) sine wav output to speakers,
2. you are capturing 4 channels(actually only channel 0/1 has data input) which expected the channel 0/1 getting the exact output of the playback channel 0/1 and 0s at channel 2/3.

3. is it possible to probe the output/input on the SSP pins on your side?

Hi @aiChaoSONG @keqiaozhang let's try if we can reproduce it on our side.

**Comment by aiChaoSONG** [comment] 2020-03-02 04:21
@keyonjie could you please have a look at https://github.com/thesofproject/sof/pull/2430, and see if this merged PR has any influence on the abnormal behavior mentioned in this issue?

**Comment by sathyap-chrome** [comment] 2020-03-02 04:24
@keyonjie  

you are playing stereo(2 channels) sine wav output to speakers
>> Yes

you are capturing 4 channels(actually only channel 0/1 has data input) which expected the channel 0/1 getting the exact output of the playback channel 0/1 and 0s at channel 2/3
>. Its a 4 CH capture since there are 4 individual codecs configured ( 1 in each TDM slot ) 
    Hence feedback will have data on all 4 channels.
    The 4 individual codecs play 2 CH playback but provide feedback individually.
    Refer TDM slot mapping here:
https://github.com/thesofproject/linux/blob/30887e1f1548ba97f8a88e616c140ce93b511b4e/sound/soc/intel/boards/cml_rt1011_rt5682.c#L185

3. is it possible to probe the output/input on the SSP pins on your side?
   I can try. But i wanted to know if we can get a dump or some s/w means to easily debug without opening up the closed chassis machine.
 Also easy for codec vendors to duplicate any debug points.

@aiChaoSONG I guess not. This issue was seen with SOFv0.7 as well as SOF v0.8.

**Comment by keyonjie** [comment] 2020-03-02 04:36
> @keyonjie could you please have a look at [thesofproject/sof#2430](https://github.com/thesofproject/sof/pull/2430), and see if this merged PR has any influence on the abnormal behavior mentioned in this issue?

the PR is to divide playback/capture channel numbers, I believe it won't fix channel swapping issue.

**Comment by keyonjie** [comment] 2020-03-02 04:37
@sathyap-chrome can you help upload the playback and captured .wav files?

**Comment by sathyap-chrome** [comment] 2020-03-02 04:46
This has 2 captured files. playback for this case was just normal music playback.
[008_aec.zip](https://github.com/thesofproject/linux/files/4273463/008_aec.zip)

If you need sinewave for testing, here it is -

[left1KHz_right777Hz.zip](https://github.com/thesofproject/linux/files/4273473/left1KHz_right777Hz.zip)

I'll send out the captures from this file in a few minutes

**Comment by aiChaoSONG** [comment] 2020-03-02 05:11
On sof-dev + master, seems reocrd nothing. @sathyap-chrome @keyonjie 
![record4ch](https://user-images.githubusercontent.com/52959957/75647214-40757000-5c87-11ea-8ff8-e59cc493004f.jpg)

**Comment by sathyap-chrome** [comment] 2020-03-02 05:13
@aiChaoSONG did you make the topology modification ?
I've shared the tplg and also m4 for reference . You need to test only on the Helios device.

 Can you try the SOF 0.8 backport on chrome first ?

**Comment by aiChaoSONG** [comment] 2020-03-02 05:29
@keyonjie   @sathyap-chrome result on 008 backport(Chrome OS) is below. 
![recorded4ch4](https://user-images.githubusercontent.com/52959957/75648962-a1537700-5c8c-11ea-9a05-22197004eae1.png)


@sathyap-chrome @keyonjie Now, I understand what the issue is.  the wave seems on different channel slot at each recording.

**Comment by sathyap-chrome** [comment] 2020-03-02 05:43
@aiChaoSONG please do multiple recordings (during same playback) and check the snaphot.. above is only 1 recording, we need to compare 2 recording.

**Comment by keyonjie** [comment] 2020-03-02 05:47
> @keyonjie @sathyap-chrome result on 008 backport(Chrome OS) is below. some phase shift?
> ![recrodedwave](https://user-images.githubusercontent.com/52959957/75648028-cf838780-5c89-11ea-9c57-12290a68861d.png)
> [record4ch.zip](https://github.com/thesofproject/linux/files/4273591/record4ch.zip)

@aiChaoSONG did you play the left1KHz_right777Hz file Sathya shared?

**Comment by aiChaoSONG** [comment] 2020-03-02 05:56
@keyonjie The problem is here: we have two channel with sound, and there are 4 recording channels, the two with sound distribute randomly on the 4 recording channels. sometimes on ch1&ch2, sometimes on ch1&ch4. you can see the picture I attached above.   file used for playback is the one Sathya shared.

**Comment by sathyap-chrome** [comment] 2020-03-02 06:01
@aiChaoSONG this is correct 👍  https://github.com/thesofproject/linux/issues/1838#issuecomment-593226941

The feedback should actually get data from SSP Rx and its mapped to codec.
there are 4 individual channels on feedback. its not a playback loopback. if its behaving the way you mentioned, its actually incorrect.

**Comment by keyonjie** [comment] 2020-03-02 06:08
@sathyap-chrome @aiChaoSONG let's try to verify if the issue exist with hardware loopback mode(codec playback output jack connected to capture input jack).

**Comment by keyonjie** [comment] 2020-03-02 11:47
@sathyap-chrome can you submit a PR with your topology change? then FW/driver team can debug with it. @jajanusz @tlauda FYI.

**Comment by sathyap-chrome** [comment] 2020-03-03 02:52
Sure. But we can use the attached one ( in 1st comment) for now until i post the same.

**Comment by sathyap-chrome** [comment] 2020-03-04 09:14
@keyonjie as  discussed , i tested the feedback by making it 2 CH TDM SLOT 

-               SSP_TDM(4, 25, 3, 15),
+               SSP_TDM(4, 25, 3, 3),

With this i dont get any data when i record from the feedback PCM.
![image](https://user-images.githubusercontent.com/48010719/75863482-90d70400-5e26-11ea-808c-6391109b91a2.png)

**Comment by sathyap-chrome** [comment] 2020-03-10 09:21
@keyonjie As discussed, did you try 4 CH TDM playback with loopback on your side ?

**Comment by sathyap-chrome** [comment] 2020-03-19 07:14
@keyonjie  gentle ping.

**Comment by keyonjie** [comment] 2020-03-26 08:08
@sathyap-chrome sorry didn't get clear enough email even you tagged me. 

Let's add this to our daily bug scrub meeting and proceed it. @mengdonglin @ClarexZhou

**Comment by aiChaoSONG** [comment] 2020-03-27 05:35
Here are the test result on 4ch. @keyonjie @keqiaozhang @sathyap-chrome 
1. change nocodec tplg to support 4ch: [cml_nocodec_2ch_to_4ch.txt](https://github.com/thesofproject/linux/files/4391647/cml_nocodec_2ch_to_4ch.txt)
2.  playback waveform 1
![sine_saw_square_noise](https://user-images.githubusercontent.com/52959957/77724613-609e1200-702e-11ea-8b34-9bad0a4405c1.png)
3. loopback recorded waveform of waveform 1
![recorded_sine_saw_square_noise](https://user-images.githubusercontent.com/52959957/77724706-993deb80-702e-11ea-8055-240db61714fb.png)
4. playback waveform 2
![sine_saw_silent](https://user-images.githubusercontent.com/52959957/77724784-c9858a00-702e-11ea-949e-21e580fc83db.png)
5. loopback recorded waveform of waveform 2
![recorded_sine_saw_silent](https://user-images.githubusercontent.com/52959957/77724953-284b0380-702f-11ea-8773-905b048d5dc2.png)
tried several times of step 5, the waveform keep unchanged.(no swap seen)
seems we do have some problem with 4ch loopback.

**Comment by keyonjie** [comment] 2020-03-27 06:20
Hi @aiChaoSONG can you change the tplg to use DSP_A mode:

```
--           SSP_CONFIG(I2S, SSP_CLOCK(mclk, 24000000, codec_mclk_in),
++         SSP_CONFIG(DSP_A, SSP_CLOCK(mclk, 24000000, codec_mclk_in),
```

And change the recorded .wav file to S32_LE before using audacity to open it.

**Comment by aiChaoSONG** [comment] 2020-03-27 07:34
@keyonjie Did the same test according to your instruction, got the same result with step 4 and step 5.
on step 3, the waveform should be:
![Screenshot from 2020-03-27 15-26-28](https://user-images.githubusercontent.com/52959957/77732635-35bcb980-7040-11ea-9369-e0d2c5f803a5.png)
seems 4ch waveform is modulated into the first channel.

**Comment by sathyap-chrome** [comment] 2020-03-27 07:36
@aiChaoSONG do you see difference (channel swap) with different record sessions in step #3 ? using DSP_A

**Comment by aiChaoSONG** [comment] 2020-03-27 07:40
@sathyap-chrome No, through the waveform is not right, but the order keep unchanged.

**Comment by keyonjie** [comment] 2020-03-27 07:53
@sathyap-chrome @aiChaoSONG can you try to dump the regmap to see if the registers setting are same between the correct and wrong order respectively:
#cat cat /sys/kernel/debug/regmap/*rt1011*/registers

**Comment by sathyap-chrome** [comment] 2020-03-30 03:35
@keyonjie I've done the regmap experiment already. it stays same across all recording

**Comment by aiChaoSONG** [comment] 2020-03-30 06:34
I tried 10 times, seem the regmap changed, even the recorded waves are the same.
[regmap.zip](https://github.com/thesofproject/linux/files/4401165/regmap.zip)

**Comment by aiChaoSONG** [comment] 2020-03-31 07:25
@sathyap-chrome Hi, Sathya, sometimes, the volume component cannot process 4ch stream correctly, could you please remove volume component on recording pipeline, and see if issue reproduced?

**Comment by aiChaoSONG** [comment] 2020-03-31 09:00
@sathyap-chrome @keyonjie Nocodec loopback is OK. DO NOT use audacity or sox to do any conversion, they are not user friendly, and sometimes error-prone. Use Octave to read and view the recorded data.

**Comment by keyonjie** [comment] 2020-04-01 02:50
Thanks @aiChaoSONG and @sathyap-chrome.

Hi @sathyap-chrome I am thinking it might be the clock synchronization issue among the 4 channels/codecs, the most straight forward way is to probe the tx pin of the SSP interface.

**Comment by sathyap-chrome** [comment] 2020-04-01 04:03
@keyonjie  with current situation, i wont be able to probe the tx pin. Can we try probes on CML ?

**Comment by keyonjie** [comment] 2020-04-02 02:43
> @keyonjie as discussed , i tested the feedback by making it 2 CH TDM SLOT
> 
> * ```
>             SSP_TDM(4, 25, 3, 15),
>   ```
> 
> * ```
>             SSP_TDM(4, 25, 3, 3),
>   ```
> 
> With this i dont get any data when i record from the feedback PCM.
> ![image](https://user-images.githubusercontent.com/48010719/75863482-90d70400-5e26-11ea-808c-6391109b91a2.png)

I guess you actually got the correct S24_LE data(don't use audacity to open S24_LE format file), can you try play this file and check if it sounds good?

**Comment by keyonjie** [comment] 2020-04-02 02:50
> @keyonjie with current situation, i wont be able to probe the tx pin. Can we try probes on CML ?

We can't do that here neither as we don't have hardware technician to support hardware rework at these days.

Maybe we can ask for some support(e.g. buffer probe?) from the FW team. @fkaczmar ?

**Comment by sathyap-chrome** [comment] 2020-05-15 08:42
@keyonjie  i tried to enable traces to get SSP 1 Rx dump. But i hit some issue.

Following recipe on CML worked for speaker playback traces. same when i tried for feedback, i see feedback capture itself is not working. can you help enable at your end too and let me know if we can continue debug from there ?

The FW and Topology is build with below commit:
b8b96a20bb02 CI: travis: Add boot test for i.MX8M
e3216be87dfd probe: add uuid to probe task
5550a5f6768d timer: increase next timer set in case of delay
3746f459e70b probe: fix dma buffer init wrong rballoc flags
10a72a42a079 src: ssi-spi: Use !x instead of NULL comparison

The m4 file is already available in the bug.

Please check if you are able to record data on the feedback path ( PCM10) i see blank.
If we are able to do so, enabling probes on SSP Rx can be done ?

**Comment by keyonjie** [comment] 2020-05-15 12:45
@sathyap-chrome did you mean the PCM10 capture only 0s with kernel topic/sof-dev + FW master? If so, can you help to file a bug with it? I think the CML rt1011 platform is on our daily track @aiChaoSONG ?

**Comment by aiChaoSONG** [comment] 2020-05-18 01:34
@keyonjie Yes,  daily and PR tests run on this platform everyday,

**Comment by sathyap-chrome** [comment] 2020-07-15 10:59
Hi @keyonjie  @aiChaoSONG  due to other priorities i couldnt do any debug on this one.
I have some info from my test using CML 008 release :
I'm attaching the TPLG, m4 file the feedback wav snapshot and asoc graph here.

[008_aec_ww29.zip](https://github.com/thesofproject/linux/files/4924676/008_aec_ww29.zip)

Note that the feedback is swapped as per the original issue. But interestingly i see that the pipeline for SSP1.IN is not active during my record session in both sessions.

Can you help replicate this issue on latest master ? this can help debug this faster.
any suggestions on what can be next debug step.

**Comment by aiChaoSONG** [comment] 2020-09-04 06:08
@keyonjie @sathyap-chrome Hi, Sathya, I tried the topology attached with the latest kernel and FW, there is nothing in the recorded feedback wave.

**Comment by sathyap-chrome** [comment] 2020-09-04 12:51
Hi @aiChaoSONG  this is what i also observed . Hence we are not able to use the dump to check the SSP Rx data. Note that with CML v0.8, the feedback has data.

**Comment by keyonjie** [comment] 2020-09-14 02:25
Hi @sathyap-chrome Thanks for the feedback, so how urgent is this now?

**Comment by keyonjie** [comment] 2020-09-27 06:20
Hi, @sathyap-chrome can you help to try if PR https://github.com/thesofproject/sof/pull/3476 help for this issue?

**Comment by plbossart** [comment] 2021-01-22 00:27
@sathyap-chrome @keyonjie @aiChaoSONG @kv2019i can we close this one?

**Comment by keyonjie** [comment] 2021-01-22 00:56
since thesofproject/sof#3476 already merged, so if either @sathyap-chrome or @aiChaoSONG re-check it with master firmware to confirm it, we can close it.

**Comment by aiChaoSONG** [comment] 2021-01-22 02:16
@keyonjie I remembered that I have tried to check this issue on master with the topology provided, no data recorded via feedback pipeline.

**Comment by plbossart** [comment] 2021-06-10 17:47
It's unclear if this bug is current or not. I will close, if this is an error @sathyap-chrome @aiChaoSONG @keyonjie please reopen with a status.

**Closed as completed by plbossart** 2021-06-10 17:47 UTC
Labels: bug, P3, CML, Chrome, I2S
