### ISSUE TITLE
[BUG][CML/CFL]ipc error for 0x60050000 size 12 occurred when run s3 stress test with HDMI playback.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1099] opened 2019-07-29 05:23 UTC
**Describe the bug**
ipc error for 0x60050000 size 12 when run s3 stress test with HDMI playback

**To Reproduce**

1.Connect HDMI external port 
2.Run with command aplay -Dhw:0,3 -r48000 -c2 -fs16_le /dev/zero & sudo ./stress-s3.sh 300 1 1

**frequency**

1/288

**Expected result**
S3 and HDMI aplay normally

**Actual result**
ipc error for 0x60050000 size 12

**Environment**
Firmware: f7809a2e https://github.com/thesofproject/sof/commits/master
Kernel: f745362c https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology:file: tools/topology/sof-hda-generic-2ch.tplg

**dmesg**
```
[ 2107.306731] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 1
[ 2107.307260] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[ 2107.307261] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 2107.307422] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 2107.307425] sof-audio-pci 0000:00:1f.3: In hda_link_pcm_trigger cmd=1
[ 2107.579968] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 2107.580005] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 2107.676394] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 0
[ 2107.681376] done.
[ 2107.683387] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[ 2107.683392] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 2107.683493] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60050000 size 12
[ 2107.683496]  HDMI1: ASoC: trigger FE failed -22
[ 2107.686432] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 1
[ 2107.690555] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[ 2107.690556] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 2107.691408] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60040000 size 12
[ 2107.691410]  HDMI1: ASoC: trigger FE failed -22
[ 2107.691412] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 3 dir 0 cmd 0
[ 2107.692033] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x140000 successful
[ 2107.692037] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 2107.699378] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60050000 size 12
[ 2107.699380]  HDMI1: ASoC: trigger FE failed -22
[ 2107.786478] PM: suspend exit
[ 2108.079904] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 2108.080106] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 2108.303975] asix 1-2:1.0 enx00248c029038: link up, 100Mbps, full-duplex, lpa 0x41E1
[ 2108.306767] sof-audio-pci 0000:00:1f.3: pcm: free stream 3 dir 0
[ 2108.306776] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 2108.307011] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 2108.307098] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[ 2108.307236] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[ 2108.307254] sof-audio-pci 0000:00:1f.3: pcm: close stream 3 dir 0
```
**error logger**
```
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1          DAI 7.41    2495044962.239583              nan      src/audio/dai.c:575 	dai_check_for_xrun() error: underrun due to no data available
    0      1         COMP         2495044969.062500         6.822917 of/audio/component.h:743 	comp_underrun() error: dev->comp.id = 41, source->avail = 0, copy_bytes = 0
    0      1         PIPE         2495045019.791667        50.729168 src/audio/pipeline.c:764 	pipeline_copy() error: ret = -61
    0      1         PIPE 7.42    2495045026.250000         6.458333 src/audio/pipeline.c:977 	pipeline_task(): xrun recover failed! pipeline will be stopped!
    0      1         COMP         2495045744.010417       717.760437 rc/audio/component.c:164 	comp_set_state() error: wrong state = 1, COMP_TRIGGER_STOP
    0      1          IPC         2495045750.625000         6.614583 src/audio/pipeline.c:635 	pipeline_trigger() error: ret = -22, host->comp.id = 37, cmd = 0
    0      1          IPC         2495045757.916667         7.291667    src/ipc/handler.c:484 	ipc: comp 37 trigger 0x50000 failed -22
    0      1         COMP         2495054696.197917      8938.281250 rc/audio/component.c:143 	comp_set_state() error: wrong state = 1, COMP_TRIGGER_START
    0      1          IPC         2495054702.708333         6.510417 src/audio/pipeline.c:635 	pipeline_trigger() error: ret = -22, host->comp.id = 37, cmd = 1
    0      1          IPC         2495054710.156250         7.447917    src/ipc/handler.c:484 	ipc: comp 37 trigger 0x40000 failed -22
    0      1         COMP         2495056544.531250      1834.375000 rc/audio/component.c:164 	comp_set_state() error: wrong state = 1, COMP_TRIGGER_STOP
    0      1          IPC         2495056551.145833         6.614583 src/audio/pipeline.c:635 	pipeline_trigger() error: ret = -22, host->comp.id = 37, cmd = 0
    0      1          IPC         2495056558.593750         7.447917    src/ipc/handler.c:484 	ipc: comp 37 trigger 0x50000 failed -22

```
[s3_test_288_logger_error.log](https://github.com/thesofproject/linux/files/3440336/s3_test_288_logger_error.log)
[test_288.log](https://github.com/thesofproject/linux/files/3440337/test_288.log)
[s3_test_288_logger_all.log](https://github.com/thesofproject/linux/files/3440338/s3_test_288_logger_all.log)

**Comment by xiulipan** [comment] 2019-07-29 05:29
@YvonneYang2 
Please help to add following patch to kernel and try to test again with these logs. I have seen some similar issue, please help to confirm with the following logs

```diff
diff --git a/sound/soc/sof/intel/hda-stream.c b/sound/soc/sof/intel/hda-stream.c
index ad8d41f22e92..e963975027d5 100644
--- a/sound/soc/sof/intel/hda-stream.c
+++ b/sound/soc/sof/intel/hda-stream.c
@@ -252,6 +252,7 @@ int hda_dsp_stream_trigger(struct snd_sof_dev *sdev,
        case SNDRV_PCM_TRIGGER_SUSPEND:
        case SNDRV_PCM_TRIGGER_PAUSE_PUSH:
        case SNDRV_PCM_TRIGGER_STOP:
+               dev_err(sdev->dev, "PXL: DMA STOP %d\n", cmd);
                snd_sof_dsp_update_bits(sdev, HDA_DSP_HDA_BAR,
                                        sd_offset,
                                        SOF_HDA_SD_CTL_DMA_START |
diff --git a/sound/soc/sof/pcm.c b/sound/soc/sof/pcm.c
index 8612896673a5..a239fd3ba19a 100644
--- a/sound/soc/sof/pcm.c
+++ b/sound/soc/sof/pcm.c
@@ -370,8 +370,10 @@ static int sof_pcm_trigger(struct snd_pcm_substream *substream, int cmd)
                return -EINVAL;
        }

+       dev_err(sdev->dev, "PXL: pcm trigger %d\n", cmd);
        snd_sof_pcm_platform_trigger(sdev, substream, cmd);

+       dev_err(sdev->dev, "PXL: ipc trigger %d\n", cmd);
        /* send IPC to the DSP */
        ret = sof_ipc_tx_message(sdev->ipc, stream.hdr.cmd, &stream,
                                 sizeof(stream), &reply, sizeof(reply));

```

**Comment by ClarexZhou** [comment] 2019-08-07 07:32
Error occurred at 366th timed during S3 with analog playback stress test

linux (topic/sof-dev): 53d77540
sof (master): 9e2aa3d3
tplg:sof-hda-generic-2ch.tplg
Platform: CML HDA notebook

**Comment by dengyangchao** [comment] 2019-08-28 01:19
1.CML test 2000 times issue can't reproduce
2.CFL test 1200 times issue can't reproduce

**Comment by dengyangchao** [comment] 2019-08-28 02:11
issue can not reproduce, close the issue

**Closed as completed by dengyangchao** 2019-08-28 02:11 UTC
Labels: bug, P2, CML, HDA, CFL
