### ISSUE TITLE
[BUG][IPC4]IO error on TGL NOCODEC when pause release while playback

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3613] opened 2022-04-25 09:30 UTC
**Describe the bug**
IO error on TGL NOCODEC when pause release while playback , no dmesg error (ipc error/timeout) however

This was observed on TGLU_RVP_NOCODEC_IPC4 and also TGL  Xtreme board. Seems the later platform has higher reproduction rate

**To Reproduce**

```
TPLG=/lib/firmware/intel/avs-tplg/cavs-tgl-nocodec.tplg MODEL=TGLU_RVP_NOCODEC_IPC4 ~/sof-test/test-case/check-pause-resume.sh -c 100 -m playback
```

**Environment**
Kernel Branch: topic/sof-dev
Kernel Commit: [7d7db5cef4ea](https://github.com/thesofproject/linux/commit/7d7db5cef4ea)
SOF Branch: main
SOF Commit: [dbdaba93bb72](https://github.com/thesofproject/sof/commit/dbdaba93bb72)
Topology:cavs-tgl-nocodec.tplg
 Platform: TGL RVP  and TGL Up Xtreme board

**Screenshots or console output**
[console output]
```
=== PAUSE ===                                                            
(2/100) Wait for 140 ms before pause

(2/100) Wait for 159 ms before resume
                                                                           
 
#+                                                 | 00%
=== PAUSE ===                                                            
(3/100) Wait for 115 ms before pause

(3/100) Wait for 146 ms before resume
                                                                           
 aplay: pcm_write:2086: write error: Input/output error
2022-04-24 23:07:38 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2022-04-24 23:07:38 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/check-pause-resume.sh
```

**Comment by plbossart** [comment] 2022-04-25 21:41
@XiaoyunWu6666 @ranj063 @fredoh9 is this not a duplicate of https://github.com/thesofproject/linux/issues/3591, or vice-versa?

**Comment by XiaoyunWu6666** [comment] 2022-04-29 12:48
> @XiaoyunWu6666 @ranj063 @fredoh9 is this not a duplicate of #3591, or vice-versa?

yes , looks they are describing the same isse

**Closed as completed** 2022-05-17 20:43 UTC
Labels: duplicate, IPC4
