### ISSUE TITLE
PM: the dai config message sent by hda_load and sof_restore_pipelines are not the same

### ISSUE THREAD

**Issue by zhuyingjiang** [thesofproject/linux#442] opened 2018-12-14 11:27 UTC
The tx message sequence which send by first load and the tx message sequence  by runtime resume are not the same. This leads to WHL have error when do runtime resume:
[   19.377552] sof-audio sof-audio: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   19.377765] sof-audio sof-audio: error: ipc error for 0x80010000 size 0xc
[   19.377776] sof-audio sof-audio: error: failed to set dai config for Analog Playback and Capture
[   19.377780] sof-audio sof-audio: error: failed to restore pipeline after resume -5
[   19.377786] sof-audio sof-audio: error: volume get failed to resume -16

**Comment by plbossart** [comment] 2018-12-14 16:27
@zhuyingjiang Can you please provide a better description of the problem and attach the logs for startup and resume. No one can help with the limited information described.

**Comment by ranj063** [comment] 2018-12-14 17:08
@zhuyingjiang @plbossart I think the problem is in the call to sof_set_dai_config() in sof_link_hda_load().
For the other dai types, we update config for all dai's matching the link name but for hda we should also match the direction. I think that should fix this problem.

**Comment by zhuyingjiang** [comment] 2018-12-16 07:01
@ranj063 It is not the direction, it is the dai_index has not been set. Fixed by #450

**Comment by zhuyingjiang** [comment] 2018-12-17 07:33
[down.log](https://github.com/thesofproject/linux/files/2684891/down.log)
@plbossart Log attached, with the tx message data also added to log, more analysis is in #450

**Comment by zhuyingjiang** [comment] 2018-12-20 03:20
#472 will fix this.

**Comment by wenqingfu** [comment] 2019-01-19 03:42
fixed by #509

**Closed as completed by wenqingfu** 2019-01-19 03:42 UTC
Labels: bug
