### ISSUE TITLE
multiple-pause-resume fail on CML_RVP_SDW_ZEPHYR

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#3748] opened 2022-07-11 20:04 UTC
https://sof-ci.01.org/linuxpr/PR3742/build354/devicetest/?model=CML_RVP_SDW_ZEPHYR&testcase=multiple-pause-resume-5

This looks like an xrun in the firmware

````
[   105053023.481818] (          14.374999) c0 alh-dai      4.259  src/drivers/intel/alh.c:31   INFO alh_trigger() cmd 2
[   105053040.877651] (          17.395832) c0 zll-schedule       src/schedule/zephyr_ll.c:69   INFO task complete 0xbe088ac0 pipe-task 
[   104980581.245113] (        1558.645752) c0 hda-dma            ..../intel/hda/hda-dma.c:948  ERROR hda_dma_link_check_xrun(): underrun detected
[   104981830.411730] (        1249.166626) c0 hda-dma            ..../intel/hda/hda-dma.c:948  ERROR hda_dma_link_check_xrun(): underrun detected
````

**Comment by plbossart** [comment] 2022-07-11 20:07
Possible duplicate of https://github.com/thesofproject/linux/issues/3712

@keqiaozhang ?

**Comment by keqiaozhang** [comment] 2022-07-12 02:37
> Possible duplicate of #3712
> 
it seems that they are not the same. 
First, the scenarios are different. 

Secondly, For https://github.com/thesofproject/linux/issues/3712, the XRUN is caused by `WARN dai_copy(): nothing to copy` and detected by `dw_dma_get_data_size()`
But in this bug, the XRUN is detected by `hda_dma_link_check_xrun()`

**Comment by fredoh9** [comment] 2022-10-12 22:19
daily stable-v2.2 test uses CML_RVP_SDW (XTOS, non ZEPHYR).
I don't see similar xrun with XTOS test.
CML_RVP_SDW_ZEPHYR is not actively being tested, so hard to tell.

**Comment by mengdonglin** [comment] 2022-10-13 01:48
CML will park at https://github.com/thesofproject/sof/tree/stable-v2.2 with XTOS for product support. So we won't fix this issue.

**Closed as completed by mengdonglin** 2022-10-13 01:48 UTC
Labels: won't fix, P2, CML
