### ISSUE TITLE
[WHL] HDA - huge distortion during playback and capture

### ISSUE THREAD

**Issue by emilchudzik** [thesofproject/linux#202] opened 2018-10-23 07:37 UTC
After debugging previous issues (https://hsdes.intel.com/appstore/article/#/1506769462 and https://github.com/thesofproject/sof/issues/433) where https://github.com/thesofproject/linux/pull/172 was applied to repo linux-sof-dev:5300a52
- capture - silence was recorded
- playback - clear sound on jack output

After last debug kernel and topology (uploaded by Rander to my machine in 19 August) - I don't know which branch was created from (both linux and soft repo) I hear very distorded sound on jack output. Capture is also very noisy.
- checked 16/24/48kHz - 16/16, 24/32 and 32/32, 1/2/4/8 channels.

**Comment by RanderWang** [comment] 2018-10-23 08:29
The PR to fix capture issue has been closed, so I am creating a new one

**Comment by RanderWang** [comment] 2018-10-23 08:29
The noisy is caused by Host DMA according to Janusz

**Comment by mengdonglin** [comment] 2018-10-24 11:13
@RanderWang Has Janusz confirmed this is a firmware issue on Host DMA? If yes, we need to move this issue to sof repo.

**Comment by jajanusz** [comment] 2018-10-24 11:59
@mengdonglin probably it's FW issue that should be fixed when this PR will be merged: https://github.com/thesofproject/sof/pull/504

**Comment by mengdonglin** [comment] 2018-10-26 07:36
@echudzi Would you please check if this issue can still be reproduced?

**Comment by mengdonglin** [comment] 2018-10-26 08:23
Close this issue since it's a duplicate of the known metallic noise issue of playback, and fixed by thesofproject/sof#504.

**Closed as completed by mengdonglin** 2018-10-26 08:23 UTC
Labels: bug, P1, WHL, firmware
