### ISSUE TITLE
[SDW UCM2][BUG][CML-H]Left and Right speaker can't be separated when do speaker test 0,2.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1998] opened 2020-04-08 03:50 UTC
**Describe the bug**
Left and Right speaker can't be separated when do speaker test 0,2.

More info:
Need manually change "rt1308-1 RX Channel Select " to LL  and  "rt1308-2 RX Channel Select "to RR in alsamixer can recover.
UCM2:
 https://github.com/thesofproject/alsa-ucm-conf (commit: 4722f5b ) +https://github.com/thesofproject/alsa-ucm-conf/pull/29

**To Reproduce**
1.Boot up system successfully.
2. Run "speaker-test -Dhw:0,2 -r48000 -f1000 -c2 -t wav -l 10"

**Reproduce rate**
5/5

**Expected result**
Left and Right speaker should be separated when do speaker test0,2.

**Actual result**
Left and Right speaker can't be separated when do speaker test 0,2. 

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:052e45d
FW: https://github.com/thesofproject/sof/commits/master commit:  b4e8b1e4
Tplg: Same with FW branch,  sof-cml-rt711-rt1308-rt715.tplg
Platform:CML-H Laptop with codec ALC711, 2 x RT1308, RT715 in SDW mode.

**Comment by plbossart** [comment] 2020-04-08 17:45
@sinahuang can you retry with https://github.com/thesofproject/alsa-ucm-conf/pull/34
I only checked in 2ch cases, my CML-H is not functional at the moment.

**Comment by sinahuang** [comment] 2020-04-09 09:18
Checked this with PR https://github.com/thesofproject/alsa-ucm-conf/pull/34, issue still can be reproduce.
[amixer contents.txt](https://github.com/thesofproject/linux/files/4455169/amixer.contents.txt)

**Comment by plbossart** [comment] 2020-04-09 11:33
@sinahuang you'll have to debug a bit here:

````
numid=9,iface=MIXER,name='rt1308-1 RX Channel Select'
  ; type=ENUMERATED,access=rw------,values=1,items=4
  ; Item #0 'LR'
  ; Item #1 'LL'
  ; Item #2 'RL'
  ; Item #3 'RR'
  : values=0

numid=10,iface=MIXER,name='rt1308-2 RX Channel Select'
  ; type=ENUMERATED,access=rw------,values=1,items=4
  ; Item #0 'LR'
  ; Item #1 'LL'
  ; Item #2 'RL'
  ; Item #3 'RR'
  : values=0
````

The UCM file sets those values, so something's clearly wrong in the setup?

**Comment by libinyang** [comment] 2020-04-10 09:30
This bug should be the same root cause of https://github.com/thesofproject/linux/issues/1997. The pulseaudio or sound-setting can't recognize our UCM2 configuration in "EnableSequence" and "DisableSequence"

**Comment by ClarexZhou** [comment] 2020-04-30 01:31
Error not seen with UCM2 https://github.com/libinyang/alsa-ucm-conf/tree/sdw_ucm2_singleprofile/ucm2/sof-soundwire  commit: c2c5042

**Closed as completed** 2020-05-01 13:09 UTC
Labels: bug, CML, PulseAudio, SDW, UCM2
