### ISSUE TITLE
[SDW] Overshoot on RT715 record

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#1480] opened 2019-11-13 22:01 UTC
when I try the latest code and UCM file, I hear a very loud pop noise when I play on RT1308 the files I recorded w/ RT715.

Looking at the file 
[plb.wav.gz](https://github.com/thesofproject/linux/files/3843642/plb.wav.gz)
, this seems to be a record issue: there's a quite strong overshoot on startup, wondering if we are missing some settings in the RT715, or of we need to insert a DC component removal in the SOF topology as we do for DMICs (copying @singalsu ).
![Screenshot from 2019-11-13 16-01-07](https://user-images.githubusercontent.com/1149035/68808189-d5981e80-062e-11ea-9bc5-13e61afaddcc.png)

@shumingfan @bardliao can you reproduce this?

**Comment by shumingfan** [comment] 2019-11-13 23:48
@jack-cy-yu loop Jack

**Comment by bardliao** [comment] 2019-11-14 02:26
@plbossart Yes I can reproduce it.

**Comment by jack-cy-yu** [comment] 2019-11-14 02:37
@plbossart I can reproduce it on my side. I am checking it with system engineer and will keep you posted.

**Comment by jack-cy-yu** [comment] 2019-11-14 11:32
@plbossart From system engineer's opinion, this overshoot is caused by DC value in DMIC, it needs some time to calibrate from its DC value to 0 by codec's filter, and from their past experience, most of overshoot issues are workaround by software. If workaround by driver is the best way, I'll send a patch for it, how do you think?

**Comment by plbossart** [comment] 2019-11-14 14:26
> @plbossart From system engineer's opinion, this overshoot is caused by DC value in DMIC, it needs some time to calibrate from its DC value to 0 by codec's filter, and from their past experience, most of overshoot issues are workaround by software. If workaround by driver is the best way, I'll send a patch for it, how do you think?

@jack-cy-yu can you clarify what you mean by 'software workaround'?
For the case where the DMICs are attached to the Intel DSP, we have an IIR filter to remove the DC. @singalsu can you help describe the solution to see if we need to use the same IIR filter in the RT715 capture path in the topology?

**Comment by jack-cy-yu** [comment] 2019-11-15 02:00
@plbossart 'Software workaround' means to use delay function like msleep/usleep_range to delay the capture switch from switched On which is to bypass the calibration period of DC value. But the side effect is that some data will be lost (around 100~200ms) with this workaround. I think it's better to use IIR filter for this if IIR filter really works.

**Comment by singalsu** [comment] 2019-11-15 07:10
Can you try in topology that is used to use pipeline macro pipe-eq-capture.m4 instead of pipe-volume-capture.m4. I'm not sure what topology is now used but sof-icl-rt711-rt1308-rt715.m4 topology seems to use it.

The EQ capture pipe includes a +20 dB gain to compensate typical quite low sensitivity in PDM digital microphones for notebooks usage, so you should in first test in audio editor attenuate the clip by the same 20 dB to preserve the planned sensitivity. If that gives good result I can upstream another IIR coefficients set that doesn't include the gain. Also the cut-off frequency is quite low 50 Hz so  there would be room to increase it a bit (maybe up to 60 - 80 Hz) for faster DC settling. Maybe also the used IIR response should be made an argument for the pipeline macro to define it at top level topology.

Below is  patch for topology to change the capture pipeline macro.

```
diff --git a/tools/topology/sof-icl-rt711-rt1308-rt715.m4 b/tools/topology/sof-icl-rt711-rt1308-rt715.m4
index 6861e610902f..93dda3d315fb 100644
--- a/tools/topology/sof-icl-rt711-rt1308-rt715.m4
+++ b/tools/topology/sof-icl-rt711-rt1308-rt715.m4
@@ -42,7 +42,7 @@ PIPELINE_PCM_ADD(sof/pipe-volume-playback.m4,
 
 # Low Latency capture pipeline 2 on PCM 1 using max 2 channels of s32le.
 # Schedule 48 frames per 1000us deadline on core 0 with priority 0
-PIPELINE_PCM_ADD(sof/pipe-volume-capture.m4,
+PIPELINE_PCM_ADD(sof/pipe-eq-capture.m4,
        2, 1, 2, s32le,
        1000, 0, 0,
        48000, 48000, 48000)
@@ -63,7 +63,7 @@ PIPELINE_PCM_ADD(sof/pipe-volume-playback.m4,
 
 # Low Latency capture pipeline 5 on PCM 4 using max 2 channels of s32le.
 # Schedule 48 frames per 1000us deadline on core 0 with priority 0
-PIPELINE_PCM_ADD(sof/pipe-volume-capture.m4,
+PIPELINE_PCM_ADD(sof/pipe-eq-capture.m4,
        5, 4, 2, s32le,
        1000, 0, 0,
        48000, 48000, 48000)
```

**Comment by singalsu** [comment] 2019-11-15 07:24
I tried myself that but unfortunately recent edits to pipe-eq-capture.m4 allow there to be only one instance of this pipeline (a PGA is renamed to dmic0). Having two pipelines causes the topology to merge the pipelines at common "dmic0" and make things fail.

So please edit only one capture pipe that you use for testing this way and please let me know what happens!

**Comment by singalsu** [comment] 2019-11-20 11:58
The volume unmute ramp seems to be broken / not happening in all capture scenarios, I'll try to fix it first.

**Comment by plbossart** [comment] 2020-01-09 19:59
@singalsu @kv2019i This issue is still seen on my CML device. If you have one available, can you try a reproduce this? I am not sure what to make of the earlier feedback, the capture with RT715 is already at the right level so we don't need the 20dB boost at all.

**Comment by singalsu** [comment] 2020-01-10 09:07
The PR https://github.com/thesofproject/sof/pull/2109 has been stuck for far too long time with non-related random CI issues. It contains the needed high-pass filter set to use here. I'll make today an update that removes the impact to KPB, hope it gets merged soon.

**Comment by singalsu** [comment] 2020-01-10 09:37
There was no need to update my PR, hope it can be merged soon. I can start to make a topology PR for this issue. What topology m4 file does this platform use?

**Comment by plbossart** [comment] 2020-01-10 15:03
@singalsu all topologies with the -rt715 suffix needs this overshoot compensation

**Comment by lgirdwood** [comment] 2020-01-11 16:39
@singalsu worthy of another technical note on SOF docs showing the problem and how we can fix it in topology etc.

**Comment by singalsu** [comment] 2020-01-17 12:10
The needed filters are now merged to SOF. I'll make today a topology PR to address this issue.

**Comment by singalsu** [comment] 2020-01-17 12:42
I got a test device for loan where this can be repeated:

![Screenshot from 2020-01-17 14-40-45](https://user-images.githubusercontent.com/28754793/72613142-70ff8580-3937-11ea-99e3-cdbec8b6f079.png)

**Comment by singalsu** [comment] 2020-01-17 15:06
It's now a lot better. This the best that I can achieve with the volume linear ramp. The log ramp type would provide more attenuation to beginning but it's not yet available.

![Screenshot from 2020-01-17 17-04-51](https://user-images.githubusercontent.com/28754793/72622337-ac0bb400-394b-11ea-80d3-9e5d8c164044.png)

**Comment by singalsu** [comment] 2020-01-17 15:13
The SOF PR is now in https://github.com/thesofproject/sof/pull/2302 .

**Comment by singalsu** [comment] 2020-01-21 10:53
The PR is now merged. Can you please check that it works as expected in your platforms!

**Comment by plbossart** [comment] 2020-02-07 19:38
looks fine now, thanks @singalsu 

I see hear a lot of pop when stopping playback but that's an amplifier issue now.
well actually now that I think of it, is there a volume ramp when we stop playing? Since we don't support any drain capabilities, we probably stop without ramping down, no?

**Comment by YvonneYang2** [comment] 2020-02-21 05:29
Found a RT715 record noise issue may be similar to this issue.  
Noise is at the beginning of the record file. If could't hear it, please volume up the PGA5.0 5 in alsamixer capture and try it again.

CML-U and CML-H laptops can both reproduce it.

Test recipe:
Firmware: 247af13 https://github.com/thesofproject/sof/commits/master 
Kernel: 6af9a26 https://github.com/bardliao/linux/tree/topic/sof-dev
tplg:  
For CML-U:  master branch + PR2358, sof-cml-rt711-rt1308-mono-rt715.tplg
For CML-H: master branch,  sof-cml-rt711-rt1308-rt715.tplg
 
wav file: [test.zip](https://github.com/thesofproject/linux/files/4234408/test.zip)
Logs:
[all_sof_trace.log](https://github.com/thesofproject/linux/files/4234412/all_sof_trace.log)
[dmesg.log](https://github.com/thesofproject/linux/files/4234415/dmesg.log)

**Comment by YvonneYang2** [comment] 2020-03-03 11:44
Error not seen with master commit: 182e62a1
Error still seen with master+https://github.com/thesofproject/sof/pull/2358

**Comment by singalsu** [comment] 2020-03-03 15:20
> looks fine now, thanks @singalsu
> 
> I see hear a lot of pop when stopping playback but that's an amplifier issue now.
> well actually now that I think of it, is there a volume ramp when we stop playing? Since we don't support any drain capabilities, we probably stop without ramping down, no?

That's correct, we do not have end ramp in driver / firmware. Such could help to mitigate end pop.

**Comment by singalsu** [comment] 2020-03-03 15:27
> Found a RT715 record noise issue may be similar to this issue.
> Noise is at the beginning of the record file. If could't hear it, please volume up the PGA5.0 5 in alsamixer capture and try it again.
> 
> CML-U and CML-H laptops can both reproduce it.
> 
> Test recipe:
> Firmware: 247af13 https://github.com/thesofproject/sof/commits/master
> Kernel: [6af9a26](https://github.com/thesofproject/linux/commit/6af9a26f2bf334cdef2748959ff93c7ac737cbd4) https://github.com/bardliao/linux/tree/topic/sof-dev
> tplg:
> For CML-U: master branch + PR2358, sof-cml-rt711-rt1308-mono-rt715.tplg
> For CML-H: master branch, sof-cml-rt711-rt1308-rt715.tplg
> 
> wav file: [test.zip](https://github.com/thesofproject/linux/files/4234408/test.zip)
> Logs:
> [all_sof_trace.log](https://github.com/thesofproject/linux/files/4234412/all_sof_trace.log)
> [dmesg.log](https://github.com/thesofproject/linux/files/4234415/dmesg.log)

When looking at waveform it can be seen that a high-pass IIR would fix this. Also the capture volume ramp (defined by volume tokens) should be longer. Not sure if it's defined in this topology but we have in most topologies a mistake that makes the volume tokens global in the flat .conf file and the winning token is a random lottery.

I'm confused why this happens again. Is not the mute switch topology compatible with keeping the high-pass filter?

**Comment by YvonneYang2** [comment] 2020-03-05 06:42
Issue cannot be reproduced on master branch, but can still be reproduced on cml-010-hotfix branch. @libinyang  Could you please help to have a look.

**Comment by YvonneYang2** [comment] 2020-03-26 04:54
Since https://github.com/thesofproject/sof/pull/2358 has been merged, issue cannot be reproduced on latest sof-dev + master. So close it.

**Closed as completed** 2020-03-26 04:54 UTC
Labels: bug, CML, SDW_DEV, SDW
