### ISSUE TITLE
[SDW] RT711 IO error on CML-H

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2443] opened 2020-09-16 16:28 UTC
Intel daily tests ID: 408 show the following dmesg error for the test scenario multiple-pause-resume-25.sh

````bash
cmd: TPLG=sof-cml-rt711-rt1308-rt715.tplg ~/sof-test/test-case/multiple-pause-resume.sh -r 25
````

[dmesg-408.txt](https://github.com/thesofproject/linux/files/5233552/dmesg-408.txt)

````
kernel: [ 5914.149412] IO error in rt711_btn_check_handler, ret -16
````
@bardliao @shumingfan any idea what this could be?

**Comment by plbossart** [comment] 2020-09-16 16:39
FWIW, I am thinking of a workqueue that doesn't complete when we suspend.

**Comment by shumingfan** [comment] 2020-09-17 01:50
> FWIW, I am thinking of a workqueue that doesn't complete when we suspend.

Right, the problem should be caused by the work queue.
We need to cancel the delayed work when the system/codec suspends.
Could you try to test again with the following modification?

```
--- a/sound/soc/codecs/rt711-sdw.c
+++ b/sound/soc/codecs/rt711-sdw.c
@@ -491,6 +491,10 @@ static int __maybe_unused rt711_dev_suspend(struct device *dev)
        if (!rt711->hw_init)
                return 0;

+       cancel_delayed_work_sync(&rt711->jack_detect_work);
+       cancel_delayed_work_sync(&rt711->jack_btn_check_work);
+       cancel_work_sync(&rt711->calibration_work);
+
        regcache_cache_only(rt711->regmap, true);

        return 0;
```

**Comment by aiChaoSONG** [comment] 2020-09-17 02:24
submit a test PR for this, https://github.com/thesofproject/linux/pull/2445,

**Comment by aiChaoSONG** [comment] 2020-09-18 02:12
@mengdonglin I think @shumingfan will send the patch to alsa, so the my PR  is only for test purpose

**Comment by shumingfan** [comment] 2020-09-18 03:11
> @mengdonglin I think @shumingfan will send the patch to alsa, so the my PR is only for test purpose

@aiChaoSONG How about the test result? If the patch fixes this issue, I will send it to upstream.

**Comment by aiChaoSONG** [comment] 2020-09-18 10:58
@shumingfan The test result is good, I think you can send the patch to alsa.

**Comment by mengdonglin** [comment] 2020-09-22 13:33
Patches for upstream:
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-September/174476.html
https://mailman.alsa-project.org/pipermail/alsa-devel/2020-September/174477.html

**Comment by keyonjie** [comment] 2020-09-28 02:42
@shumingfan can you let us know if commits are merged in upstream?

**Comment by shumingfan** [comment] 2020-09-28 02:57
> @shumingfan can you let us know if commits are merged in upstream?

@keyonjie The commits are merged already.
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=501ef013390b774e8e61000a78d1d640d6c3411d
https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?id=5f2df2a4583b0d7b85054f0c1820f11a01936d35

**Comment by plbossart** [comment] 2020-09-28 15:06
Right, let's close when we've merged these upstream patches back into the SOF tree.

**Comment by mengdonglin** [comment] 2020-10-10 07:35
Close as sof-dev merged the 2 upstream patches.

**Closed as completed by mengdonglin** 2020-10-10 07:35 UTC
Labels: bug, P2, CML, codec, SDW
