### ISSUE TITLE
[BUG][CML][UCM2]No sound output in headset after plug/unplug HDMI&DP&headset when Output Device is Headphone

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2131] opened 2020-05-20 07:00 UTC
Describe the bug
No sound output in headset after plug/unplug HDMI&DP&headset when Output Device is Headphone
  

To Reproduce
 1.’sudo reboot’ to reboot system with all of  HDMI&DP&headset  connected
 2.open sound setting to set Output Device as HDMI,keep sound setting opening
 3.unplug DP then plug DP(Output Device switched to DP)
 4.unplug HDMI then plug HDMI(Output Device switched to HDMI)
 5.unplug headset then plug headset
 6.at the time Output Device is “Headphones-sof-hda-dsp” and Input Device is “Headset Mono Microphone-sof-hda-dsp"
 7.paplay -vv wav/48California_Dreaming.wav

Reproduction Rate
Repeat step2-step7,reproduced once in 3 times

Expected behavior
Sound output normal in headset when paplay via headset

Actual result
No sound output in headset,need unplug/plug headset again to recovery,if closed sound setting in step2,error not seen

Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: d9e3d4d4 https://github.com/thesofproject/sof/commits/master
Kernel: 3914cd29 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware
UCM2:https://github.com/thesofproject/alsa-ucm-conf/commits/master (commit: 81465c56) 
Pulseaudio:default pulseaudio of Ubuntu20.04+ https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/295  +https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/294

[amixercontents_0520.txt](https://github.com/thesofproject/linux/files/4655100/amixercontents_0520.txt)
[dmesg0520.log](https://github.com/thesofproject/linux/files/4655102/dmesg0520.log)
[sof-logger0520.log](https://github.com/thesofproject/linux/files/4655103/sof-logger0520.log)

**Comment by libinyang** [comment] 2020-08-12 10:07
This bug is still reproduced on the latest pulseaudo + gnome + alsa-lib + UCM

I can reproduce this issue even with `aplay` with the alsamixer setting correctly. After disabling pulseaudio, I can't reproduce this issue with more than 10 times trys.

**Comment by plbossart** [comment] 2020-08-12 15:35
> This bug is still reproduced on the latest pulseaudo + gnome + alsa-lib + UCM
> 
> I can reproduce this issue even with `aplay` with the alsamixer setting correctly. After disabling pulseaudio, I can't reproduce this issue with more than 10 times trys.

If you disable PulseAudio, you also disable UCM, no? I don't get the last sentence at all.

**Comment by plbossart** [comment] 2020-09-03 20:41
@libinyang can we try and close all UCM2 issues? This is 3+ months old now.

**Comment by libinyang** [comment] 2020-09-04 02:30
@plbossart OK, I will work on the UCM2 issues next week after I finish the user space test cases. This issue is very strange and it is not related to UCM.

**Comment by libinyang** [comment] 2020-09-09 09:13
I found an easy way to reproduce this issue. With HDMI monitor connected, disconnecting headset and then connecting headset will also trigger this issue. But if the HDMI monitor is not connected, it's hardly to reproduce this issue.

The pulseaudio and UCM should be OK. When connecting and disconnecting the headset, the device switching and amixer setting are exact following what we design. It's more like the audio codec HW/driver issue.

I will continue debug the issue this week.

**Comment by libinyang** [comment] 2020-09-11 09:33
After these 2 days debug, I'm pretty sure this is a codec issue. If we quickly unplug and plug the headset, the codec tries to setting the "Processing Coefficient" registers. However, there is a probability that the codec's register setting will be wrong. After I manually  re-write the codec's register, there is sound output from the headset.

**Comment by libinyang** [comment] 2020-09-14 01:40
@mengdonglin As this is a codec issue, shall we close this bug as won't fix?

**Comment by libinyang** [comment] 2020-09-14 07:51
Close it as this is a codec issue.

**Comment by libinyang** [comment] 2020-09-23 02:19
As discussed with Mengdong and Kai, I would like to reopen this issue and tag it as "won't fix". So we won't put any effort on it and we can be aware the bug is still there.

**Closed as completed** 2021-06-10 17:55 UTC
Labels: bug, won't fix, P3, CML, HDA, codec, UCM2, single-profile UCM + PA#295+PA#294
