### ISSUE TITLE
Send mt8186 patches to alsa-devel

### ISSUE THREAD

**Issue by tinghan-shen** [thesofproject/linux#3593] opened 2022-04-18 06:37 UTC
Hi sirs,

I've a look at the [SOF maintainers process](https://thesofproject.github.io/latest/contribute/linux/development_tree.html#sof-maintainers-process), and have a question about the next step of upstream mt8186 patches to mailnline.

According to my colleagues working on the MT8195, they had discussed with Intel/NXP this before.
From their recollection, MediaTek has to upstream its own patches to alsa-devel.

If possible, could you please guide us on how to upstream SOF patches to mainline? we had upstream experience on drivers based on linux maintainer's repo or linux-next, but don't sure how to do it right on SOF project.

Best regards,
TingHan

**Comment by kuanhsuncheng** [comment] 2022-04-18 07:22
Hi sirs,

I found there was a discussion before (Title : How to upstream Linux SOF driver patches?)

The process is 

a) use scripts to cherry-pick commits from topic/sof-dev to topic/sof-dev-rebase. The scripts automatically add the Reviewed-by tags based on github 'accept' status. The fixup! patches can be squashed at that point. At this point the two branches topic/sof-dev and topic/sof-dev-rebase shall be identical (using git diff).

b) create an upstream baseline from broonie/for-next, tiwai/for-next, soundwire/next and regmap/for-next.

c) rebase topic/sof-dev-rebase on top of this upstream baseline. Conflicts may occur due to upstream contributions sent directly to maintainers. We tag this branch with the label sof-dev-rebase-YYYYMMDD to be able to reconstruct it in case of an error, and also to be able to 'bisect' between tags.

d) create a merge commit for this upstream baseline on top of topic/sof-dev/. Usually there can be conflicts as well.

e) at this points both branches be identical again.


I think we (mediatek) should wait for item a) and then do item b). am I right ?

**Comment by dbaluta** [comment] 2022-04-18 07:50
We don't need to wait for b). It is not clear who will be doing a)? Cc: @lgirdwood 

Also, you don't actually need to wait for a)  you just go the PR and add the Reviewed-by tags manually and then continue with b) and so on. 

I usually try once my patches are meged into sof-dev to also send them to alsa devel if they are NXP specific patches.

**Comment by plbossart** [comment] 2022-04-18 15:32
@dbaluta @kuanhsuncheng @tinghan-shen the process described above is what Intel does on a weekly basis to create the topic/sof-dev-rebase branch.

You can send the MTK or NXP patches from topic/sof-dev-rebase directly to Mark Brown, that's fine if you take them *AS IS*. What is not fine is that you send patches directly to Mark Brown and we end-up having to deal with conflicts during the upstream merge. You would still need to make sure the patches you extract from topic/sof-dev-rebase have no dependencies on previous patches that are already queued, e.g. there is currently a dependency on my 'IPC4 plumbing' series that's been under review upstream for a week already.

There were cases where I did send MTK and AMD patches directly as part of regular SOF contributions. That's typically close to the end of the cycle where we want to try and flush as many patches as possible.

**Comment by dbaluta** [comment] 2022-04-18 17:04
> What is not fine is that you send patches directly to Mark Brown and we end-up having to deal with conflicts during the upstream merge.

I'm sorry if i've done that and generated conflicts. Maybe because I wanted a larger audience. Anyhow, the problem is that I haven't merged that back.

**Comment by plbossart** [comment] 2022-04-18 20:03
no worries @dbaluta, it was an isolated incident

**Comment by plbossart** [comment] 2022-04-19 16:27
@kuanhsuncheng @tinghan-shen I updated the topic/sof-dev-rebase branch, and if you take a look your patches are currently gated by the 'IPC4 plumbing' series that's under review on alsa-devel

https://lore.kernel.org/alsa-devel/20220414184817.362215-1-pierre-louis.bossart@linux.intel.com/T/#t

**Comment by tinghan-shen** [comment] 2022-04-21 02:08
@dbaluta @plbossart , thanks for your clear explanation and remind.  
I will check dependencies before send to alsa-devel.
many thanks!

**Closed as completed** 2022-04-21 02:09 UTC
Labels: discussion

**Comment by plbossart** [comment] 2022-04-21 13:58
@tinghan-shen the 'IPC4 plumbing' series was merged so you can take the following patches from topic/sof-dev-rebase

````
76264d1381f92 ASoC: SOF: mediatek: Add DSP system PM callback for mt8186
85719a0f44a3d ASoC: SOF: mediatek: Add mt8186 dsp clock support
0bea1a4f072e7 ASoC: SOF: mediatek: Add mt8186 sof fw loader and dsp ops
c36b5fdbd1f9a ASoC: SOF: mediatek: Add mt8186 hardware support
````

**Comment by tinghan-shen** [comment] 2022-04-22 03:00
> @tinghan-shen the 'IPC4 plumbing' series was merged so you can take the following patches from topic/sof-dev-rebase
> 
> ```
> 76264d1381f92 ASoC: SOF: mediatek: Add DSP system PM callback for mt8186
> 85719a0f44a3d ASoC: SOF: mediatek: Add mt8186 dsp clock support
> 0bea1a4f072e7 ASoC: SOF: mediatek: Add mt8186 sof fw loader and dsp ops
> c36b5fdbd1f9a ASoC: SOF: mediatek: Add mt8186 hardware support
> ```

@plbossart , ok, thanks!
