### ISSUE TITLE
[BUG][SDW] 0,0 aplay and 0,1 arecord can't be triggered at same timed

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#1198] opened 2019-09-12 03:22 UTC
**Describe the bug**
0,0 aplay and 0,1 arecord can't be triggered at same timed for "Compute transport params failed: -22"

**To Reproduce**
1. Terminal 1: time aplay -Dhw:0,0 -r48000 -c2 -fs16_le /dev/zero -vv -i -d 180
2. Terminal 2: arecord -Dhw:0,1 -r48000 -c2 -fs32_le 1.wav -vv -i

**frequency**
100%

**Actual result**
arecord failed for "unable to install hw params"

**Expected result**
arecord should be triggered successfully

**Environment**
linux: https://github.com/thesofproject/linux/tree/topic/soundwire commit: bccf4a8a
sof: https://github.com/thesofproject/sof/commits/sdw-001-drop-stable commit: d9c0463
Topology: file: sof-cml-rt700.m4 same path as firmware
platform: CML SDW RVP, with onboard ALC700 in SDW mode

No error messages.

**dmesg**
```
[   15.529694] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 0
[   15.529699] sof-audio-pci 0000:00:1f.3: generating page table for 0000000073947968 size 0xffc0 pages 16
[   15.529715] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   15.529742] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[   15.529746] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[   15.529749] sof-audio-pci 0000:00:1f.3: periods:4
[   15.529774] sof-audio-pci 0000:00:1f.3: stream_tag 1
[   15.529785] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   15.530072] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   15.530075] sof-audio-pci 0000:00:1f.3: pcm: stream dir 0, posn mailbox offset is 790528
[   15.530078] plb: soc_pcm_hw_params component name snd-soc-dummy
[   15.531741] plb: soc_pcm_trigger codec_dai name snd-soc-dummy-dai
[   15.531754] plb: soc_pcm_trigger component name 0000:00:1f.3
[   15.531762] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 1
[   15.532285] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x14001e successful
[   15.532290] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   15.532659] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   15.532663] plb: soc_pcm_trigger component name snd-soc-dummy
[   15.532667] plb: soc_pcm_trigger cpu_dai name SDW1-speakers 0
[   15.532672] plb: soc_pcm_trigger codec_dai name rt700-aif1
[   15.532674] plb: soc_pcm_trigger component name int-sdw.1
[   15.532676] plb: soc_pcm_trigger component name sdw:1:25d:700:0:0
[   15.532678] plb: soc_pcm_trigger component name 0000:00:1f.3
[   15.532681] plb: soc_pcm_trigger cpu_dai name SDW1 Pin2
[   15.986511] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   15.986542] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   16.486722] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   16.486755] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[   25.855588] sof-audio-pci 0000:00:1f.3: pcm: open stream 1 dir 1
[   25.855590] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[   25.855591] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[   25.855591] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[   25.855690] plb: soc_pcm_hw_params codec_dai name rt700-aif1
[   25.855694] rt700 sdw:1:25d:700:0:0: rt700_pcm_hw_params rt700-aif1
[   25.856436] plb: soc_pcm_hw_params cpu_dai name SDW1 Pin3
[   25.856450] sof-audio-pci 0000:00:1f.3: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[   25.856678] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[   25.856689] int-sdw int-sdw.1: Compute transport params failed: -22
[   25.856692] int-sdw int-sdw.1: Compute params failed: -22
[   25.856694] Prepare for stream:SDW1 Pin3-Capture failed: -22
[   25.856696] int-sdw int-sdw.1: ASoC: can't set SDW1 Pin3 hw params: -22
[   25.856698]  SDW1-Capture: ASoC: hw_params BE failed -22
[   25.856700]  SDW1-mics: ASoC: hw_params BE failed -22
[   25.856786] sof-audio-pci 0000:00:1f.3: pcm: close stream 1 dir 1
[   26.486457] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[   26.486493] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  118.598346] plb: soc_pcm_trigger codec_dai name snd-soc-dummy-dai
```
[aplayArecordAtSameTime_dmesg.txt](https://github.com/thesofproject/linux/files/3603548/aplayArecordAtSameTime_dmesg.txt)
[aplayArecordAtSameTime_logger.txt](https://github.com/thesofproject/linux/files/3603549/aplayArecordAtSameTime_logger.txt)

**Comment by plbossart** [comment] 2019-09-18 22:27
please retest with firmware master and kernel integration/soundwire-latest

**Comment by ClarexZhou** [comment] 2019-09-19 07:49
Error seen with firmware master and kernel integration/soundwire-latest branch.
**Environment**
Firmware: 460c41a  Master
Kernel: 4ac5440 on integration/soundwire-latest
Topology: file: same with firmware branch, sof-cml-rt700.m4
platform: CML rt700 SDW RVP

**Comment by plbossart** [comment] 2019-09-19 21:06
behavior NOT reproduced on ICL. This looks like a CML-specific problem

@RanderWang can you look into this?

**Comment by ClarexZhou** [comment] 2019-09-20 02:29
Issue not seen with sof_debug=1

**Comment by plbossart** [comment] 2019-09-20 18:49
closing for now, will have to be retested when suspend-resume is supported

**Closed as completed by plbossart** 2019-09-20 18:49 UTC
Labels: bug, CML, SDW_DEV, SDW
