### ISSUE TITLE
[IPC4][cAVS reference firmware] Unexpected error when runtime resume while HDA Analog capturing on TGL UPboard 

### ISSUE THREAD

**Issue by XiaoyunWu6666** [thesofproject/linux#3636] opened 2022-05-09 13:52 UTC
**Description**
A bug happened in inner daily IPC4 tests on 
12017 April 23
11908 April 20
12388 May 09
on TGLU_UP_HDA_CAVSIPC4 

While recording with HDA analog hw:0,0 and runtime suspend-resume , in approximately 11 or 12 rounds among 15 , FW reported error:2 - Unknown message type specified
**Test Recipe**
[take May 09's test recipe as example]
Kernel Branch: topic/sof-dev
Kernel Commit: [68b76766e8ba](https://github.com/thesofproject/linux/commit/68b76766e8ba)
SOF Branch: main
SOF Commit: [b36db45a7da7](https://github.com/thesofproject/sof/commit/b36db45a7da7)
tplg:cavs-mixin-mixout-hda.tplg
**how to reproduce**
```
TPLG=/lib/firmware/intel/avs-tplg/cavs-mixin-mixout-hda.tplg MODEL=TGLU_UP_HDA_CAVSIPC4 ~/sof-test/test-case/check-runtime-pm-status.sh -l 15
```
**LOG**
```
[ 1724.979170] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 2 -> 5
[ 1724.979175] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 1724.979194] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[ 1724.979201] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000002 at  00000048
[ 1724.979213] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000004 at  00000044
[ 1724.979218] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000000 at  00000044
[ 1724.979221] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware boot complete
[ 1724.979223] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 5 -> 6
[ 1724.979256] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x21000002|0x0: GLB_ROM_CONTROL
[ 1724.979260] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 2 - Unknown message type specified
[ 1724.979266] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x21000002, will be ignored
```

[complete dmesg]
[IPC4dmesg.txt](https://github.com/thesofproject/linux/files/8657274/IPC4dmesg.txt)

**Comment by bardliao** [comment] 2022-05-09 14:00
The **ipc tx reply: 0x21000002|0x0: GLB_ROM_CONTROL** ipc is a unexpected ipc. We will ignore it eventually. See **no reply expected, received 0x21000002, will be ignored**. However, CI will get the error when ``sof_ipc4_check_reply_status`` is called in ``sof_ipc4_get_reply``.
I think we should test ``if (msg->ipc_complete)`` before ``sof_ipc4_check_reply_status``. Either in ``sof_ipc4_get_reply`` and ``sof_ipc3_get_reply`` or in ``snd_sof_ipc_get_reply``. What do you think @ujfalusi @ranj063 ?

**Comment by ujfalusi** [comment] 2022-05-09 14:26
@bardliao, we are receiving a tx reply to a ROM_CONTROL message which we did not sent?
Can this be a reply to the ROM control message we are sending as part of the boot sequence? But the reply should be handled there as well while interrupts are disabled.
Is this IMR boot or cold boot?
Who is sending the reply that the message is unknown?

@XiaoyunWu6666, can attach the full dmesg? I don't know the context.
EDIT by @XiaoyunWu6666 : hi @ujfalusi , I updated it in the original issue description

**Comment by ujfalusi** [comment] 2022-05-09 15:06
I guess this is one of the cases:
```
[ 3835.494484] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: IMR restore supported, booting from IMR directly
[ 3835.494488] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 3835.494493] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0f successful
[ 3835.494500] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0e successful
[ 3835.494503] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 3835.494508] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 3835.495341] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010e0e successful
[ 3835.495346] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 3835.495351] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 3835.506539] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0xd4]=0x80000000 successful
[ 3835.506550] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x40000005 successful
```
IMR boot successful
```
[ 3835.506588] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx      : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
[ 3835.506593] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 2 -> 5
[ 3835.506598] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done : 0x1b080000|0x0: GLB_NOTIFICATION|FW_READY
```
FW ready arrives
```
[ 3835.506617] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[ 3835.506624] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000002 at  00000048
[ 3835.506635] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000004 at  00000044
[ 3835.506640] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000000 at  00000044
[ 3835.506642] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware boot complete
[ 3835.506644] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 5 -> 6
[ 3835.506674] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x21000002|0x0: GLB_ROM_CONTROL
[ 3835.506678] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 2 - Unknown message type specified
[ 3835.506684] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x21000002, will be ignored
```
A reply with error code...

But most of the time we don't receive a reply out of the blue, not even with a success. Interesting.

**Comment by ranj063** [comment] 2022-05-09 15:37
@ujfalusi @bardliao havent we seen this in the past with the SOF firmware as well. And this was the reason why this commit was added right? 
commit 37a079415456b34520454828d582b5bbdad0473f
Author: Keyon Jie <yang.jie@linux.intel.com>
Date:   Sat Nov 9 05:21:00 2019 +0800

    ASoC: SOF: Intel: hda-loader: clear the IPC ack bit after FW_PURGE done
    
    Set DONE bit after the FW_PURGE IPC is polled successfully, to clear the
    interrupt and avoid the arrival of the confusing unexpected ipc.

**Comment by ujfalusi** [comment] 2022-05-09 20:07
@ranj063, hrm, so with IPC4 we need to set different DONE?
We are polling on IPC DONE bit, which is set when the IPC BUSY is cleared by the ROM.
The sequence looks OK and it is working most of the time...
I'll re-check the difference between IPC3 and IPC4, but in IPC4 the host to DSP message ack and the reply is a separate step.
The ack from DSP is just an ack, then it is sending the reply as a new message, while with IPC3 the ack carries the reply itself.

It is possible that we have some overlooked corner case when we accidentally send an IPC4 message to the already running firmware (not clearing old message data, or something).

**Comment by ujfalusi** [comment] 2022-05-10 08:00
Long shot, but let's give this PR a test: #3639. I can not reproduce it on my machine after 100+ iterations (even without the patch).
The way we do the ROM control message sending is correct.

**Comment by ujfalusi** [comment] 2022-05-10 11:00
PR #3639 does not help and the issue happens with SOF firmware as well, but in there we are ending up with a flood of tx reply messages:
```
[ 2330.322478] sof-audio-pci-intel-tgl 0000:00:1f.3: IMR restore supported, booting from IMR directly
[ 2330.322482] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 2330.322488] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0f successful
[ 2330.322494] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0e successful
[ 2330.322498] sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 2330.323320] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 2330.323338] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010e0e successful
[ 2330.323343] sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 2330.323347] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 2330.338514] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0xd4]=0x80000000 successful
[ 2330.338526] sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x5 successful
[ 2330.338577] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x2100000f|0x0: GLB_ROM_CONTROL
[ 2330.338582] sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 15 - Requested service or data is unavailable on the target platform
[ 2330.338588] sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x2100000f, will be ignored
[ 2330.338641] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x2000000f|0x0: GLB_BOOT_CONFIG
[ 2330.338644] sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 15 - Requested service or data is unavailable on the target platform
[ 2330.338647] sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x2000000f, will be ignored
...
```
It took about 100 iteration of the test to end up like this.

**Comment by ujfalusi** [comment] 2022-05-10 11:22
manually running the kernel from #3640

**Comment by ujfalusi** [comment] 2022-05-10 12:53
So far #3640 is passing over 150 iterations of the test run, I think that should be a good candidate as a fix.

**Comment by bardliao** [comment] 2022-05-11 02:24
> So far #3640 is passing over 150 iterations of the test run, I think that should be a good candidate as a fix.

@ujfalusi Instead of reverting the IMR change, can we just ignore the unexpected IPC reply? Will it cause any issue?

**Comment by ujfalusi** [comment] 2022-05-11 06:12
@bardliao, what I have seen on the CI machine is that with the SOF IPC4 firmware we get a flood the ghost tx reply messages:
```
sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x2000000f|0x0: GLB_BOOT_CONFIG
sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 15 - Requested service or data is unavailable on the target platform
sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x2000000f, will be ignored
...
sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx reply: 0x2000000f|0x0: GLB_BOOT_CONFIG
sof-audio-pci-intel-tgl 0000:00:1f.3: FW reported error: 15 - Requested service or data is unavailable on the target platform
sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x2000000f, will be ignored
```
the only way to stop it is to remove the drivers.

**Comment by ujfalusi** [comment] 2022-05-11 11:56
Right, tried to reproduce it today, but nothing after 4k+ runs
¯\(º_o)/¯

**Comment by ujfalusi** [comment] 2022-05-12 16:30
Another candidate which survived 1000 IMR boot iteration on upx-i11 (TGL) and up2 (APL) on local testing: #3649

**Comment by XiaoyunWu6666** [comment] 2022-06-01 04:46
haven't seen this in CI for 3 weeks

**Comment by bardliao** [comment] 2022-06-30 00:41
@XiaoyunWu6666 Do we still see this issue? We can close it if it wasn't reproducible for a while.

**Comment by lgirdwood** [comment] 2022-08-10 08:11
> @XiaoyunWu6666 Do we still see this issue? We can close it if it wasn't reproducible for a while.

@mengdonglin @XiaoyunWu6666 @keqiaozhang still an issue ?

**Comment by keqiaozhang** [comment] 2022-10-10 00:46
No reproductions in CI for a long time. Closing this bug.

**Closed as completed by keqiaozhang** 2022-10-10 00:46 UTC
Labels: TGL, suspend resume, IPC4, IPC4 tester
