### ISSUE TITLE
[BUG][CML][MST] Delay in audio while switching device between multiple monitors

### ISSUE THREAD

**Issue by kamal-ap** [thesofproject/linux#1069] opened 2019-07-02 10:01 UTC
Platform : CML
**SOF firmware & topology :** 
SOF   FW source | URL: https://github.com/thesofproject/sof/tree/cml-004-drop-stable          Commit:  f82d9dad7bd48fa3243d94d45dac68261184bc55
**UCM :** 
https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/1648310

**Kernel:** : 
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1650019/6

**Steps to download chromium kernel:**
git add remote google https://chromium.googlesource.com/chromiumos/third_party/kernel
git fetch google
git fetch "https://chromium.googlesource.com/chromiumos/third_party/kernel" refs/changes/19/1650019/6 && git checkout FETCH_HEAD

**SOF reference release details:**
SOF   FW source | URL: https://github.com/thesofproject/sof/tree/cml-004-drop-stable          Commit:  f82d9dad7bd48fa3243d94d45dac68261184bc55
SOF   Drivers source | URL: https://github.com/thesofproject/linux/commits/topic/sof-dev   Commit: 4d1fc20

 

Steps to reproduce :
1) Connect 2 external DP monitors to 'typeC to MST' dongle
2) open 'audio settings' from system tray
3) Switch between Speaker -> Monitor1 -> monitor2  in random ( do it multiple time )

Expected Result : 
Audio should be routed properly to selected device

Actual result : 
No audio hear in any devices and dmesg show multiple errors on each device transition

Error logs taken while device transition:
[  108.228529] fscrypt: AES-256-CTS-CBC using implementation "cts(cbc-aes-aesni)"
[  108.299065] fscrypt: AES-256-XTS using implementation "xts-aes-aesni"
[  108.692446] wlan0: authenticate with 2c:4d:54:49:bc:b0
[  108.693980] wlan0: send auth to 2c:4d:54:49:bc:b0 (try 1/3)
[  108.716738] wlan0: authenticated
[  108.716977] wlan0: associate with 2c:4d:54:49:bc:b0 (try 1/3)
[  108.723166] wlan0: RX AssocResp from 2c:4d:54:49:bc:b0 (capab=0x1411 status=0 aid=7)
[  108.729729] wlan0: associated
[  108.779753] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  109.748190] init: arc-kmsg-logger main process (2997) killed by TERM signal
[  115.794568] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[  115.884073] sof-audio-pci 0000:00:1f.3: firmware boot complete
[  115.921698] div[0]=1
[  115.921702] div[1]=2
[  159.412560] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:2
[  159.412995] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:2
[  159.413391] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi3 hw params: -19
[  159.413400]  iDisp3: ASoC: hw_params BE failed -19
[  159.413407]  HDMI3: ASoC: hw_params BE failed -19
[  159.414415] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi3 hw params: -19
[  159.414429]  iDisp3: ASoC: hw_params BE failed -19
[  159.414436]  HDMI3: ASoC: hw_params BE failed -19
[  161.426969] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-2 Output event failed: -5
[  183.783046] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[  183.875330] sof-audio-pci 0000:00:1f.3: firmware boot complete
[  209.654018] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-1 Output event failed: -5
[  232.755477] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:2
[  232.755740] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:2
[  232.756123] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi3 hw params: -19
[  232.756132]  iDisp3: ASoC: hw_params BE failed -19
[  232.756138]  HDMI3: ASoC: hw_params BE failed -19
[  232.757092] HDMI HDA Codec ehdaudio0D2: ASoC: can't set intel-hdmi-hifi3 hw params: -19
[  232.757105]  iDisp3: ASoC: hw_params BE failed -19
[  232.757117]  HDMI3: ASoC: hw_params BE failed -19
[  234.767968] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-2 Output event failed: -5

**Comment by kv2019i** [comment] 2019-07-02 13:46
@kamal-ap You are at least missing this patch from upstream:
"ASoC: codec: hdac_hdmi: fix pin connections at cvt enable"

... it solves issues with use cases involving multiple monitors.

Based on logs, there is something else wrong as well. It would seem the use-case manager is not updating alsamixer settings correctly. Has the Chrome equivalent of Pulseaudio+ALSA-UCM been updated to work with SOF HDMI interface (FYI @libinyang who has been fixing issues with Pulse).
See the attached UCM description to show how alsamixer settings need to be set when monitor connectivity is changed and/or different PCM is activated (see mail attachment):
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-June/151052.html

**Comment by kamal-ap** [comment] 2019-07-03 06:44
Thanks Kai Vehmanen ,
with below patches most errors are gone
 ASoC: codec: hdac_hdmi: fix pin connections at cvt enable
 ASoC: codec: hdac_hdmi: no checking monitor in hw_params

Only  " PRE_PMU  Output event failed: -5"  errors are there now .

**Comment by kamal-ap** [comment] 2019-07-03 16:15
@libinyang @ranj063 
There is some 3-5 sec delay in audio switch now.
Is that related to PRE_PMU  -5  errors  ?

**Comment by ranj063** [comment] 2019-07-04 04:28
@libinyang could you please take a look at the delay issue pointed out here?

**Comment by libinyang** [comment] 2019-07-04 07:56
> @libinyang @ranj063
> There is some 3-5 sec delay in audio switch now.
> Is that related to PRE_PMU -5 errors ?
@kamal-ap 
Does the delay happen when playing DP audio, or HDMI audio or Speaker?

**Comment by dsgirish** [comment] 2019-07-04 11:49
@libinyang 
Yes, We have been using the DP MST Hub with 2 external monitors and the DP MST Monitor (Daisy Chaining). Throughout the unit testing, the delay of 3-5 seconds was observed.
The transition to the Speaker and Headset is seen smooth.

**Monitors Used:**
1. Dell 24 Ultra HD 4K Monitor | P2415Q
2. Dell UltraSharp 27 Monitor: U2719D

DP MST Hub: 3-Port USB-C to DisplayPort MST Hub - 4K 30Hz

**Comment by libinyang** [comment] 2019-07-05 02:06
@Girish-DS 

If it is related to DP, we have a similar bug traced: https://github.com/thesofproject/linux/issues/925
But we think this is a low priority issue, so we didn't put any effort on it.

**Comment by kamal-ap** [comment] 2019-07-10 05:32
@libinyang  , can you also comment on -5 errors in logs .

**Comment by libinyang** [comment] 2019-07-10 05:57
I couldn't reproduce your bug on my side. I think maybe you are operating on a pin or converter which is not bound to any PCM. So the driver can't get any PCM to operate. Based on my understanding, after reviewing the hdmi driver code, it won't impact on the user experience, will it?

**Comment by kamal-ap** [comment] 2019-07-10 06:27
@libinyang   no impact on user experience as such.
but we may face questions from customer regarding the errors.

**Comment by libinyang** [comment] 2019-07-11 06:47
@kamal-ap 
Clare tested on CML with ubuntu, and we can't reproduce this bug. Is DPMST a must? We use hdmi and DP monitor to do the test. Suppose ubuntu and chrome should be similar for this bug, right?

**Comment by kamal-ap** [comment] 2019-07-11 07:32
@libinyang 
We observed only when switching between MST monitors 

are you using MST release to validate same ?
SOF FW source | URL: https://github.com/thesofproject/sof/tree/cml-004-drop-stable   Commit:  f82d9dad7bd48fa3243d94d45dac68261184bc55
SOF Drivers source | URL: https://github.com/thesofproject/linux/commits/topic/sof-dev Commit: 4d1fc20

**Comment by libinyang** [comment] 2019-07-11 07:39
@kamal-ap 
No, we didn't test in DPMST mode. This is because our HW platform can't support DPMST well. We will try to find a platform to test in DPMST mode.

**Comment by kamal-ap** [comment] 2019-07-11 07:41
@libinyang   Thanks libin . May be you can check with @ranj063  for platform

**Comment by kamal-ap** [comment] 2019-10-09 05:24
Below dmesg error messages seen Pre-Merge validation of SOF v0.7 also

[ 1687.641964] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:2
[ 1687.642219] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:2
[ 1688.642054] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-2 Output event failed: -5
[ 1716.891138] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:0
[ 1716.891405] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:0
[ 1717.894466] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: hif5-1 Output event failed: -5
[ 1737.487996] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:2
[ 1737.488263] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:2
[ 1738.490455] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:0
[ 1738.490723] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:0
[ 1745.310809] HDMI HDA Codec ehdaudio0D2: ASoC: POST_PMD: hif5-2 Output event failed: -5
[ 1745.321341] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 6:0
[ 1745.321664] HDMI HDA Codec ehdaudio0D2: No connections found for pin:port 7:0
[ 1749.496785] HDMI HDA Codec ehdaudio0D2: ASoC: POST_PMD: hif5-1 Output event failed: -5

[  213.724797] HDMI HDA Codec ehdaudio0D2: ASoC: PRE_PMU: Pin5-Port2 Mux event failed: -5

**Comment by plbossart** [comment] 2020-01-17 00:40
@kamal-ap @kv2019i @ranj063 @libinyang can we close this one?

**Comment by kamal-ap** [comment] 2020-01-17 08:18
Till SOF0.7 , this is not fixed . We will check and close in SOF0.8 release.

**Comment by plbossart** [comment] 2020-06-09 19:18
@kv2019i do you have a DP-MST rig that you can use to check this? I don't think the delay when switching monitors can be avoided but there shouldn't be any errors.

**Comment by kv2019i** [comment] 2020-07-20 12:38
@plbossart This has fallen through the cracks. I'll tagged this with HDA, so it stays on my radar. I'll test with DP-MST on CML once I have the chance (some remote-work contraints at the moment).

**Comment by plbossart** [comment] 2021-06-10 18:12
@kv2019i it's been nearly a year, shall we keep this open?

**Comment by kv2019i** [comment] 2021-06-11 14:09
Tested with today's sof-dev (https://github.com/thesofproject/linux/commit/574402853ecaaddb2c3699641700fc3048a09cbb) in a Tiger Lake laptop and a USB-C docking station as the DP-MST hub and switching audio is immediate and with no errors.
The 3-5sec delay in audio sounds like an issue with DP receiver ramping up from standby and can be avoided by enabling CONFIG_SND_HDA_INTEL_HDMI_SILENT_STREAM=y in kernel config.

With that, closing.

**Closed as completed by kv2019i** 2021-06-11 14:09 UTC
Labels: bug, P3, CML, HDA
