### ISSUE TITLE
[BUG][GLK][DA7219] Do playback and capture at same time pause/stop catch pop noise in headset

### ISSUE THREAD

**Issue by Bin-QA** [thesofproject/linux#1342] opened 2019-10-21 07:56 UTC
# Describe the bug
Do playback and capture using same device at same time pause/stop at aplay catch pop noise in headset

# To Reproduce
Playback via headset (device 0,1) and Capture via headset (device 0,1) simultaneously.
1. In terminal to run "aplay -D hw:0,1 -f dat 48California_Dreaming.wav"
2. In other terminal to run "arecord -Dhw:0,1 -f dat -vv -i test.wav"

At "aplay" terminal pause/resume audio, reproduce pause/resume step >= 3 times
Catch pop noise in headset

# frequency
100%

# Expected result
Do playback and capture at same time ensure pause/stop no effect for each other

# Actual result
Do playback and capture with same device at same time pause/stop on playback catch pop noise on playback

# Environment
|  Name | branch  | commit  | 
|---|---|---|
|  kerenl  | [sof-dev](https://github.com/thesofproject/linux/commits/topic/sof-dev)  | 97ccba77  |
| Firmware | [master](https://github.com/thesofproject/sof/commits/master) | 3d5d3146 |
| Topology | [master](https://github.com/thesofproject/sof/tree/master/tools/topology) | sof-glk-da7219  |
| platform | GLK Chrome(I2S) |  |

[dmesg-boot.log](https://github.com/thesofproject/linux/files/3749596/dmesg-boot.log)
[sof_logger.log](https://github.com/thesofproject/linux/files/3749597/sof_logger.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3749598/dmesg.log)

**Comment by plbossart** [comment] 2019-10-21 11:12
@Bin-QA you added 4 scenarios but it's very hard to figure out which ones work and which ones don't. please clarify when the issue is seen?

**Comment by Bin-QA** [comment] 2019-10-22 00:25
Also verify for those Scenario which **couldn't reproduce** this bug:
1. Just headset to play audio with pause/resume operation without pop noise
2. headset to play audio & dmic to capture with pause/resume operation on playback without pop noise
3. speaker to play audio & headset to capture with pause/resume operation on playback without pop noise

So confirm this bug base on the **headset** to **playback & capture**, pause the playback will catch the pop noise

**Comment by Bin-QA** [comment] 2019-10-22 07:54
Reproduce this issue for daily test

This Scenario **couldn't reproduce** this bug:
1. In terminal to run "aplay -D hw:0,1 -f dat 48California_Dreaming.wav"
2. In other terminal to run "arecord -Dhw:0,1 -f  dat -vv -i test.wav"
3. Close "arecord"
pause & resume "aplay"

# Test Environment 
|  Name | branch  | commit  | 
|---|---|---|
|  kerenl  | [sof-dev](https://github.com/thesofproject/linux/commits/topic/sof-dev)  | fd274c2b  |
| Firmware | [master](https://github.com/thesofproject/sof/commits/master) | 1dbd14b3 |
| Topology | [master](https://github.com/thesofproject/sof/tree/master/tools/topology) | sof-glk-da7219  |
| platform | GLK Chrome(I2S) |  |


[sof-logger.log](https://github.com/thesofproject/linux/files/3754287/sof-logger.log)
[dmesg.log](https://github.com/thesofproject/linux/files/3754288/dmesg.log)
[dmesg-boot.log](https://github.com/thesofproject/linux/files/3754289/dmesg-boot.log)

**Comment by plbossart** [comment] 2019-10-30 22:05
@Bin-QA the pop noise can fully be removed on only for silence, so try and play with /dev/zero and see if the error still exists. If not then we can't do anything.

**Comment by dengyangchao** [comment] 2019-10-31 11:01
> @Bin-QA the pop noise can fully be removed on only for silence, so try and play with /dev/zero and see if the error still exists. If not then we can't do anything.

@plbossart play with /dev/zero, the issue can't reproduce,  no pop noise

**Comment by ClarexZhou** [comment] 2019-11-04 01:23
Close for Won't fix

**Closed as completed by ClarexZhou** 2019-11-04 01:23 UTC
Labels: bug, GLK
