### ISSUE TITLE
multi-pipeline-capture test fails in dell xps 17 sdw device

### ISSUE THREAD

**Issue by juimonen** [thesofproject/linux#2751] opened 2021-02-09 21:24 UTC
sof-test multiple-pipeline-capture.sh fails in sdw driver: 
"rt711 sdw:0:25d:711:0: DPN_PortCtrl register write failed for port 4"

test itself tries to open multiple stream simultaneously (2 playback and 2 capture).

sof-dev kernel: 37d57e0e29a5f6703b5bbab73055239b7df4d43a
fw: 9d41d63ac79e551f4022c388284c2233606788a1
topology: sof-cml-rt711-rt1308-rt715.tplg

dmesg attached:
[sdw_fail.txt](https://github.com/thesofproject/linux/files/5954342/sdw_fail.txt)

**Comment by juimonen** [comment] 2021-02-09 21:25
@bardliao @plbossart FYI

**Comment by plbossart** [comment] 2021-02-09 22:30
@juimonen I don't see anything in the log that looks suspicious before that error message.

can you copy/paste the command used so that we can reproduce this? Is this 100% reproducible or just random. 

I don't have this device (only the mono version) but we've not seen this in daily tests.

**Comment by plbossart** [comment] 2021-02-09 22:32
What's odd is that there's a failure on playback as well

````
[   63.678870] intel-sdw intel-sdw.0: Msg ignored for Slave 0
[   63.678892] rt711 sdw:0:25d:711:0: DPN_PortCtrl register write failed for port 4

somehow this is initiated *before* the enumeration completes. Not sure how it's possible.

[   63.678917] soundwire sdw-master-0: Program transport params failed: -61
[   63.678933] soundwire sdw-master-0: Program params failed: -61
[   63.678950]  SDW0-Capture: ASoC: error at snd_soc_link_prepare on SDW0-Capture: -61
[   63.678973]  SDW0-Capture: ASoC: backend prepare failed -61
[   63.679071] sof-audio-pci 0000:00:1f.3: error: failed to update DAI config for: SDW2 Pin2
[   63.679077] intel-sdw intel-sdw.2: ASoC: error at snd_soc_dai_hw_params on SDW2 Pin2: -22
[   63.679107] sdw_deprepare_stream: subdevice #0-Playback: inconsistent state state 1

The name #0-Playback looks odd. Not sure if it's a feature or a memory corruption issue?

[   63.679133]  SDW1-Playback: ASoC: hw_params BE failed -22
[   63.679136]  SDW1-speakers: ASoC: hw_params BE failed -22
[   63.679146] sof-audio-pci 0000:00:1f.3: pcm: free stream 2 dir 0
[   63.679321] rt711 sdw:0:25d:711:0: DPN_PortCtrl register write failed for port 4
[   63.679348] soundwire sdw-master-0: Program transport params failed: -61
[   63.679352] soundwire sdw-master-0: Program params failed: -61
[   63.679355]  SDW0-Playback: ASoC: error at snd_soc_link_prepare on SDW0-Playback: -61
[   63.679359]  SDW0-Playback: ASoC: backend prepare failed -61
[   63.679847] sof-audio-pci 0000:00:1f.3: pcm: free stream 1 dir 1
````

**Comment by plbossart** [comment] 2021-02-09 22:37
I note however that the firmware is, well, was modified by you @juimonen ...

I have no idea what this commit "mux: enable playback of multiple simultaneous streams" does but we do use mux/demux on this device. Do you get this error with 1.6.1?

**Comment by juimonen** [comment] 2021-02-10 06:51
@plbossart, so kernel and fw should be that time "main/masters" so no mods. I've compiled both myself of course. Command to reproduce is script multiple-pipeline-capture.sh in sof-tests. For me it fails always, not randomly. I've also not worked at all on sdw devices, so I might have some config issues etc? The mux patch you mention from me is in master and is totally for mux case, not _demux_ as in this topology (but ok, maybe could affect, not sure).

**Comment by juimonen** [comment] 2021-02-10 06:57
@plbossart so the test is launching 4 separate user space processes with 2 starting playback and 2 starting recording, so the stream building and teardown may come in random order to kernel driver...

**Comment by juimonen** [comment] 2021-02-10 07:26
and I get the same error with 1.6.1 fw...

**Comment by juimonen** [comment] 2021-02-10 07:32
actually I get the error with just whatever aplay command. Do I need to use some different kernel config for this or am I possibly missing something else fundamental for this. fw loads ok, no errors.

**Comment by bardliao** [comment] 2021-02-22 06:25
@juimonen I can't reproduce the issue on my side. I tested on Dell CML sdw laptop SKU 098F.
sof-test multiple-pipeline-capture.sh passed on my side and so does aplay.
[dmesg.txt](https://github.com/thesofproject/linux/files/6019834/dmesg.txt)
My kconfig is https://github.com/thesofproject/kconfig/commit/353642b3d5f53158ca4a822f405b559f5d3b2d3f

**Comment by juimonen** [comment] 2021-02-22 08:00
@bardliao ok thanks, seems that my device has some hw issues, so it is not probably related to this issue at all.. I can't play anything with it.

**Comment by keyonjie** [comment] 2021-03-01 02:44
let's close it @juimonen with hw specific, reopen it if needed.

**Closed as completed by keyonjie** 2021-03-01 02:44 UTC
Labels: bug, CML, SDW, hardware
