### ISSUE TITLE
Playback/Capture can't work on UP^2

### ISSUE THREAD

**Issue by ZhendanYang** [thesofproject/linux#96] opened 2018-08-27 10:27 UTC
Summary:
After booting, there was no error message in dmesg. Then I tried to playback/capture, but playback/capture couldn't work and ipc error occurred.

Environment:
on up^2 with gcc
sof-dev:7481f7af7ac711504ae52fa9ae5cb5c3322ea91f
sof:4aff776d1c290542ded98f8aa22f50d4b9477d37
soft:41861aac373eb1f6978bfdb0bbe97cd882b1785a
tplg:sof-apl-nocodec.tplg
(I tested on sof-dev : c46546120955e049cf1e454f4ba2c7292284aaf0 and there was no such issue)

Log:
[dmesg-up2.log](https://github.com/thesofproject/linux/files/2323387/dmesg-up2.log)
[rmbox-t-up2.log](https://github.com/thesofproject/linux/files/2323388/rmbox-t-up2.log)
[rmbox-up2.log](https://github.com/thesofproject/linux/files/2323389/rmbox-up2.log)

**Comment by ghost** [comment] 2018-08-28 09:06
@lgirdwood 
I added test code like this below in the function sof_route_load()


		sroute->route.source = kstrdup(route->source, GFP_KERNEL);
		if (!sroute->route.source) {
			dev_err(sdev->dev, "==wzg: route soure malloc fail %s\n",sroute->route.source);
			goto err;
		}

		sroute->route.sink = kstrdup(route->sink, GFP_KERNEL);
		if (!sroute->route.sink) {
			dev_err(sdev->dev, "==wzg: route sink malloc fail %s\n",sroute->route.source);
			kfree(sroute->route.source);
			goto err;
		}

		sroute->route.control = kstrdup(route->control, GFP_KERNEL);
		if (!sroute->route.control) {
			dev_err(sdev->dev, "==wzg: route control malloc fail %s\n",sroute->route.source);
			kfree(sroute->route.source);
			kfree(sroute->route.sink);
			goto err;
		}

I got the log:  "route control malloc fail .....".
It is strange. I do not know why this would happen.
It seems it failed many times.

**Comment by ghost** [comment] 2018-08-28 09:31
@lgirdwood 
I found the root cause of this PR #80 
I will send another fix for this issue.

**Comment by ghost** [comment] 2018-08-28 10:00
@lgirdwood 
The root cause is: the upper function will sometimes set the route->control pointer = NULL.
then in the sof_route_load() function, it will malloc failure. the error will happen. the route is not added
into the list. the IPC error will happen.

**Comment by ghost** [comment] 2018-08-28 11:23
fixed by the PR #99

**Closed as completed** 2018-08-31 06:46 UTC
