### ISSUE TITLE
[S3] Audio open error: Device or resource busy after suspend/resume cycles on APL UP^2 PCM512X platform. 

### ISSUE THREAD

**Issue by Jiangxinx** [thesofproject/linux#848] opened 2019-04-19 08:33 UTC
***Summary***
Audio open error: Device or resource busy after suspend/resume on APL-UP2-pcm512x.
Dmesg and sof-logger have no abvious error trace.

***To Reproduce***
1.aplay -Dhw:0,0 -fS16_LE -c2 -r48000 /dev/zero& sudo ~/test/stress-s3.sh 50 1 1

***Screenshots or console output***
```
System will suspend after 4 seconds ...
system will resume after 2 seconds ...
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 19 15:22:59 2019
Suspended. Trying resume. Failed. Restarting stream. Done.
---- test 48 of 50 ----
System will suspend after 2 seconds ...
system will resume after 5 seconds ...
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 19 15:23:11 2019
Suspended. Trying resume. Failed. Restarting stream. Done.
---- test 49 of 50 ----
System will suspend after 4 seconds ...
system will resume after 4 seconds ...
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 19 15:23:24 2019
Suspended. Trying resume. Failed. Restarting stream. Done.
---- test 50 of 50 ----
System will suspend after 1 seconds ...
system will resume after 5 seconds ...
rtcwake: assuming RTC uses UTC ...
rtcwake: wakeup from "mem" using /dev/rtc0 at Fri Apr 19 15:23:35 2019
Suspended. Trying resume. Failed. Restarting stream. Done.
```

```
 #test@cd-apl-up2-pcm512x-02:~/test$ aplay -Dhw:0,0 -fS16_LE -c2 -r48000 /dev/zero
aplay: main:788: audio open error: Device or resource busy
```

```
test@cd-apl-up2-pcm512x-02:~/test$ fuser /dev/snd/*
/dev/snd/pcmC0D0p:    4355m
test@cd-apl-up2-pcm512x-02:~/test$ ps -ax | grep 4355
 4355 pts/0    S      0:05 aplay -Dhw:0,0 -fS16_LE -c2 -r48000 /dev/zero
 6444 pts/0    R+     0:00 grep --color=auto 4355
```

***Dmesg***
```
[  985.490887] sof-audio-pci 0000:00:0e.0: ipc tx: 0x80010000: GLB_DAI_MSG: CONFIG
[  985.490967] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x80010000: GLB_DAI_MSG: CONFIG
[  985.490973] sof-audio-pci 0000:00:0e.0: tplg: complete pipeline PIPELINE.4.HDA2.OUT id 23
[  985.490978] sof-audio-pci 0000:00:0e.0: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491124] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491129] sof-audio-pci 0000:00:0e.0: tplg: complete pipeline PIPELINE.3.HDA1.OUT id 17
[  985.491134] sof-audio-pci 0000:00:0e.0: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491217] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491222] sof-audio-pci 0000:00:0e.0: tplg: complete pipeline PIPELINE.2.HDA0.OUT id 11
[  985.491227] sof-audio-pci 0000:00:0e.0: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491298] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491303] sof-audio-pci 0000:00:0e.0: tplg: complete pipeline PIPELINE.1.SSP5.OUT id 5
[  985.491308] sof-audio-pci 0000:00:0e.0: ipc tx: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491380] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x30130000: GLB_TPLG_MSG: PIPE_COMPLETE
[  985.491389] sof-audio-pci 0000:00:0e.0: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491487] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491495] sof-audio-pci 0000:00:0e.0: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491621] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491630] sof-audio-pci 0000:00:0e.0: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491752] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491761] sof-audio-pci 0000:00:0e.0: ipc tx: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491880] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x50010000: GLB_COMP_MSG: SET_VALUE: SET_VALUE
[  985.491889] sof-audio-pci 0000:00:0e.0: ipc tx: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  985.491946] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  985.492075] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 5:0
[  985.492118] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 6:0
[  985.492130] HDMI HDA Codec ehdaudio0D2: hdac_hdmi_present_sense: disconnect for pin:port 7:0
[  985.492782] OOM killer enabled.
[  985.492784] Restarting tasks ... done.
[  985.498552] video LNXVIDEO:00: Restoring backlight state
[  985.498568] PM: suspend exit
[  985.519013] sof-audio-pci 0000:00:0e.0: pcm: prepare stream 0 dir 0
[  985.519017] sof-audio-pci 0000:00:0e.0: pcm: hw params stream 0 dir 0
[  985.519038] sof-audio-pci 0000:00:0e.0: period_bytes:0x3fc0
[  985.519039] sof-audio-pci 0000:00:0e.0: periods:4
[  985.519048] sof-audio-pci 0000:00:0e.0: stream_tag 1
[  985.519055] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  985.519207] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  985.519210] sof-audio-pci 0000:00:0e.0: pcm: stream dir 0, posn mailbox offset is 790528
[  985.519328] sof-audio-pci 0000:00:0e.0: pcm: trigger stream 0 dir 0 cmd 1
[  985.519334] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  985.519601] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
[  985.646513] ata2: SATA link down (SStatus 4 SControl 300)
[  985.646553] ata1: SATA link down (SStatus 4 SControl 300)
[  985.993533] sof-audio-pci 0000:00:0e.0: ipc rx: 0x90020000: GLB_TRACE_MSG
[  985.993548] sof-audio-pci 0000:00:0e.0: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  986.493523] sof-audio-pci 0000:00:0e.0: ipc rx: 0x90020000: GLB_TRACE_MSG
[  986.493535] sof-audio-pci 0000:00:0e.0: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  987.552435] r8169 0000:02:00.0 enp2s0: Link is Up - 100Mbps/Full - flow control rx/tx   
```

***Environment***
sof master: 50bd96de
kernel sof-dev: 90860434
tplg:  #sof-apl-pcm512x.tplg

**Comment by Jiangxinx** [comment] 2019-04-19 09:02
#1241

**Comment by wenqingfu** [comment] 2019-04-20 03:11
Quoted from @lgirdwood  from https://github.com/thesofproject/sof/issues/1241#issuecomment-484484684 to make up the whole context

---

@Jiangxinx can you log this as a kernel bug, link to this one and close this issue.

@plbossart @ranj063 @kv2019i this looks like a kernel race where aplay will hang on to the PCM (and keep it BUSY), it could be that PM works when the aplay PCM is in playing state but may not when the PCM is in hw_free(), hw_params() or prepare() state ? This may prevent aplay from close()ing the PCM device.

The log below shows driver stopping the stream, but do we check the PCM state prior to STOP ?

**Comment by stevyan** [comment] 2019-04-22 08:25
Actually, 'Device busy' is not original error info.  "I/O error" occurred at #1241 on that daily version (2019-04-09) refer to log fragment:

```
underrun!!! (at least 0.015 ms long)
aplay: pcm_write:2011: write error: Input/output error
aplay doesn't exist!
```
But, recently, 'I/O error' doesn't reproduce. Regarding to 'Device Busy', due to the 'aplay' is already running at background before S3, hence, when try to 'aplay' again with the same PCM pipeline after S3, 'Device Busy' seems be correct response behavior, is it right? @lgirdwood

**Summary**
'I/O' error isn't reproduced, 'Device Busy' can be seen when try to 'aplay' twice at the same time on UP2 PCM512x.

**Test Recipe**
date: 2019-04-22
sof master: 0c93261
kernel sof-dev: 90860434
tplg: sof-apl-pcm512x.tplg

**Comment by stevyan** [comment] 2019-04-23 07:21
Invalid issue, closed.

**Closed as completed by stevyan** 2019-04-23 07:21 UTC
Labels: bug, APL, suspend resume
