### ISSUE TITLE
Send time since boot to the firmware upon resume

### ISSUE THREAD

**Issue by ranj063** [thesofproject/linux#41] opened 2018-07-19 20:59 UTC
This issue complements https://github.com/thesofproject/sof/issues/130
to send the time offset to the firmware from the kernel

**Comment by bardliao** [comment] 2018-09-11 02:07
@ranj063 Which board and branch did you test? I am working on UP2 board and SOF firmware will get error after suspend/resume. Also, the /sys/kernel/debug/sof/trace file will be empty after suspend/resume. It implies that rmbox -t will show nothing.

**Comment by bardliao** [comment] 2019-03-01 07:38
Close it as we are using sof-logger now

**Comment by plbossart** [comment] 2019-03-01 16:43
On 3/1/19 1:38 AM, Bard Liao wrote:
>
> Close it as we are using sof-logger now
>
I am not clear as to how sof-logger solves the issues of timestamps not 
being aligned between host and firmware. If there is no IPC to pass the 
system time on resume, then the timestamps generated by the firmware 
will not be aligned and will restart at zero.

What am I missing?

**Comment by bardliao** [comment] 2019-03-04 10:13
@plbossart If I recall it correctly, the issue is for rmbox. The main issue is that the log will be clean after runtime suspend. But it seems no one complain about that on sof-logger. It can be reopen if we still need this feature.

**Comment by plbossart** [comment] 2019-03-04 17:11
@bardliao the requirement is the same regardless of the tool.
@ranj063 do we send the time on a resume?

**Comment by ranj063** [comment] 2019-03-04 17:13
@plbossart @bardliao yes, this issue remains irrespective of the tool and yes we do need the feature so we can align the time stamps between the kernel and the fw

**Comment by plbossart** [comment] 2019-03-24 18:20
@bardliao are you working on this or do we need to ask @mengdonglin to assign someone else. This is a simple problem that should be fixed.

**Comment by bardliao** [comment] 2019-03-25 09:07
@plbossart Yes, I can do it.

**Comment by bardliao** [comment] 2019-03-25 14:04
@plbossart @ranj063 I guess we can send jiffies to align the time stamps. But how do we handle the clock difference between kernel and firmware? e.g. 1000 on kernel and 19.2M on FW.

**Comment by bardliao** [comment] 2019-03-26 12:39
@plbossart @ranj063 My idea is that save the value of jiffies when SOF_IPC_PM_CTX_SAVE ipc is sent and send the delta to FW in resume (trace init). The delta should be converted to match the timer clock frequency of FW.  The conversion formula is delta = delta * 1000 / HZ * <FW timer clock rate>; And I will need to get the <FW timer clock rate> via IPC.
Does it make sense?

**Comment by plbossart** [comment] 2019-03-26 15:59
@bardliao I would do the opposite, provide the absolute time on resume. And it'd use the full ns value to avoid ms quantizations

**Comment by bardliao** [comment] 2019-03-27 09:51
@plbossart thanks, it makes more sense to send the absolute time on resume. Regarding to the quantization, I will send the full value of jiffies to FW, but its unit is ms. Actually, it depends on the value of HZ. And I will use clock_ms_to_ticks function to transfer value to ticks. 
I will send RFC for discussion. :)

**Comment by bardliao** [comment] 2019-03-28 06:11
@plbossart @ranj063 I have sent RFC on https://github.com/thesofproject/sof/pull/1194 and https://github.com/thesofproject/linux/pull/756. Could you give me come comments? Thanks.

**Comment by bardliao** [comment] 2019-06-09 14:49
Fixed by https://github.com/thesofproject/linux/pull/756 thesofproject/sof#1194 and https://github.com/thesofproject/sof/pull/1358

**Closed as completed by bardliao** 2019-06-09 14:49 UTC
Labels: enhancement
