### ISSUE TITLE
[BUG][CML] page fault in module reload stress test

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#1471] opened 2019-11-13 03:21 UTC
**Bug Description**
in module reload stress test, there is `rmmod: ERROR: Module snd_sof_intel_byt is in use by: snd_sof_pci` error.

**To Reproduce**
1. disable pulseaudio
2. wait dsp status to suspended
3. run script: `sudo ./sof_bootloop.sh`

**Reproduction Rate**
12th/100, 35th/100

**Platform**
Kernel: sof-dev: `f55db62e`
Sof: master: `835d876b`
tplg: sof-hda-generic-2ch.tplg
platform: dell hda platform with ALC3204 codec

**Terminal output**
```
test 12
Removing snd_sof_pci
./sof_remove.sh: line 5:  6509 Killed                  rmmod $MODULE
Removing snd_sof_acpi
Removing snd_sof_intel_byt
rmmod: ERROR: Module snd_sof_intel_byt is in use by: snd_sof_pci
Removing snd_sof_intel_bdw
Removing snd_sof_intel_hda_common
rmmod: ERROR: Module snd_sof_intel_hda_common is in use by: snd_sof_pci
Removing snd_sof_intel_hda
rmmod: ERROR: Module snd_sof_intel_hda is in use by: snd_sof_intel_hda_common
Removing snd_sof_intel_ipc
rmmod: ERROR: Module snd_sof_intel_ipc is in use by: snd_sof_intel_byt
Removing snd_sof_xtensa_dsp
rmmod: ERROR: Module snd_sof_xtensa_dsp is in use by: snd_sof_pci
Removing snd_soc_acpi_intel_match
rmmod: ERROR: Module snd_soc_acpi_intel_match is in use by: snd_sof_pci snd_sof_intel_hda_common
```
[module_reload_dmesg.log](https://github.com/thesofproject/linux/files/3839273/module_reload_dmesg.log)

**Comment by dengyangchao** [comment] 2019-11-13 08:01
Issue also can reproduce on:
CML Chrome with onboard codec RT5682 in I2S mode
ICL RVP with onboard codec ALC700 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
CFL-S RVP with onboard codec ALC700 in HDA mode
APL UP2 nocodec
APL UP2 with  codec PCM512x in I2S mode
BYT MB nocodec
BYT MB with codec RT5682 in I2S mode

**Environment**
Firmware: 835d876b https://github.com/thesofproject/sof/commits/master
Kernel: f55db62 https://github.com/thesofproject/linux/commits/topic/sof-dev

<details>
 <summary>Dmesg</summary>

````
[  210.138167] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf0f successful
[  210.138171] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[  210.575456] ------------[ cut here ]------------
[  210.575464] WARNING: CPU: 2 PID: 3212 at /srv/home/jenkins/workspace/kernel_build_template/kernel/workqueue.c:3031 __flush_work+0x18b/0x1a0
[  210.575465] Modules linked in: snd_soc_skl_hda_dsp snd_hda_codec_hdmi snd_soc_hdac_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_sof_acpi snd_sof_intel_bdw snd_soc_dmic snd_sof_pci(-) snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof_intel_byt snd_soc_acpi_intel_match snd_sof_intel_ipc snd_sof snd_sof_xtensa_dsp snd_soc_acpi snd_hda_ext_core snd_hda_codec snd_hda_core snd_soc_pcm512x_i2c snd_soc_pcm512x snd_soc_da7213 snd_soc_rt5640 snd_soc_rt5651 snd_soc_rt5645 snd_soc_rt5670 snd_soc_rl6231 snd_soc_core snd_pcm asix usbnet snd_intel_dspcfg snd_hwdep wmi_bmof snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq iwlmvm i915 snd_seq_device snd_timer snd x86_pkg_temp_thermal i2c_algo_bit intel_powerclamp drm_kms_helper soundcore syscopyarea sysfillrect sysimgblt fb_sys_fops drm iwlwifi intel_lpss_pci mei_me intel_lpss processor_thermal_device mei mfd_core int340x_thermal_zone intel_soc_dts_iosf wmi int3400_thermal acpi_thermal_rel efivarfs sdhci_pci xhci_pci cqhci
[  210.575499]  sdhci xhci_hcd [last unloaded: snd_pcm]
[  210.575504] CPU: 2 PID: 3212 Comm: rmmod Not tainted 5.4.0-rc7-daily-default-20191113 #f55db62e
[  210.575505] Hardware name: Intel Corporation Ice Lake Client Platform/IceLake U DDR4 SODIMM PD RVP TLC, BIOS ICLSFWR1.R00.3294.A01.1907260027 07/26/2019
[  210.575508] RIP: 0010:__flush_work+0x18b/0x1a0
[  210.575510] Code: 3b 8d 8d 00 b8 01 00 00 00 e9 0a ff ff ff 8b 4d 00 48 8b 55 08 83 e1 08 48 0f ba 6d 00 03 80 c9 f0 eb c6 0f 0b e9 ee fe ff ff <0f> 0b 31 c0 e9 e5 fe ff ff e8 c7 30 fe ff 0f 1f 80 00 00 00 00 31
[  210.575512] RSP: 0018:ffff9775414b3b40 EFLAGS: 00010246
[  210.575514] RAX: 0000000000000000 RBX: ffff9670dbc50000 RCX: 0000000000000000
[  210.575515] RDX: 0000000000000001 RSI: 0000000000000000 RDI: ffff967071c3be38
[  210.575516] RBP: ffff967071c3be38 R08: 0000000000000000 R09: ffffffffc0495a00
[  210.575517] R10: ffff96707c853cc0 R11: 0000000000000001 R12: ffff9670cfc1b1a0
[  210.575518] R13: ffff9670cfc1b000 R14: ffff9670cfe3aeb0 R15: 0000000000000003
[  210.575520] FS:  00007fc6ac2c5540(0000) GS:ffff9670dfe80000(0000) knlGS:0000000000000000
[  210.575521] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  210.575523] CR2: 00005644f8a0e060 CR3: 000000043d2aa004 CR4: 0000000000760ee0
[  210.575524] PKRU: 55555554
[  210.575524] Call Trace:
[  210.575532]  ? try_to_del_timer_sync+0x48/0x70
[  210.575541]  soc_pcm_private_free+0x17/0x20 [snd_soc_core]
[  210.575547]  snd_pcm_free+0x1a/0x50 [snd_pcm]
[  210.575552]  __snd_device_free+0x41/0x70 [snd]
[  210.575557]  snd_device_free_all+0x36/0x80 [snd]
[  210.575560]  release_card_device+0x14/0x60 [snd]
[  210.575565]  device_release+0x22/0x80
[  210.575570]  kobject_put+0x84/0x1b0
[  210.575575]  snd_card_free+0x60/0x90 [snd]
[  210.575581]  soc_cleanup_card_resources+0xc2/0x2e0 [snd_soc_core]
[  210.575588]  snd_soc_unbind_card+0x9b/0xe0 [snd_soc_core]
[  210.575593]  snd_soc_unregister_card+0x1d/0x60 [snd_soc_core]
[  210.575597]  release_nodes+0x121/0x220
[  210.575601]  device_release_driver_internal+0xf0/0x1c0
[  210.575604]  bus_remove_device+0xd6/0x140
[  210.575607]  device_del+0x15f/0x380
[  210.575609]  ? iommu_need_mapping+0x54/0xd0
[  210.575613]  platform_device_del.part.15+0xe/0x60
[  210.575617]  platform_device_unregister+0x17/0x30
[  210.575620]  snd_sof_device_remove+0x50/0x90 [snd_sof]
[  210.575624]  sof_pci_remove+0x10/0x30 [snd_sof_pci]
[  210.575627]  pci_device_remove+0x36/0xb0
[  210.575630]  device_release_driver_internal+0xe0/0x1c0
[  210.575632]  driver_detach+0x3a/0x80
[  210.575635]  bus_remove_driver+0x53/0xd0
[  210.575639]  pci_unregister_driver+0x1d/0x90
[  210.575643]  __x64_sys_delete_module+0x155/0x240
[  210.575646]  do_syscall_64+0x43/0x120
[  210.575650]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  210.575652] RIP: 0033:0x7fc6abde41b7
[  210.575655] Code: 73 01 c3 48 8b 0d d1 8c 2c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 b8 b0 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d a1 8c 2c 00 f7 d8 64 89 01 48
[  210.575656] RSP: 002b:00007ffc4b1341a8 EFLAGS: 00000206 ORIG_RAX: 00000000000000b0
[  210.575658] RAX: ffffffffffffffda RBX: 00007ffc4b134208 RCX: 00007fc6abde41b7
[  210.575659] RDX: 000000000000000a RSI: 0000000000000800 RDI: 000055d640d287f8
[  210.575660] RBP: 000055d640d28790 R08: 00007ffc4b133121 R09: 0000000000000000
[  210.575662] R10: 00007fc6abe60cc0 R11: 0000000000000206 R12: 00007ffc4b1343d0
[  210.575663] R13: 00007ffc4b1346fd R14: 000055d640d28260 R15: 000055d640d28790
[  210.575665] ---[ end trace 77e9f9cd49566de0 ]---
[  210.575671] BUG: unable to handle page fault for address: fffffffffffffff8
[  210.575675] #PF: supervisor read access in kernel mode
[  210.575677] #PF: error_code(0x0000) - not-present page
[  210.575679] PGD 46cc0c067 P4D 46cc0c067 PUD 46cc0e067 PMD 0 
[  210.575684] Oops: 0000 [#1] SMP NOPTI
[  210.575687] CPU: 2 PID: 3212 Comm: rmmod Tainted: G        W         5.4.0-rc7-daily-default-20191113 #f55db62e
[  210.575688] Hardware name: Intel Corporation Ice Lake Client Platform/IceLake U DDR4 SODIMM PD RVP TLC, BIOS ICLSFWR1.R00.3294.A01.1907260027 07/26/2019
[  210.575696] RIP: 0010:snd_soc_pcm_component_free+0x49/0x60 [snd_soc_core]
[  210.575698] Code: 8d 58 f8 49 89 fc eb 22 48 8b 47 60 48 8b 40 70 48 85 c0 74 08 4c 89 e6 e8 74 7e 18 ca 48 8b 43 08 48 39 c5 48 8d 58 f8 74 09 <48> 8b 78 f8 48 85 ff 75 d5 5b 5d 41 5c c3 66 0f 1f 84 00 00 00 00
[  210.575700] RSP: 0018:ffff9775414b3ba8 EFLAGS: 00010282
[  210.575703] RAX: 0000000000000000 RBX: fffffffffffffff8 RCX: 0000000000000000
[  210.575704] RDX: 0000000000000001 RSI: 0000000000000000 RDI: ffff9670dbc50000
[  210.575706] RBP: ffff967071c3beb0 R08: 0000000000000000 R09: ffffffffc0495a00
[  210.575707] R10: ffff96707c853cc0 R11: 0000000000000001 R12: ffff9670dbc50000
[  210.575709] R13: ffff9670cfc1b000 R14: ffff9670cfe3aeb0 R15: 0000000000000003
[  210.575711] FS:  00007fc6ac2c5540(0000) GS:ffff9670dfe80000(0000) knlGS:0000000000000000
[  210.575713] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  210.575715] CR2: fffffffffffffff8 CR3: 000000043d2aa004 CR4: 0000000000760ee0
[  210.575716] PKRU: 55555554
[  210.575717] Call Trace:
[  210.575722]  snd_pcm_free+0x1a/0x50 [snd_pcm]
[  210.575727]  __snd_device_free+0x41/0x70 [snd]
[  210.575732]  snd_device_free_all+0x36/0x80 [snd]
[  210.575736]  release_card_device+0x14/0x60 [snd]
[  210.575741]  device_release+0x22/0x80
[  210.575746]  kobject_put+0x84/0x1b0
[  210.575752]  snd_card_free+0x60/0x90 [snd]
[  210.575761]  soc_cleanup_card_resources+0xc2/0x2e0 [snd_soc_core]
[  210.575767]  snd_soc_unbind_card+0x9b/0xe0 [snd_soc_core]
[  210.575773]  snd_soc_unregister_card+0x1d/0x60 [snd_soc_core]
[  210.575777]  release_nodes+0x121/0x220
[  210.575781]  device_release_driver_internal+0xf0/0x1c0
[  210.575783]  bus_remove_device+0xd6/0x140
[  210.575787]  device_del+0x15f/0x380
[  210.575789]  ? iommu_need_mapping+0x54/0xd0
[  210.575793]  platform_device_del.part.15+0xe/0x60
[  210.575797]  platform_device_unregister+0x17/0x30
[  210.575800]  snd_sof_device_remove+0x50/0x90 [snd_sof]
[  210.575804]  sof_pci_remove+0x10/0x30 [snd_sof_pci]
[  210.575806]  pci_device_remove+0x36/0xb0
[  210.575809]  device_release_driver_internal+0xe0/0x1c0
[  210.575812]  driver_detach+0x3a/0x80
[  210.575815]  bus_remove_driver+0x53/0xd0
[  210.575819]  pci_unregister_driver+0x1d/0x90
[  210.575823]  __x64_sys_delete_module+0x155/0x240
[  210.575826]  do_syscall_64+0x43/0x120
[  210.575829]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  210.575831] RIP: 0033:0x7fc6abde41b7
[  210.575834] Code: 73 01 c3 48 8b 0d d1 8c 2c 00 f7 d8 64 89 01 48 83 c8 ff c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 b8 b0 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d a1 8c 2c 00 f7 d8 64 89 01 48
[  210.575836] RSP: 002b:00007ffc4b1341a8 EFLAGS: 00000206 ORIG_RAX: 00000000000000b0
[  210.575838] RAX: ffffffffffffffda RBX: 00007ffc4b134208 RCX: 00007fc6abde41b7
[  210.575840] RDX: 000000000000000a RSI: 0000000000000800 RDI: 000055d640d287f8
[  210.575842] RBP: 000055d640d28790 R08: 00007ffc4b133121 R09: 0000000000000000
[  210.575843] R10: 00007fc6abe60cc0 R11: 0000000000000206 R12: 00007ffc4b1343d0
[  210.575845] R13: 00007ffc4b1346fd R14: 000055d640d28260 R15: 000055d640d28790
[  210.575847] Modules linked in: snd_soc_skl_hda_dsp snd_hda_codec_hdmi snd_soc_hdac_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_sof_acpi snd_sof_intel_bdw snd_soc_dmic snd_sof_pci(-) snd_sof_intel_hda_common snd_soc_hdac_hda snd_sof_intel_hda snd_sof_intel_byt snd_soc_acpi_intel_match snd_sof_intel_ipc snd_sof snd_sof_xtensa_dsp snd_soc_acpi snd_hda_ext_core snd_hda_codec snd_hda_core snd_soc_pcm512x_i2c snd_soc_pcm512x snd_soc_da7213 snd_soc_rt5640 snd_soc_rt5651 snd_soc_rt5645 snd_soc_rt5670 snd_soc_rl6231 snd_soc_core snd_pcm asix usbnet snd_intel_dspcfg snd_hwdep wmi_bmof snd_seq_midi snd_seq_midi_event snd_rawmidi snd_seq iwlmvm i915 snd_seq_device snd_timer snd x86_pkg_temp_thermal i2c_algo_bit intel_powerclamp drm_kms_helper soundcore syscopyarea sysfillrect sysimgblt fb_sys_fops drm iwlwifi intel_lpss_pci mei_me intel_lpss processor_thermal_device mei mfd_core int340x_thermal_zone intel_soc_dts_iosf wmi int3400_thermal acpi_thermal_rel efivarfs sdhci_pci xhci_pci cqhci
[  210.575871]  sdhci xhci_hcd [last unloaded: snd_pcm]
[  210.575878] CR2: fffffffffffffff8
[  210.575880] ---[ end trace 77e9f9cd49566de1 ]---
[  210.575887] RIP: 0010:snd_soc_pcm_component_free+0x49/0x60 [snd_soc_core]
[  210.575889] Code: 8d 58 f8 49 89 fc eb 22 48 8b 47 60 48 8b 40 70 48 85 c0 74 08 4c 89 e6 e8 74 7e 18 ca 48 8b 43 08 48 39 c5 48 8d 58 f8 74 09 <48> 8b 78 f8 48 85 ff 75 d5 5b 5d 41 5c c3 66 0f 1f 84 00 00 00 00
[  210.575891] RSP: 0018:ffff9775414b3ba8 EFLAGS: 00010282
[  210.575893] RAX: 0000000000000000 RBX: fffffffffffffff8 RCX: 0000000000000000
[  210.575895] RDX: 0000000000000001 RSI: 0000000000000000 RDI: ffff9670dbc50000
[  210.575896] RBP: ffff967071c3beb0 R08: 0000000000000000 R09: ffffffffc0495a00
[  210.575898] R10: ffff96707c853cc0 R11: 0000000000000001 R12: ffff9670dbc50000
[  210.575900] R13: ffff9670cfc1b000 R14: ffff9670cfe3aeb0 R15: 0000000000000003
[  210.575902] FS:  00007fc6ac2c5540(0000) GS:ffff9670dfe80000(0000) knlGS:0000000000000000
[  210.575904] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  210.575905] CR2: fffffffffffffff8 CR3: 000000043d2aa004 CR4: 0000000000760ee0
[  210.575907] PKRU: 55555554
````
</details>

[dmesg.log](https://github.com/thesofproject/linux/files/3839960/dmesg.log)

**Comment by plbossart** [comment] 2019-11-13 17:02
known issue fixed by https://github.com/thesofproject/linux/pull/1469

please try with this PR

**Comment by dengyangchao** [comment] 2019-11-15 01:35
Applied #1469,  and tried 100 times on CFL-S RVP with onboard codec ALC700 in HDA mode
issue can't reproduce.

**Comment by Liviali155** [comment] 2019-11-22 09:25
Error not seen on 
CML Chrome with onboard codec RT5682 in I2S mode
ICL RVP with onboard codec ALC700 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
CFL-S RVP with onboard codec ALC700 in HDA mode
CML Mantis with onboard codec ALC3204 in HDA mode
CML Helios with onboard codec RT5682 in I2S mode
APL UP2 nocodec
APL UP2 with codec PCM512x in I2S mode
BYT MB nocodec
BYT MB with codec RT5682 in I2S mode

Environment
Firmware: 9b5dc8c6 https://github.com/thesofproject/sof/commits/master
Kernel: bc30957c https://github.com/thesofproject/linux/commits/topic/sof-dev

**Comment by Liviali155** [comment] 2019-11-22 09:28
closed

**Closed as completed** 2019-11-22 09:27 UTC
Labels: bug, BYT, APL, GLK, ICL, CML, CFL
