### ISSUE TITLE
[BUG]Microphone can be detected but doesn't work 

### ISSUE THREAD

**Issue by johnysh** [thesofproject/linux#4033] opened 2022-11-21 07:50 UTC
**Describe the bug**
The microphone can be detected , but it doesn't work , records no sound, only has  one "pop" noise. Audio playback appears to be working and headset can be used to record and play normally . I did some attempt   to modify alsa-base.conf , added these lines 
       options snd-intel-dspcfg dsp_driver=3
 or  options snd_sof_intel_hda_common dmic_num=4 to check which PDM it connects , but any channel has waveform.

      
**To Reproduce**
sudo arecord -Dhw:0,6 -c2 -r48000 -fS32_LE -d 10 test6.wav -vvv

**Reproduction Rate**
100%

**Expected behavior
Dmic can work and used for record  

**Impact**

I can't use the built in microphone for video conferencing. 

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel:  Linux junhan 5.15.64-for-audio thesofproject/sof#9 SMP Fri Oct 21 15:09:55 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
    * OS:  ubuntu22.04.1-LTS
    * SOF:  I'm not quite sure, I used debug-key signed firmware for debugging.
   
2) Name of the topology file
    * Topology:  default 
3) Name of the platform(s) on which the bug is observed.
    * Platform:  
          CPU : ADL-N 
          audio codec :   Conexant  SN6140 

**Screenshots or console output**

inxi -A 
Audio:
  Device-1: Intel driver: N/A
  Device-2: Intel driver: sof-audio-pci-intel-tgl
  Sound Server-1: ALSA v: k5.15.64-for-audio running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes

unhan@junhan:~$ arecord -l 
**** List of CAPTURE Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: DMIC (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: DMIC16kHz (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

![Screenshot 2022-11-21 154723](https://user-images.githubusercontent.com/15604431/202993618-43834695-91c5-46f4-8a75-cf86ed9dcaa5.png)
![Screenshot 2022-11-21 155008](https://user-images.githubusercontent.com/15604431/202994150-5a81c375-4efe-448b-824e-0dec458f6c26.png)
![Screenshot 2022-11-21 155024](https://user-images.githubusercontent.com/15604431/202994164-8172dbcf-5d39-441e-aa50-ea5a2df64066.png)
[dmesg_for_mic_1121.txt](https://github.com/thesofproject/sof/files/10054454/dmesg_for_mic_1121.txt)

**Comment by lgirdwood** [comment] 2022-11-21 14:24
@plbossart @bardliao HDA verbs ? Looks like the pop captured could be the ADC being switched on ?

**Comment by johnysh** [comment] 2022-11-22 07:54
confirmed with our hardware engineer, DMIC is connected to PDM1, I used this link reference PDM1 topology (https://github.com/thesofproject/linux/issues/2460), but it still doesn't work.

**Comment by bardliao** [comment] 2022-11-22 11:05
@lgirdwood I think the `DMIC` device is for PCH DMIC, not the DMIC via HDA codec. I am wondering if the topology matches @johnysh's HW configuration. @johnysh Do you have the audio subsystem diagram of your device?

**Comment by bigrammy** [comment] 2022-11-22 22:00
Same issue using Asus X515JA Intel Core i3
`dmesg | grep snd
[    2.250274] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    2.250280] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    2.907216] usbcore: registered new interface driver snd-usb-audio
`
`bigrammy@asus ~ $ dmesg | grep -i sof
[    0.530980] PCI-DMA: Using software bounce buffering for IO (SWIOTLB)
[    0.530981] software IO TLB: mapped [mem 0x0000000063774000-0x0000000067774000] (64MB)
[    2.250280] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    2.275173] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    2.275180] sof-audio-pci-intel-icl 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    2.275196] sof-audio-pci-intel-icl 0000:00:1f.3: enabling device (0000 -> 0002)
[    2.275323] sof-audio-pci-intel-icl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[    2.281136] sof-audio-pci-intel-icl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    2.287764] sof-audio-pci-intel-icl 0000:00:1f.3: use msi interrupt mode
[    2.309121] sof-audio-pci-intel-icl 0000:00:1f.3: hda codecs found, mask 4
[    2.309189] sof-audio-pci-intel-icl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    2.309194] sof-audio-pci-intel-icl 0000:00:1f.3: DMICs detected in NHLT tables: 2
[    2.311957] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    2.311960] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:18:0
[    2.311962] sof-audio-pci-intel-icl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    2.311967] sof-audio-pci-intel-icl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    2.408880] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware info: version 2:2:0-57864
[    2.408887] sof-audio-pci-intel-icl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:18:0
[    2.408889] sof-audio-pci-intel-icl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    2.412083] sof-audio-pci-intel-icl 0000:00:1f.3: Topology: ABI 3:22:1 Kernel ABI 3:18:0
[    2.412088] sof-audio-pci-intel-icl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    2.423260] sof-audio-pci-intel-icl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    2.444092] input: sof-hda-dsp HDMI/DP,pcm=1 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input9
[    2.444128] input: sof-hda-dsp HDMI/DP,pcm=2 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input10
[    2.444159] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input11
`

**Comment by johnysh** [comment] 2022-11-23 01:34
> @lgirdwood I think the `DMIC` device is for PCH DMIC, not the DMIC via HDA codec. I am wondering if the topology matches @johnysh's HW configuration. @johnysh Do you have the audio subsystem diagram of your device?

Yes , it is PCH DMIC , pls check this file for audio subsystem.

**Comment by bardliao** [comment] 2022-11-23 06:16
@johnysh U1 CX11880-11Z and U2 M_CODEC are codecs, and DMIC is connected to the codecs. And the codec sends DMIC through HDA to SoC. Lust like how headset connect.
Like
```
     DMIC -> Codec -> HDA -> CUP
           |               
  Headset->
```
Am I correct?
If so, the topology doesn't fit your HW configuration.
The codec may provide alsa mixer control to switch codec input from headset mic to DMIC. Can you contact with Codec vendor to get the alsa mixer setting?

**Comment by bardliao** [comment] 2022-11-23 06:53
@lgirdwood I just chatted with @johnysh. The DMIC is directly connected to CPU, not through codec. So, there is nothing to do on HDA verb. He will measure if DMIC clock is enabled.

**Comment by johnysh** [comment] 2022-11-23 08:03
@bardliao I confirmed with internal engineer , DMIC  clock source  doesn't connect to  external crystal oscillator，and  connects to PCH clk source ,  but I'm not sure which is.

**Comment by bardliao** [comment] 2022-11-23 12:32
@johnysh Can you try with "options snd-intel-dspcfg dsp_driver=1"?

**Comment by johnysh** [comment] 2022-11-24 01:28
@bardliao 
update ""options snd-intel-dspcfg dsp_driver=1" , it still doesn't work.
junhan@junhan:~$ arecord -l 
**** List of CAPTURE Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: SN6140 Analog [SN6140 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

junhan@junhan:~$ inxi -A 
Audio:
  Device-1: Intel driver: N/A
  Device-2: Intel driver: snd_hda_intel
  Sound Server-1: ALSA v: k5.15.64-for-mrd running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
[dmesg_for_dspcfg1_1124.txt](https://github.com/thesofproject/linux/files/10080141/dmesg_for_dspcfg1_1124.txt)

**Comment by johnysh** [comment] 2022-11-24 08:05
@bardliao I tested the DMIC CLK with oscilloscope , there is no waveform. I think DMIC clk isn't enable.

**Comment by bardliao** [comment] 2022-11-24 08:13
> @bardliao I tested the DMIC CLK with oscilloscope , there is no waveform. I think DMIC clk isn't enable.

@juimonen @singalsu Do you know what problem it might be?

**Comment by plbossart** [comment] 2022-11-28 17:37
@johnysh can you confirm that you have 2 microphones connected to PDM1?

If yes, that's a known issue with the topology that assumes the use of PDM0. You would need to explicitly change the topology name to be sof-hda-generic-2ch-pdm1.tplg

options snd-sof-pci tplg_filename=sof-hda-generic-2ch-pdm1.tplg

this may require a kernel and sof-bin update, I don't remember when we added this option and when we added those options.

**Comment by johnysh** [comment] 2022-11-29 03:46
@plbossart There has dual mic  connected to PDM1.  I use this topology (https://github.com/thesofproject/linux/files/5981682/sof-hda-generic-2ch-pdm1.zip) and add options  in alsa.conf, but it shows error.
junhan@junhan:~$ sudo dmesg | grep snd
[sudo] password for junhan: 
[    4.403951] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[    4.404001] snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver
[    4.845198] **snd_sof_pci: unknown parameter 'tplg_filename' ignored**
[    6.554768] sjh: register driver name =snd_hda_codec_generic
[    6.562656] sjh: register driver name =snd_hda_codec_conexant
[    7.205399] sjh: register driver name =snd_hda_codec_hdmi
[    7.416935] snd_hda_codec_conexant ehdaudio0D0: SN6140: BIOS auto-probing.
[    7.417529] snd_hda_codec_conexant ehdaudio0D0: autoconfig for SN6140: line_outs=1 (0x17/0x0/0x0/0x0/0x0) type:speaker
[    7.417540] snd_hda_codec_conexant ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    7.417544] snd_hda_codec_conexant ehdaudio0D0:    hp_outs=1 (0x16/0x0/0x0/0x0/0x0)
[    7.417548] snd_hda_codec_conexant ehdaudio0D0:    mono: mono_out=0x0
[    7.417550] snd_hda_codec_conexant ehdaudio0D0:    inputs:
[    7.417553] snd_hda_codec_conexant ehdaudio0D0:      Mic=0x19
[    7.423963] snd_hda_codec_conexant ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[    7.423978] snd_hda_codec_conexant ehdaudio0D0: ASoC: source widget AIF1RX overwritten

and reference this link (https://thesofproject.github.io/latest/getting_started/intel_debug/suggestions.html#digital-mic-issues)
 override the file installed in /lib/firmware/intel/sof-tplg/sof-hda-generic-2ch.tplg , it is not useful. I think we should first enable dmic clock .

**Comment by singalsu** [comment] 2022-11-29 10:24
If the kernel is not new enough to support tplg_filename, then overwrite the topology that gets loaded (sof-hda-generic-2ch.tplg?)  with file sof-hda-generic-2ch-pdm1.tplg. If the clock line is still not active and no incoming PDM data bits, then the issue is in clock start. But can you please first check overwrite the topoloogy, or get a more recent kernel.

**Comment by plbossart** [comment] 2022-11-29 17:10
@johnysh your answers are a bit confusing. Can you please override the topology with the unzipped file:

cp /lib/firmware/intel/sof-tplg/sof-hda-generic-2ch-pdm1.tplg /lib/firmware/intel/sof-tplg/sof-hda-generic-2ch.tplg

then copy this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/10115427/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf, reboot and attach the dmesg log.

**Comment by johnysh** [comment] 2022-11-30 06:29
@plbossart @singalsu I get  a new P1 device and  sof-v2.2.3 fw , after override the topology, it works well. Before that , I used an old P0 device. It seems to be a  fw ,tplg and device compatibility problem. We will use this new device to debug ,and issue can be solved.  
[dmesg_pdm1_1130.txt](https://github.com/thesofproject/linux/files/10119795/dmesg_pdm1_1130.txt)

**Comment by plbossart** [comment] 2022-11-30 13:41
I'll close this issue @johnysh. If there is anything else on this platform please reopen a new bug.

**Closed as completed by plbossart** 2022-11-30 13:41 UTC
Labels: bug, dmic, ADL, DMIC-PDM1
