### ISSUE TITLE
[BUG][CML]Headset mic boost and Headphone mic boost are listed in F3 playback view via alsamixer

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#867] opened 2019-04-25 03:06 UTC
**Describe the bug**
Headset mic boost and Headphone mic boost are listed in F3 playback view via alsamixer

**To Reproduce**
alsamixer, check F3 playback view.

**Expected behavior**
Headset mic boost and Headphone mic boost shouldn't list in playback view.

**Environment**
Kernel repo | https://github.com/RanderWang/linux/tree/cml-validation-20190424
Made from:
2e94569 [thesofproject/linux: topic/sof-dev]

85a86d9 [RanderWang/linux: cml-validation-20190424]
b51284b[RanderWang/linux: cml-validation-20190424]
8f41f15 [RanderWang/linux: cml-validation-20190424]
202216f [RanderWang/linux: cml-validation-20190424]
ce16096 [RanderWang/linux: cml-validation-20190424]
4459c97 [RanderWang/linux: cml-validation-20190424]
4f4bfb1 [RanderWang/linux: cml-validation-20190424]
0bc8e92 [RanderWang/linux: cml-validation-20190424]
4de6c77 [RanderWang/linux: cml-validation-20190424]
7ec78da [RanderWang/linux: cml-validation-20190424]
30d5691 [RanderWang/linux: cml-validation-20190424]
98d6916 [RanderWang/linux: cml-validation-20190424]

Firmware repo | https://github.com/RanderWang/sof/tree/cml-linux-20190424
Made from:
e4c1651 [thesofproject/sof: master]

e3ade00 [RanderWang/sof: cml-linux-20190424]
08d40fc [RanderWang/sof: cml-linux-20190424]
Topology: | https://github.com/RanderWang/sof/tree/cml-linux-20190424 | Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, using sof-hda-generic-2ch.tplg

![Alsamixer](https://user-images.githubusercontent.com/49641224/56707096-1fc8b980-674a-11e9-9f22-d2d8f85cf48a.PNG)

**Comment by wenqingfu** [comment] 2019-05-06 22:44
ping~ @zhuyingjiang are you making progress on this?

**Comment by zhuyingjiang** [comment] 2019-05-07 02:11
@wenqingfu The root cause is that the codec called the HDA code to get the kcontrol name, and the name given by HDA has not follow the "source-direction-function" rule. So it is same for the legacy HDA. Maybe we need fix it in HDA code.

**Comment by wenqingfu** [comment] 2019-05-08 16:39
Mark as won't fix for it's not a SOF problem.

**Closed as completed by wenqingfu** 2019-05-08 16:39 UTC
Labels: bug, won't fix, P2, CML, HDA

**Comment by libinyang** [comment] 2019-05-13 03:13
@zhuyingjiang Although it is closed, may I ask what is "source-direction-function"?

**Comment by zhuyingjiang** [comment] 2019-05-13 04:26
> Although it is closed, may I ask what is "source-direction-function"?

@libinyang 
Here is the link of Takashi Iwai's doc:
https://www.kernel.org/doc/html/v4.10/sound/kernel-api/writing-an-alsa-driver.html#control-names

**Comment by libinyang** [comment] 2019-05-13 05:15
OK. thanks.
