### ISSUE TITLE
Suspend stress test failure due to IPC timeouts on v0.6

### ISSUE THREAD

**Issue by naveen-manohar** [thesofproject/linux#370] opened 2018-12-05 05:24 UTC
Chrome PV target for S0ix is 2500 cycles and the stress test fails on multiple boards due to IPC timeouts.

SoF v0.6 OS Recipe:
----------------------
Flash the latest ww48 BKC OS and Coreboot image(only) from path: 
ChromeOS-test-R72-11284 or later OS and Coreboot
• Remove the rootfs verification (/usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partition 2)

2. Kernel change - checkout to CL:1352860 to get all the v0.6 patches, compile & update kernel
OR update from pre-built kernel using steps:
~/trunk/src/scripts $ download_kernel_image.sh octopus
password: auto
~/trunk/src/scripts $ update_pre_build_kernel.sh --remote=<IP> octopus

3. Firmware change
DSP FW Copy the sof-glk.ri-1f79920 to /lib/firmware/intel/sof-glk.ri
SOF FW source: Commit: 1f799207f4d7eb7108d5e5602a4a4c15ed9c49f6
Md5sum: cd5bdaf4bca100f6186e4e2d93a4a352 /lib/firmware/intel/sof-glk.ri

Topology FW copy the sof-glk-da7219.tplg-8cc1dad to /lib/firmware/intel/sof-glk-da7219.tplg
Topology FW source: Commit: : 8cc1daddfc513dd6fa04dd2712cf61b17922ca9c
Md5sum: 74dcc70 /lib/firmware/intel/sof-glk-da7219.tplg

How to validate:
Description: Run 2500 consecutive suspend resume cycles on all SKU.
Duration: 24 hours
Setup Steps:
1. Check device mode is set to normal mode.
2. Reinstall OS to ensure you have a fresh OS and all logs are cleared.
3. Connect AC power.
4. Remove all external USB devices.
5. Connect to WiFi network.
 
Test Steps:
1. Open browse as Guest in VT1
2. Press Ctrl+Alt+T to start a crosh
3. Type shell to launch a shell
4. Start the test with 
    sudo suspend_stress_test -c 2500 | tee /home/root/suspend.log

Attached logs.
DUT1:
[ 2858.019887] sof-audio sof-audio: error: ipc timed out for 0x80010000 size 0x48
[ 2858.019925] sof-audio sof-audio: status: fw entered - code 00000005
[ 2858.020113] sof-audio sof-audio: error: unexpected fault 0x00000000 trace 0x00004000
[ 2858.020114] sof-audio sof-audio: error: waking up any trace sleepers
[ 2858.020123] sof-audio sof-audio: error: failed to set dai config for iDisp3
[ 2858.020125] sof-audio sof-audio: error: failed to restore pipeline after resume -110
[ 2858.020131] dpm_run_callback(): pci_pm_resume+0x0/0xbe returns -110
[ 2858.020134] call 0000:00:0e.0+ returned -110 after 409461 usecs
[ 2858.020144] PM: Device 0000:00:0e.0 failed to resume: error -110

DUT2
[ 4599.345157] sof-audio sof-audio: error: waiting for HIPCIE done, reg: 0x0
[ 4599.345172] sof-audio sof-audio: unknown ROM status value 80000000
[ 4599.345176] sof-audio sof-audio: error: status = 0xecc00301 panic = 0x00000000
[ 4599.345179] sof-audio sof-audio: unknown ROM status value 80000000
[ 4599.367322] sof-audio sof-audio: DSP core(s) enabled? 0 : core_mask 3
[ 4599.367332] sof-audio sof-audio: error: could not get stream with stream tag0
[ 4599.367334] sof-audio sof-audio: error: load fw failed err: -19
[ 4599.367350] sof-audio sof-audio: unknown ROM status value ffffffff
[ 4599.367366] sof-audio sof-audio: error: status = 0xffffffff panic = 0xffffffff
[ 4599.367381] sof-audio sof-audio: unknown ROM status value ffffffff
[ 4599.367397] sof-audio sof-audio: error: load fw failed err: -19
[ 4599.367399] sof-audio sof-audio: error: failed to reset DSP
[ 4599.367402] sof-audio sof-audio: error: failed to boot DSP firmware after resume -19
[S0ix_failure.zip](https://github.com/thesofproject/linux/files/2647293/S0ix_failure.zip)

**Comment by ranj063** [comment] 2018-12-06 19:58
#373 didnt help solve the problem

**Comment by jocelyn-li** [comment] 2018-12-07 04:09
@bardliao ran the suspend_stress_test overnight on a Bobba DUT, has passed 3725+ iterations and the test is still going.  

@keyonjie @xiulipan Any ideas about this?

**Comment by xiulipan** [comment] 2018-12-11 04:06
[test_13_pass.log](https://github.com/thesofproject/linux/files/2665906/test_13_pass.log)
[test_12_pass.log](https://github.com/thesofproject/linux/files/2665907/test_12_pass.log)
Reproduced on an UP2 borad with more debug message.
Please see 12 as a success log, and 13 as a fail log.

```
[ 2291.436852] PM: Some devices failed to suspend, or early wake event detected
[ 2291.437118] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[ 2291.437123] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[ 2291.437127] sof-audio sof-audio: Debug PCIW: 00000000 at  00000048
[ 2291.437133] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[ 2291.437136] sof-audio sof-audio: Debug PCIW: 00000040 at  00000048
[ 2291.437140] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[ 2291.437144] sof-audio sof-audio: Debug PCIW: 00000000 at  00000048
[ 2291.437149] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[ 2291.437153] sof-audio sof-audio: Debug PCIW: 00000040 at  00000048
[ 2291.437192] sof-audio sof-audio: loading firmware
[ 2291.437203] sof-audio sof-audio: Debug PCIR: 00000000 at  00000048
[ 2291.437206] sof-audio sof-audio: Debug PCIW: 00000000 at  00000048
[ 2291.437211] sof-audio sof-audio: Debug PCIR: 00000000 at  00000044
[ 2291.437216] sof-audio sof-audio: Debug PCIW: 00000004 at  00000044
[ 2291.437218] sof-audio sof-audio: booting DSP firmware
[ 2291.437413] sof-audio sof-audio: period_bytes:0x0
[ 2291.437416] sof-audio sof-audio: periods:1
[ 2291.437490] sof-audio sof-audio: unstall/run core: core_mask = 1
[ 2291.437494] sof-audio sof-audio: DSP core(s) enabled? 1 : core_mask 1
[ 2291.483635] sof-audio sof-audio: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 2291.483650] sof-audio sof-audio: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 2291.746580] ata2: SATA link down (SStatus 4 SControl 300)
[ 2291.746603] ata1: SATA link down (SStatus 4 SControl 300)
[ 2291.938350] sof-audio sof-audio: error: waiting for HIPCIE done, reg: 0x0
[ 2291.938354] sof-audio sof-audio: status: fw entered - code 00000005
[ 2291.938358] sof-audio sof-audio: error: status = 0x00000000 panic = 0x00004000
[ 2291.938361] sof-audio sof-audio: status: fw entered - code 00000005
[ 2291.940848] r8169 0000:03:00.0 enp3s0: link down
[ 2291.940892] r8169 0000:02:00.0 enp2s0: link down
```
Note the `ipc rx: 0x90020000: GLB_TRACE_MSG` from DSP when we loading the FW and first 
`[ 2291.436852] PM: Some devices failed to suspend, or early wake event detected`

**Comment by ranj063** [comment] 2018-12-12 15:17
This issue has been root caused to a race condition caused by the timing of when the host gets a done interrupt and when the ipc task state in the DSP is set to "completed". A workaround to set the task state to completed before notifying the host works to pass 2500 iterations on 6 boards so far. 

Work in progress to finalize the fix

**Comment by mengdonglin** [comment] 2018-12-31 06:58
Random firmware loading failure is observed in the stress test https://github.com/thesofproject/sof/issues/785

**Comment by ranj063** [comment] 2019-01-11 18:55
@mengdonglin @naveen-manohar can we close this bug now that we have proved there are no issues with stress test?

**Comment by mengdonglin** [comment] 2019-01-14 14:03
Closing this issue since we can no longer reproduce it no matter with SOF V0.55 or V1.0 release for GLK with all recent fixes.

**Closed as completed by mengdonglin** 2019-01-14 14:03 UTC
Labels: bug, P1, GLK
