### ISSUE TITLE
[BUG][SDW]Arecord0,4(RT715) cannot work with tplg in master branch.

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1816] opened 2020-02-21 04:31 UTC
**Describe the bug**
With sof-dev and master branch, arecord0,4(RT715) cannot work and will cause ipc error. If replace the tplg to master + PR2358, issue is gone.

Note: I used to update the alsa-lib for multi-profile ucm validation.  I'm not sure if this issue is relevant to it or not. Tried to test it with Pulse audio off, issue can still be reproduced.

alsa-lib deb file: 
[libasound2_1.2.1.2-intel_amd64.deb.zip](https://github.com/thesofproject/linux/files/4235881/libasound2_1.2.1.2-intel_amd64.deb.zip)

**To Reproduce** 
1. Boot up with Pulse Audio off.
2. arecord -Dhw:0,4 -r48000 -c2 -fs32_le test.wav

**Reproduced rate**
100%
Other pipline works fine.
 
**Expected result**
Arecord successfully

**Actual result**
Dmesg shows "error: ipc error for 0x60010000 size 20" and cannot work.

**Test recipe**
Firmware: 247af13 https://github.com/thesofproject/sof/commits/master 
Kernel: 6af9a26 https://github.com/bardliao/linux/tree/topic/sof-dev
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML-U Laptop with ALC711+ ALC1308+ ALC715 in SDW mode

dmesg:
```
[  186.651821] sof-audio-pci 0000:00:1f.3: stream_tag 2
[  186.651824] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  186.652595] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
[  186.652597] sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 2
[  186.652598] sof-audio-pci 0000:00:1f.3: ASoC: 0000:00:1f.3 hw params failed: -22
[  186.652600]  Microphones: ASoC: hw_params FE failed -22
[  186.652602] sdw_deprepare_stream: SDW3 Pin2-Capture: inconsistent state state 1
[  186.652603] int-sdw int-sdw.3: sdw_deprepare_stream: failed -22
[  186.652605] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 1
[  186.652607] sdw_deprepare_stream: SDW3 Pin2-Capture: inconsistent state state 1
[  186.652608] int-sdw int-sdw.3: sdw_deprepare_stream: failed -22
[  186.652712] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 1
[  187.132444] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  187.132477] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  187.346181] usb usb2-port3: Cannot enable. Maybe the USB cable is bad?
[  187.632382] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
```

error_sof-trace:
```
CORE  LEVEL      COMP_ID                TIMESTAMP            DELTA                FILE_NAME	CONTENT
    0      1         COMP 5.20    233307973.906250 233307968.000000 udio/eq_iir/eq_iir.c:857 	eq_iir_prepare(), No proc func
    0      1         PIPE         233307993.072917        19.166666 src/audio/pipeline.c:499 	pipeline_prepare() error: ret = -22, dev->comp.id = 18
    0      1          IPC         233308012.291667        19.218750    src/ipc/handler.c:311 	ipc: pipe 5 comp 18 prepare failed -22
```

[dmesg.log](https://github.com/thesofproject/linux/files/4234242/dmesg.log)
[sof_error_trace.log](https://github.com/thesofproject/linux/files/4234243/sof_error_trace.log)

**Comment by YvonneYang2** [comment] 2020-02-21 04:50
Tested it with latest sof-dev(dfd3776) and master(c35e1aa), issue can still be reproduced.

**Comment by sinahuang** [comment] 2020-02-21 10:56
Issue also can be reproduced on TGL-RVP Dmic(0,4). alsa-lib version: libasound2_1.1.3

```
[  129.173756] sof-audio-pci 0000:00:1f.3: generating page table for 00000000c2b68d6c size 0xf9c0 pages 16
[  129.173761] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  129.173776] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x40000 successful
[  129.173778] sof-audio-pci 0000:00:1f.3: period_bytes:0x3e40
[  129.173778] sof-audio-pci 0000:00:1f.3: periods:4
[  129.173788] sof-audio-pci 0000:00:1f.3: stream_tag 2
[  129.173794] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[  129.173983] sof-audio-pci 0000:00:1f.3: error: ipc error for 0x60010000 size 20
[  129.173986] sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 2
[  129.173987] sof-audio-pci 0000:00:1f.3: ASoC: 0000:00:1f.3 hw params failed: -22
[  129.173988]  DMIC16kHz: ASoC: hw_params FE failed -22
[  129.173990] sof-audio-pci 0000:00:1f.3: pcm: free stream 4 dir 1
[  129.174109] sof-audio-pci 0000:00:1f.3: pcm: close stream 4 dir 1
[  129.673783] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  129.673818] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  130.173758] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  130.173794] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[  131.674178] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x20140000 successful
[  131.718198] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  131.718519] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  131.718656] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1010f0f successful
[  131.718660] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x1000f0f successful
[  131.718662] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
```
**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit: dfd3776 
FW:  https://github.com/thesofproject/sof/commits/master commit: c35e1aa
Tplg: Same with FW branch, sof-tgl-rt711-i2s-rt1308.tplg 
Platform:TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode
[dmesg.log](https://github.com/thesofproject/linux/files/4235674/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4235676/sof_trace.log)

**Comment by YvonneYang2** [comment] 2020-02-24 13:27
Tested it with latest topic/sof-dev(1d2ad93 ) + master( 1d273c3), issue cannot be reproduced on CML-U SDW laptop.

**Comment by sinahuang** [comment] 2020-02-25 05:25
Tested it with latest topic/sof-dev(8bf1a29 ) + master( 8b59506), issue still can be reproduced on TGL-RVP  with codec ALC711 in SDW mode and  RT1308 in I2S mode.

[dmesg.log](https://github.com/thesofproject/linux/files/4248175/dmesg.log)

**Comment by sinahuang** [comment] 2020-02-25 11:08
According to the bi-sect result this is a FW issue, because TGL-U RVP's FW can't be built manually.
 So I only can confirm issue may be generated by the commit from  https://github.com/thesofproject/sof/commit/b0ad9578a7864c602fa2c688cbcdc9b955235798 to https://github.com/thesofproject/sof/commit/53d35e49126612a819feace25de6cfd5bd609b44.


[dmesg.log](https://github.com/thesofproject/linux/files/4249656/dmesg.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4249657/sof_trace.log)

**Comment by sinahuang** [comment] 2020-02-26 11:29
Split TGL issue to #1828, so closed this issue.

**Closed as completed by sinahuang** 2020-02-26 11:29 UTC
Labels: bug, P1, CML, SDW
