### ISSUE TITLE
Up2-nocodec: sof-logger / ldc failure in capture/playback test

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2361] opened 2020-08-13 15:41 UTC
Adding issue to keep track of problem reported here: https://sof-ci.01.org/linuxpr/PR2357/build4293/devicetest/

**Comment by plbossart** [comment] 2020-08-13 15:42
@marc-hb @lyakh FYI.

**Comment by marc-hb** [comment] 2020-08-13 22:22
Quoting myself from #2357 :

We started paying more attention to the sof-logger (and there's more coming, see https://github.com/thesofproject/sof-test/issues/297 and 298)

The two failures in https://sof-ci.01.org/linuxpr/PR2357/build4293/devicetest/ look basically the same:

```
2020-08-13 01:58:18 UTC [REMOTE_ERROR] sof-logger was already dead  # (new test)
```
At the bottom of the (long) `slogger` tab:
```
error: Invalid filename length or ldc file does not match firmware
```

**Comment by lyakh** [comment] 2020-08-14 07:11
> ```
> 2020-08-13 01:58:18 UTC [REMOTE_ERROR] sof-logger was already dead  # (new test)
> ```
> ```
> error: Invalid filename length or ldc file does not match firmware
> ```
yeah, doesn't look like an "audio problem" to me either

**Comment by paulstelian97** [comment] 2020-08-14 08:15
ldc failure means that for some reason the active firmware image and ldc file aren't from the same build, or you use an old version of sof-logger that cannot properly decode the ldc file. Sounds like a CI problem.

**Comment by plbossart** [comment] 2020-08-14 15:46
it could very well be a CI problem but why would it affect only this platform?

**Comment by paulstelian97** [comment] 2020-08-14 15:54
The test machine maybe has an older version of sof-logger or some misconfiguration.

**Comment by paulstelian97** [comment] 2020-08-14 15:55
Although I think it should have said "ABI mismatch" instead.

**Comment by mengdonglin** [comment] 2020-08-17 05:14
@marc-hb Can you help check this issue?

**Comment by keyonjie** [comment] 2020-08-24 02:57
@plbossart so what's the issue here? CI provided inaccurate info?

**Comment by juimonen** [comment] 2020-08-24 07:40
@keyon the question is why is the CI machine having incompatible versions of fw and debug file, or is this because of some other reason...

**Comment by plbossart** [comment] 2020-08-24 14:46
we have another sof-logger issue #2379 
This really pollutes our CI results, needs to be fixed.

**Comment by mengdonglin** [comment] 2020-08-31 01:50
> we have another sof-logger issue #2379
> This really pollutes our CI results, needs to be fixed.

@paulstelian97 I think that sof-logger issue is https://github.com/thesofproject/sof/issues/3344, right?

**Comment by paulstelian97** [comment] 2020-08-31 07:30
Took a look and commented on the sof-logger issue. _Scratching my head..._

**Comment by mengdonglin** [comment] 2020-11-23 02:48
Cannot reproduce in CI recently, so lower the priority.

**Comment by mengdonglin** [comment] 2020-11-23 02:53
The slogger shows it's more likely the *.ldc file has changed during the test. CI hasn't reproduced this issue. So closed it.

**Closed as completed by mengdonglin** 2020-11-23 02:53 UTC
Labels: bug, P3, APL
