### ISSUE TITLE
[bug][TGL][UCM2]UCM2 can not work on tgl hda RVP

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#2145] opened 2020-05-28 08:13 UTC
***Describe the bug***
UCM2 can not work on tgl hda RVP

  
***To Reproduce***
1.Put “sof-hda-dsp” to /usr/share/alsa/ucm2
2."sudo reboot" to reboot system
3.check if ucm2 can work

***Reproduction Rate***
10/10

Expected behavior
UCM2 can work on tgl hda RVP

Actual result
UCM2 can not work on tgl hda RVP

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 46897802 https://github.com/thesofproject/sof/commits/master
Kernel: 0d22f66b https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/ sof-hda-generic-4ch.tplg same as firmware
UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp 
 (commit:https://github.com/thesofproject/alsa-ucm-conf/commit/81465c566444c2a697d080e06ef0e00bfe62b792)

[amixercontents0528.log](https://github.com/thesofproject/linux/files/4694155/amixercontents0528.log)
[dmesg0528.log](https://github.com/thesofproject/linux/files/4694156/dmesg0528.log)
[sof-logger0528.log](https://github.com/thesofproject/linux/files/4694160/sof-logger0528.log)

**Comment by kv2019i** [comment] 2020-06-03 12:56
@Liviali155 Could you attach pulseaudio log? That should reveal what goes wrong with the UCM2. There are multiple ways to get the log.. here's one:
edit /etc/pulse/client.conf, then set autospawm = no, then reboot, open a terminal, and kill all pulse audio instances, if any,  then run pulseaudio -vvv &> log.txt, and attach the log.txt

**Comment by Liviali155** [comment] 2020-06-04 01:56
> Could you attach pulseaudio log? That should reveal what goes wrong with the UCM2. There are multiple ways to get the log.. here's one:
> edit /etc/pulse/client.conf, then set autospawm = no, then reboot, open a terminal, and kill all pulse audio instances, if any, then run pulseaudio -vvv &> log.txt, and attach the log.txt

Pulseaudio log as below
[log.txt](https://github.com/thesofproject/linux/files/4727041/log.txt)

**Comment by kv2019i** [comment] 2020-06-08 14:19
@Liviali155 wrote:
> Pulseaudio log as below
> [log.txt](https://github.com/thesofproject/linux/files/4727041/log.txt)

Oops, it seems autospawn setting did not take effect:
E: [pulseaudio] pid.c: Daemon already running.

You could try this (no need for reboot):
sudo mv /usr/bin/pulseaudio /usr/bin/pulseaudio-off
killall -v pulseaudio
pulseaudio-off -vvv &> log.txt
sudo mv /usr/bin/pulseaudio-off /usr/bin/pulseaudio

**Comment by Liviali155** [comment] 2020-06-09 01:31
> @Liviali155 wrote:
> 
> > Pulseaudio log as below
> > [log.txt](https://github.com/thesofproject/linux/files/4727041/log.txt)
> 
> Oops, it seems autospawn setting did not take effect:
> E: [pulseaudio] pid.c: Daemon already running.
> 
> You could try this (no need for reboot):
> sudo mv /usr/bin/pulseaudio /usr/bin/pulseaudio-off
> killall -v pulseaudio
> pulseaudio-off -vvv &> log.txt
> sudo mv /usr/bin/pulseaudio-off /usr/bin/pulseaudio

log as below
[log0609.txt](https://github.com/thesofproject/linux/files/4749350/log0609.txt)

**Comment by ClarexZhou** [comment] 2020-06-10 10:02
linux PC team is waiting UCM2 to work

**Comment by kv2019i** [comment] 2020-06-10 12:22
Ack, this is related to HDA config in the BIOS:

I: [pulseaudio-off] (alsa-lib)main.c: unable to execute cset 'name='Auto-Mute Mode' 'Disabled''
I: [pulseaudio-off] (alsa-lib)main.c: error: failed to initialize new use case: HiFi
E: [pulseaudio-off] alsa-ucm.c: Failed to get the verb HiFi

I'll make a patch to alsa-ucm to be more robust against this.

**Comment by kv2019i** [comment] 2020-06-10 15:14
@Liviali155 @ClarexZhou Can you try with following fix to UCM2:
https://github.com/alsa-project/alsa-ucm-conf/pull/33

**Comment by plbossart** [comment] 2020-06-10 15:16
can we provide the alsa-info log to Jaroslav, when we add new conditions in UCM the ucm-validator test script will check what paths in the UCM file are covered by a config.

**Comment by Liviali155** [comment] 2020-06-11 03:23
> @Liviali155 @ClarexZhou Can you try with following fix to UCM2:
> [alsa-project/alsa-ucm-conf#33](https://github.com/alsa-project/alsa-ucm-conf/pull/33)

Tried with  [alsa-project/alsa-ucm-conf#33](https://github.com/alsa-project/alsa-ucm-conf/pull/33),ucm still can not  work,log as below
[amixercontents0611.log](https://github.com/thesofproject/linux/files/4762400/amixercontents0611.log)
[dmesg0611.log](https://github.com/thesofproject/linux/files/4762401/dmesg0611.log)
[pulseaudio.log](https://github.com/thesofproject/linux/files/4762403/pulseaudio.log)
[sof-logger.log](https://github.com/thesofproject/linux/files/4762404/sof-logger.log)

**Comment by kv2019i** [comment] 2020-06-11 14:53
Sorry @Liviali155 ! There was a pretty bad mistake in my bad. I tested a wrong version before submitting the PR, sorry about that. I fixed that PR and fixed one more issue reported. Now UCM should work with these fixes:

https://github.com/alsa-project/alsa-ucm-conf/pull/33
https://github.com/alsa-project/alsa-ucm-conf/pull/34

**Comment by Liviali155** [comment] 2020-06-12 10:39
> Sorry @Liviali155 ! There was a pretty bad mistake in my bad. I tested a wrong version before submitting the PR, sorry about that. I fixed that PR and fixed one more issue reported. Now UCM should work with these fixes:
> 
> [alsa-project/alsa-ucm-conf#33](https://github.com/alsa-project/alsa-ucm-conf/pull/33)
> [alsa-project/alsa-ucm-conf#34](https://github.com/alsa-project/alsa-ucm-conf/pull/34)

Tried with 
> [alsa-project/alsa-ucm-conf#33](https://github.com/alsa-project/alsa-ucm-conf/pull/33)
> [alsa-project/alsa-ucm-conf#34](https://github.com/alsa-project/alsa-ucm-conf/pull/34)
UCM2 can work on tgl RVP,but has below issues:
1.Output device in sound setting is blank after reboot without headset and HDMI connected,but if you tap it once,Input device changed to speaker
2.Plug headset,there is no headset item in Input device
3.Reboot with HDMI connected,then plug headset and set Outputdevice as headphone,Input device as headphone, sound  still output in HDMI,but if reboot connected with HDMI and headset,error not seen,log as below
[amixercontents0612.txt](https://github.com/thesofproject/linux/files/4770259/amixercontents0612.txt)
[dmesg0612.log](https://github.com/thesofproject/linux/files/4770260/dmesg0612.log)
[pulseaudio.txt](https://github.com/thesofproject/linux/files/4770263/pulseaudio.txt)
[sof-logger.log](https://github.com/thesofproject/linux/files/4770264/sof-logger.log)

**Comment by kv2019i** [comment] 2020-06-12 14:24
Thanks @Liviali155 This matches with other reports I've got.

I now made one additional fix (draft still) that fixes the case where sound settings is empty if booting without headset connected:
https://github.com/thesofproject/alsa-ucm-conf/pull/43

There would still seem to be a problem in following case:
 - boot without HDMI/DP or headphone connected
 - plug in headphone
 -> only "dummy" sink listed in "pactl list sinks" 

Pulseaudio log when this happens:
Jun 12 13:44:17 ubuntu pulseaudio[3195]: Jack 'Headphone Jack' is now plugged in
Jun 12 13:44:17 ubuntu pulseaudio[3195]: Setting port [Out] Headphones1 to status yes
Jun 12 13:44:17 ubuntu pulseaudio[3195]: Trying to switch to port [Out] Headphones1
Jun 12 13:44:17 ubuntu pulseaudio[3195]: Finding best profile for port [Out] Headphones1, preferred = (null)
Jun 12 13:44:17 ubuntu pulseaudio[3195]: No suitable profile found
Jun 12 13:44:17 ubuntu pulseaudio[3195]: Setting card alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic profile HiFi to availability status unknown

As this requires plugging the headphones, I'll try to reproduce with some local device. Not sure why Pulseaudio thinks this to be the case.

**Comment by Liviali155** [comment] 2020-06-16 07:21
@kv2019i 

Tried with https://github.com/thesofproject/alsa-ucm-conf/commits/master+ https://github.com/thesofproject/alsa-ucm-conf/pull/43 +  https://github.com/alsa-project/alsa-ucm-conf/pull/33,   ucm2 can work,but has below issue:
1.boot without HDMI/DP or headphone connected
2.open sound setting
Output Device is "Dummy Output",Input Device is blank 
After plug headset,Output Device has "Dummy Output" and "headphone",Input Device is blank ,if tap Input device once,it will change to"Digital Microphone-sof-hda-dsp"
<img width="296" alt="1" src="https://user-images.githubusercontent.com/56707932/84743381-6fb8ae80-afe4-11ea-90b1-5e5d679c675c.PNG">
<img width="296" alt="2" src="https://user-images.githubusercontent.com/56707932/84743384-71827200-afe4-11ea-8ec5-188e69609df2.PNG">

[pulseaudio0616.log](https://github.com/thesofproject/linux/files/4785011/pulseaudio0616.log)
[sof-logger0616.log](https://github.com/thesofproject/linux/files/4785012/sof-logger0616.log)
[dmesg0616.log](https://github.com/thesofproject/linux/files/4785008/dmesg0616.log)
[amixercontents0616.log](https://github.com/thesofproject/linux/files/4785007/amixercontents0616.log)

**Comment by ClarexZhou** [comment] 2020-06-29 02:46
@kv2019i  Are you going to refine  thesofproject/alsa-ucm-conf#43?

**Comment by kv2019i** [comment] 2020-06-29 15:23
@ClarexZhou wrote:
> @kv2019i Are you going to refine [thesofproject/alsa-ucm-conf#43](https://github.com/thesofproject/alsa-ucm-conf/pull/43)?

Yes, I'm working on a refined version, ETA for fix tomorrow (Tuesday).

**Comment by kv2019i** [comment] 2020-07-01 12:39
@ClarexZhou Jaroslav beat me to it, this is now fixed in upstream commit "sof-hda-dsp: make the boot init optional for all controls". There was unrelated regression, but latest commit https://github.com/alsa-project/alsa-ucm-conf/commit/ffe0cab5cfceb921a50a655d4024467f8aeab701 should be ok now.

**Comment by kv2019i** [comment] 2020-07-01 12:47
@ClarexZhou wrote:
> 1.boot without HDMI/DP or headphone connected
> 2.open sound setting
> Output Device is "Dummy Output",Input Device is blank
> After plug headset,Output Device has "Dummy Output" and "headphone",Input Device is blank ,if tap Input device once,it will 
> change to"Digital Microphone-sof-hda-dsp"

I double-checked and this is expected behaviour of Pulseaudio. As no sinks are available (system doesn't have a speaker, headphone/set not connected, no HDMI/DP monitor), there are no available sinks in the system, so Pulseaudio go ahead and creates the Dummy one:

D: [pulseaudio-off] card.c: Looking for initial profile for card alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic
D: [pulseaudio-off] card.c: HiFi availability no
D: [pulseaudio-off] card.c: off availability unknown
I: [pulseaudio-off] card.c: alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic: active_profile: off
D: [pulseaudio-off] module-card-restore.c: Not restoring profile HiFi for card alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic, because the profile is currently unavailable.
...
D: [pulseaudio-off] module-always-sink.c: Autoloading null-sink as no other sinks detected.


I think this is ok as functionality still works. In practise all commercial systems will have some type of speaker connected, so this won't in practise be hit.

Ok to close?

**Comment by ClarexZhou** [comment] 2020-07-02 08:30
Agree to be closed since all PRs are mergd.  But current latest commit alsa-project/alsa-ucm-conf@ffe0cab is “Syntax 3". Not work on all sof products now. @libinyang  is checking on this
And now we can use https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2 + PRs to test.

**Closed as completed by ClarexZhou** 2020-07-02 08:30 UTC
Labels: bug, P1, HDA, TGL, UCM2
