### ISSUE TITLE
[BUG] ADL Wake from Soix not working using Intel clap-WoV

### ISSUE THREAD

**Issue by Vamshigopal** [thesofproject/linux#3026] opened 2021-07-05 13:47 UTC
Intel clap (Wov) from soix is not working seeing below error messages in dmesg.
sof-audio-pci-intel-tgl 0000:00:1f.3: error: ipc error for 0x60010000 size 20
sof-audio-pci-intel-tgl 0000:00:1f.3: error: pcm params failed for DETECT12.0
sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to set pcm params for widget DETECT12.0
sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: PRE_PMU: DETECT12.0 event failed: -22

Note: In S0 (active state) Intel clap is working without any issues. Observation is same on Soundwire and I2S daughterboards.

Command used to test:
arecord -Dhw:0,100 -M -N -r 16000 -c2 -f s16_le --buffer-size=96000 -vvv /tmp/wov.wav

We have also tried tgl-012 drop with google hotword and observations are similar.

logs attached:
[dmesg_wov_soix.log](https://github.com/thesofproject/linux/files/6764625/dmesg_wov_soix.log)
[soflogger_wov_soix.log](https://github.com/thesofproject/linux/files/6764626/soflogger_wov_soix.log)

Configuration:
FW : adl-002-drop-stable( same observation with adl-001-drop-stable)
Kernel : https://chromium.googlesource.com/chromiumos/third_party/kernel/+log/refs/heads/chromeos-5.10
Board : ADL Brya board

**Comment by Vamshigopal** [comment] 2021-07-05 13:50
@libinyang @keyonjie @kv2019i @sathyap-chrome @keqiaozhang @yongzhi1 @sathya-nujella @jairaj-arava

**Comment by ranj063** [comment] 2021-07-06 20:50
@Vamshigopal from the logs it doesnt look like you are suspending to S0ix at all:

[  280.649279] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[  280.649375] usb 3-10: usb_dev_suspend+0x0/0x14 returned 0 after 566 usecs
[  280.649547] sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE

You should never see this for S0ix. This is sent only before D3 to the DSP

**Comment by sathyap-chrome** [comment] 2021-07-07 04:30
@ranj063 so you are saying DSP is entering D3 instead of D0i3 ? System wide S0ix is working fine. 

should we set anything from userspace or any setting missed in kernel to be added to ensure DSP enter D0i3 ?

**Comment by ranj063** [comment] 2021-07-07 04:43
> should we set anything from userspace or any setting missed in kernel to be added to ensure DSP enter D0i3 ?

@sathyap-chrome can you please check if the target_state is getting set to S0ix here?
https://github.com/thesofproject/linux/blob/6bd3089a40a564ecb099f34ee31bf6093adbec24/sound/soc/sof/pm.c#L320

**Comment by sathyap-chrome** [comment] 2021-07-07 05:20
>@sathyap-chrome can you please check if the target_state is getting set to S0ix here?


yes. this is present

**Comment by jairaj-arava** [comment] 2021-07-07 05:33
@ranj063 , I think we can find the DSP state transitions during S0IX with the logs just to make sure it's in D3 or D0I3?

**Comment by ranj063** [comment] 2021-07-07 15:42
> > @sathyap-chrome can you please check if the target_state is getting set to S0ix here?
> 
> yes. this is present

what does present mean? you mean the check is there or did you actually check that during suspend, the sdev->system_suspend_taget is actually set to SOF_SUSPEND_S0IX? The latter is what I am looking for

**Comment by sathyap-chrome** [comment] 2021-07-08 08:31
thanks @ranj063  for pointer. the PR https://github.com/thesofproject/linux/pull/3033 fixes the soix entry.
Now we see right logs for entry and the we see different set of erros.

When we open wov stream and then try soix, there is early wake from DSP
- see attached logs: 
[soix.txt](https://github.com/thesofproject/linux/files/6783689/soix.txt)

- Resume caused by IRQ 179, AudioDSP
- 
But when wov stream is closed, the soix entry and exit is fine.

NOTE : logs was taken when we tried with google hotword ,but we saw similar log with intel wov module (clap) as well.

**Comment by ranj063** [comment] 2021-07-08 14:18
> When we open wov stream and then try soix, there is early wake from DSP
> 
> *
do you have trace enabled in the FW?

**Comment by sathyap-chrome** [comment] 2021-07-08 14:36
Yes. trace was enabled . should i try without enabling traces ?

**Comment by ranj063** [comment] 2021-07-08 14:43
> Yes. trace was enabled . should i try without enabling traces ?

yes, please!

**Comment by sathyap-chrome** [comment] 2021-07-08 14:45
thanks. had it enabled for debug purpose. will try asap

**Comment by sathyap-chrome** [comment] 2021-07-09 05:00
@ranj063 thanks for quick suggestion.

Confirmed that with debug trace disabled and https://github.com/thesofproject/linux/pull/3033 wov is working.
we can close this issue. Can raise a new one on why debug trace is resulting in early wake.

**Comment by sathyap-chrome** [comment] 2021-07-09 05:21
Raised https://github.com/thesofproject/linux/issues/3034 for the early wake with FW trace enabled

**Comment by ranj063** [comment] 2021-07-09 15:42
FIxed by https://github.com/thesofproject/linux/pull/3033

**Closed as completed by ranj063** 2021-07-09 15:42 UTC
Labels: bug, P1, Keyword Detection, Chrome, NOT on topic/sof-dev, ADL
