### ISSUE TITLE
MinnowBoard: SOF fails to boot with latest 1.0 BIOS

### ISSUE THREAD

**Issue by lyakh** [thesofproject/linux#751] opened 2019-03-25 15:11 UTC
This might be a mis-configuration issue, but 2 days of debugging and multiple emails on https://mailman.alsa-project.org/pipermail/sound-open-firmware/2019-March/003204.html failed to fix the issue so far. Trying to boot current SOF firmware and the kernel on 2 MinnowBoard systems (Max with an attached codec card and Turbot with no card) with the latest 1.0 BIOS and ACPI scripts to enable the DSP, results in a failure like
```
[    9.373983] sof-audio-acpi 80860F28:01: error:  unable to run DSP firmware
[    9.374330] sof-audio-acpi 80860F28:01: error: unexpected fault 0xffffffff trace 0xffffffff
[    9.374417] sof-audio-acpi 80860F28:01: error: failed to reset DSP
[    9.374483] sof-audio-acpi 80860F28:01: error: failed to boot DSP firmware -19
```
A complete dmesg output is attached.
[20190325-dmesg.txt](https://github.com/thesofproject/linux/files/3004018/20190325-dmesg.txt)

**Comment by plbossart** [comment] 2019-03-25 17:31
@lyakh to rule out SOF issues, please try with the SST driver and nocodec machine driver (use sst-defconfig and add nocodec machine driver). If it doesn't work it's your hardware and config that's broken. If it works then it's an issue on the SOF side.

**Comment by lyakh** [comment] 2019-03-27 08:35
@plbossart thanks, that was a good idea. Just tried it and sure enough it doesn't work either. I'm getting

> [    7.764231] intel_sst_acpi 80860F28:01: BYT-CR not detected
> [    7.764834] intel_sst_acpi 80860F28:01: LPE base: 0x90a00000 size:0x200000
> [    7.764837] intel_sst_acpi 80860F28:01: IRAM base: 0x90ac0000
> [    7.764885] intel_sst_acpi 80860F28:01: DRAM base: 0x90b00000
> [    7.764893] intel_sst_acpi 80860F28:01: SHIM base: 0x90b40000
> [    7.764902] intel_sst_acpi 80860F28:01: Mailbox base: 0x90b44000
> [    7.764909] intel_sst_acpi 80860F28:01: DDR base: 0x20000000
> [    7.765030] intel_sst_acpi 80860F28:01: Got drv data max stream 25
> [    7.774305] i915 0000:00:02.0: fb0: inteldrmfb frame buffer device
> [    7.845687] bytcht_nocodec bytcht_nocodec: snd-soc-dummy-dai <-> media-cpu-dai mapping ok
> [    7.845749] bytcht_nocodec bytcht_nocodec: snd-soc-dummy-dai <-> deepbuffer-cpu-dai mapping ok
> [    7.845795] bytcht_nocodec bytcht_nocodec: snd-soc-dummy-dai <-> ssp2-port mapping ok
> [    8.159476] intel_rapl: Found RAPL domain package
> [    8.159479] intel_rapl: Found RAPL domain core
> [   16.485693] igb 0000:03:00.0 enp3s0: igb: enp3s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
> [   16.486300] IPv6: ADDRCONF(NETDEV_CHANGE): enp3s0: link becomes ready
> [   22.540480] intel_sst_acpi 80860F28:01: Wait timed-out condition:0x0, msg_id:0x0 fw_state 0x1
> [   22.540489] intel_sst_acpi 80860F28:01: fw download failed -16
> [   22.540499] intel_sst_acpi 80860F28:01: FW download fail -16

I actually haven't used those SST drivers before, do they also need the same ACPI scripting as the SOF? (my guess: yes) Do they need any additional firmware? (guess: no) Anything else special?

**Comment by plbossart** [comment] 2019-03-27 12:02
@lyakh do you actually run the acpi scripts w/ the startup.nsh step? If you boot directly without going to the EFI shell first it's not going to work. That's my only remaining idea before getting new hardware or sending it to someone else for checks

**Comment by lyakh** [comment] 2019-03-27 13:50
@plbossart yes, from the startup.nsh script. And yes, I see that script running, because also the kernel does find the ACPI device and tries to probe it, otherwise no probing is taking place at all. I don't think getting new hardware would help - I have 3 minnow boards here. Maybe it's my ubuntu that's somehow powering that down. I also tried your defconfig files and the exact "make defconfig && merge && make bzImage modules" sequence. I think with that and SST nocodec my dmesg looks a bit better, but still with errors and "aplay -l" is empty. Maybe someone could upload a tarball with bzImage, modules, topology and firmware somewhere for me...

**Comment by lyakh** [comment] 2019-03-27 14:45
A comparison with @juimonen 's logs (thanks!) and a follow-up verification revealed, that BIOS 1.0 doesn't work with our software. A downgrade to 0.94 fixes the problem.

**Comment by lyakh** [comment] 2019-03-27 15:29
The next problem:

> [   10.888710] sof-audio-acpi 80860F28:01: loading topology:intel/sof-tplg/sof-byt-rt5651.tplg
> [   10.928453] systemd[1]: sys-devices-platform-80860F16:00-mmc_host-mmc2-mmc2:aaaa-block-mmcblk2.device: Changed dead -> plugged
> [   10.933449] sof-audio-acpi 80860F28:01: tplg: ready widget id 0 pipe 1 type 1 name : codec_out0 stream none
> [   10.933455] sof-audio-acpi 80860F28:01: warning: widget type 1 name codec_out0 not handled
> [   10.933464] sof-audio-acpi 80860F28:01: tplg: ready widget id 1 pipe 1 type 23 name : PCM0P stream Low Latency Playback 0
> [   10.933470] sof-audio-acpi 80860F28:01: loaded host PCM0P
> [   10.933474] sof-audio-acpi 80860F28:01:  config: periods snk 2 src 0 fmt 0
> [   10.933483] sof-audio-acpi 80860F28:01: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
> [   10.933578] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x30010000: GLB_TPLG_MSG: COMP_NEW
> [   10.933595] sof-audio-acpi 80860F28:01: tplg: load control type 1 name : 1 PCM 0 Playback Volume
> [   10.933609] sof-audio-acpi 80860F28:01: tplg: load kcontrol index 2 chans 2
> [   10.933616] sof-audio-acpi 80860F28:01: tplg: ready widget id 2 pipe 1 type 6 name : PGA1.0 stream none
> [   10.933623] sof-audio-acpi 80860F28:01:  config: periods snk 1 src 2 fmt 2
> [   10.933630] sof-audio-acpi 80860F28:01: ipc tx: 0x30010000: GLB_TPLG_MSG: COMP_NEW
> [   10.933688] sof-audio-acpi 80860F28:01: error: ipc error for 0x30010000 size 20
> [   10.933698] sof-audio-acpi 80860F28:01: error: DSP failed to add widget id 0 type 6 name : PGA1.0 stream none reply -22
> [   10.933703] sof-audio-acpi 80860F28:01: ASoC: failed to load widget PGA1.0
> [   10.933709] sof-audio-acpi 80860F28:01: error: tplg component load failed -22

**Comment by lyakh** [comment] 2019-03-27 15:59
hm, this one got fixed by rebuilding the firmware... Looks like the build system doesn't always rebuild properly. One of the indications of that is that the .ldc is often left empty after a partial rebuild.

**Comment by ranj063** [comment] 2019-03-27 16:03
@lyakh do you use the build scripts or build it manually?

**Comment by lyakh** [comment] 2019-03-27 16:38
@ranj063 if "make" counts as "manually" then yes, that's what I do :-)

**Comment by ranj063** [comment] 2019-03-27 16:40
@lyakh can you please try the scripts/build-xtensa-all script. It should avoid the issues you're describing.

**Comment by plbossart** [comment] 2019-03-27 19:51
> A comparison with @juimonen 's logs (thanks!) and a follow-up verification revealed, that BIOS 1.0 doesn't work with our software. A downgrade to 0.94 fixes the problem.

Ah interesting. It could be that we need to update the AudioSSDTUpdate.efi application due to some ABI change.

**Comment by wenqingfu** [comment] 2019-03-27 20:46
> Ah interesting. It could be that we need to update the AudioSSDTUpdate.efi application due to some ABI change.

Who can do this? Anything we should do, or close this bug as known issue?

**Comment by plbossart** [comment] 2019-03-27 20:54
> > Ah interesting. It could be that we need to update the AudioSSDTUpdate.efi application due to some ABI change.
> 
> Who can do this? Anything we should do, or close this bug as known issue?

We should definitively try to update the code. I did this 2-3 years ago, it's just a matter of recompiling in theory.

**Comment by wenqingfu** [comment] 2019-03-27 23:14
> We should definitively try to update the code. I did this 2-3 years ago

sounds like you volunteered? :)  can I assign this to you? I have no idea where is the .efi file..

**Comment by xun2z** [comment] 2019-03-28 03:33
> sounds like you volunteered? :) can I assign this to you? I have no idea where is the .efi file.

I think I can try this. I forked and recompiled pierre's [branch](https://github.com/plbossart/MinnowBoardMaxFirmware) to support 5682 on Minnowboard recently. 
What we need to do is to follow some [compiling guide](https://firmware.intel.com/sites/default/files/minnowboard_max-rel_1_00-releasenotes.txt).

I've had the same issue weeks before and succeeded by downgrading to 0.97, sorry not see this issue yesterday.

**Comment by wenqingfu** [comment] 2019-03-28 04:35
> I think I can try this.

👍

**Comment by lyakh** [comment] 2019-03-28 07:41
@ranj063 that script just does a clean build every time by deleting any previous builds. I don't think we want to force that, we want to have functional incremental builds too.

**Comment by plbossart** [comment] 2019-03-28 13:47
@xun2z if you take https://github.com/plbossart/MinnowBoardMaxFirmware, you need to change the build.sh, MinnowFirmwareSetup.sh and MinnowFirmware.patch to compile, add the .efi application and recompile it. It's not too hard but it's not simple either. The main problem I faced was issues with GCC in the past, this never worked on Ubuntu for some reason and the firmware folks use an ancient 4.2 version that isn't present on any recent distro.

**Comment by xun2z** [comment] 2019-03-29 01:36
@plbossart yes, I succeeded in compiling the 1.00 AudioSsdtUpdate(LPEX, RT5651...) yesterday. I meet with some compiling errors (on ubuntu 18.04 typically the inconsistency between build and link) and fixed by using ubuntu 16.04. I will test on device today and create a pr when it's done.

**Comment by xun2z** [comment] 2019-03-29 08:52
I have done the [updates](https://github.com/xun2z/MinnowBoardMaxFirmware/commit/70e17d172febc4d29c96cf594744f8cc2f3cf352) for building bios v1.00. But the sad news is that I still cannot wake up the DSP using the newly compiled efi and asl files.

After some research I might find the [cause](https://firmware.intel.com/sites/default/files/Intel_WhitePaper_Using_IOMMU_for_DMA_Protection_in_UEFI.pdf) (some DMA protection tactics) of this issue. I think this is the case because I passed on v0.97 and failed on v0.98. And It seems BIOS team has some changes with DMA this period

```
commit 767b1c4f5a0a6db5bbddc837bf1cd72168e25261
Bus Master DMA protection.
    
    (1) Clean up code which enables PCI Bus Master DMA before SMRAM lock. (2) Lock SMRAM before PCI bus enumeration at BDS stage.
```

I may look into this feature and do some work-around in the kernel next few days. 

So am I on the right way? @plbossart

**Comment by plbossart** [comment] 2019-03-30 01:08
@xun2z if the problem already happens with 0.98 then it's a rather problematic bug. the MinnowBoard firmware team is based in China, please check with them. If the BIOS introduced a regression it needs to be fixed.

**Closed as completed** 2020-01-09 00:54 UTC
Labels: bug, won't fix, BYT
