### ISSUE TITLE
Unrecoverable XRUN on speakers after HDMI hw_params error

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#391] opened 2018-12-07 00:57 UTC
This scenario may not be a valid sequence but it totally wrecks SOF on APL/Reef

1. boot and start a guest session, then start a YouTube channel in the browser, listen on the speakers
2. start an SSH command-line terminal and run speaker-test -Dhw:0,5 -c2 -r48000 (this is trying to play on HDMI without any prior configuration or UCM updates). speaker-test fails since the mixers are not correctly set. Precision: HDMI is not connected at all
3. watch the playback stop on speakers and a rain of underrun IPC happen with repeated messages such as 
[ 1047.596214] sof-audio sof-audio: ipc rx done: 0x60090001
[ 1047.597404] sof-audio sof-audio: ipc rx: 0x60090001
[ 1047.597446] sof-audio sof-audio: posn mailbox: posn offset is 0xc1000
[ 1047.597448] sof-audio sof-audio: posn XRUN: host 0 comp 2 size -192

In theory an error on one stream should not impact an existing one, and using a hw: device while CRAS is playing should either not work (device busy) or should have no impact.

Can someone, e.g. @cujomalainey @ranj063 try and reproduce this on GLK?

**Comment by mengdonglin** [comment] 2018-12-29 11:24
@plbossart 
@xiulipan had 2 FW PR to fix FW XRUN recovery. Could you check if this solution works for you?
https://github.com/thesofproject/sof/pull/755
https://github.com/thesofproject/sof/pull/757

**Comment by zhuyingjiang** [comment] 2019-04-03 07:43
@kv2019i I heard you have a Reef platform, could you verify if this issue is still valid?

**Comment by kv2019i** [comment] 2019-04-03 17:46
@zhuyingjiang wrote:
> @kv2019i I heard you have a Reef platform, could you verify if this issue is still valid?

Sure, I'll test this tomorrow. Haven't used HDMI yet with SOF, but this is probably a good case to learn with.

**Comment by kv2019i** [comment] 2019-04-04 11:17
@zhuyingjiang  @plbossart 
Tested this with tip of SOF fw (cbd3e07031bca60865ef6c6fd5f3b0c0d5fe296b) and could not reproduce the error (30+ tries with the recipe Pierre you provided).

I did not get XRUN on the FW logs though, so I'm not 100% sure I am triggering the issue in the same way. There are other errors in the FW log and this does not disrupt the primary audio stream that is playing youtube, so this seems to be working.

**Comment by zhuyingjiang** [comment] 2019-04-08 02:52
@kv2019i OK, thanks, so we can close this?

**Comment by kv2019i** [comment] 2019-04-10 08:29
@zhuyingjiang wrote:
> @kv2019i OK, thanks, so we can close this?

Better of course if we could get ack from @plbossart , but considering he is very busy atm, I think we can trust my tests and close this. I now got HDMI working (in general) as well and I retested this today on my UP2 board and could not trigger the error Pierre described.

**Closed as completed by kv2019i** 2019-04-10 08:29 UTC
Labels: bug, APL
