### ISSUE TITLE
Feedback path can not be setup

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/linux#4042] opened 2022-11-28 10:11 UTC
Below picture shows the current graph for IPC4 smart_amp,  in my testing, I found that the route setup call back is not called for the route copier.SSP.4.1->smart_amp.1.1. So I worked with bard and added some prints to debug it and found that the smart_amp widget is not present in the capture stream widget list. And current path go through routine only goes through the sink path for playback, and source path for capture, so that the feedback path is not connected.  https://github.com/thesofproject/linux/blob/62c1ccce6c6514a3ff8590156fbd7fff9d24586f/sound/soc/sof/sof-audio.c#L252

![cavs-smart-amp-nocodec](https://user-images.githubusercontent.com/52959957/204245725-1dcca037-9f15-473b-9744-401fe767d3a4.png)

Bard and I have tried to replace the end condition function  `dpcm_end_walk_at_be` with a function that never ends the walk,  but it doesn't help, the smart_amp widget is still not present in the capture stream widget list. 

We could add a widget go-through in the sink path for capture, but this seems not a good fix for the issue. Bard also comes with an idea to make the topology just like the smart_amp topology in IPC3, like this: 
![image](https://user-images.githubusercontent.com/52959957/204251318-3ca91c55-12c5-499d-9ca5-9add76123be1.png)

This worth a try if we don't have solution to fix the issue.

**Comment by ranj063** [comment] 2022-11-28 17:30
@aiChaoSONG This worked in IPC3 because the smart amp component was only part of static topologies right? So the connection was established unconditionally after boot.

But I have a suggestion for a simpler fix. The reason this route set up fails is because the smart_amp widget is not part of the list of DAPM widgets belonging to the capture PCM. https://github.com/thesofproject/linux/blob/62c1ccce6c6514a3ff8590156fbd7fff9d24586f/sound/soc/sof/sof-audio.c#L288

Maybe we can add a sof_comp_tkn to not ignore routes with widgets not in list and set it for the copier.SSP.4.1 so that when it comes to getting up the routes to all its sinks, we also set up the route in question.

**Comment by plbossart** [comment] 2022-11-28 23:28
@aiChaoSONG @ranj063 Can you clarify when we would need this copier.ssp.4.1->smart_amp.1.1 route to be setup?

If this when the copier.host.3.1 widget is setup, i.e. when the capture path is enabled? Or when the copier.host.1.1 is enabled?

I am also in the dark on what the benefit of adding a second copier.module.4.1 would be, wouldn't we have the same issue that there is no way to connect capture and playback widgets?

**Comment by ranj063** [comment] 2022-11-29 00:25
> If this when the copier.host.3.1 widget is setup, i.e. when the capture path is enabled? Or when the copier.host.1.1 is enabled?

Right, when the capture path is enabled is when we'd need this route set up. Thats why I'm suggesting to add the token to copier.SSP.4.1 so the route can be set up after this widget has been set up

> I am also in the dark on what the benefit of adding a second copier.module.4.1 would be, wouldn't we have the same issue that there is no way to connect capture and playback widgets?

This im not sure about @bardliao can you take this one?

**Comment by plbossart** [comment] 2022-11-29 00:35
> > If this when the copier.host.3.1 widget is setup, i.e. when the capture path is enabled? Or when the copier.host.1.1 is enabled?
> 
> Right, when the capture path is enabled is when we'd need this route set up. Thats why I'm suggesting to add the token to copier.SSP.4.1 so the route can be set up after this widget has been set up

What happens if the capture path is not opened then? Does this mean the smart-amp can't deal with feedback UNLESS the echo reference path is opened? This seems to make the 'hostless' case even more complicated, i.e. if the echo reference is fed into a DSP-enabled AEC module we don't have a solution at all for smart-amps?

**Comment by ranj063** [comment] 2022-11-29 00:43
> What happens if the capture path is not opened then? Does this mean the smart-amp can't deal with feedback UNLESS the echo reference path is opened? This seems to make the 'hostless' case even more complicated, i.e. if the echo reference is fed into a DSP-enabled AEC module we don't have a solution at all for smart-amps?

@plbossart I think the hostless case is going to require major changes to the topology for the smart-amp. If the feedback pipeline is hostless, we'd need to find a way to set up the pipeline widgets and trigger that pipeline whenever the playback stream is started. I'm not sure if that's within the scope of the work that Chao is targeting.

**Comment by plbossart** [comment] 2022-11-29 00:54
It's fine to implement the solutions in steps @ranj063 but we have to identify those steps and scope what is required.

Even outside of echo cancellation in the DSP, I am worried that the suggested solution is a regression compared to IPC3, I don't recall having seen a requirement or expectations that the echo reference PCM capture be opened to enable speaker protection. Unless I am gravely mistaken, our CI/sof-test scripts will open PCM devices completely independently/randomly, so I am not sure how the mockup smart-amp module was tested on CI devices.

**Comment by ranj063** [comment] 2022-11-29 01:12
> Even outside of echo cancellation in the DSP, I am worried that the suggested solution is a regression compared to IPC3, I don't recall having seen a requirement or expectations that the echo reference PCM capture be opened to enable speaker protection. Unless I am gravely mistaken, our CI/sof-test scripts will open PCM devices completely independently/randomly, so I am not sure how the mockup smart-amp module was tested on CI devices.

@plbossart I do not think we test the smart-amp tplg with IPC3 in our CI with the scope of testing the feature itself. Please correct me if I am wrong @aiChaoSONG. And I know for a fact that the chrome UCM has the hooks to start the feedback PCM whenever the playback stream is opened to make use of this feature.

**Comment by plbossart** [comment] 2022-11-29 01:17
@ranj063 even if the processing in the mockup smart-amp does absolutely nothing, we'd still need *something* that will test that the routes are created. And clearly I don't think that is possible with sof-test/CI, which begs the question if our tests are relevant ore not, and what exactly we can infer from our tests.

**Comment by ranj063** [comment] 2022-11-29 01:19
But @plbossart like I mentioned our IPC3 tests with smart-amp were with static pipelines. So all the routes were set up already.  IPC4 is different with dynamic pipelines.

**Comment by aiChaoSONG** [comment] 2022-11-29 02:15
> I am also in the dark on what the benefit of adding a second copier.module.4.1 would be, wouldn't we have the same issue that there is no way to connect capture and playback widgets?

@plbossart We thought that the smart_amp is not added to the capture widget list because we used `dpcm_end_walk_at_be` in getting connected widget to a DAI.  we think if we add a copier.module (demux) in between, we can have smart_amp in the capture widget list, this is wrong. From Ranjani, the IPC3 smart amp topology is good because it is static, not because it has a demux in between the DAI and smart_amp.

**Comment by aiChaoSONG** [comment] 2022-11-29 02:18
> I'm not sure if that's within the scope of the work that Chao is targeting.

Current plan is to let IPC4 smart_amp work just like IPC3 smart_amp

**Comment by aiChaoSONG** [comment] 2022-11-29 02:27
> I do not think we test the smart-amp tplg with IPC3 in our CI with the scope of testing the feature itself. Please correct me if I am wrong @aiChaoSONG.

@ranj063 @plbossart Actually, we had a topology for smart_amp test, (the test is enabled before, but disabled later) https://github.com/thesofproject/sof/blob/main/tools/topology/topology1/development/sof-tgl-nocodec-ci.m4, and we have a test case for dummy smart_amp: https://github.com/thesofproject/sof-test/blob/main/test-case/check-smart-amplifier.sh
what the test case does is find the two pipelines that connected to smart_amp, and do playback (sine wave) and capture simultaneously, we even have a python script to verify the wave.

**Comment by aiChaoSONG** [comment] 2022-11-29 05:51
> @aiChaoSONG This worked in IPC3 because the smart amp component was only part of static topologies right? So the connection was established unconditionally after boot.
> 
> But I have a suggestion for a simpler fix. The reason this route set up fails is because the smart_amp widget is not part of the list of DAPM widgets belonging to the capture PCM.
> 
> https://github.com/thesofproject/linux/blob/62c1ccce6c6514a3ff8590156fbd7fff9d24586f/sound/soc/sof/sof-audio.c#L288
> 
> Maybe we can add a sof_comp_tkn to not ignore routes with widgets not in list and set it for the copier.SSP.4.1 so that when it comes to getting up the routes to all its sinks, we also set up the route in question.

I don't think this is going to work, because we are checking if the widget's source widget (p->source) is in the list or not, but smart_amp is the sink widget of copier.SSP.4.1. we will need to visit the sink path for copier.SSP.4.1.

I think we can improve your simpler fix: if the token is set for a widget, let's visit the sink path for the widget, but `copier.SSP.4.1->copeir.host.3.1` will be setup twice, so we also set the token for smart_amp, we setup the route only if the token is set both for source and sink widgets.
@ranj063 what do you think?

**Comment by ranj063** [comment] 2022-11-29 06:10
@aiChaoSONG how about instead of using any tokens, you add widget flags for COPIER>SSP.4.1 and establish the connection from the copier to all its sinks in the widget binding function during the PRE_PMU event and take down the route during the PRE_PMD event? Something similar to what we do for the keyword detect component in IPC3 but instead of triggering we only setup/free the route for this case

**Comment by bardliao** [comment] 2022-11-29 13:43
> 
> > I am also in the dark on what the benefit of adding a second copier.module.4.1 would be, wouldn't we have the same issue that there is no way to connect capture and playback widgets?
> 
> This im not sure about @bardliao can you take this one?

I was wondering how does IPC3 work. I compared IPC3 and IPC4 topology and found that there is a demux in IPC3 topology but not in IPC4 topology. The copier.SSP.4.1 widget is associated with a BE and `snd_soc_dapm_dai_get_connected_widgets` will end at `copier.SSP.4.1`. So, I guess `smart_amp.1.1` might be added in the list if we add a `copier.module.1.1` between `copier.SSP.4.1` and `copier.host.3.1`.
Now I know it won't help after reading all those comments.
I agree with @ranj063 adding a flag to the widget is a good idea if we can't add smart_amp widget in the list.

**Comment by plbossart** [comment] 2022-11-29 17:16
> But @plbossart like I mentioned our IPC3 tests with smart-amp were with static pipelines. So all the routes were set up already. IPC4 is different with dynamic pipelines.

IPC3 is enabled with dynamic pipelines in all CI devices (HDA, nocodec, SoundWire). 

If we didn't do this for the smart-amp mockup test, then it's a miss in our test coverage. That would hardly be surprising, when we fork stuff it becomes abandonware.

**Comment by aiChaoSONG** [comment] 2022-11-30 06:26
> @aiChaoSONG how about instead of using any tokens, you add widget flags for COPIER>SSP.4.1 and establish the connection from the copier to all its sinks in the widget binding function during the PRE_PMU event and take down the route during the PRE_PMD event? Something similar to what we do for the keyword detect component in IPC3 but instead of triggering we only setup/free the route for this case

@ranj063 @bardliao My only concern is that the route `copier.SSP.4.1->smart_amp.1.1` will be setup twice, one in the normal route setup, one in the event handler, won't it cause trouble if a route is setup twice?

**Comment by bardliao** [comment] 2022-11-30 12:10
> > @aiChaoSONG how about instead of using any tokens, you add widget flags for COPIER>SSP.4.1 and establish the connection from the copier to all its sinks in the widget binding function during the PRE_PMU event and take down the route during the PRE_PMD event? Something similar to what we do for the keyword detect component in IPC3 but instead of triggering we only setup/free the route for this case
> 
> @ranj063 @bardliao My only concern is that the route `copier.SSP.4.1->smart_amp.1.1` will be setup twice, one in the normal route setup, one in the event handler, won't it cause trouble if a route is setup twice?

`copier.SSP.4.1->smart_amp.1.1` will not likely be setup twice, but `copier.SSP.4.1->copier.host.3.1` could be. IMHO, we should think about a way to prevent it.
Can we add the PRE_PMU and POST_PMD event on `smart_amp.1.1`, and only setup the connection on the reference input pin? Then, we probably won't need to add new flags.

**Comment by ujfalusi** [comment] 2022-11-30 12:43
If the DAPM route generated from the topology would be correct then with the graph in the initial comment we would _never_ be able to power off the DSP. Since it is not the case then my observation is stands that the DAPM we get is incorrect.
DAPM will power up things in a path between an input  and output.
`copier.SSP.4.1` -> `smart_amp.1.1` -> `copier.SSP.2.1`
`copier.SSP.4.1` is input
`copier.SSP.2.1` is output
and there is the `smart_amp.1.1` in between, which is not a switch, so there is a connection, which will power up the path and will never going to allow it powered down (no switch).

The thing is that SOF does not use or care about DAPM, we are running in PCM domain and our widgets are in the PCM path, DAPM is ignored and it works in some cases, but not in other.

On upx-i11 with the HDA topology I have this patch: 
[0001-PoC-ASoC-SOF-topology-DAPM-based-loopback-on-upx-i11.patch.txt](https://github.com/thesofproject/linux/files/10123122/0001-PoC-ASoC-SOF-topology-DAPM-based-loopback-on-upx-i11.patch.txt)

I is placing a switch between the HDA analog in / out copiers and it does bring up some widgets, but not in the order you would expect.
But the patch have other nice additions: it adds the events to all DAPM widget we create so I can see which event happens and when. Neat.
If you do a playback to HDMI: there will be 0 (zero) DAPM events, despite that we have DAPM widgets, but the DAPM is broken. This is perfectly fine as we don't care about DAPM, things work because we do our own "SOFDAPM" in the PCM stream domain.

You can also check the DAPM connections and statuses with
https://chromium.googlesource.com/chromiumos/third_party/adhd/+/refs/heads/master/scripts/asoc_dapm_graph
and you can see how incorrect our DAPM domain is.

Having said that:
The DAPM level of loopback also creates another level of interesting issues that it is run in (initially) in prepare phase, it is _independent_ of the PCM state (sort of, a PCM stream would introduce a new active input/output to trigger a DAPM walk), but it is still a possibility that you have an incomplete DAPM route and all components are in power down (in DAPM domain), but audio is still running (playback can, capture needs incoming data for the DMA).
So, to do a DAPM level loopback you need to prepare for a case when the path is up without any audio active, you need to specify audio formats for the DAI, get DMAs in the firmware to service the DAIs, get the components ticking internally in firmware without a host stream.
And you need to prepare for the fact that a widget can be triggered by independent paths (PCM, DAPM) and these needs to be in sync and work together.

Imho this can be only done if the tplg describes that
`copier.SSP.4.1` should always send the data out in two pins, one to `copier.host.3.1` and to `smart_amp.1.1`
When the playback path is active then the `smart_amp.1.1` should be described always receive two streams, one from `coper.host.1.1` and from `copier.SSP.4.1`, if the capture is not running, the smart amp should receive nothing from there and it has to be able to handle this.

Fixing our representation in DAPM domain is going to take a bit, afaik.

**Comment by plbossart** [comment] 2022-11-30 15:36
@ujfalusi @ranj063 the loopback issue with DAPM was observed on KBL with the smart-amp integration many moons ago. As you correctly pointed out, there is no switch between IV feedback on capture and the speaker output, so the DSP remains powered. This was solved by playing with the speaker DAPM pin, see https://github.com/thesofproject/linux/blob/3869d8a05995703b73b4deab2d97e18326c54f6d/sound/soc/intel/boards/kbl_da7219_max98927.c#L255

This is the only method I know of to avoid having the DAPM and PCM states handled independently. In earlier versions IIRC there was a kcontrol with a switch turned on/off in the UCM file when the endpoint was enabled, but that adds an external dependency on user-space setup.

````c
		switch (cmd) {
		case SNDRV_PCM_TRIGGER_START:
		case SNDRV_PCM_TRIGGER_RESUME:
		case SNDRV_PCM_TRIGGER_PAUSE_RELEASE:
			ret = snd_soc_dapm_enable_pin(dapm, pin_name);
			if (ret) {
				dev_err(rtd->dev, "failed to enable %s: %d\n",
				pin_name, ret);
				return ret;
			}
			snd_soc_dapm_sync(dapm);
			break;
		case SNDRV_PCM_TRIGGER_STOP:
		case SNDRV_PCM_TRIGGER_SUSPEND:
		case SNDRV_PCM_TRIGGER_PAUSE_PUSH:
			ret = snd_soc_dapm_disable_pin(dapm, pin_name);
			if (ret) {
				dev_err(rtd->dev, "failed to disable %s: %d\n",
				pin_name, ret);
				return ret;
			}
			snd_soc_dapm_sync(dapm);
			break;
		}

````
We also have this in the Maxim 98373 support with SOF for Chromebooks, see sof_maxim_common.c

**Comment by ranj063** [comment] 2022-11-30 16:43
> @ranj063 @bardliao My only concern is that the route `copier.SSP.4.1->smart_amp.1.1` will be setup twice, one in the normal route setup, one in the event handler, won't it cause trouble if a route is setup twice?

@aiChaoSONG im confused. Did you not raise this issue because this route was not getting set up? If so, why would it be set up twice?

**Comment by aiChaoSONG** [comment] 2022-12-01 10:01
> @aiChaoSONG im confused. Did you not raise this issue because this route was not getting set up? If so, why would it be set up twice?

@ranj063  My bad, I mean the route `copier.SSP.4.1->copier.host.3.1` will be setup twice, one in the normal route setup, one in the event handler, becuase
> you add widget flags for COPIER>SSP.4.1 and establish the connection from the copier to **ALL** its sinks in the widget binding function during the PRE_PMU event and take down the route during the PRE_PMD event

**Comment by ranj063** [comment] 2022-12-09 16:48
@aiChaoSONG a route cannot be setup twice. We have a flag in struct snd_sof_route, setup, that prevents this. What you can do is only have the PRE_PMU event to set up the route. The freeing of the route will be handled automatically when the feedback pipeline is torn down during hw_free

**Comment by aiChaoSONG** [comment] 2022-12-15 07:05
With below code in the end of `sof_setup_pipeline_connections()`, the feedback route will be setup at the second pipeline running. @bardliao  thanks.
```	
	list_for_each_entry(sroute, &sdev->route_list, list)
		if (sroute->src_widget->use_count && sroute->sink_widget->use_count &&
			!sroute->setup) {
			ret = sof_route_setup(sdev, sroute->src_widget->widget,
				sroute->sink_widget->widget);
			if (ret < 0)
				return ret;
		}
```

**Comment by plbossart** [comment] 2022-12-15 16:14
@aiChaoSONG it's very very scary to use unprotected use_count across different widgets.

**Comment by mengdonglin** [comment] 2023-01-04 06:45
Closing as  #4104 has been merged.

**Closed as completed by mengdonglin** 2023-01-04 06:45 UTC
Labels: bug, Smart Amp, dynamic pipeline
