### ISSUE TITLE
[BUG][CFL]Firmware load failed when system boot up.(Random)

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#940] opened 2019-05-14 10:08 UTC
**Describe the bug**
Sudo reboot to do system reboot, do aplay or arecord , error shows " load fw failed ret: -110" .

**To Reproduce**

1. Sudo reboot to do system reboot,
2. Do arecord via command "arecord -Dhw:0,0 -f dat wav/test1.wav"

**Expected behavior**
Bootup without any issues and arecord successfully.

**Impact**
Shows "error: load fw failed ret: -110 "

**Reproduce rate**
Random

**Test recipe**
linux (topic/sof-dev): 7271e69
sof (master): b73b9a6
topology: sof-hda-generic.tplg
Platform: CFL laptop with ALC3254 codec

dmesg
```
[   78.092494] sof-audio-pci 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[   78.093060] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x80000000 successful
[   78.093072] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0xf010e0e successful
[   78.093082] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x6000021 successful
[   78.093181] sof-audio-pci 0000:00:1f.3: error: no reply expected, received 0x0
[   81.093534] sof-audio-pci 0000:00:1f.3: FW Poll Status: reg=0x5000001 timedout
[   81.093544] sof-audio-pci 0000:00:1f.3: error: load fw failed ret: -110
[   81.093578] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
[   81.093586] sof-audio-pci 0000:00:1f.3: error: status = 0x00000000 panic = 0x00000000
[   81.093594] sof-audio-pci 0000:00:1f.3: unknown ROM status value 05000001
[   81.093599] sof-audio-pci 0000:00:1f.3: error: failed to reset DSP
[   81.093603] sof-audio-pci 0000:00:1f.3: error: failed to boot DSP firmware after resume -110
[   81.093623] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1
[   81.093627] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[   81.093630] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[   81.093632] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[   81.094216] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[   81.094230] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 1
[   81.094235] sof-audio-pci 0000:00:1f.3: generating page table for 00000000cd71a054 size 0xffc0 pages 16
[   81.094270] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[   81.094273] sof-audio-pci 0000:00:1f.3: periods:4
[   81.094297] sof-audio-pci 0000:00:1f.3: stream_tag 1
[   81.094309] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   81.401508] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60010000 size 108
[   81.401524] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[   81.401534] sof-audio-pci 0000:00:1f.3: error: status = 0x001c003c panic = 0x00000001
[   81.401543] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[   81.401553] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
[   81.401558] sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 1
[   81.401563] sof-audio-pci 0000:00:1f.3: ASoC: 0000:00:1f.3 hw params failed: -110
[   81.401569]  HDA Analog: ASoC: hw_params FE failed -110
[   81.401594] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 1
[   81.401600] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[   81.705508] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
[   81.705525] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[   81.705534] sof-audio-pci 0000:00:1f.3: error: status = 0x001c003c panic = 0x00000001
[   81.705543] sof-audio-pci 0000:00:1f.3: unknown ROM status value 01009701
[   81.705552] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00040000 mask 0x00000000
[   81.705944] sof-audio-pci 0000:00:1f.3: pcm: close stream 0 dir 1
```
[firmwareLoadfailed.log](https://github.com/thesofproject/linux/files/3177001/firmwareLoadfailed.log)
[firmwareLoadFailed_dmesg.log](https://github.com/thesofproject/linux/files/3177002/firmwareLoadFailed_dmesg.log)

**Comment by RanderWang** [comment] 2019-05-15 08:32
@YvonneYang2 This should be fixed by link dma refinement by @ranj063 https://github.com/thesofproject/linux/pull/895
It is a HDA issue, not a IPC timeout issue.

**Comment by lyakh** [comment] 2019-05-17 15:30
duplicate of #938

**Comment by wenqingfu** [comment] 2019-05-20 21:00
close as dup of #938

**Closed as completed by wenqingfu** 2019-05-20 21:00 UTC
Labels: bug, duplicate, HDA, CFL, IPC timeout
