### ISSUE TITLE
[BUG]Can't detect HDMI/DP unplug status when unplug HDMI/DP external port during suspending.

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#1364] opened 2019-10-24 10:21 UTC
**Describe the bug**
Can't detect HDMI unplug status when unplug HDMI external port during suspending.

**To Reproduce**
1.boot up with HDMI external port
2.run"amixer contents | less" and check the HDMI status.  
3.run "sudo rtcwake -m mem -s 10" then unplug HDMI during suspending.
4.run"amixer contents | less" and check the HDMI status after waking from suspending. 

**frequency**
100%

**Expected result**
 HDMI unplug status should be detected when unplug HDMI external port during suspending. 
After step 4, amixer HDMI jack detect value should be off

**Actual result**
1. Plug in HDMI external port ,then check amixer contents
```
numid=58,iface=CARD,name='HDMI/DP, pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
2. Unplug HDMI external port during s3, then wake up check amixer contents.
```
numid=58,iface=CARD,name='HDMI/DP, pcm=6 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
**Environment**
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 15f27d8
FW: https://github.com/thesofproject/sof/commits/master  commit: f277189
tplg: Same with FW branch, sof-icl-rt711-rt1308-rt715-hdmi.tplg  rename  to  sof-icl-rt711-rt1308-rt715.tplg
platform: ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode 
[dmesg.log](https://github.com/thesofproject/linux/files/3766965/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/3766966/logger.log)

**Comment by YvonneYang2** [comment] 2019-10-24 10:22
Issue can be reproduced on CML SDW Laptop with ALC711+ ALC1308+ ALC715 .

kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 15f27d8 + PR1359
FW: https://github.com/thesofproject/sof/commits/master  commit: f277189
tplg: Same with FW branch, sof-cml-rt711-rt1308-rt715.tplg
platform: CML SDW Laptop with ALC711+ ALC1308+ ALC715

**Comment by kv2019i** [comment] 2019-10-24 16:10
@sinahuang @YvonneYang2 Can you check output of 

cat /sys/kernel/debug/dri/0/i915_display_info 

... when the bug happens. E.g. is the i915 state updated when the bug happens. If it shows HDMI is still plugged, this is a i915 bug, if not, then it's ours.

**Comment by bardliao** [comment] 2019-10-25 01:59
@sinahuang @YvonneYang2 Could you check it on other platforms? It doesn't look like a SDW related issue.

**Comment by YvonneYang2** [comment] 2019-10-25 03:34
@kv2019i  Test it on CML SDW Laptop with ALC711+ ALC1308+ ALC715 
Step 1.  Boot up with HDMI externel port connected, but Connector in i915_display_info shows DP-2 type. 
```
connector 105: type DP-2, status: connected
```
Step 2.   Unplugged the HDMI external port during s3. i915 display_info shows as  below
```
connector 105: type DP-2, status: disconnected
```
So It seems like not a i915 issue. 

@bardliao  
Confirmed, it's not s SDW related issue. Check it on cml laptop with latest topic/sof-dev and master branch, issue can still be reproduced.

**Comment by YvonneYang2** [comment] 2019-10-28 09:57
Test it on CML laptop with legacy-HDA mode, issue cannot reproduced.
Issue can still be reproduced on CML laptop with latest master (78b022b)and topic/sof-dev (34562a4)branch. Test steps as below:

1. Boot up with DP external port connected.
2. Check amixer contents via "amixer contents | less" and i915_display_info via "cat /sys/kernel/debug/dri/0/i915_display_info", shows as below:
<details>
 <summary>amxier contents</summary>

````
numid=42,iface=CARD,name='HDMI/DP, pcm=13 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off 

````
</details>

<details>
 <summary>i915_display_info</summary>

````
connector 100: type DP-1, status: connected
        physical dimensions: 550x350mm
        subpixel order: Unknown
        CEA rev: 3
        DPCD rev: 11
        audio support: yes
        DP branch device present: no
        HDCP version: HDCP1.4

````
</details>
    
  3.  Unplug DP external port during s3. Check up amixer contents and i915_display_info again.
<details>
 <summary>amxier contents</summary>

````
numid=42,iface=CARD,name='HDMI/DP, pcm=13 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off 

````
</details>

<details>
 <summary>i915_display_info</summary>

````

connector 100: type DP-1, status: disconnected


````
</details>

dmesg:
[dmesg.log](https://github.com/thesofproject/linux/files/3778115/dmesg.log)

**Comment by bardliao** [comment] 2019-10-28 12:15
> Test it on CML laptop with legacy-HDA mode, issue cannot reproduced.
> Issue can still be reproduced on CML laptop with latest master (78b022b)and topic/sof-dev ([34562a4](https://github.com/thesofproject/linux/commit/34562a4ed17326dd7a7f7927bb0e6cf8f0484cac))branch. Test steps as below:
> 
> 1. Boot up with DP external port connected.
> 2. Check amixer contents via "amixer contents | less" and i915_display_info via "cat /sys/kernel/debug/dri/0/i915_display_info", shows as below:
> 
> amxier contents
> ```
> numid=42,iface=CARD,name='HDMI/DP, pcm=13 Jack'
>   ; type=BOOLEAN,access=r-------,values=1
>   : values=off 
> ```

@YvonneYang2 Looks like the status is already wrong in the step. 

> 
> i915_display_info
> ```
> connector 100: type DP-1, status: connected
>         physical dimensions: 550x350mm
>         subpixel order: Unknown
>         CEA rev: 3
>         DPCD rev: 11
>         audio support: yes
>         DP branch device present: no
>         HDCP version: HDCP1.4
> ```
> 
> 1. Unplug DP external port during s3. Check up amixer contents and i915_display_info again.
> 
> amxier contents
> ```
> numid=42,iface=CARD,name='HDMI/DP, pcm=13 Jack'
>   ; type=BOOLEAN,access=r-------,values=1
>   : values=off 
> ```
> 
> i915_display_info
> ```
> 
> connector 100: type DP-1, status: disconnected
> ```
> 
> dmesg:
> [dmesg.log](https://github.com/thesofproject/linux/files/3778115/dmesg.log)

**Comment by YvonneYang2** [comment] 2019-10-30 10:40
@bardliao 
Sorry, I attatched the wrong amixer contents info in step 2. 
Amixer contents after step 2 should be 
```
numid=42,iface=CARD,name='HDMI/DP, pcm=13 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

So step 2 are fine , error occurred in step 3.

**Comment by dengyangchao** [comment] 2019-11-04 01:51
1. Issue can be reproduced on 
CFL-S RVP HDA 
CML SDW Laptop with ALC711+ ALC1308+ ALC715 
ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode

2. Issue cannot be reproduced on 
GLK Chrome
CML Chrome
ICL RVP HDA
CML laptop with onboard ALC3204 in HDA mode
Note: Can't test on UP2, not support HDMI Jack detect on up2

**Environment**
Firmware: e5fe2ca2 https://github.com/thesofproject/sof/commits/master
Kernel:4e76b4a1 https://github.com/thesofproject/linux/commits/topic/sof-dev

For SDW:
Firmware: e5fe2ca2 https://github.com/thesofproject/sof/commits/master
kernel: 9f1bd5b https://github.com/thesofproject/linux/tree/integration/soundwire-latest

**Comment by plbossart** [comment] 2019-11-04 19:51
@dengyangchao @YvonneYang2 please retry with integration/soundwire-latest, all SDW machine drivers use @kv2019i hdmi common HDMI module.

**Comment by YvonneYang2** [comment] 2019-11-06 07:17
Issue cannot be reproduced on SDW machine drivers after using @kv2019i common HDMI module.

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 313bb6e 
FW: https://github.com/thesofproject/sof/commits/master  commit: 9b6ad970

Platforms:
CML SDW Laptop with ALC711+ ALC1308+ ALC715
CML RVP with codec ALC700 in SDW mode

Note:
Not tested it on TGL RVP with codec ACL711 in SDW mode, ALC1308 in I2S mode, since it's using no-hdmi SDW kernel, blocked by i915 issue.

**Comment by YvonneYang2** [comment] 2019-11-06 07:56
Close the issue since not reproduced.

**Closed as completed by YvonneYang2** 2019-11-06 07:56 UTC
Labels: bug, ICL, CML, suspend resume

**Comment by YvonneYang2** [comment] 2019-11-06 10:14
Other detect HDMI/DP issue on  ICL RVP, with codec ALC711 -RT1308, RT715 in SDW mode will track in https://github.com/thesofproject/linux/issues/1440
