### ISSUE TITLE
[BUG] [HDMI] setting on HDMI/DP pin will impact on other pins

### ISSUE THREAD

**Issue by libinyang** [thesofproject/linux#1077] opened 2019-07-04 09:03 UTC
If the pins are connecting to the same converter, setting on HDMI/DP pin will impact on other pins.
For example, if pin5-port1 and pin6-port0 are both connected to the cvt3. If we mute pin5-port1, pin6-port0 will be muted automatically. But muting pin6-port0 will not mute pin5-port1 automatically.

How to reproduce:
(in DPMST mode, 1 monitor is connected to pin5-port1, 1 monitor is connected to pin6-port0)
1. in alsamixer, set "pin5-port1 Mux" to "cvt 3", "pin6-port0 Mux" to "cvt 3"; unmute "hif5-1 Jack" and "hif6-0 Jack"
2. playback with aplay -Dhw:0,3 xxx
3. mute "hif5-1 Jack"
And you will find the monitor which is connected to pin6-port0 is also muted.

**Comment by libinyang** [comment] 2019-07-04 09:05
After these days debug, I found this is a HW defect. The driver is OK. The dmesg is OK, and no any errors occurs in the kernel. So I will not attach the useless dmesg log.

**Comment by kv2019i** [comment] 2019-07-12 11:15
@libinyang I'll take this to my name and start investigating how to tackle this.

**Comment by libinyang** [comment] 2019-07-15 05:52
@kv2019i We have root caused this bug. This is a HW limitation. If 2 pin connects to one converter, the setting on the 2 pins will impact on each other.

**Comment by kv2019i** [comment] 2019-08-16 15:12
It seems https://github.com/thesofproject/linux/issues/1123 is a feasible option to handle this limitation.

**Comment by kv2019i** [comment] 2019-09-12 18:14
https://github.com/thesofproject/linux/issues/1123 now ready for testing (take https://github.com/thesofproject/linux/pull/1155 and https://github.com/thesofproject/kconfig/pull/15 to test), should fix this bug

**Comment by YvonneYang2** [comment] 2019-09-16 08:41
Test DPMST on cml with test recipe as below, pins connect to the same converter, but pins setting is disabled in alsamixer. So cannot reproduce the issue. When do DPMST test, two DP monitors can output sound automatically without setting pins in alsamixer. 

Environment
Firmware: 2bd725d https://github.com/thesofproject/sof/commits/master
Kernel: 6cf9ef0 https://github.com/thesofproject/linux/commits/topic/sof-dev + PR1155 + thesofproject/kconfig#15
tplg: sof-hda-generic-2ch.tplg
platform: CML

**Comment by kv2019i** [comment] 2019-11-04 11:18
This bug is now fixed with #1404 and #1422

**Closed as completed by kv2019i** 2019-11-04 11:18 UTC
Labels: bug, enhancement, P1, reuse legacy HDMI codec
