### ISSUE TITLE
TGL; sound card binding fails with error "failed to ready HDA controller"

### ISSUE THREAD

**Issue by sathya-nujella** [thesofproject/linux#3078] opened 2021-08-03 02:42 UTC
**Error from dmesg:**
sof-audio-pci 0000:00:1f.3: error: get caps error
sof-audio-pci 0000:00:1f.3: error: failed to probe DSP -5
sof-audio-pci 0000:00:1f.3: error: sof_probe_work failed err: -5

**Test step to repro:**
This issue is happening only when: "google hotword capture path is OPEN + panic happened in DUT which prevented normal shutdown sequence".

**History for the issue:**
* https://github.com/thesofproject/linux/issues/2571
* PR# https://github.com/thesofproject/linux/pull/2768 DSP state will be put to D3 at shutdown to follow spec.

Earlier fix provided for this issue:
 Added shutdown call back to put DSP to D3 at the time of shutdown.

Why we are seeing the issue now:
  Some times DUT encountered non-audio related kernel panic. Because of this kernel did not do proper shutdown.
  So, audio driver could not perform putting DSP to D3 state.
  When some kernel panic happens, DUT rebooted and encountered this audio issue.

Now,
**WA accepted in Chrome 5.4 kernel:**
Do not enable D0i3 work
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3025608/
This kernel WA prevents the problem observed.

Google's comment:
Upstream is still susceptible to this issue. 
So, this WA can be accepted only for short term only. 

Based on this comment: creating this tracker for long term fix.

EDIT: internal issue 22012784321

**Comment by plbossart** [comment] 2021-08-03 20:06
This a tough one @sathya-nujella. We have a known requirement to execute the .shutdown callback to be able to reboot reliably. If anything non-audio interferes with this, the options are really really limited. I can't think of any turn-key proposal outside of 'fix the other drivers'...
@ranj063 any suggestions?

**Comment by plbossart** [comment] 2021-11-10 02:23
@sathya-nujella can you confirm when the  non-audio related kernel panic. Is this after the start of device_shutdown()?

@ranj063 I vaguely recall you mentioning that there might be a magic sequence we could use on the reboot part? if not we'd have to hack the shutdown() sequence to be done earlier, maybe with a reboot notifier

````c
static void kernel_shutdown_prepare(enum system_states state)
{
    blocking_notifier_call_chain(&reboot_notifier_list,
        (state == SYSTEM_HALT) ? SYS_HALT : SYS_POWER_OFF, NULL); <<< This is where we can add a callback to force the device to get out of D0i1
    system_state = state;
    usermodehelper_disable();
    device_shutdown(); <<< this is where we force the device to get out of D0i1 today, and it's not reached if there's a panic earlier.
}
````

**Comment by ranj063** [comment] 2021-11-10 03:36
> @ranj063 I vaguely recall you mentioning that there might be a magic sequence we could use on the reboot part? if not we'd have to hack the shutdown() sequence to be done earlier, maybe with a reboot notifier

@plbossart the magic sequence didnt quite work as expected and the HW team is still debugging further.

**Comment by marc-hb** [comment] 2021-11-12 02:32
> When some kernel panic happens, DUT rebooted 

@sathya-nujella  How is the DUT rebooted in that case?

(In 2011 there were at least 5 ways to reboot: https://mjg59.livejournal.com/137313.html )

**Comment by plbossart** [comment] 2022-06-29 20:27
@sathya-nujella there's been no update since November 2021, so closing this bug. If there's still an ask to fix something, please re-create an issue with a test that can be reproduced.

**Closed as completed by plbossart** 2022-06-29 20:27 UTC
Labels: P3, TGL
