### ISSUE TITLE
pcm suspend/resume cleanup

### ISSUE THREAD

**Issue by keyonjie** [thesofproject/linux#570] opened 2019-01-21 09:22 UTC
we should do it like this:
suspend:
1. send stream trigger stop IPC(to FW) in sof_pcm_trigger() when TRIGGER_SUSPEND arrive, and mark spcm->restore_stream[] to be true;
2. (after #1 done for all PCMs) send suspend IPC(context_save) to FW, and suspend ADSP.

resume:
1. send resume IPC(context_restore) to FW (after FW rebooted).
2. send stream trigger start IPC(to FW) in sof_pcm_trigger() when TRIGGER_RESUME arrive(if spcm->restore_stream[] is true), and mark spcm->restore_stream[] back to be false;

But now this is messed, we need cleanup it.

**Comment by keyonjie** [comment] 2019-01-21 09:23
@ranj063 can you do this?

**Comment by plbossart** [comment] 2019-01-22 16:45
@keyonjie can you try to be clearer in the description of issues? "this is messed [up]" does not describe what we are currently doing wrong and what your proposal solves.
remember the 3 steps: 
- what is the issue (visible/side effects)
- why the issue happens (root cause)
- how we can solve it (proposal).
Also why is this an "enhancement"?

**Comment by ranj063** [comment] 2019-01-22 20:40
@plbossart @keyonjie I am already working on this. This change is for addressing the following issue:
https://github.com/thesofproject/linux/issues/489
https://github.com/thesofproject/sof/issues/788

**Comment by ranj063** [comment] 2019-02-02 04:35
Fixed by #582

**Closed as completed by ranj063** 2019-02-02 04:35 UTC
Labels: enhancement
