### ISSUE TITLE
No Internal Speaker Sound on GML Kuu Yobook M with ES8336

### ISSUE THREAD

**Issue by pierro78** [thesofproject/linux#3365] opened 2022-01-11 19:16 UTC
NO SOUND on internal speaker or headphone, but i can hear a little sound at the beginning of the xfce session
(Gemini Lake (GML) n4020 Kuu Yobook M laptop)

**Environment :**
* xubuntu 22.04 / Kernel 5.16 from https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/
* SOF : 2:0:0-b678a

```
 $ lspci -nn |grep audio
00:0e.0 Multimedia audio controller [0401]: Intel Corporation Celeron/Pentium Silver Processor High Definition Audio [8086:3198] (rev 06)

```

alsa-info : http://alsa-project.org/db/?f=bc53fcb6eadd87bb7bdbc8c4b17ab34a032f7686

```
$ sudo dmesg | grep audio
[    6.010196] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    6.011055] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    6.113646] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    6.170758] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    6.229261] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[    6.233067] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    6.233074] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    6.233077] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    6.233085] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    6.274845] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    6.274855] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    6.274857] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    6.742136] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[    6.742144] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel

```

```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofessx8336 [sof-essx8336], device 0: ES8336 (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 5: HDMI 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 6: HDMI 2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofessx8336 [sof-essx8336], device 7: HDMI 3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```

Thanks !

**Comment by plbossart** [comment] 2022-01-11 19:21
looks like yet another duplicate of https://github.com/thesofproject/linux/issues/3336

please try to see if things improve with the quirk 

options snd-soc-sof-es8336 quirk=0x10

in /etc/modprobe.d/alsa-base.conf

and using the topology file suggested in https://github.com/thesofproject/linux/issues/3336#issuecomment-994933061

sof-glk-es8336-ssp0.tplg.gz unzipped and copied as /lib/firmware/inte/sof-tplg/sof-glk-es8336.tplg

**Comment by pierro78** [comment] 2022-01-11 19:34
thanks !

unfortunately it seems to be worse : 

```
#  dmesg | grep audio
[    5.143172] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    5.143449] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    5.193617] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    5.280652] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    5.308782] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[    5.313048] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    5.313056] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    5.313059] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    5.313065] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    5.370014] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    5.370024] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    5.370027] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    5.593197] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[    5.593205] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel
[    5.593230] sof-audio-pci-intel-apl 0000:00:0e.0: error: can't connect DAI SSP2.OUT stream SSP2-Codec
[    5.593232] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to add widget id 0 type 27 name : SSP2.OUT stream SSP2-Codec
[    5.593242] sof-audio-pci-intel-apl 0000:00:0e.0: error: tplg component load failed -22
[    5.593250] sof-audio-pci-intel-apl 0000:00:0e.0: error: failed to load DSP topology -22
[    5.593252] sof-audio-pci-intel-apl 0000:00:0e.0: ASoC: error at snd_soc_component_probe on 0000:00:0e.0: -22
```

**Comment by plbossart** [comment] 2022-01-11 19:36
the quirk wasn't used, as seen by the use of SSP2 above. This should be SSP0. try and reboot. You also need to make sure the .tplg file was indeed copied, there's a need to have an exact match between dailinks in machine driver and topology.

**Comment by pierro78** [comment] 2022-01-11 19:46
oops sorry

still no sound from internal speaker

"dmesg | grep audio" is good as in first post (it seems)

can I do sthg else now ? 

```


[    6.001386] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if info 0x040100
[    6.010101] sof-audio-pci-intel-apl 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    6.061910] sof-audio-pci-intel-apl 0000:00:0e.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    6.117653] sof-audio-pci-intel-apl 0000:00:0e.0: use msi interrupt mode
[    6.160062] sof-audio-pci-intel-apl 0000:00:0e.0: hda codecs found, mask 4
[    6.164267] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    6.164274] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    6.164277] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    6.164285] sof-audio-pci-intel-apl 0000:00:0e.0: unknown sof_ext_man header type 3 size 0x30
[    6.203935] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware info: version 2:0:0-b678a
[    6.203946] sof-audio-pci-intel-apl 0000:00:0e.0: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    6.203949] sof-audio-pci-intel-apl 0000:00:0e.0: warn: FW ABI is more recent than kernel
[    6.415047] sof-audio-pci-intel-apl 0000:00:0e.0: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[    6.415052] sof-audio-pci-intel-apl 0000:00:0e.0: warn: topology ABI is more recent than kernel

```

**Comment by plbossart** [comment] 2022-01-11 19:49
try the other suggested quirk
options snd-soc-sof-es8336 quirk=0x0

also try to play with alsamixer settings.

**Comment by pierro78** [comment] 2022-01-11 20:00
thanks again !

I tried alsamixer settings with the 2 quirks

but there doesn t seem to be a lot to play with (see picture : https://photos.app.goo.gl/UmvGHSKcTjbU6tWk6 )

thanks again if you can help me !

**Comment by plbossart** [comment] 2022-01-11 20:07
you have to unmute speaker and headphone with 'm'

**Comment by pierro78** [comment] 2022-01-11 20:27
thanks

I made sure my headphone and speaker were not mute with the 2 quirks and original (non touched) conf but still no joy

the strange thing is that alsamixer says "Intel Gemini Lake **HDMI**" and I want to play from the internal speaker/headphone
(but the headphone is detected by the way when I plug it in  : the left alsamixer headphone slider goes from "mute" to "whatever" I set it (although this doesnt work) ... )
(another strange thing is that there is no way that I can change the speaker volume as it is set to "0" when I "unmute" it and I can't change this "0")

any more help maybe ?

thanks again

**Comment by plbossart** [comment] 2022-01-11 20:29
if you are able to compile your kernel, maybe try https://github.com/thesofproject/linux/pull/3338 to see which interface is used. that would avoid the guesswork by using the information from ACPI tables.

Otherwise I have no other suggestions, this is a nightmare to support.

**Comment by pierro78** [comment] 2022-01-12 09:07
I tried with the custom kernel compiled by @yangxiaohua2009 ( see https://github.com/thesofproject/linux/issues/2955#issuecomment-1010654476 )

and it seems like things now work a little bit differently : "sudo dmesg | grep audio" now gives me a lot of lines (see http://alsa-project.org/db/?f=0246bb8c62bf49bc7f1d700a4162e5b1397b5f96 as it was really long) but it still doesn t seem to work ...
a strange thing is that when my headphones are unplugged then the xubuntu audiomixer says that the speakers are unavailable and when I plug them then the audiomixer says that my headphones are unplugged (but no sound from internal speaker) ...

alsamixer still says "Intel Gemini Lake **HDMI**"

thanks

**Comment by yangxiaohua2009** [comment] 2022-01-12 10:04
>and it seems like things now work a little bit differently : "sudo dmesg | grep audio" now gives me a lot of lines (see http://alsa-project.org/db/?f=0246bb8c62bf49bc7f1d700a4162e5b1397b5f96 as it was really long) but it still doesn t seem to work ...
a strange thing is that when my headphones are unplugged then the xubuntu audiomixer says that the speakers are unavailable and when I plug them then the audiomixer says that my headphones are unplugged (but no sound from internal speaker) ...



I see several widgets turned off. Use 
`amixer -c 0 sset 'Right Headphone Mixer Right DAC Switch' on` 
`amixer -c 0 sset 'Left Headphone Mixer Left DAC Switch' on` and `amixer -c 0 sset 'Headphone' on` to turn them on.
Please tell me if you can record voice. The CODEC need mclk to detect jack and play music. If the jack detection works, we are using SSP2 and both 'Speaker' and 'Headphone' is set to be on, then you should have sound. 
@pierro78

**Comment by pierro78** [comment] 2022-01-12 10:51
@yangxiaohua2009 

the 2 first commands failed :

```
pierro78@YOBOOK:~/sof/custom-kernel$ amixer -c 0 sset 'Right Headphone Mixer Right DAC Switch' on
amixer: Unable to find simple control 'Right Headphone Mixer Right DAC Switch',0

pierro78@YOBOOK:~/sof/custom-kernel$ amixer -c 0 sset 'Left Headphone Mixer Left DAC Switch' on
amixer: Unable to find simple control 'Left Headphone Mixer Left DAC Switch',0

pierro78@YOBOOK:~/sof/custom-kernel$ amixer -c 0 sset 'Headphone' on
Simple mixer control 'Headphone',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
pierro78@YOBOOK:~/sof/custom-kernel$
```

I tried to record sound with onlinemictest.com but it apparently fails ...

thanks if you can help me !

**Comment by pierro78** [comment] 2022-01-12 10:57
oh the right commands were :  

```
pierro78@YOBOOK:~/sof/custom-kernel$ amixer -c 0 sset 'Left Headphone Mixer Left DAC' on
Simple mixer control 'Left Headphone Mixer Left DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
pierro78@YOBOOK:~/sof/custom-kernel$ amixer -c 0 sset 'Right Headphone Mixer Right DAC' on
Simple mixer control 'Right Headphone Mixer Right DAC',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]
pierro78@YOBOOK:~/sof/custom-kernel$

```

it s working now ! 
thanks !

**Comment by pierro78** [comment] 2022-01-12 11:03
PS : oops microphone doesn t work (works in Windows though) @yangxiaohua2009

**Comment by pierro78** [comment] 2022-01-13 00:03
a "funny" thing is that I tried with the "regular" kernel ( https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/ ) again and the sound played but weaker ... and with the regular kernel there is not the bug in the audiomixer where it says that the speaker is unavailable (but works nonetheless) ...

but then with yangxiaohua2009's custom-kernel the sound didn't work anymore ... the speaker and headphones  disappeared from the audiomixer ... but I discovered they would reappear if I plugged the headphones in and out ...

PS : the sound is quite loud with yangxiaohua2009's custom-kernel ! louder than in Windows it seems ! :) 

PS2 : with yangxiaohua2009's custom-kernel it looks like I ve lost the microphone in the audiomixer (it was not working anyway ...)

**Comment by yangxiaohua2009** [comment] 2022-01-13 03:25
> a "funny" thing is that I tried with the "regular" kernel ( https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.16/ ) again and the sound played but weaker ... and with the regular kernel there is not the bug in the audiomixer where it says that the speaker is unavailable (but works nonetheless) ...
> 
> but then with yangxiaohua2009's custom-kernel the sound didn't work anymore ... the speaker and headphones disappeared from the audiomixer ... but I discovered they would reappear if I plugged the headphones in and out ...
> 
> PS : the sound is quite loud with yangxiaohua2009's custom-kernel ! louder than in Windows it seems ! :)
> 
> PS2 : with yangxiaohua2009's custom-kernel it looks like I ve lost the microphone in the audiomixer (it was not working anyway ...)

Does the general kernel work well for you? You may change volume using alsamixer or pavucontrol.

**Comment by pierro78** [comment] 2022-01-15 20:36
> Does the general kernel work well for you?

yes the kernel works well in general operations. thanks !

**Comment by pierro78** [comment] 2022-06-12 17:53
trying now with lubuntu 22.04 and kernel 5.18.3 : http://alsa-project.org/db/?f=f641b612306242aed8d50e9c497e653ef8b72a34

**Comment by pierro78** [comment] 2022-06-12 18:21
PS : I am not competent enough to understand the alsa-info http://alsa-project.org/db/?f=f641b612306242aed8d50e9c497e653ef8b72a34 output ...

I tried the 3 commands that worked in january : 

```
amixer -c 0 sset 'Left Headphone Mixer Left DAC' on
amixer -c 0 sset 'Right Headphone Mixer Right DAC' on
amixer -c 0 sset 'Headphone' on
```

but these don t seem to work for me this time : There s a click sound when the session manager starts and then I seem to only be able to hear some white noise in the headphone ...

**Comment by pierro78** [comment] 2022-06-15 16:43
trying now with endeavour os and kernel 5.19.rc2 http://alsa-project.org/db/?f=4f42b1eba9c3b7f04addc29b5f7083ce198d55bd ... apparently still same result ... I need to learn how to read the alsa-info ... thanks @yangxiaohua2009 if you can help me again

**Comment by yangxiaohua2009** [comment] 2022-06-16 01:52
@pierro78 Please run the make.sh and reboot.
[ucm.zip](https://github.com/thesofproject/linux/files/8914993/ucm.zip)
Or you can use these commands:

`amixer sset 'Headphone' 3,3`
`amixer sset 'DAC' 192,192`

to set maxium volume.

**Comment by pierro78** [comment] 2022-06-16 13:06
> @pierro78 Please run the make.sh and reboot. [ucm.zip](https://github.com/thesofproject/linux/files/8914993/ucm.zip)

thanks so much @yangxiaohua2009 : I've just run the make.sh and rebooted my ubuntu 22.04 with kernel 5.18.3 and I now have sound !  that s awesome !

(had less luck with archlinux (endeavouros) with kernel 5.19.0.rc2 although I have a very weak sound in the headphone when I set sound output to my speaker ...

PS : the commands : 
```
amixer sset 'Headphone' 3,3
amixer sset 'DAC' 192,192
```
were working only on ubuntu ... maybe because I don t seem to have some kind of alsa/Pulseaudio server installed on archlinux ....


PS2 : I have rebooted into archlinux and I now have stronger sound in the headphones with sound output selected to headphone ! (still no sound through speaker though)
)

**Comment by plbossart** [comment] 2022-08-08 09:07
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.

**Closed as completed by plbossart** 2022-08-08 09:07 UTC
Labels: codec, Community, codec ES8336
