### ISSUE TITLE
[BUG] NO SPEAKER or NO HDMI sound depending on snd-intel-dspcfg option for Cannon Point - LP with ES8336 on DEPO DPC156

### ISSUE THREAD

**Issue by realnickel** [thesofproject/linux#3412] opened 2022-02-03 12:16 UTC
Card ID:
`
00:1f.3 Multimedia audio controller [0401]: Intel Corporation Cannon Point-LP High Definition Audio Controller [8086:9dc8] (rev 30)`

CPU:     
`Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz`

When using mentioned laptop with kernel 5.10.9x (with a backported vendor driver for ES8336) I observe a situation when running by default or with

`option snd-intel-dspcfg dsp_driver=1`

there is no SOF support and only HDMI outputs are active

when run with 

`option snd-intel-dspcfg dsp_driver=3`

speakers and headphones operate, but there are no HDMI outputs.

When building a 5.16.3 kernel with following config options

```
CONFIG_SND_SOC_INTEL_SOF_ES8316_MACH=m
CONFIG_SND_SOC_INTEL_SOF_ES8336_MACH=m
[...]
CONFIG_SND_SOC_SOF_CANNONLAKE=m
CONFIG_SND_SOC_SOF_COFFEELAKE=m
```

and run with 

`option snd-intel-dspcfg dsp_driver=3`

there is no support for sound devices at all.

I'll collect additional info and extend the issue description soon.

It seems to me my issue has much in common with #3357 (concerning audio subsystem behaviour)

**Comment by plbossart** [comment] 2022-02-03 14:53
5.16.3 is definitively not going to work.

I don't know what the backported kernel is and why HDMI outputs are not there.

Please try PR https://github.com/thesofproject/linux/pull/3338 (need additional topologies listed in https://github.com/thesofproject/linux/pull/3338#issuecomment-1013246294)

**Comment by realnickel** [comment] 2022-02-08 17:40
@plbossart , thank you for your advice!
Which kernel version this PR is best applicable to?
I tried 5.17-rc3, but haven't succeeded yet. Patch adoption is needed.

**Comment by plbossart** [comment] 2022-02-08 21:37
@realnickel use the PR as is, it's already on top of 5.16-rc7 IIRC.

**Comment by realnickel** [comment] 2022-02-10 05:06
Still no luck applying PR patch set, but I managed to build your PR development branch with my settings.
Config and dmesg are attached, do not be confused with kernel version, it's just a fake one not to interfere with existing.
Additional topologies were added to those of version 2.0.
I still have to add 
`options snd-intel-dspcfg dsp_driver=3`
to start driver in SOF mode.

No devices were found in GUI, but aplay -l shows:

```
 $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 1: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 2: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

```
$ ls /proc/asound/card0/
codec#2  eld#2.1  eld#2.3  eld#2.5  eld#2.7  id     pcm2p
eld#2.0  eld#2.2  eld#2.4  eld#2.6  eld#2.8  pcm1p  pcm3p
```
[sof_codec_essx8336_on_Depo_notebook.zip](https://github.com/thesofproject/linux/files/8038216/sof_codec_essx8336_on_Depo_notebook.zip)

What else could be done to figure out issue root cause?

**Comment by plbossart** [comment] 2022-02-10 15:49
@realnickel unfortunately the dmesg log starts *after* the parts on the card creation, so I can't tell you what's happening.

Can you do the following:
in /etc/modprobe.d/alsa-base.conf add 

blacklist sof-audio-pci-intel-cnl

reboot, then do a dmesg -C, then modprobe sof-audio-pci-intel-cnl and capture the dmesg log immediately. That will help get the initial log. Then remove the blacklist.

Thanks!

**Comment by realnickel** [comment] 2022-02-11 09:29
@plbossart, sorry, I didn't notice before that head of dmesg log was missing.
Please refer to attached logs.
[modprobe_dsp3.log](https://github.com/thesofproject/linux/files/8047407/modprobe_dsp3.log)
[clean_snd_init_lsmod_dsp_3.log](https://github.com/thesofproject/linux/files/8047408/clean_snd_init_lsmod_dsp_3.log)
[clean_sound_init_dmesg_with_dyndebug_dsp_3.log](https://github.com/thesofproject/linux/files/8047409/clean_sound_init_dmesg_with_dyndebug_dsp_3.log)

**Comment by plbossart** [comment] 2022-02-11 15:48
@realnickel no idea what's going on. The code skips the creation of the sof_es8336 card and jumps to HDAudio.

can you try to apply the following diff to see what might happen:

````diff
diff --git a/sound/soc/sof/intel/hda.c b/sound/soc/sof/intel/hda.c
index 5d3cee13b008..35251af15865 100644
--- a/sound/soc/sof/intel/hda.c
+++ b/sound/soc/sof/intel/hda.c
@@ -1379,6 +1379,8 @@ struct snd_soc_acpi_mach *hda_machine_select(struct snd_sof_dev *sdev)
                        mach->mach_params.links = mach->links;
                        mach->mach_params.link_mask = mach->link_mask;
                }
+       } else {
+               dev_info(sdev->dev, "No ACPI/I2S machine found\n");
        }
 
        /*
````

install, reboot and see if this trace shows up.

**Comment by realnickel** [comment] 2022-02-11 15:51
Yes, surely, I'll try

**Comment by realnickel** [comment] 2022-02-16 01:19
@plbossart , it seems sound/soc/intel/common/soc-acpi-intel-cnl-match.c lacks information on ESSX8336.
Please refer to my test commit which made possible for me to have at least sound in phones : https://github.com/realnickel/sound/commit/cd2d1602bdec88b21f613342d2592a3a26501dc0 . 
I tested with sof-glk-es8336 topology, as there is no sof-cnl-es8336, but will try others also.
Any ideas for improvement?

**Comment by plbossart** [comment] 2022-02-16 02:27
good catch @realnickel, I didn't know there were CNL devices. that also means we need a change in intel-dspcfg. Gah.

The other point that you made me realize is that we can't use the same topology as GLK, this will not work because of clocking differences. I have to re-generate new topologies for this that use 24 MHz as the root clock for CML and CNL, not 19.2 MHz

**Comment by plbossart** [comment] 2022-02-16 02:51
@realnickel would you mind re-testing the updated PR #3338 with the new topologies for CML/CNL that need to be installed in /lib/firmware/intel/sof-tplg/

[es8336-topologies-3.tar.gz](https://github.com/thesofproject/linux/files/8076329/es8336-topologies-3.tar.gz)

edit: the topology PR is here https://github.com/thesofproject/sof/pull/5368

**Comment by realnickel** [comment] 2022-02-17 15:59
@plbossart , thanks for your support!
I retested both the updated PR https://github.com/thesofproject/linux/pull/3338 and the topology PR  https://github.com/thesofproject/sof/pull/5368 changes provided as an archive together.

Good news are that sound system starts in SOF mode without 
`option snd-intel-dspcfg dsp_driver=3`
and phones operate. 

[sof_mode_logs_wo_quirks.zip](https://github.com/thesofproject/linux/files/8090108/sof_mode_logs_wo_quirks.zip)


Bad news: I still can't get HDMI outputs to produce sound. And there is no any microphone by default.
In addition jack detection seems to be inverted.
That made me to play around with quirks. As codec seems to work with SSP0, I tried values 0x10...0x70 (changing bits 4-6).

It turned out that on my system bits 5 and 6 are mixed. 
SOF_ES8336_JD_INVERTED affects microphone detection and SOF_ES8336_ENABLE_DMIC affects jack detection.
But settings both bits simultaneously still results in inversion making external mic unavailable when headset is connected.
Should I consider adding GPIO quirk based on DMI data of laptop?

What concerns to HDMI, I noticed that topology file mentions only 3 hdmi nodes, while HDA mode (where HDMI playback works fine) has 5. Should SOF topology for Cannon Lake be extended?
[hda_hdmi_alsa-info.txt](https://github.com/thesofproject/linux/files/8090118/hda_hdmi_alsa-info.txt)

**Comment by plbossart** [comment] 2022-02-17 16:45
Good progress @realnickel thanks for testing.

> Bad news: I still can't get HDMI outputs to produce sound. 

If you are testing at the PulseAudio level, you would need an UCM file to use the right Jack.
otherwise you can use amixer -Dhw:0 controls to see something like this.

numid=33,iface=CARD,name='HDMI/DP,pcm=5 Jack'
numid=39,iface=CARD,name='HDMI/DP,pcm=6 Jack'
numid=45,iface=CARD,name='HDMI/DP,pcm=7 Jack'

then do amixer -Dhw:0 cget numid=33 
and see if the value is on/off

it's on , then use speaker-test -Dhw:0,5 -c2 -r48000 -f S16_LE

repeat for other numid and pcm.

> And there is no any microphone by default. In addition jack detection seems to be inverted. That made me to play around with quirks. As codec seems to work with SSP0, I tried values 0x10...0x70 (changing bits 4-6).
> 
> It turned out that on my system bits 5 and 6 are mixed. SOF_ES8336_JD_INVERTED affects microphone detection and SOF_ES8336_ENABLE_DMIC affects jack detection. But settings both bits simultaneously still results in inversion making external mic unavailable when headset is connected. Should I consider adding GPIO quirk based on DMI data of laptop?

ok, so one thing at a time. Do not touch the SOF_ES8336_ENABLE_DMIC part, you don't have dmics in this system.
You should only try  SOF_ES8336_JD_INVERTED that should only impact the headphone detection

you can try this manually with numid=27,iface=CARD,name='Headphone Jack'
plug you headphone, see the value, remove the headphone, recheck the value. That will tell you if the detection works or not.

For the speakers, you may or may not have to enable the TGL quirk for the GPIO
 
> What concerns to HDMI, I noticed that topology file mentions only 3 hdmi nodes, while HDA mode (where HDMI playback works fine) has 5. Should SOF topology for Cannon Lake be extended? [hda_hdmi_alsa-info.txt](https://github.com/thesofproject/linux/files/8090118/hda_hdmi_alsa-info.txt)

No, there are only 3 streams going into the display audio. Use what I indicated above.

**Comment by realnickel** [comment] 2022-02-18 06:24
@plbossart , thank you for the detailed guidance and you were totally right.

> then do amixer -Dhw:0 cget numid=33 and see if the value is on/off
> 
> it's on , then use speaker-test -Dhw:0,5 -c2 -r48000 -f S16_LE
> 
> repeat for other numid and pcm.

HDMI with numid=33 appeared to be muted, and it is not present in GUI controls interface.
Unmuting it with alsamixer and issuing:
`speaker-test -Dhw:0,5 -c2 -r48000 -f S16_LE`
resulted in successful sound test.
So could you point me to a good manual on how do I wire it's controls in system/GUI for software to be able to play sound  via HDMI.

**Comment by plbossart** [comment] 2022-02-18 18:00
@realnickel the jack controls are typically read-only, I don't get how you could unmute it. That might have been a different control, no?

**Comment by realnickel** [comment] 2022-02-21 08:33
> @realnickel the jack controls are typically read-only, I don't get how you could unmute it. That might have been a different control, no?

Yes, of course it was. 
My explanation might have been confusing, but first I used **alsamixer** (with it's pseudo-graphics GUI), which combines all controls for a node to unmute HDMI (S/PDIF).
In terms of **amixer** it was 

```
$ amixer -Dhw:0 cset numid=37 on
numid=37,iface=MIXER,name='IEC958 Playback Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=on
```

Finally, I was provided with an example of a solution ( to use UCM2 config files to describe audio devices for GUI), which made all subdevices selectable and visible to OS GUI. Even microphones operate. 
The only persisting problem : speakers remain silent no matter headset jack is plugged or not.
Working on that now.

**Comment by plbossart** [comment] 2022-03-03 00:27
@realnickel can you give these topologies a try, it seems we used the wrong MCLK_ID1 which doesn't exist on CannonLake... Oh well.

[es8336-topologies-4.tar.gz](https://github.com/thesofproject/linux/files/8173800/es8336-topologies-4.tar.gz)

**Comment by realnickel** [comment] 2022-03-09 06:33
> @realnickel can you give these topologies a try, it seems we used the wrong MCLK_ID1 which doesn't exist on CannonLake... Oh well.
> 
> [es8336-topologies-4.tar.gz](https://github.com/thesofproject/linux/files/8173800/es8336-topologies-4.tar.gz)

@plbossart, I tried to replace topology files and my setup still works like before. At least it seems to me so.
May be I am missing something I should pay attention for?

**Comment by plbossart** [comment] 2022-03-09 23:09
> > @realnickel can you give these topologies a try, it seems we used the wrong MCLK_ID1 which doesn't exist on CannonLake... Oh well.
> > [es8336-topologies-4.tar.gz](https://github.com/thesofproject/linux/files/8173800/es8336-topologies-4.tar.gz)
> 
> @plbossart, I tried to replace topology files and my setup still works like before. At least it seems to me so. May be I am missing something I should pay attention for?

Thanks for testing. It's possible that internally the registers are aliased and if you configure MCLK_ID1 you end-up configuring MCLK_ID0. Anyways, there's no regression so that's already good.

**Comment by realnickel** [comment] 2022-03-25 11:50
@plbossart, as for "backported vendor driver" mentioned by me at the top post, I grabbed pa-enable detection code from it and commit:
  https://github.com/realnickel/sound/commit/3574d6e683c94dbdf7d92bf24bb2a1b4eab3cfdc
  gives me working pa-enable detection and ability to control speakers.
  Unfortunately this code replaces current detection code and looks like a hack.
  In your opinion what is the best way to integrate this quirk into existing codebase?

**Comment by plbossart** [comment] 2022-03-25 16:03
I am not sure I understand this patch @realnickel. It looks like the GPIO is not exposed in ACPI at all? Have you tried with the two existing quirks for GPIO?

If indeed there's nothing, then we probably need to add a GPIO manually but that seems like a major hack to me.

**Comment by plbossart** [comment] 2022-08-08 09:06
Added recommended information in https://github.com/thesofproject/linux/wiki/ES8336-support

closing for now, please re-open an issue if the recommended setup doesn't work for you.

**Closed as completed** 2022-08-08 09:07 UTC
Labels: CNL, Community, codec ES8336
