### ISSUE TITLE
Missing topology sof-mtl-rt711.tplg

### ISSUE THREAD

**Issue by pjriot** [thesofproject/linux#5071] opened 2024-06-18 21:29 UTC
This is a help request. I seem to be hitting an issue with a OneXplayer X1 (Core 155h) on Fedora 40. Having read #4879 I waited until kernel 6.9 rolled out for Fedora before filing this issue. (I was hoping I was having a similar problem to the poster there)

```
$ uname -a

Linux vimes 6.9.4-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 12 13:33:34 UTC 2024 x86_64 GNU/Linux
```

After installing the [sof-dyndbg.conf.txt](https://github.com/thesofproject/linux/files/14760112/sof-dyndbg.conf.txt) file posted by @plbossart I get the following:

```
$ sudo dmesg | grep -E 'sof-audio-pci-intel-mtl|snd_hda_intel|cs35l56|sof_sdw|sof-audio-pci-intel-mtl|input|cs42l43-codec'
[    7.157601] input: Lid Switch as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:00/PNP0C09:00/PNP0C0D:00/input/input0
[    7.158471] input: Sleep Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input1
[    7.158831] input: Power Button as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input2
[    7.159046] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input3
[    7.643030] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input4
[    8.954808] input: Compx 2.4G Wireless Receiver as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.3/3-8.3:1.0/0003:25A7:FA7C.0001/input/input5
[    8.955637] hid-generic 0003:25A7:FA7C.0001: input,hidraw0: USB HID v1.10 Mouse [Compx 2.4G Wireless Receiver] on usb-0000:00:14.0-8.3/input0
[    8.958514] input: Compx 2.4G Wireless Receiver Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.3/3-8.3:1.1/0003:25A7:FA7C.0002/input/input6
[    9.010536] input: Compx 2.4G Wireless Receiver as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.3/3-8.3:1.1/0003:25A7:FA7C.0002/input/input7
[    9.011169] input: Compx 2.4G Wireless Receiver as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.3/3-8.3:1.1/0003:25A7:FA7C.0002/input/input8
[    9.012675] hid-generic 0003:25A7:FA7C.0002: input,hiddev96,hidraw1: USB HID v1.10 Keyboard [Compx 2.4G Wireless Receiver] on usb-0000:00:14.0-8.3/input1
[    9.173662] input: Nordic Semiconductor Air75 V2 Dongle as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4:1.0/0003:19F5:3247.0003/input/input9
[    9.229914] hid-generic 0003:19F5:3247.0003: input,hidraw2: USB HID v1.11 Keyboard [Nordic Semiconductor Air75 V2 Dongle] on usb-0000:00:14.0-8.4/input0
[    9.232535] input: Nordic Semiconductor Air75 V2 Dongle Keyboard as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4:1.1/0003:19F5:3247.0004/input/input10
[    9.288085] input: Nordic Semiconductor Air75 V2 Dongle Mouse as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4:1.1/0003:19F5:3247.0004/input/input11
[    9.288545] hid-generic 0003:19F5:3247.0004: input,hidraw3: USB HID v1.11 Keyboard [Nordic Semiconductor Air75 V2 Dongle] on usb-0000:00:14.0-8.4/input1
[    9.293800] hid-generic 0003:19F5:3247.0005: hiddev97,hidraw4: USB HID v1.11 Device [Nordic Semiconductor Air75 V2 Dongle] on usb-0000:00:14.0-8.4/input2
[   12.118523] input: NVTK0603:00 0603:F001 Touchscreen as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input12
[   12.119019] input: NVTK0603:00 0603:F001 Stylus as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input13
[   12.119415] input: NVTK0603:00 0603:F001 as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input14
[   12.119617] input: NVTK0603:00 0603:F001 as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input15
[   12.120149] hid-generic 0018:0603:F001.0006: input,hidraw5: I2C HID v1.00 Device [NVTK0603:00 0603:F001] on i2c-NVTK0603:00
[   12.318849] input: NVTK0603:00 0603:F001 as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input16
[   12.319616] input: NVTK0603:00 0603:F001 Stylus as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input17
[   12.320129] input: NVTK0603:00 0603:F001 UNKNOWN as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input18
[   12.320334] input: NVTK0603:00 0603:F001 UNKNOWN as /devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-NVTK0603:00/0018:0603:F001.0006/input/input19
[   12.320803] hid-multitouch 0018:0603:F001.0006: input,hidraw5: I2C HID v1.00 Device [NVTK0603:00 0603:F001] on i2c-NVTK0603:00
[   17.406148] input: Video Bus as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input20
[   24.441321] input: PC Speaker as /devices/platform/pcspkr/input/input21
[   25.710771] snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   25.710991] snd_hda_intel 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[   26.980868] sof-audio-pci-intel-mtl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040100
[   26.981054] sof-audio-pci-intel-mtl 0000:00:1f.3: SoundWire enabled on CannonLake+ platform, using SOF driver
[   26.981063] snd_sof_pci:sof_pci_probe: sof-audio-pci-intel-mtl 0000:00:1f.3: PCI DSP detected
[   26.981109] sof-audio-pci-intel-mtl 0000:00:1f.3: enabling device (0000 -> 0002)
[   26.982309] sof-audio-pci-intel-mtl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040100
[   26.982697] sof-audio-pci-intel-mtl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[   26.989752] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: checking for capabilities at offset 0xc00
[   26.989768] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: found ML capability at 0xc00
[   26.989775] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: checking for capabilities at offset 0x500
[   26.989784] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: found DRSM capability at 0x500
[   26.989791] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: checking for capabilities at offset 0x700
[   26.989800] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: found SPIB capability at 0x700
[   26.989807] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: checking for capabilities at offset 0x800
[   26.989816] snd_sof_intel_hda_common:hda_dsp_ctrl_get_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: found DSP capability at 0x800
[   26.990085] snd_sof_intel_hda_common:hda_dsp_stream_init: sof-audio-pci-intel-mtl 0000:00:1f.3: hda global caps = 0x1009a01
[   26.990094] snd_sof_intel_hda_common:hda_dsp_stream_init: sof-audio-pci-intel-mtl 0000:00:1f.3: detected 9 playback and 10 capture streams
[   26.990473] sof-audio-pci-intel-mtl 0000:00:1f.3: use msi interrupt mode
[   26.990482] snd_sof_intel_hda_common:hda_dsp_probe: sof-audio-pci-intel-mtl 0000:00:1f.3: using IPC IRQ 220
[   26.990928] snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000044
[   26.990945] snd_sof_intel_hda_common:hda_init_caps: sof-audio-pci-intel-mtl 0000:00:1f.3: PP capability, will probe DSP later.
[   26.993752] snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[   26.997957] snd_sof_intel_hda:hda_codec_detect_mask: sof-audio-pci-intel-mtl 0000:00:1f.3: codec_mask = 0x5
[   26.998027] snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[   26.998041] snd_sof:snd_sof_pci_update_bits_unlocked: sof-audio-pci-intel-mtl 0000:00:1f.3: Debug PCIW: 00000040 at  00000048
[   27.000622] snd_sof_intel_hda:hda_codec_probe: sof-audio-pci-intel-mtl 0000:00:1f.3: HDA codec #0 probed OK: response: 10ec0245
[   27.141910] snd_sof_intel_hda:hda_codec_probe: sof-audio-pci-intel-mtl 0000:00:1f.3: HDA codec #2 probed OK: response: 8086281d
[   27.193186] snd_intel_dspcfg:intel_nhlt_get_dmic_geo: sof-audio-pci-intel-mtl 0000:00:1f.3: dmic number 0 max_ch 0
[   27.193218] sof-audio-pci-intel-mtl 0000:00:1f.3: DMICs detected in NHLT tables: 0
[   27.193229] snd_sof_intel_hda_common:hda_sdw_machine_select: sof-audio-pci-intel-mtl 0000:00:1f.3: SoundWire machine driver sof_sdw topology sof-mtl-rt711.tplg
[   27.193239] sof-audio-pci-intel-mtl 0000:00:1f.3: hda codecs found, mask 5
[   27.201570] snd_sof:sof_test_topology_file: sof-audio-pci-intel-mtl 0000:00:1f.3: Failed to open topology file: intel/sof-ace-tplg/sof-mtl-rt711.tplg
[   27.201590] sof-audio-pci-intel-mtl 0000:00:1f.3: SOF firmware and/or topology file not found.
[   27.201597] sof-audio-pci-intel-mtl 0000:00:1f.3: Supported default profiles
[   27.201602] sof-audio-pci-intel-mtl 0000:00:1f.3: - ipc type 1 (Requested):
[   27.201610] sof-audio-pci-intel-mtl 0000:00:1f.3:  Firmware file: intel/sof-ipc4/mtl/sof-mtl.ri
[   27.201617] sof-audio-pci-intel-mtl 0000:00:1f.3:  Topology file: intel/sof-ace-tplg/sof-mtl-rt711.tplg
[   27.201623] sof-audio-pci-intel-mtl 0000:00:1f.3: Check if you have 'sof-firmware' package installed.
[   27.201628] sof-audio-pci-intel-mtl 0000:00:1f.3: Optionally it can be manually downloaded from:
[   27.201633] sof-audio-pci-intel-mtl 0000:00:1f.3:    https://github.com/thesofproject/sof-bin/
[   27.203067] snd_sof_intel_hda_common:mtl_enable_sdw_irq: sof-audio-pci-intel-mtl 0000:00:1f.3: FW Poll Status: reg[0x114c]=0x0 successful
[   27.205617] snd_sof_intel_hda_common:mtl_power_down_dsp: sof-audio-pci-intel-mtl 0000:00:1f.3: FW Poll Status: reg[0x1000]=0x0 successful
[   27.206768] sof-audio-pci-intel-mtl 0000:00:1f.3: error: sof_probe_work failed err: -2
[   79.667725] rfkill: input handler disabled
```

```
$ lspci -knn | grep -i -A3 audio                                                                                          
00:1f.3 Multimedia audio controller [0401]: Intel Corporation Meteor Lake-P HD Audio Controller [8086:7e28] (rev 20)
	DeviceName: Onboard - Sound
	Subsystem: Device [1f75:1602]
	Kernel driver in use: sof-audio-pci-intel-mtl
	Kernel modules: snd_hda_intel, snd_sof_pci_intel_mtl
00:1f.4 SMBus [0c05]: Intel Corporation Meteor Lake-P SMBus Controller [8086:7e22] (rev 20)
	DeviceName: Onboard - Other
```

I have installed the latest sof-firmware and alsa-ucm.

Could this be another case of misidentified hardware? (One interesting thing I've noticed is that I seem to be one of the only people running into this issue according to the OneXPlayer discord. I should note that sound works well in Windows)

Any pointers at all would be much appreciated!

**Comment by plbossart** [comment] 2024-06-19 06:08
This is an ACPI problem, the DSDT reports the presence of SoundWire interfaces but your platform is based on HDaudio only. These two lines are mutually incompatible.

````
[   27.193229] snd_sof_intel_hda_common:hda_sdw_machine_select: sof-audio-pci-intel-mtl 0000:00:1f.3: SoundWire machine driver sof_sdw topology sof-mtl-rt711.tplg
[   27.193239] sof-audio-pci-intel-mtl 0000:00:1f.3: hda codecs found, mask 5
````

This was reported already in https://github.com/thesofproject/linux/issues/4962 and the problem is fixed with commit 
5a7543d0ca01d68d992f480d151efd693807e0ce "ASoC: SOF: Intel: discard SoundWire configuration if HDaudio codec is reported", which will land in 6.10.

**Comment by pjriot** [comment] 2024-06-20 12:32
Gah, I missed that - thanks a lot for the explanation, very much appreciated!

**Closed as completed** 2024-06-20 12:35 UTC
Labels: duplicate, HDA

**Comment by pavlokozlenko** [comment] 2024-09-14 13:38
when will this fix come to arch or debian packages? how to track
