### ISSUE TITLE
RKL: soundcard is failed to be initialized for link error

### ISSUE THREAD

**Issue by RanderWang** [thesofproject/linux#2261] opened 2020-07-09 07:19 UTC
````
[  884.040113] skl_hda_dsp_generic skl_hda_dsp_generic: ASoC: error at snd_soc_card_add_dai_link on sof-hda-dsp: -22
[  884.040121] sof-audio-pci 0000:00:1f.3: ASoC: adding FE link failed
[  884.040125] sof-audio-pci 0000:00:1f.3: ASoC: topology: could not load header: -22
````
Now RKL GPU driver is not included in our kernel, so there is no HDMI support now. It failed at https://github.com/thesofproject/linux/blob/topic/sof-dev/sound/soc/intel/boards/skl_hda_dsp_generic.c#L83. @kv2019i Do you have any advice ?

**Comment by kv2019i** [comment] 2020-07-09 08:52
@RanderWang hmm, this is a new kind of error. Are you using an unmodified topology file and hda machine driver? 

Possible things to check:

- idisp codec is reported to be present even if driver is not in kernel (should not happen, but best to check):
       -> try with modprobe option: "options snd_sof_intel_hda_common codec_mask=0x1"

- in skl_hda_hdmi_add_pcm(), only thing that could fail seems to be snd_soc_card_get_codec_dai() ... can you print out what is the "dai_name" when the error happens?

**Comment by RanderWang** [comment] 2020-07-10 03:01
> @RanderWang hmm, this is a new kind of error. Are you using an unmodified topology file and hda machine driver?
> 
> Possible things to check:
> 
> * idisp codec is reported to be present even if driver is not in kernel (should not happen, but best to check):
>   -> try with modprobe option: "options snd_sof_intel_hda_common codec_mask=0x1"

I checked idsp codec is not enabled

> * in skl_hda_hdmi_add_pcm(), only thing that could fail seems to be snd_soc_card_get_codec_dai() ... can you print out what is the "dai_name" when the error happens?

dai_name = intel-hdmi-hifi0 and no such dai in sound card.  I checked hdmi in sof_sdw.  you added check 
````
sof_sdw_hdmi_card_late_probe  {
......
	if (!ctx->idisp_codec)
		return 0;
......
}
````
How about apply the idea to hda machine driver to skip creating hdmi pcm in this case ?

**Comment by kv2019i** [comment] 2020-07-10 09:37
@RanderWang Ok, interesting. It seems we have a regression in the HDA driver for this. I'm investigating what has happened.

**Comment by kv2019i** [comment] 2020-07-10 11:06
Ok, this is a regression in 5.8-rc :( ... I'm now bisecting what happened.

**Comment by kv2019i** [comment] 2020-07-10 19:39
Found it, it's this patch in 5.8-rc that breaks current HDA generic driver when i915 init fails:

cbc7a6b5a87a129084c643455d16699ea490fd2f
ASoC: soc-card: add snd_soc_card_add_dai_link()

... I'll make a fix on Monday.

**Comment by ClarexZhou** [comment] 2020-07-14 06:44
SOF can be loaded with this patch #2270 after workarround https://github.com/thesofproject/sof/issues/3173

**Comment by ClarexZhou** [comment] 2020-07-20 01:57
Close for PR #2270 is merged

**Closed as completed by ClarexZhou** 2020-07-20 01:57 UTC
Labels: bug, P1, HDA
