### ISSUE TITLE
[BUG][CML]Can't detect HDMI/DP via amixer contents after reboot with HDMI/DP connected

### ISSUE THREAD

**Issue by dengyangchao** [thesofproject/linux#1687] opened 2020-01-10 06:51 UTC
**Describe the bug**
Can't detect HDMI/DP after reboot with HDMI/DP connected. Amixer contents shows HDMI/DP ststus is OFF, but monitor display and sound output are OK. 
when issue reproduced then Check with command" cat /sys/kernel/debug/dri/0/i915_display_info ", and it shows monitor connected.

```
numid=88,iface=CARD,name='HDMI/DP,pcm=2 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=94,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
```
**To Reproduce**
1.Connect HDMI/DP monitor
2.Check HDMI/DP detection via"amixer contents |less", status are ON
3.Reboot system via "sudo reboot"
4.Wait runtime PM status to suspend
5.check HDMI/DP detection again via"amixer contents |less"

**Reproduction Rate**
3/3

**Expected behavior**
HDMI/DP detection is OK, and sound output normal

**Impact**
Can't detect HDMI/DP via amixer contents

**Environment**
Platform: CML Chrome with onboard codec RT5682 and RT1011 in I2S mode
Firmware: c6baa979 https://github.com/thesofproject/sof/commits/master
Kernel: 2ed00e58 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-cml-rt1011-rt5682.tplg same as firmware

[amixer.txt](https://github.com/thesofproject/linux/files/4044275/amixer.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/4044276/dmesg.log)
[logger.log](https://github.com/thesofproject/linux/files/4044277/logger.log)

**Comment by kv2019i** [comment] 2020-01-10 14:01
This seems similar (but not identical) to https://github.com/thesofproject/linux/issues/1440
I would expect this to be seen on other platforms as well.

**Comment by dengyangchao** [comment] 2020-01-13 02:06
@kv2019i #1440 only can be reproduced on platforms which are no EDP display connected.

This issue observed on a laptop, also tried this on other platforms, details below:

**Can be reproduced**
 CML Chrome with onboard codec RT5682 and RT1011 in I2S mode
**Can't be reproduced**
ICL-U RVP with onboard codec ALC700 in HDA mode
CML laptop with onboard codec ALC3204 in HDA mode
GLK Chrome with onboard codec DA7219 in I2S mode
APL-UP2 with codec PCM512X in I2S mode

**Comment by aiChaoSONG** [comment] 2020-02-17 09:22
@kv2019i can we be sure if this is i915 issue or sof issue from the below info?
Checked the two steps below:
1. add code to print message in intel_pin_eld_notify() and see if it's called
2. checked value of `changed` variable in `sync_eld_via_acomp()`

**Result:**
- after boot, hdmi jack is off
- intel_pin_eld_notify() is called on boot at 3.042636
- value of `changed` is changed from 1 to 0.
```
test@helios:~$ dmesg | grep CHANGED
[    3.042652] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 1
[   11.793571] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793572] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793573] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793575] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793576] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793577] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793578] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793578] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   11.793579] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815476] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815477] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815478] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815482] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815484] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815485] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815486] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815487] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.815488] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825951] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825953] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825954] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825957] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825958] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825959] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825960] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825961] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.825961] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840054] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840055] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840055] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840058] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840058] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840059] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840060] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840060] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
[   12.840061] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
```

**Comment by kv2019i** [comment] 2020-02-17 16:14
@aiChaoSONG Thanks for digging deeper into this. My suspicion is in this 4-patch series from Takashi:

adf615a605017089c8948f393087080e1b61b114 ALSA: hda/hdmi: Move ELD parse and jack reporting into update_eld()
ae47e2ec5b4504cd91968e97ce2dab4ccd346fb6 ALSA: hda/hdmi: Move runtime PM resume into hdmi_present_sense_via_verbs()
db8454023b7f9ca6d341cc83ce033a1f0e33d9c3 ALSA: hda/hdmi: Don't use standard hda_jack for generic HDMI jacks
165c0946a863cdfd056e472d8a9673d7197ef066 ALSA: hda/hdmi: Reduce hda_jack_tbl lookup at unsol event handling

Could you try reproduce with these four patches reverted  (you need to revert them in reverse order).

I was trying to reproduce this on APL and CFL today. but could not trigger similar behaviour. This matches with your report that this doesn't happen on all platforms. I'll try tomorrow with other platforms. If you could try the reverts.

**Comment by aiChaoSONG** [comment] 2020-02-18 05:19
@kv2019i after reverting these four patches in the latest kernel, I got the same result as above. in fact, I use linux-5.5rc6 to get the above result, and at the time of linux5.5rc6, there are no these four patches. you can seen this issue is from Jan 10th,  at that time, no these four patches either.

**Comment by kv2019i** [comment] 2020-02-18 15:55
Thanks @aiChaoSONG . So it's not the 4-patch series from Takashi. This starts to seem more and more like a drm issue indeed.

I think in your original log, this part is probably related to this problem:

[    4.787277] WARNING: CPU: 2 PID: 732 at /home/test/jenkins/workspace/kernel_build_template/sound/pci/hda/hda_codec.c:2523 snd_hda_spdif_ctls_unassign+0x45/0x50 [snd_hda_codec]

.... so we are getting some bogus info via eld_notify during boot. Unfortunately I still can't reproduce this myself.

Could you reproduce this once with full drm logs? Please add "drm.debug=0x1e" to kernel cmdline parameters.

**Comment by aiChaoSONG** [comment] 2020-02-19 03:36
@kv2019i  Hope these logs can help.
[with_hdmi_connected_kernel.log](https://github.com/thesofproject/linux/files/4222968/with_hdmi_connected_kernel.log)
[without_hdmi_connected_kernel.log](https://github.com/thesofproject/linux/files/4222970/without_hdmi_connected_kernel.log)

**Comment by kv2019i** [comment] 2020-02-21 11:54
@aiChaoSONG Interesting. Based on the logs, I think the display-audio driver communication looks ok and one monitor is reported to be connected:

Feb 19 11:32:09 helios kernel: [    2.989491] [drm:intel_audio_codec_enable [i915]] ELD on [CONNECTOR:111:DP-2], [ENCODER:110:DDI C]
Feb 19 11:32:09 helios kernel: [    2.989545] [drm:hsw_audio_codec_enable [i915]] Enable audio codec on transcoder B, 36 bytes ELD
Feb 19 11:32:09 helios kernel: [    2.989602] [drm:hsw_audio_config_update [i915]] using automatic Maud, Naud
Feb 19 11:32:09 helios kernel: [    2.989606] snd_hda_codec_hdmi ehdaudio0D2: INTEL_PIN_ELD_NOTIFY CALLED
Feb 19 11:32:09 helios kernel: [    2.989612] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 1

Later we refresh the state but do not change the state anymore:
Feb 19 11:32:17 helios kernel: [   11.692375] [drm:i915_audio_component_get_eld [i915]] Not valid for port B
Feb 19 11:32:17 helios kernel: [   11.692380] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692425] [drm:i915_audio_component_get_eld [i915]] Not valid for port B
Feb 19 11:32:17 helios kernel: [   11.692428] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692469] [drm:i915_audio_component_get_eld [i915]] Not valid for port B
Feb 19 11:32:17 helios kernel: [   11.692471] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692477] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692518] [drm:i915_audio_component_get_eld [i915]] Not valid for port C
Feb 19 11:32:17 helios kernel: [   11.692521] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692564] [drm:i915_audio_component_get_eld [i915]] Not valid for port C
Feb 19 11:32:17 helios kernel: [   11.692566] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692607] [drm:i915_audio_component_get_eld [i915]] Not valid for port D
Feb 19 11:32:17 helios kernel: [   11.692609] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692653] [drm:i915_audio_component_get_eld [i915]] Not valid for port D
Feb 19 11:32:17 helios kernel: [   11.692655] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0
Feb 19 11:32:17 helios kernel: [   11.692699] [drm:i915_audio_component_get_eld [i915]] Not valid for port D
Feb 19 11:32:17 helios kernel: [   11.692702] snd_hda_codec_hdmi ehdaudio0D2: VALUE OF CHANGED: 0

So the problem must be in publishing the results via amixer. This also means the bug is on the audio driver side. I'll try to figure out what could cause this.

**Comment by Liviali155** [comment] 2020-04-02 05:31
On CML laptop also reproduce this issue,but it is random,about 2/5
···
numid=20,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=26,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=32,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=17,iface=CARD,name='Headphone Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=18,iface=CARD,name='Headset Mic Phantom Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
···

Kernel: [97453d9] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
SOF:[2ef369d57][ https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2]
rename sof-cnl.ri to sof-cml.ri
tplg: [sof-hda-generic-2ch.tplg ]
Platform:[CML laptop with onboard codec ALC3204 in HDA mode]
PalseAudio Version: [13.99.1]
https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

[amixercontents0402.txt](https://github.com/thesofproject/linux/files/4419936/amixercontents0402.txt)
[dmesg0402.log](https://github.com/thesofproject/linux/files/4419937/dmesg0402.log)

**Comment by Liviali155** [comment] 2020-04-02 09:21
Test on CML Chrome with onboard codec RT5682 and RT1011 in I2S mode with latest /sof/dev(b8464d14)+master(5452ac56),issue still can be reproduced

**Comment by kv2019i** [comment] 2020-04-02 09:52
@Liviali155 wrote:
> Test on CML Chrome with onboard codec RT5682 and RT1011 in I2S mode with latest /sof/dev([b8464d1](https://github.com/thesofproject/linux/commit/b8464d1494c64652195ccd65e1a45ecc01042207))+master(5452ac56),issue still can be reproduced

Ack, this is likely still a separate bug. I'll continue debug on this.

**Comment by Liviali155** [comment] 2020-04-07 07:07
On CML laptop with latest sof/dev(052e45d7) +master(b4e8b1e4) +UCM2(https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp) also has this issue when reboot with DP/HDMI connected
```
numid=20,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=26,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=32,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=17,iface=CARD,name='Headphone Mic Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=18,iface=CARD,name='Headset Mic Phantom Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```
[amixercontentsfail.txt](https://github.com/thesofproject/linux/files/4442524/amixercontentsfail.txt)
[dmesg0407.log](https://github.com/thesofproject/linux/files/4442526/dmesg0407.log)
[sof-logger.log](https://github.com/thesofproject/linux/files/4442528/sof-logger.log)

**Comment by kv2019i** [comment] 2020-04-17 17:43
Started work on this again. I tried 10/10 with no success (i.e. no errors seen during test) on CML laptop with HDA codec. I wonder if I'm doing something differently in the sequence. One potential difference in setup is the I2S codec. I'll try next reproduce on this same laptop, but run the tests with external HDA codec disabled. This should mimic the HDA setup of the I2S board. If no success, I'll try setup a CML laptop with I2S codec.

**Comment by Liviali155** [comment] 2020-04-21 08:24
On  CML laptop with onboard codec ALC3204 in HDA mode the reproduce step as below:
1.sudo reboot
2.plug headset
3.sudo reboot with HDMI/DP connected

***Reproduction Rate***
5/5

Expected behavior
HDMI/DP detection is OK, and sound output normal

Impact
Can't detect HDMI/DP via amixer contents, and there is no" HDMI2/DP2 Output-sof-hda-dsp"  item of Output Device in sound settings, but has sound output and monitor display normal
If unplug headset then reboot with HDMI/DP connected,error not seen

[amixerfailed.txt](https://github.com/thesofproject/linux/files/4508577/amixerfailed.txt)
[amixerpass.txt](https://github.com/thesofproject/linux/files/4508579/amixerpass.txt)
[dmesg0421.log](https://github.com/thesofproject/linux/files/4508581/dmesg0421.log)
[sof-logger0421.log](https://github.com/thesofproject/linux/files/4508583/sof-logger0421.log)


<img width="450" alt="Capture" src="https://user-images.githubusercontent.com/56707932/79841723-6945f600-83ea-11ea-9e71-270bfce183b6.PNG">

Platform: CML laptop with onboard codec ALC3204 in HDA mode
Firmware: v1.5-rc3 (49cba21)+ PR2827(to fix #2810 EQ issue )
Kernel: stable linux 5.5.9 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.9, commit 81b6e04c4b
Topology: file: tools/topology/sof-hda-generic-2ch.tplg same as firmware

on sof/dev (f17b96ae)+master(504ec438) also has this issue

**Comment by kv2019i** [comment] 2020-04-21 09:05
@Liviali155 @dengyangchao Hmm. I wonder what I'm doing different. I now have CML laptops with both HDA audio codec and one with I2S codec, and I still can't reproduce the problem.

Some questions on the flow:
 - do you have the display lid closed (so that laptop output only goes to DP/HDMI monitor)?
 - any difference whether monitor is connected via DP (USB-C or DP connector) or native HDMI?
 - do you have autologin (you need to enter password) or does the DUTs boot directly into desktop?

I'll continue to try reproduce this today and will variate the above variables. I'll also try with more monitors just in case that has some impact.

**Comment by Liviali155** [comment] 2020-04-21 09:33
> @Liviali155 @dengyangchao Hmm. I wonder what I'm doing different. I now have CML laptops with both HDA audio codec and one with I2S codec, and I still can't reproduce the problem.
> 
> Some questions on the flow:
> 
> * do you have the display lid closed (so that laptop output only goes to DP/HDMI monitor)?
> * any difference whether monitor is connected via DP (USB-C or DP connector) or native HDMI?
> * do you have autologin (you need to enter password) or does the DUTs boot directly into desktop?
> 
> I'll continue to try reproduce this today and will variate the above variables. I'll also try with more monitors just in case that has some impact.

1.I did not closed the display lid
2.I used Type c DP and native HDMI ,because I have no other device
<img width="188" alt="dp" src="https://user-images.githubusercontent.com/56707932/79850182-20943a00-83f6-11ea-8ce2-815483247a07.PNG">
<img width="133" alt="hdmi" src="https://user-images.githubusercontent.com/56707932/79850197-2427c100-83f6-11ea-9439-d5908c4a6e3b.PNG">

3.My dut boot directly into desktop，But after disable autologin,issue still can be reproduced

**Comment by YvonneYang2** [comment] 2020-04-21 09:58
Issue can be reproduced on CML chromebook with I2SRT5682 which only support Type-C port.
DP or HDMI can both reproduce the issue.  Boot up with autologin.
HDMI: native HDMI external port + Type-c converter port.
DP: native DP external type-c port.
Reproduce rate: 100%

amixer contents cannot detect connected status:
```
numid=88,iface=CARD,name='HDMI/DP,pcm=2 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=94,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=100,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=82,iface=MIXER,name='Headphone Jack Switch'
  ; type=BOOLEAN,access=rw------,values=1
  : values=off
```

/sys/kernel/debug/dri/0/i915_display_info shows it detected.
```
[CONNECTOR:112:DP-2]: status: connected
	physical dimensions: 530x300mm
	subpixel order: Unknown
	CEA rev: 3
	DPCD rev: 12
	audio support: yes
	DP branch device present: yes
		Type: HDMI
		ID: 176GB0
		HW: 1.0
		SW: 7.38
		Max TMDS clock: 600000 kHz
		Max bpc: 12
	HDCP version: HDCP1.4 
```
Unplug the external port and replug in, issue can be recovered.
[amixer.after.txt](https://github.com/thesofproject/linux/files/4509139/amixer.after.txt)
[i915_after.txt](https://github.com/thesofproject/linux/files/4509140/i915_after.txt)

**Comment by kv2019i** [comment] 2020-04-21 19:17
Thanks @YvonneYang2 and @Liviali155 ! I could now reproduce this one on my CML I2S laptop, so I can proceed debug. It seems the reproduction rate is lower, but that's not a problem -- it's enough I can reproduce now.

**Comment by kv2019i** [comment] 2020-04-23 12:54
Good news, I think I found the rootcause for this bug and it's a clear bug on the audio side. I don't yet have a working bugfix, but will be posting one soon.

**Comment by kv2019i** [comment] 2020-04-27 14:36
@YvonneYang2 @Liviali155 Ok now I have a fix candidate as #2057 . Could you please test and see if the problem still occurs?

**Comment by Liviali155** [comment] 2020-04-28 02:08
> @YvonneYang2 @Liviali155 Ok now I have a fix candidate as #2057 . Could you please test and see if the problem still occurs?

Tried with PR #2057 on CML laptop with onboard codec ALC3204 in HDA mode,error not seen

**Comment by YvonneYang2** [comment] 2020-04-28 02:38
Tried with PR #2057 on CML chromebook with I2S RT5682, error not seen.

**Comment by kv2019i** [comment] 2020-04-28 11:57
@Liviali155 @YvonneYang2 Thank you, that is excellent news! This has been a tough bug to root out, but it seems we have both a rootcause and a fix now. I'll be sending a patch to upstream and will backport to sof-dev immediately when I get the approval. PS And thanks to @dengyangchao and @aiChaoSONG  as well!

**Comment by kv2019i** [comment] 2020-04-28 14:34
Merged upstream now. Let's keep this open until we do the next rebase and get the patch to sof-dev. That is probably sufficient and a separate backport is not needed.

**Comment by ClarexZhou** [comment] 2020-04-30 09:55
Error can be reproduced on TGL HDA laptop with AL3204 codec. 
And no HDMI output option when boot up with HDMI connected.

**Comment by Liviali155** [comment] 2020-05-14 03:31
Error not seen with latest sof-dev(a43e72a3) +Master(83cecc95) on matins,because PR #2098 merged

**Comment by ClarexZhou** [comment] 2020-05-14 03:48
Error not occurred on TGL HDA laptop with AL3204 codec with latest sof-dev(a43e72a) +Master(83cecc95)

**Comment by sinahuang** [comment] 2020-05-14 03:55
Error not occurred on CML Chrome with onboard codec RT5682 and RT1011 in I2S mode with sof-dev(commit: a43e72a3) and master (commit:83cecc95)

**Comment by Liviali155** [comment] 2020-05-14 03:58
closed it

**Closed as completed by Liviali155** 2020-05-14 03:58 UTC
Labels: bug, P2, CML, I2S
