### ISSUE TITLE
Up2/nocodec: IPC error with 4 playback streams

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#669] opened 2019-02-22 17:58 UTC
100% reproducible error with the FORCE_NOCODEC config and HDAudio removed.
3 streams can be supported, the 4th one fails during the trigger step.
This happens with topic/sof-dev as well as the simplified IPC.

````
[   84.693563] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   84.693824] sof-audio-pci 0000:00:0e.0: ipc tx succeeded: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[   84.695155] sof-audio-pci 0000:00:0e.0: pcm: trigger stream 5 dir 0 cmd 1
[   84.695169] sof-audio-pci 0000:00:0e.0: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[   84.695738] sof-audio-pci 0000:00:0e.0: error: ipc error for 0x60040000 size 0xc
[   84.696154]  Port5: ASoC: trigger FE failed -12
````

**Comment by plbossart** [comment] 2019-02-22 21:25
This may actually be a firmware issue
kernel: ee19d24e26c7e8cb193bfb72cce27561ec281c92
firmware: 4d715e060dcba1a40d1dd0138e148f717eb109ea
[sof-logger.txt](https://github.com/thesofproject/linux/files/2895865/sof-logger.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/2895866/dmesg.log)

steps to reproduce:
open 4 SSH terminals and use 
speaker-test -Dhw:0,0 -c2 -r48000 -t sine
speaker-test -Dhw:0,1 -c2 -r48000 -t sine
speaker-test -Dhw:0,3 -c2 -r48000 -t sine
speaker-test -Dhw:0,5 -c2 -r48000 -t sine

**Comment by plbossart** [comment] 2019-03-04 22:33
@mengdonglin can we get someone assigned, this will soon gate the IPC hardening that @lyakh is working on and prevent stress-tests from working.

**Comment by plbossart** [comment] 2019-03-24 17:58
@lyakh is this configuration with 4 streams functional on Up2? Thanks!

**Comment by wenqingfu** [comment] 2019-03-29 14:46
@juimonen would you be able to take this?

**Comment by juimonen** [comment] 2019-03-29 14:53
@wenqingfu sure I'll take a look

**Comment by juimonen** [comment] 2019-04-01 06:34
@plbossart with latest codes, I can reproduce this in up2 with nocodec but with 4th stream I get:
 src/drivers/dw/dma.c:1396	DWDMA failed to allocate IRQ, error -12
which is ENOMEM

**Comment by juimonen** [comment] 2019-04-01 06:40
@plbossart and now when looking at your log, is exactly the same as you get :)

**Comment by zhuyingjiang** [comment] 2019-04-01 07:00
Should this be a firmware issue? I see in the sof-logger.txt there is: `DWDMA failed to allocate IRQ`,
if open streams more than 3, the log will come out. and the 4th stream then will be stopped

**Comment by juimonen** [comment] 2019-04-01 07:02
@zhuyingjiang so we just run out of memory in firmware?

**Comment by zhuyingjiang** [comment] 2019-04-01 07:07
@juimonen  the `interrupt_register` failed, need to debug into to found what is the problem.

**Comment by juimonen** [comment] 2019-04-01 07:08
@zhuyingjiang I already did see above. It is rzalloc failing...

**Comment by juimonen** [comment] 2019-04-01 07:09
@zhuyingjiang so move to firmware and see are we really out of mem, can we change the mem map etc.

**Comment by juimonen** [comment] 2019-04-09 20:00
@michalgrodzicki can you assign to someone in firmware team to check if this is just valid out of memory error or something else?

**Comment by juimonen** [comment] 2019-04-11 10:19
@abonislawski @dabekjakub I saw you we're doing something with fw memory... could you check this issue from fw side?

**Comment by dabekjakub** [comment] 2019-04-12 07:23
We will try to set up this topology and check what is happening - however first question - what is the requirement here ? How many streams should we support ?

**Comment by juimonen** [comment] 2019-04-12 07:28
@dabekjakub good question and I don't have answer... So my point was that see are we really running out of memory or it is some corruption etc. If we run out of memory we can decide what to do...
Also I don't have so much history to tell if this has worked before.

@lgirdwood @plbossart how many streams should we support?

**Comment by plbossart** [comment] 2019-04-12 15:12
On 4/12/19 2:28 AM, juimonen wrote:
> @dabekjakub <https://github.com/dabekjakub> good question and I don't 
> have answer... So my point was that see are we really running out of 
> memory or it is some corruption etc. If we run out of memory we can 
> decide what to do...
> Also I don't have so much history to tell if this has worked before.
> 
> @lgirdwood <https://github.com/lgirdwood> @plbossart 
> <https://github.com/plbossart> how many streams should we support?

We have 6 SSPs so in theory we could use 6 playback streams.
We reduced to 4 due to a limitation in the number of DMA channels.
So the ask is really to clarify what firmware can do instead of failing 
miserably on the 4th stream. If there is a strong technical reason why 
4ch can't be supported we'd need to know. If however it's a bug then it 
needs to be fixed.

**Comment by dabekjakub** [comment] 2019-04-15 11:02
We will be trying to reproduce it tomorrow.

**Comment by dabekjakub** [comment] 2019-04-18 12:36
@michalgrodzicki Could You assign a developer here ? We had little luck with @wwittbrx getting sick and I will be on vacation next week. However someone should take a look at this.

**Comment by dabekjakub** [comment] 2019-04-19 13:57
I had to pass the issue to @wwittbrx for reproduction but he fell ill. We are waiting for his return.

**Comment by wwittbrx** [comment] 2019-04-23 08:19
Hi, this issue seems to be fixed with PR https://github.com/thesofproject/sof/pull/1294. Could you check it on your side so we could close it (after the PR is merged of course)?

**Comment by plbossart** [comment] 2019-04-23 19:57
@wwittbrx is this fixed or it does #1294 just make the problem go away by reducing the memory footprint?
Looks like working-by-accident instead of by design. try to play on 5 streams and the problem will come back...

**Comment by YvonneYang2** [comment] 2019-05-13 01:59
Reproduced the bug during modules reload stress test

**env as below**:
Rander UCM https://github.com/RanderWang/intel-UCM
Kernel repo：d698c4f https://github.com/thesofproject/linux/tree/release/sof-v5.0
Firmware repo: 030c81c https://github.com/thesofproject/sof/commits/master |
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

**dmesg log**
```
[ 1249.243017] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60040000 size 12
[ 1249.243030] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[ 1249.243234] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[ 1249.243246] sof-audio-pci 0000:00:1f.3: error: host status 0x80000000 dsp status 0x90020000 mask 0x00000003
[ 1249.243250] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[ 1249.243256]  HDA Analog: ASoC: trigger FE failed -110
[ 1249.243265] sof-audio-pci 0000:00:1f.3: pcm: trigger stream 0 dir 0 cmd 0
[ 1249.243279] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 1249.243426] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1249.243452] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x60050000: GLB_STREAM_MSG: TRIG_STOP
[ 1249.243465] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1249.243540] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1249.243566] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1249.244097] sof-audio-pci 0000:00:1f.3: pcm: open stream 0 dir 1
[ 1249.244103] sof-audio-pci 0000:00:1f.3: period min 192 max 16384 bytes
[ 1249.244107] sof-audio-pci 0000:00:1f.3: period count 2 max 16
[ 1249.244110] sof-audio-pci 0000:00:1f.3: buffer max 65536 bytes
[ 1249.244309] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[ 1249.244319] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 1
[ 1249.244323] sof-audio-pci 0000:00:1f.3: generating page table for 000000004b1f1fd2 size 0xffc0 pages 16
[ 1249.244364] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[ 1249.244366] sof-audio-pci 0000:00:1f.3: periods:4
[ 1249.244390] sof-audio-pci 0000:00:1f.3: stream_tag 2
[ 1249.244400] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
[ 1249.547017] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60010000 size 108
[ 1249.547030] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[ 1249.547296] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[ 1249.547310] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 1249.547314] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[ 1249.547318] sof-audio-pci 0000:00:1f.3: error: hw params ipc failed for stream 2
[ 1249.547323] sof-audio-pci 0000:00:1f.3: ASoC: 0000:00:1f.3 hw params failed: -110
[ 1249.547330]  HDA Analog: ASoC: hw_params FE failed -110
[ 1249.547349] sof-audio-pci 0000:00:1f.3: pcm: free stream 0 dir 1
[ 1249.547355] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60030000: GLB_STREAM_MSG: PCM_FREE
[ 1249.729414] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[ 1249.729437] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
[ 1249.851030] sof-audio-pci 0000:00:1f.3: error: ipc timed out for 0x60030000 size 12
[ 1249.851048] sof-audio-pci 0000:00:1f.3: status: fw entered - code 00000005
[ 1249.851304] sof-audio-pci 0000:00:1f.3: error: unexpected fault 0x00000000 trace 0x00004000
[ 1249.851317] sof-audio-pci 0000:00:1f.3: error: host status 0x00000000 dsp status 0x00000000 mask 0x00000003
[ 1249.851320] sof-audio-pci 0000:00:1f.3: error: waking up any trace sleepers
[ 1249.851436] sof-audio-pci 0000:00:1f.3: format_val=49, rate=48000, ch=2, format=10
[ 1249.851461] sof-audio-pci 0000:00:1f.3: pcm: hw params stream 0 dir 1
[ 1249.851465] sof-audio-pci 0000:00:1f.3: generating page table for 000000004b1f1fd2 size 0xffc0 pages 16
[ 1249.851505] sof-audio-pci 0000:00:1f.3: period_bytes:0x3fc0
[ 1249.851508] sof-audio-pci 0000:00:1f.3: periods:4
[ 1249.851531] sof-audio-pci 0000:00:1f.3: stream_tag 2
[ 1249.851542] sof-audio-pci 0000:00:1f.3: ipc tx: 0x60010000: GLB_STREAM_MSG: PCM_PARAMS
```
[boot_fail.log](https://github.com/thesofproject/linux/files/3170868/boot_fail.log)

**Comment by Jiangxinx** [comment] 2019-07-30 07:11
Can not be reproduced on daily test version.
***Env***
build date: 2019-07-30
sof master: f7809a2e
kernel sof-dev: f745362
tplg: sof-apl-nocodec.tplg

***Step***
speaker-test -Dhw:0,0 -c2 -r48000 -t wav
speaker-test -Dhw:0,1 -c2 -r48000 -t wav
speaker-test -Dhw:0,3 -c2 -r48000 -t wav
speaker-test -Dhw:0,5 -c2 -r48000 -t wav

**Closed as completed by Jiangxinx** 2019-07-30 07:11 UTC
Labels: bug
