### ISSUE TITLE
pulse audio not detecting sound card (MTL,HDA)

### ISSUE THREAD

**Issue by syedk008** [thesofproject/linux#4068] opened 2022-12-02 19:10 UTC
aplay output:
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: DeepBuffer (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 6: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 7: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$pacmd list-cards
0 card(s) available.

ubuntu-22.04,  kernelv6.0.2, sof-fw: mtl-002-drop-stable

**Comment by plbossart** [comment] 2022-12-02 19:14
It's probably a mismatch between topology names and UCM expectations. @RanderWang @ranj063 FYI.

**Comment by RanderWang** [comment] 2022-12-05 01:11
wait for https://github.com/thesofproject/sof/pull/6508

**Comment by mengdonglin** [comment] 2022-12-05 01:33
@syedk008 Can you please clarify what HD-Audio codec(s) are you using on your MTL platform? Are you using the onboard ALC711 or external HD-Audio codec(s) on Realtek Add-in-card?

**Comment by keqiaozhang** [comment] 2022-12-05 09:38
I can reproduce this issue on our MTL-RVP-HDA, I also copied the ucm2 files(https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp) to /usr/share/alsa/ucm2/, but it still doesn't work.

**Comment by syedk008** [comment] 2022-12-05 18:12
> @syedk008 Can you please clarify what HD-Audio codec(s) are you using on your MTL platform? Are you using the onboard ALC711 or external HD-Audio codec(s) on Realtek Add-in-card?

ALC245 with Realtek Gen3.x card.

**Comment by syedk008** [comment] 2022-12-07 01:45
Error from pulseaudio:
pulseaudio[949]: Failed to find a working profile.
pulseaudio[949]: Failed to load module "module-alsa-card" (argument: "device_id="0" name="pci-0000_00_1f.3-platform-skl_hda_dsp_generic" card_name="alsa_card.pci-0000_00_1f.3-platform-skl_hda_dsp_generic" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1""): initialization failed.

**Comment by syedk008** [comment] 2022-12-07 23:53
Attached is the pulse audio complete log. Below are the device mappings :
intel@ubuntu:/dev/snd$ ll
total 0
drwxr-xr-x   3 root root      300 Dec  8 04:26 ./
drwxr-xr-x  17 root root     5560 Dec  8 04:26 ../
drwxr-xr-x   2 root root       60 Dec  8 04:26 by-path/
crw-rw----+  1 root audio 116, 11 Dec  8 04:26 controlC0
crw-rw----+  1 root audio 116, 10 Dec  8 04:26 hwC0D0
crw-rw----+  1 root audio 116,  9 Dec  8 04:26 hwC0D2
crw-rw----+  1 root audio 116,  6 Dec  8 04:30 pcmC0D0c
crw-rw----+  1 root audio 116,  5 Dec  8 04:30 pcmC0D0p
crw-rw----+  1 root audio 116,  8 Dec  8 04:26 pcmC0D10c
crw-rw----+  1 root audio 116,  7 Dec  8 04:26 pcmC0D1p
crw-rw----+  1 root audio 116,  2 Dec  8 04:30 pcmC0D5p
crw-rw----+  1 root audio 116,  3 Dec  8 04:26 pcmC0D6p
crw-rw----+  1 root audio 116,  4 Dec  8 04:26 pcmC0D7p
crw-rw----+  1 root audio 116,  1 Dec  8 04:26 seq
crw-rw----+  1 root audio 116, 33 Dec  8 04:26 timer


Pulseaudio error shows:
(alsa-lib)pcm_hw.c: open '/dev/snd/pcmC0D6c' failed (-2) [
[pulse_audio_log_mtl.txt](https://github.com/thesofproject/linux/files/10180951/pulse_audio_log_mtl.txt)
](url)

**Comment by plbossart** [comment] 2022-12-08 00:17
try using alsaucm to see what you are missing, it'll be a lot less complicated than figuring out what PulseAudio does. PulseAudio is history btw, you ought to be looking at PipeWire.

**Comment by syedk008** [comment] 2022-12-08 18:43
with changing PCM numbers for Dmic and HDMI in UCM files (Hdmi.conf and HiFi.conf), PulseAudio seems working. These changes may not be compatible with other platforms.

**Comment by plbossart** [comment] 2022-12-08 19:18
can you share those UCM changes, it means the topology is incorrect. @ranj063 @bardliao FYI

**Comment by syedk008** [comment] 2022-12-08 22:52
HiFi.conf --> CapturePCM "hw:${CardId},10" changed from 6
Hdmi.conf--> HdmiPCM changed to 5,6,7

**Comment by plbossart** [comment] 2022-12-08 23:16
I think the HDMI PCM IDs are wrong in cavs-passthrough-hdmi.conf

@ranj063 @bardliao any idea why we are using these, instead of default 5,6,7?
````
Define {
	NUM_HDMIS 	3
	HDMI1_ID	1
	HDMI2_ID	2
	HDMI3_ID	3
}
````

For the DMIC, I have no idea how the DMIC0_ID is 10 in your setup @syedk008. The default is DMIC0_ID 6 in topology files. You must be using a different topology that didn't come from mtl-stable-002, or there's a configuration issue somewhere.

**Comment by syedk008** [comment] 2022-12-08 23:42
platform/intel/dmic-generic.conf : id is 10 here..

````
Object.PCM {
        pcm.10 {
                name    "DMIC"
                id 10
                direction       "capture"
                Object.Base.fe_dai."DMIC" {}

                Object.PCM.pcm_caps."capture" {
                        name $DMIC0_PCM_CAPS
                        # only 32-bit capture supported now
                        formats 'S32_LE'
                        channels_min $NUM_DMICS
                        channels_max $NUM_DMICS
                }
        }
}
````

**Comment by plbossart** [comment] 2022-12-09 00:46
8d0ac8e2da (Ranjani Sridharan 2022-02-16 10:28:19 -0800 125)            id 10

@ranj063 can you look into this?

**Comment by bardliao** [comment] 2022-12-09 03:22
> I think the HDMI PCM IDs are wrong in cavs-passthrough-hdmi.conf
> 
> @ranj063 @bardliao any idea why we are using these, instead of default 5,6,7?
> 
> ```
> Define {
> 	NUM_HDMIS 	3
> 	HDMI1_ID	1
> 	HDMI2_ID	2
> 	HDMI3_ID	3
> }
> ```
> 

This seems to be redundant. We define HDMI_IDs in hdmi-default.conf
```
        HDMI1_ID                        5
        HDMI2_ID                        6
        HDMI3_ID                        7
        HDMI4_ID                        8
```

**Comment by syedk008** [comment] 2022-12-09 04:15
> > I think the HDMI PCM IDs are wrong in cavs-passthrough-hdmi.conf
> > @ranj063 @bardliao any idea why we are using these, instead of default 5,6,7?
> > ```
> > Define {
> > 	NUM_HDMIS 	3
> > 	HDMI1_ID	1
> > 	HDMI2_ID	2
> > 	HDMI3_ID	3
> > }
> > ```
> 
> This seems to be redundant. We define HDMI_IDs in hdmi-default.conf
> 
> ```
>         HDMI1_ID                        5
>         HDMI2_ID                        6
>         HDMI3_ID                        7
>         HDMI4_ID                        8
> ```

But UCM expected ids are 3,4,5

**Comment by plbossart** [comment] 2022-12-09 14:08
That's right, the file ucm2/Intel/sof-hda-dsp/Hdmi.conf refers to HDMI devices 3,4,5

edit: makes sense, HDA analog is 0, digital 1 and alt digital 2. So the base can only be 3.

**Comment by bardliao** [comment] 2022-12-13 12:16
@plbossart In fact, HDMI1_ID is BE id, not PCM id. The pcm id is hard code to 5, 6, 7, 8.

hdmi-generic.conf will be used by sdw topologies, too. So, we can't simply update the pcm id.
See https://github.com/thesofproject/sof/pull/6787

**Comment by libinyang** [comment] 2023-01-03 10:21
@syedk008 Could you please try https://github.com/thesofproject/sof/pull/6904

**Comment by syedk008** [comment] 2023-01-05 20:05
> @syedk008 Could you please try [thesofproject/sof#6904](https://github.com/thesofproject/sof/pull/6904)

yes, changing DMIC_PCM_ID to 6 works. I had tested this change before.

**Comment by libinyang** [comment] 2023-02-06 05:54
@syedk008 Patches are merged. Could you please try the tplg for the latest sof code?

**Comment by mengdonglin** [comment] 2023-02-09 05:19
Closing. @syedk008 Please reopen this issue or file a new one if you still see opens.

**Closed as completed by mengdonglin** 2023-02-09 05:19 UTC
Labels: bug, P1, PulseAudio, topology, MTL
