### ISSUE TITLE
[BUG] No Sound on Dell SoundWire SKU 0AF0 - Arch Linux 5.18.12-arch1-1  - hanging shutdown

### ISSUE THREAD

**Issue by changedsoul** [thesofproject/linux#3772] opened 2022-07-17 06:37 UTC
This on a Dell XPS 17 9720 Laptop with Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01).
I have gone thru the wiki and installed sof-firmware as instructed.

sof version: sof-firmware 2.2-1

with sof-installed:

> 0000:00:1f.3 Multimedia audio controller: Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
        Subsystem: Dell Device 0afe
        Kernel driver in use: sof-audio-pci-intel-tgl
        Kernel modules: snd_hda_intel, snd_sof_pci_intel_tgl

when the sof-firmware is installed the laptop hangs on shutdown indefinitely and requires holding the power button down.
looking at the next boot 'journalctl -b' i see these listed:

> Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
Jul 16 23:15:36 olderman kernel: fbcon: i915drmfb (fb0) is primary device
Jul 16 23:15:36 olderman kernel: Console: switching to colour frame buffer device 240x75
Jul 16 23:15:36 olderman kernel: i915 0000:00:02.0: [drm] fb0: i915drmfb frame buffer device
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 4
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
Jul 16 23:15:36 olderman kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
...
Jul 16 23:15:38 olderman kernel: soundwire sdw:3:025d:0714:01: Probe not complete, timed out
Jul 16 23:15:38 olderman kernel: soundwire sdw:3:025d:0714:01: Update Slave status failed:-110
Jul 16 23:15:38 olderman kernel: soundwire sdw:2:025d:1316:01: Probe not complete, timed out
Jul 16 23:15:38 olderman kernel: soundwire sdw:2:025d:1316:01: Update Slave status failed:-110
Jul 16 23:15:38 olderman kernel: soundwire sdw:1:025d:1316:01: Probe not complete, timed out
Jul 16 23:15:38 olderman kernel: soundwire sdw:1:025d:1316:01: Update Slave status failed:-110
Jul 16 23:15:38 olderman kernel: soundwire sdw:0:025d:0711:01: Probe not complete, timed out
Jul 16 23:15:38 olderman kernel: soundwire sdw:0:025d:0711:01: Update Slave status failed:-110
...
Jul 16 23:15:39 olderman kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
Jul 16 23:15:40 olderman kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
Jul 16 23:15:40 olderman kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
Jul 16 23:15:40 olderman kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
Jul 16 23:15:40 olderman kernel: sof_sdw sof_sdw: snd_soc_register_card failed -517
...
ul 16 23:16:39 olderman systemd-udevd[368]: sdw:0:025d:0711:01: Worker [374] processing SEQNUM=5150 is taking a long time
Jul 16 23:16:39 olderman systemd-udevd[368]: sdw:3:025d:0714:01: Worker [422] processing SEQNUM=5162 is taking a long time
Jul 16 23:18:39 olderman systemd-udevd[368]: sdw:0:025d:0711:01: Worker [374] processing SEQNUM=5150 killed
Jul 16 23:18:39 olderman systemd-udevd[368]: sdw:3:025d:0714:01: Worker [422] processing SEQNUM=5162 killed
...
ul 16 23:19:36 olderman kernel: INFO: task systemd-udevd:374 blocked for more than 122 seconds.
Jul 16 23:19:36 olderman kernel:       Tainted: P           OE     5.18.12-arch1-1 thesofproject/sof#1
Jul 16 23:19:36 olderman kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
Jul 16 23:19:36 olderman kernel: task:systemd-udevd   state:D stack:    0 pid:  374 ppid:   368 flags:0x00000006
Jul 16 23:19:36 olderman kernel: Call Trace:
Jul 16 23:19:36 olderman kernel:  <TASK>

If I remove sof-firmware the system will again shutdown fine.

**Comment by direc85** [comment] 2022-07-18 08:27
I noticed you have the same issue with the same lines in `dmesg` than I did:

> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
> sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel

Same here with a Tiger Lake laptop (Lenovo X1 Carbon) and Manjaro Linux. I made a [Manjaro forum post](https://forum.manjaro.org/t/no-sound-with-sof-firmware-2-2-pipewire-alsa-1-2-7-1-sequence-command-devdisall-is-ignored/116874) about it (pardon the URL and original title, I was sidetracked at first).

I managed to restore sound (and general system responsiveness) by downgrading `sof-firmware` from `2.2-1` to `2.1.1.a-1`. I still get a different ABI version mismatch message, though:

> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:1:1-3964a
> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:21:0 Kernel ABI 3:19:1
> sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel

**Comment by plbossart** [comment] 2022-07-18 15:27
@changedsoul the shutdown issues are known, they fixes were contributed upstream last week.

The bigger issue is why the probe fails. Can you please add this file 
[sof-dyndbg.conf.txt](https://github.com/thesofproject/sof/files/9133208/sof-dyndbg.conf.txt) as /etc/modprobe.d/sof-dyndbg.conf (the extension matters), reboot and attach the dmesg log.

Also please attach the 'alsa-info' log.

**Comment by plbossart** [comment] 2022-07-18 15:27
> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 2:2:0-57864
> sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:22:1 Kernel ABI 3:19:1
> sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel

please ignore this, I sent a patch upstream to remove this. You don't have to worry about it, it was intended only for developers.

**Comment by plbossart** [comment] 2022-07-18 15:29
> I managed to restore sound (and general system responsiveness) by downgrading `sof-firmware` from `2.2-1` to `2.1.1.a-1`. I still get a different ABI version mismatch message, though:

That's not normal and should be filed as a separate bug @direc85. I have no idea why downgrading the firmware would help.
@lgirdwood FYI.

**Comment by lgirdwood** [comment] 2022-07-18 16:03
@changedsoul we had a similar issue on a Chromebook that was resolved with a slightly different shutdown flow. Adding @kv2019i who is back next week and implemented the Chromebook fix. It may additionally need to be used here. Please keep using v2.1.1 for the moment.

**Comment by plbossart** [comment] 2022-07-18 16:07
@lgirdwood the shutdown issue is only on SoundWire device where we tried to remove a headset device property in the machine driver that was not set on deferred probe. Nothing to do with the SOF PCI shutdown problems.

Edit: see https://github.com/thesofproject/linux/pull/3730/commits/6da6824e1d4f60bbd3c408b53fe92cdc657438a1

**Comment by changedsoul** [comment] 2022-07-19 01:10
OK, I tried the downgrade of sof-firmware to no avail. Reinstalled the 2.2.1 version, rebooted and here are the logs @plbossart was asking for.
[alsa-info.txt](https://github.com/thesofproject/sof/files/9136625/alsa-info.txt)
[dmesg.txt](https://github.com/thesofproject/sof/files/9136626/dmesg.txt)

**Comment by direc85** [comment] 2022-07-19 08:59
> That's not normal and should be filed as a separate bug

Thanks, I'll do that,.

**Edit:** I am not able to reproduce the bug anymore by updating the sof-firmware to 2.2, and audio works fine after upgrading the whole Manjaro (i.e. ALSA 1.2.7.2). I'll reopen the bug with logs if I ever hit it again.

**Comment by plbossart** [comment] 2022-07-19 15:07
@changedsoul the Dell SKU is not handled in the kernel for now, this is a device Dell didn't mention to us....

````
System SKU:        0AFE
````

The weird part is that we end-up selecting an existing configuration that fails at run-time with all kinds of SoundWire issues.

I think what's happening is that we detect a 2-amp machine, but since we are missing the SKU support we use the 1-amp version in the machine driver.

**Comment by plbossart** [comment] 2022-07-19 15:13
@changedsoul can you try the patch in https://github.com/thesofproject/linux/pull/3773.

If you don't know how to compile your own kernel, see guidelines here: https://thesofproject.github.io/latest/getting_started/setup_linux/install_locally.html

**Comment by changedsoul** [comment] 2022-07-19 19:19
@plbossart , I am not quite sure how to test the patch in #3773. 
When you link directions for compiling my own kernel, is the patch included in that kernel?

**Comment by plbossart** [comment] 2022-07-19 20:18
> When you link directions for compiling my own kernel, is the patch included in that kernel?

No. Recompiling your own kernel requires a baseline. You can start from your arch linux stable tree, then apply the patch in PR #3773 and see what happens.

**Comment by changedsoul** [comment] 2022-07-19 20:34
Forgive me ignorance, am I applying this patch to the kernel itself before compiling and not the sof-firmware?

**Comment by plbossart** [comment] 2022-07-19 20:42
sof-firmware and linux kernel are separate things. The patch is only relevant for the kernel. It's doesn't matter what version of sof-firmware you have, as long as its 'recent-enough'.

**Comment by changedsoul** [comment] 2022-07-19 20:55
OK, Ill give the kernel patch and compile tonight when I get home and report back hopefully tonight sometime. Thanks.

Edit: I gave it my all and cannot get the kernel to boot. Pretty sure I am doing something wrong. I followed the arch wiki for instructions. Ill keep trying thru the week and maybe over the weekend if I have more free time i might be able to get it to boot.

**Comment by changedsoul** [comment] 2022-07-21 13:49
I was able to get it to finally boot the new kernel, but I still have no sound.

**Comment by plbossart** [comment] 2022-07-21 14:18
@changedsoul can you share the full dmesg log and 'alsa-info' results? we need to see if a card is created and if everything is fine.

**Comment by changedsoul** [comment] 2022-07-21 14:48
Ok, Ill do that when I get home. It will be about 10 hours from now. I was not sure how to apply the patch, so what I did was a wget on "https://raw.githubusercontent.com/thesofproject/linux/8e02f7024e36a4f1440a52133d008f94c3e9a8e8/sound/soc/intel/boards/sof_sdw.c" and placed it into "sound/soc/intel/boards/sof_sdw.c" and compiled the kernel.

I hope this was an adequate method.

**Comment by plbossart** [comment] 2022-07-21 14:53
> I hope this was an adequate method.

Good enough!

**Comment by changedsoul** [comment] 2022-07-22 01:20
Here is dmesg and alsa-info
[alsa-info.txt](https://github.com/thesofproject/linux/files/9163718/alsa-info.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/9163722/dmesg.txt)

**Comment by plbossart** [comment] 2022-07-22 15:03
I don't see any error in the kernel logs @changedsoul. The card is created alright and the following devices are exposed. 

````
**** List of PLAYBACK Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 0: Jack Out (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 2: Speaker (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 5: HDMI 1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 6: HDMI 2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 7: HDMI 3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

ARECORD

**** List of CAPTURE Hardware Devices ****
card 0: sofsoundwire [sof-soundwire], device 1: Jack In (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofsoundwire [sof-soundwire], device 4: Microphone (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
````
I do see timeouts in the logs, but the kernel seems to be able to recover and create the cards.

It seems likely that this is the same issue as #3777, some sort of delay/race condition on startup that impacts the results.

You may want to try the solutions I recommended in https://github.com/thesofproject/linux/issues/3777#issuecomment-1192655300 so see if this helps.

Happy Friday!

**Comment by changedsoul** [comment] 2022-07-22 18:00
Thanks, I compiled with the time out setting altered for a longer period and I now have sound. Now I just need to wait for a few weeks for the patch to roll into my distro kernel.

Thanks for all the help. It was a fun experience compiling the kernel.

**Comment by plbossart** [comment] 2022-07-22 19:42
Thanks for testing @changedsoul, glad we managed to fix your issues. 

If you have time, would you mind checking that our latest development kernel works on your platform? This would only add a new grub2 boot option on your device, you would keep what you have. 

the code is on GitHub here: 
https://github.com/thesofproject/linux.git

You can also get the zip file if you don't want to muck with git.
https://github.com/thesofproject/linux/archive/refs/heads/topic/sof-dev.zip

Edit: you need to use your existing config, just run 'make olddefconfig' to get all the new default options.

**Comment by changedsoul** [comment] 2022-07-23 00:43
Would be glad to, Ill report back the results

**Comment by changedsoul** [comment] 2022-07-23 12:57
Yes, my sound worked with your dev kernel without patching anything.

**Comment by plbossart** [comment] 2022-07-25 16:04
> Yes, my sound worked with your dev kernel without patching anything.

ok, will submit this upstream then. Thanks @changedsoul for your help, much appreciated.

**Closed as completed** 2022-07-25 22:01 UTC
Labels: bug, P1, SDW, ADL, Dell SDW SKU
