### ISSUE TITLE
[BUG][CML][UCM2]HDA UCM2 need set default  PGA volume

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1972] opened 2020-04-02 04:24 UTC
**Describe the bug**
Only left channel has sound output when do speak test(0,0)
```
ubuntu@cml-hda-mantis-1:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 4: HDMI2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: sofhdadsp [sof-hda-dsp], device 5: HDMI3 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**To Reproduce**
1.sudo reboot
2.speak-test -Dhw:0,0 -r48000 -f1000 -c2 -t wav -l 10

**Reproduction Rate**
10/10

**Expected behavior**
The sound of left channel and right channel normally

**Actual result**
Only left channel has sound output
<img width="647" alt="1" src="https://user-images.githubusercontent.com/56707932/78210433-c67e1400-74dc-11ea-9c42-2f16a62ce364.PNG">
<img width="418" alt="Capture" src="https://user-images.githubusercontent.com/56707932/78210437-c9790480-74dc-11ea-8460-74c4a363daa3.PNG">

[amixercontents_pass.txt](https://github.com/thesofproject/linux/files/4418858/amixercontents_pass.txt)
[amixercontents_fail.txt](https://github.com/thesofproject/linux/files/4418857/amixercontents_fail.txt)

Kernel: [97453d9b] (https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tag/?h=v5.5.8)
SOF:[2ef369d57][ https://github.com/thesofproject/sof-bin/tree/stable-v1.4.2/lib/firmware/intel/sof/v1.4.2]
rename sof-cnl.ri  to sof-cml.ri
 tplg: [sof-hda-generic-2ch.tplg ]
Platform:[CML laptop with onboard codec ALC3204 in HDA mode]
PalseAudio Version: [13.99.1]
UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

**Comment by Liviali155** [comment] 2020-04-02 04:29
shell we set  default volume for all the playback and capture?

**Comment by mengdonglin** [comment] 2020-04-13 01:18
@juimonen Any suggestions on this?

**Comment by Liviali155** [comment] 2020-04-13 06:39
This issue also can be reproduced on sof v1.5-rc1
Kernel:4b4681eb  Sof-dev
fw:5f7d4e2    https://github.com/thesofproject/sof/releases/tag/v1.5-rc1
UCM2(https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp)

**Comment by ClarexZhou** [comment] 2020-04-14 05:20
Default volume isn't set in UCM2:https://github.com/thesofproject/alsa-ucm-conf/tree/master/ucm2/sof-hda-dsp

**Comment by juimonen** [comment] 2020-04-14 11:46
@ClarexZhou @Liviali155 so if you change the volume in sound settings, does it fix the imbalance? So will the other channel also be audible? I'm just trying to figure out do we have issue in ucm or what is causing this?

**Comment by Liviali155** [comment] 2020-04-14 12:15
> @ClarexZhou @Liviali155 so if you change the volume in sound settings, does it fix the imbalance? So will the other channel also be audible? I'm just trying to figure out do we have issue in ucm or what is causing this?

Change the "Balance" to medium  in sound settings can make speak test pass,both the left  channel and right channel audible

**Comment by juimonen** [comment] 2020-04-14 12:18
@Liviali155 ok thanks! And do you see this issue if you don't update ucm? or if you don't update kernel? I just installed fresh ubuntu 20 to mantis and I don't see this, and it is loading sof. Again trying to bisect the cause...

**Comment by Liviali155** [comment] 2020-04-14 12:30
> @Liviali155 ok thanks! And do you see this issue if you don't update ucm? or if you don't update kernel? I just installed fresh ubuntu 20 to mantis and I don't see this, and it is loading sof. Again trying to bisect the cause...

The current issue is only when you set  "Balance" to left  in sound settings,then reboot device,only has left channel has sound output,It can not recover after reboot

**Comment by paulstelian97** [comment] 2020-04-14 12:33
> > @Liviali155 ok thanks! And do you see this issue if you don't update ucm? or if you don't update kernel? I just installed fresh ubuntu 20 to mantis and I don't see this, and it is loading sof. Again trying to bisect the cause...
> 
> The current issue is only when you set "Balance" to left in sound settings,then reboot device,only has left channel has sound output,It can not recover after reboot

I think setting the balance to Left will cause a Mute to be set on the right channel, can you try manually unmuting the right channel when you try to run speaker-test? I think the "balance" setting really sets different volumes for the two channels in ALSA, by design.

**Comment by juimonen** [comment] 2020-04-14 12:34
@Liviali155 hmm, I'm not sure this is a bug then? I mean if user sets the balance, that's what the user wants... and in my opinion that should stay after boot... or am I misunderstanding something here?

**Comment by ClarexZhou** [comment] 2020-04-15 01:36
@juimonen This issue was reported for the default setting isn't right and this issue occurred when first time installing ubuntu 20.04 daily release and setup ucm2 env.  But this issue not occurred when 2nd time to install 20.04 beta release.  
I think one default volume setting should be needed? Since customer also required this default volume setting on UCM1.  And sof-soundwire UCM2 also have set this default volume.

**Comment by plbossart** [comment] 2020-04-15 01:59
@juimonen the balance and soft volume should be managed by Pulseaudio, but everything controlled by UCM should be properly reset.

**Comment by juimonen** [comment] 2020-04-15 06:28
@plbossart yes I understand. I was just trying to bisect how you get to this situation, because I don't think _after_ user touches the balance, we should reset that in the boot. Or it could be resetted but the user setting should be restored?

@Liviali155 anyway as said I just installed fresh ubuntu 20 on my mantis and I don't see this issue. when you say setup ucm2 environment, you mean you update the ucm after the install? If that's the case that would indicate there's some difference in stock ucm2 and the "new" ucm2 you install?

**Comment by Liviali155** [comment] 2020-04-15 06:49
> @plbossart yes I understand. I was just trying to bisect how you get to this situation, because I don't think _after_ user touches the balance, we should reset that in the boot. Or it could be resetted but the user setting should be restored?
> 
> @Liviali155 anyway as said I just installed fresh ubuntu 20 on my mantis and I don't see this issue. when you say setup ucm2 environment, you mean you update the ucm after the install? If that's the case that would indicate there's some difference in stock ucm2 and the "new" ucm2 you install?

I reported the issue because After install the ubuntu 20.04 daily release then update the ucm,I found right channel has no sound output when do speak test,and  I found the alsamixer display as below

![Inked1_LI](https://user-images.githubusercontent.com/56707932/79306518-f17a5600-7f27-11ea-81a4-0a071831b246.jpg)

This issue only occured  once on my side

The only difference between our UCM2 and 20.04 build in UCM2 is HDMI config. Our started with if, and not found function difference right now.
 If.hdmi1 { Condition { Type ControlExists Control "iface=CARD,name='HDMI/DP,pcm=3 Jack'" } True {

**Comment by juimonen** [comment] 2020-04-15 07:04
@Liviali155 hmm ok. Yes I understand the imbalance, but not sure should we do something to it if it is not very reproducible.

The problem I have with UCM default volumes is that it will be always set when you open the device, then nanosecond later pulseaudio will restore the user volume. So we will see rapid up/down movement in volume often -> all kinds of pops might appear.

And something is setting some default volume already in this ubuntu 20 at least I have sound immediately without touching volumes.

So the question is, is this something that just has happened because of the install of new ucm and is it random, or is there some systematic issue with pulse/ucm always when installing new ucm versions...

**Comment by ClarexZhou** [comment] 2020-04-17 01:55
Change paplay volume in volume levels bar from sound setting won't effect volume settings in alsamixer. But change Balance in sound setting, will effect Heaphone and Speaker volume in alsamixer.
Change Input volume  from sound setting, it will also effect Capture or Dmic0 volume in alsamixer.
But PGA volume, such as PGA2.0 2 will not be effected by pulseaudio.  
@juimonen  shouldn't we set default PGA volume in UCM2?  Though this isn't the original bug

**Comment by juimonen** [comment] 2020-04-17 05:52
@ClarexZhou just realized that the sound settings has changed quite a bit from 18.04. So you don't see anymore volume marked for output. "System volume" is changing the alsamixer settings for current output. And the paplay appears only when used and that volume changes the pulseaudio internal sw volume.

So I think it is working as intended.

The PGA's (sof dsp volumes) are not to be touched in this case, they should be full 100% as default.

**Comment by ClarexZhou** [comment] 2020-04-20 05:22
@juimonen   current UCM2 isn't set PGA's default volume. But i think default PGA's volume both for playback and capture should be setup in UCM2. 
Could you add default PGA volume in HDA UCM2?

**Comment by ClarexZhou** [comment] 2020-04-30 09:51
Default capture PGA volume is too low. Need reset default PGA volume in HDA UCM2.

**Comment by mengdonglin** [comment] 2020-05-13 02:37
Depends on new feature https://github.com/thesofproject/linux/issues/2067

**Comment by mengdonglin** [comment] 2020-05-28 12:49
@libinyang will update and upstream ucm2

**Comment by ClarexZhou** [comment] 2020-06-24 02:12
Close for https://github.com/alsa-project/alsa-ucm-conf/pull/35 is merged.

**Closed as completed by ClarexZhou** 2020-06-24 02:12 UTC
Labels: bug, P1, CML, HDA, UCM2, initial default mixer values, single-profile UCM
