### ISSUE TITLE
ACPI needed for compile_test

### ISSUE THREAD

**Issue by cujomalainey** [thesofproject/linux#1051] opened 2019-06-19 19:19 UTC
Our local maintainer found some issues with compile test dependencies. ACPI is required but somehow not depended on.

See the local fix https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1662076

**Comment by plbossart** [comment] 2019-06-20 05:59
No, the fix is incorrect. There are devices such as Merrifield which do not rely on ACPI for the audio parts.
Can you share the config that causes the problem here and/or reproduce the issue with the latest topic/sof-dev branch to check if this is a backport issue? I know there were fixes recently since APCI and PCI are no longer tied.

**Comment by groeck** [comment] 2019-06-20 18:00
alpha:allmodconfig and many other non-Intel architectures fail build tests.

ERROR: "snd_soc_acpi_codec_list" [sound/soc/intel/common/snd-soc-acpi-intel-match.ko] undefined!

**Comment by plbossart** [comment] 2019-06-21 03:31
@groeck which code are you using?
If you look at the header file, when CONFIG_ACPI is not defined this function will default to a dummy inline, so not sure how this problem happens

https://github.com/thesofproject/linux/blob/08d3631c44da53bc101b299c7fd849f3dfee3ca1/include/sound/soc-acpi.h#L51

**Comment by groeck** [comment] 2019-06-21 06:08
The version applied to chromeos-4.14 does not include any dummy code. I can not comment on where it is from, or why it is different than the code you pointed to. It is the code I have to live with because it has been applied to a release branch.

**Comment by plbossart** [comment] 2019-06-21 07:46
@ranj063 who takes care of taking the patches from upstream and submits them to the 4.14 branch?

**Comment by ranj063** [comment] 2019-06-21 15:03
@plbossart its kamal and smit. Let me talk to them about it.

**Comment by plbossart** [comment] 2019-08-15 23:27
@cujomalainey wasn't this fixed by cherry-picking stuff from upstream?

**Comment by cujomalainey** [comment] 2019-08-16 06:46
Yes this was fixed by cherry picking the commit that created the asoc stubs for the acpi helpers.

**Closed as completed** 2019-08-16 06:47 UTC
