### ISSUE TITLE
[BUG][IMR] DSP firmware failed to boot from IMR on JSL 

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#3586] opened 2022-04-14 03:07 UTC
**Describe the bug**
We observed this issue in CI daily test 11792, firmware failed to boot form IMR on JSL_RVP_NOCODEC, tried to reproduce it but failed. 
```
[ 3536.610901] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 3536.610946] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 3536.610988] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 3538.115113] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 3538.115141] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: Firmware boot failure due to timeout
[ 3538.115151] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[ 3538.115182] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: status: fw entered - code 00000005
[ 3538.115332] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: unexpected fault 0x00000000 trace 0x000041c0
[ 3538.115343] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 3538.115352] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: error: failed to boot DSP firmware after resume -5
[ 3538.115362] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: fw_state change: 2 -> 3
[ 3538.115379] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_pm_runtime_get on 0000:00:1f.3: -5
```
**To Reproduce**
This issue happens when testing multiple-pause-resume at the first round, but I think it has nothing to do with this case, it just failed when booting firmware from suspend.

**Reproduction Rate**
How often does the issue happen ? i.e. 1/10 (once in ten attempts), 1/1000 or all the time.
Does the reproduction rate vary with any other configuration or user action, if so please describe and show the new reproduction rate.

**Expected behavior**
Firmware boot successfully from IMR.

**Impact**
Firmware boot failed.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel Branch: topic/sof-dev[4542828f16f1](https://github.com/thesofproject/linux/commit/4542828f16f1)
    * SOF Branch: main/[5ec02e32949e](https://github.com/thesofproject/sof/commit/5ec02e32949e)
2) Name of the topology file
    * Topology: sof-jsl-nocodec.tplg
3) Name of the platform(s) on which the bug is observed.
    * Platform: JSL_RVP_NOCODE

[logger.txt](https://github.com/thesofproject/linux/files/8485957/logger.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/8485958/dmesg.txt)

**Comment by plbossart** [comment] 2022-04-14 03:15
@keqiaozhang can you try to revert PR https://github.com/thesofproject/linux/pull/3558? That's the only recent change related to IMR.

Also can you clarify the reproduction rate, you wrote "tried to reproduce it but failed".

**Comment by keqiaozhang** [comment] 2022-04-14 03:57
> @keqiaozhang can you try to revert PR #3558? That's the only recent change related to IMR.
> 
> Also can you clarify the reproduction rate, you wrote "tried to reproduce it but failed".

Yes, I'm still running the runtime PM test to reproduce this issue, but no reproductions so far.
[Edit]: this issue is very hard to reproduce. 500 iterations passed without issues.

**Comment by keqiaozhang** [comment] 2022-04-25 01:14
CI also detected this issue on ADLP_RVP_NOCODEC when testing suspend-resume-with-capture.
```
[ 8488.701894] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 8488.701912] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware boot failure due to timeout
[ 8488.701920] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[ 8488.701946] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[ 8488.702197] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unexpected fault 0x00000000 trace 0x000041c0
[ 8488.702208] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 8488.702216] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware after resume -5
[ 8488.702232] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: PM: dpm_run_callback(): pci_pm_resume+0x0/0x80 returns -5
[ 8488.702271] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: PM: failed to resume async: error -5
[ 8488.710732] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc3_tx_msg_unlocked: ipc message send for 0x40070000 failed: -19
[ 8488.710750] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to enable target core for widget PIPELINE.4.SSP1.IN
[ 8488.710773] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Failed to set up connected widgets
[ 8488.710789] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc3_tx_msg_unlocked: ipc message send for 0x60010000 failed: -19
[ 8488.710805] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: HW params ipc failed for stream 2
[ 8488.710817] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: set pcm hw_params after resume
[ 8488.710829] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_prepare on 0000:00:1f.3: -19
[ 8488.710843] kernel:  Port1: ASoC: __soc_pcm_prepare() failed (-19)
[ 8488.710853] kernel:  Port1: ASoC: dpcm_fe_dai_prepare() failed (-19)
```
http://sof-ci.sh.intel.com/#/result/planresultdetail/11991?model=ADLP_RVP_NOCODEC&testcase=check-suspend-resume-with-capture-5

**Comment by keqiaozhang** [comment] 2022-04-28 05:45
I tried to reproduce this issue with suspend/resume test on ADLP_RVP_NOCODEC, but failed, it passed 100+ iterations.

**Comment by ujfalusi** [comment] 2022-04-28 14:21
@keqiaozhang, the ADL log can be 'explained', sort of. These are the events:
```
[ 8474.634462] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: booting DSP firmware
[ 8474.634656] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda_dsp_stream_setup_bdl: period_bytes:0x0
[ 8474.634667] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda_dsp_stream_setup_bdl: periods:1
[ 8474.634697] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: IMR restore supported, booting from IMR directly
...
[ 8474.635502] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x5 successful
[ 8474.650690] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x70000000: FW_READY
[ 8474.650694] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP is ready 0x70000000 offset 0x81000
[ 8474.650696] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 2 -> 5
[ 8474.650741] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000000 at  00000048
[ 8474.650752] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000002 at  00000048
[ 8474.650756] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIR: 00000004 at  00000044
[ 8474.650764] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Debug PCIW: 00000000 at  00000044
[ 8474.650765] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: firmware boot complete
[ 8474.650766] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 5 -> 6
[ 8474.650787] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x40000 successful
[ 8474.650818] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80]=0x40000 successful
[ 8474.650824] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda_dsp_stream_setup_bdl: period_bytes:0x0
[ 8474.650826] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: hda_dsp_stream_setup_bdl: periods:1
[ 8474.650832] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x70000000: FW_READY
```
The firmware booted up from IMR, all is good so far. Then some stream starts:
```
[ 8475.010019] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx: 0x60040000: GLB_STREAM_MSG: TRIG_START
[ 8475.010042] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8475.010091] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8475.011136] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc tx succeeded: 0x60040000: GLB_STREAM_MSG: TRIG_START
```
We have incoming trace messages:
```
[ 8475.510202] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8475.510277] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8476.010119] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8476.010168] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
...
```
Then this happens:
```
[ 8480.010168] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8480.010236] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG: DMA_POSITION
[ 8480.310009] kernel: PM: suspend entry (s2idle)
[ 8480.310595] kernel: Filesystems sync: 0.000 seconds
[ 8486.841146] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 8486.841170] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
...
[ 8486.974429] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 8486.974505] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 8488.701894] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 8488.701912] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware boot failure due to timeout
[ 8488.701920] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[ 8488.701946] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: status: fw entered - code 00000005
[ 8488.702197] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unexpected fault 0x00000000 trace 0x000041c0
[ 8488.702208] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 8488.702216] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware after resume -5
[ 8488.702223] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state change: 2 -> 3
[ 8488.702232] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: PM: dpm_run_callback(): pci_pm_resume+0x0/0x80 returns -5
[ 8488.702271] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: PM: failed to resume async: error -5
```
CTX_SAVE is not sent and next time the IMR boot does not work:
```
[ 8495.455488] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: IMR restore supported, booting from IMR directly
[ 8495.455492] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 8495.455500] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0f successful
[ 8495.455508] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0e successful
[ 8495.455514] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 8495.455521] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 8495.455536] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010e0e successful
[ 8495.455541] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unstall/run core: core_mask = 1
[ 8495.455548] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 1 : core_mask 1
[ 8495.456076] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0xd4]=0x80000000 successful
[ 8495.756295] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x5000001 timedout
[ 8495.756313] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump start ]------------
[ 8495.756318] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: Boot iteration failed: 0/3
[ 8495.756321] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: fw_state: SOF_FW_BOOT_IN_PROGRESS (2)
[ 8495.756336] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: unknown ROM status value 05000001
[ 8495.756369] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: extended rom status:  0x5000001 0x0 0x0 0x0 0x0 0x0 0x2560521 0x0
[ 8495.756373] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 8495.756390] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf010f0f successful
[ 8495.756414] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: FW Poll Status: reg[0x4]=0xf0f successful
[ 8495.756434] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 1
[ 8495.756439] kernel: sof-audio-pci-intel-tgl 0000:00:1f.3: IMR restore failed, trying to cold boot
```
and we recover.

But something is really odd for sure.

**Comment by ujfalusi** [comment] 2022-04-28 14:34
@keqiaozhang, it looks like we start to receive zero messages right after the IPC interrupt is enabled:
```
[ 3536.068532] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 2
[ 3536.068630] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 3536.068723] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
[ 3536.068736] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x5 successful
[ 3536.068785] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: no reply expected, received 0x0, will be ignored
...
```
and they start to come in before we check the rom state (`FW Poll Status: reg[0x80000]=0x5 successful`) for FW_ENTERED - so IMR boot success.
There is one thing I can think of: for some reason the second part of 'step 4' in `cl_dsp_init()` is somehow misses to ack the reception of the reply to the ROM message (which we tell it to boot, but boot from IMR) and it is not cleared, thus we will be constantly bombed?
But we should have acked the reply constantly, so I don't know why it is not going away.

**Comment by keqiaozhang** [comment] 2022-05-13 01:07
CI detected the IMR issues again on JSL and CML platforms. Test report ID:12564
JSL_RVP_NOCODEC:
http://sof-ci.sh.intel.com/#/result/planresultdetail/12564?model=JSL_RVP_NOCODEC&testcase=check-suspend-resume-with-capture-5
```
[ 8081.350560] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x80000]=0x5000001 timedout
[ 8081.350583] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x1010303 successful
[ 8081.350591] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x4]=0x303 successful
[ 8081.350597] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: DSP core(s) enabled? 0 : core_mask 3
[ 8081.350598] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: IMR restore failed, trying to cold boot
[ 8081.350690] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x40000 successful
[ 8081.350742] kernel: sof-audio-pci-intel-icl 0000:00:1f.3: FW Poll Status: reg[0x160]=0x40000 successful
```

CML_SKU0955_HDA :
http://sof-ci-storage.sh.intel.com/sofci/generic_test/12564/CML_SKU0955_HDA/volume-basic-test-50/dmesg.html
```
[ 6269.796069] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: unexpected fault 0x00000000 trace 0x000041c0
[ 6269.796080] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ------------[ DSP dump end ]------------
[ 6269.796089] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: error: failed to boot DSP firmware after resume -5
[ 6269.796098] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: fw_state change: 2 -> 3
[ 6269.796131] kernel: sof-audio-pci-intel-cnl 0000:00:1f.3: ASoC: error at snd_soc_pcm_component_pm_runtime_get on 0000:00:1f.3: -5
[ 6269.796146] kernel:  Analog Playback and Capture: __soc_pcm_open() failed (-5)
[ 6269.796157] kernel:  HDA Analog: ASoC: dpcm_be_dai_startup() failed at Analog Playback and Capture (-5)
[ 6269.796171] kernel:  HDA Analog: dpcm_fe_dai_startup() failed (-5)
```

**Comment by ujfalusi** [comment] 2022-05-16 11:09
@keqiaozhang, I believe #3649 will fix all IMR boot failures across all devices.
The CML (and JSL) is likely also receiving the ROM_CONTROL reply as the log is filled with:
```
no reply expected, received 0x0, will be ignored
...
no reply expected, received 0x0, will be ignored
```
I did run an extended test of 400 IMR boot on the JSL device on Friday with that PR.

**Comment by keqiaozhang** [comment] 2022-05-16 12:11
Thanks @jfalusi for fixing this issue. Since the repo rate of this issue is extremely low, so I will keep an eye on this issue in CI after https://github.com/thesofproject/linux/pull/3649 merge.

**Comment by ujfalusi** [comment] 2022-05-16 12:20
@keqiaozhang, I have few thousands of runs on different machines with that change and so far I have not been able to reproduce the issue, while without #3649 I have seen it several times under shorter runs.

Let's see if it is still popping up after when I can get the #3649 merged. Fingers crossed.

**Comment by keqiaozhang** [comment] 2022-05-21 05:06
@ujfalusi Bad news, this issue happened again on JSL. 
http://sof-ci.sh.intel.com/#/result/planresultdetail/12763?model=JSL_RVP_NOCODEC&testcase=check-runtime-pm-status-15
http://sof-ci.sh.intel.com/#/result/planresultdetail/12767?model=JSL_RVP_NOCODEC&testcase=check-runtime-pm-status-100

**Comment by ujfalusi** [comment] 2022-05-23 05:55
@keqiaozhang, thanks for the note, #3649 is not yet merged, but it it good to know that this pops up every now and then currently!

**Comment by ujfalusi** [comment] 2022-05-23 17:29
@keqiaozhang, I took the same JSL machine and run #3649 on it for 6 hours, it passed 2125 IMR boot iterations.
I also run the latest daily kernel later and after about 2.5 hours and 1100 iteration it failed.

**Closed as completed** 2022-05-23 17:51 UTC
Labels: P1, CML, JSL, suspend resume, IMR, ADL
