### ISSUE TITLE
[UCM][CML] After unplug headphone, sound setting still show headphone, and speaker volume is also muted (intermittent)

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/linux#911] opened 2019-05-07 06:33 UTC
**Describe the bug**
 Always display headphone in sound setting, also speaker volume is muted after plug out headset. Only reboot system can recover. 

**To Reproduce**
1. Stop music
2. Open sound setting of laptop
3. Plug in headset, then plug out, check.

**Expected behavior**
 switch status in sound setting when plug in/out headset in idle.

**Environment**
Rander UCM https://github.com/RanderWang/intel-UCM   
Kernel repo：c99938c https://github.com/thesofproject/linux/tree/release/sof-v5.0 
Firmware repo: 47fcac2  https://github.com/thesofproject/sof/commits/master |  
Topology: https://github.com/thesofproject/sof/commits/master . Same as above SOF repo
file: tools/topology/sof-hda-generic.m4, sof-hda-generic-2ch.tplg

[alwaysDisplayHeadphoneAfterPlugOut_dmesg.log](https://github.com/thesofproject/linux/files/3151084/alwaysDisplayHeadphoneAfterPlugOut_dmesg.log)
[alwaysHeadphone_logger.log](https://github.com/thesofproject/linux/files/3151085/alwaysHeadphone_logger.log)

**Comment by RanderWang** [comment] 2019-05-07 07:10
Next time, if you reproduce it, please check the Jack status.  The status is helpful.

**Comment by wenqingfu** [comment] 2019-05-08 02:45
likely a codec driver bug.

**Comment by keyonjie** [comment] 2019-05-08 02:46
> Next time, if you reproduce it, please check the Jack status. The status is helpful.

yes, @ClarexZhou please check and share the Jack status for both plug-in and plug-out once the issue happened.

**Comment by bardliao** [comment] 2019-05-08 02:52
@ClarexZhou Could you check if holding headset button and unplug can reproduce the issue?

**Comment by YvonneYang2** [comment] 2019-05-08 06:07
Test 20 times unplug the headphone by holding the headset button, can not reproduce the issue. @bardliao

**Comment by mengdonglin** [comment] 2019-05-09 02:28
Closing it because reproduce rate is very low and cannot be reproduced now. Will reopen if we reproduce it  again.

**Closed as completed by mengdonglin** 2019-05-09 02:28 UTC
Labels: bug, CML, HDA

**Comment by KailangYang** [comment] 2019-05-17 06:16
@mengdonglin 
I think you could refference legacy HDA driver first when you meet issue.
HDA driver was going for 15 years up. It's very stable.

This issue doesn't relation with codec driver. it's just register unsolicited event.
Jack JD was register in unsolicited event of controller code.
If jack is plug in, controller will process event for inerrupt.
If you need more info, this all in the controller code already.

If you don't like to process unsolicited event, you could use polling for time out.
Our Windows driver was use polling for 500ms time out to check JD state (95% machine).
