### ISSUE TITLE
[BYT nocodec/rt5682][BUG][v1.4.3]"DSP panic" occured when do module load/unload test .

### ISSUE THREAD

**Issue by sinahuang** [thesofproject/linux#2141] opened 2020-05-27 05:30 UTC
**Describe the bug**
"DSP panic" occured when do module load/unload test and issue occured during module remove. After error occured all pipeline work well. 

Note: Error not seen with sof-dev +master and  sof-dev+FWv1.5
    
          

**To Reproduce**
     1. Sudo reboot;
     2. Cd sof-test;
     3. Cd test-case;
4.Export TPLG=/lib/firmware/intel/sof-tplg/sof-byt-rt5682.tplg;
5../check-kmod-load-unload.sh -l 10 ;(https://github.com/thesofproject/sof-test/blob/master/test-case/check-kmod-load-unload.sh)

**Reproduction Rate**
10/10

**Expected behavior**
There is no DSP panic when do module load/unload

**Impact**
"DSP panic" occured when do module load/unload test.

```
skipping regmap_sdw, not loaded
Removing soundwire_bus
Removing snd_soc_core
Removing snd_hda_codec
Removing snd_hda_core
Removing snd_hwdep
skipping snd_compress, not loaded
Removing snd_pcm
2020-05-27 04:33:23 UTC [INFO] checking for general errors after kmod unload with sof-kernel-log-check tool
2020-05-27 04:33:23 UTC [ERROR] Caught dmesg error
===========================>>
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272141] sof-audio-acpi 80860F28:01: error : DSP panic!
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272155] sof-audio-acpi 80860F28:01: panic: dsp_oops_offset 1329152 offset 1329152
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272231] sof-audio-acpi 80860F28:01: error: invalid wait state
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272236] sof-audio-acpi 80860F28:01: error: trace point 00000000
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272239] sof-audio-acpi 80860F28:01: error: panic at .../drivers/intel/baytrail/ipc.c1:49
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272243] sof-audio-acpi 80860F28:01: error: DSP Firmware Oops
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272339] sof-audio-acpi 80860F28:01: error: ipc host -> DSP: pending no complete no raw 0x0
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272343] sof-audio-acpi 80860F28:01: error: mask host: pending yes complete no raw 0x2
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272349] sof-audio-acpi 80860F28:01: error: ipc DSP -> host: pending no complete no raw 0x800008000dead00a
May 26 21:33:22 jf-byt-mb-rt5682-4 kernel: [   63.272357] sof-audio-acpi 80860F28:01: error: mask DSP: pending no complete no raw 0x0
<<===========================
2020-05-27 04:33:23 UTC [ERROR] error found after kmod unload is real error, failing
2020-05-27 04:33:23 UTC [INFO] Test Result: FAIL!
ubuntu@jf-byt-mb-rt5682-4:~/sof-test/test-case$
```
dmesg log:
```
[   63.272086] sof-audio-acpi 80860F28:01: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   63.272141] sof-audio-acpi 80860F28:01: error : DSP panic!
[   63.272150] sof-audio-acpi 80860F28:01: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   63.272155] sof-audio-acpi 80860F28:01: panic: dsp_oops_offset 1329152 offset 1329152
[   63.272231] sof-audio-acpi 80860F28:01: error: invalid wait state
[   63.272236] sof-audio-acpi 80860F28:01: error: trace point 00000000
[   63.272239] sof-audio-acpi 80860F28:01: error: panic at .../drivers/intel/baytrail/ipc.c1:49
[   63.272243] sof-audio-acpi 80860F28:01: error: DSP Firmware Oops
[   63.272248] sof-audio-acpi 80860F28:01: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060525 SAR     0x00000000
[   63.272252] sof-audio-acpi 80860F28:01: EPC1     0x00000000 EPC2     0x00000000 EPC3     0x00000000 EPC4    0xff2d0213
[   63.272257] sof-audio-acpi 80860F28:01: EPC5     0xff2d0213 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[   63.272267] sof-audio-acpi 80860F28:01: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00060120 EPS5    0x00060120
[   63.272276] sof-audio-acpi 80860F28:01: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x000000a2
[   63.272282] sof-audio-acpi 80860F28:01: stack dump from 0xff31c550
[   63.272289] sof-audio-acpi 80860F28:01: 0xff31c550: ff31c570 00000000 00060525 00060320
[   63.272294] sof-audio-acpi 80860F28:01: 0xff31c554: 692f6c69 632e6370 00000031 00000000
[   63.272299] sof-audio-acpi 80860F28:01: 0xff31c558: 8e1cfa00 4a8d1bb4 f6d24028 ffff8c22
[   63.272304] sof-audio-acpi 80860F28:01: 0xff31c55c: f6d24028 ffff8c22 00000000 00000000
[   63.272311] sof-audio-acpi 80860F28:01: 0xff31c560: 33f21200 ffff8c23 ac4c2ff0 ffffffff
[   63.272321] sof-audio-acpi 80860F28:01: 0xff31c564: 00000000 00000000 00000000 00000000
[   63.272328] sof-audio-acpi 80860F28:01: 0xff31c568: 33f21200 ffff8c23 ac4c3160 ffffffff
[   63.272332] sof-audio-acpi 80860F28:01: 0xff31c56c: 00000000 00000000 00000000 00000000
[   63.272339] sof-audio-acpi 80860F28:01: error: ipc host -> DSP: pending no complete no raw 0x0
[   63.272343] sof-audio-acpi 80860F28:01: error: mask host: pending yes complete no raw 0x2
[   63.272349] sof-audio-acpi 80860F28:01: error: ipc DSP -> host: pending no complete no raw 0x800008000dead00a
[   63.272357] sof-audio-acpi 80860F28:01: error: mask DSP: pending no complete no raw 0x0
```

**Test recipe**

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev  commit:866e4d
FW: https://github.com/thesofproject/sof/commits/v1.4.3 commit: 7605252
Tplg: Same with FW branch,  sof-byt-rt5682.tplg
Platform:BYT MB with RT5682 in I2S mode

[dmesg27.log](https://github.com/thesofproject/linux/files/4686602/dmesg27.log)
[sof_trace.log](https://github.com/thesofproject/linux/files/4686727/sof_trace.log)

**Comment by sinahuang** [comment] 2020-05-27 05:37
Bisect result:
Caused by commit:https://github.com/thesofproject/linux/commit/8352018c7e1d4577b46d5aa6b43a86321433643c, @ranj063 please help to check it.

**Comment by plbossart** [comment] 2020-05-27 16:08
I can reproduce this problem on Baytrail (Asus T100TA) but not on CherryTrail (Cyan)

**Comment by plbossart** [comment] 2020-05-27 16:18
This doesn't seem caused by the .remove addition but rather the CTX_SAVE, the error happens *before* byt_remove() is called.

````
[   38.050483] sof-audio-acpi 80860F28:00: ipc tx: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   38.050539] sof-audio-acpi 80860F28:00: error : DSP panic!
[   38.050548] sof-audio-acpi 80860F28:00: panic: dsp_oops_offset 1329152 offset 1329152
[   38.050609] sof-audio-acpi 80860F28:00: error: invalid wait state
[   38.050613] sof-audio-acpi 80860F28:00: error: trace point 00000000
[   38.050618] sof-audio-acpi 80860F28:00: error: panic at .../drivers/intel/baytrail/ipc.c0:48
[   38.050622] sof-audio-acpi 80860F28:00: error: DSP Firmware Oops
[   38.050627] sof-audio-acpi 80860F28:00: EXCCAUSE 0x0000003f EXCVADDR 0x00000000 PS       0x00060525 SAR     0x00000000
[   38.050632] sof-audio-acpi 80860F28:00: EPC1     0x00000000 EPC2     0x00000000 EPC3     0x00000000 EPC4    0xff2cfdc3
[   38.050637] sof-audio-acpi 80860F28:00: EPC5     0xff2cfdc3 EPC6     0x00000000 EPC7     0x00000000 DEPC    0x00000000
[   38.050641] sof-audio-acpi 80860F28:00: EPS2     0x00000000 EPS3     0x00000000 EPS4     0x00060120 EPS5    0x00060120
[   38.050646] sof-audio-acpi 80860F28:00: EPS6     0x00000000 EPS7     0x00000000 INTENABL 0x00000000 INTERRU 0x000000a2
[   38.050650] sof-audio-acpi 80860F28:00: stack dump from 0xff31c550
[   38.050657] sof-audio-acpi 80860F28:00: 0xff31c550: ff31c570 00000000 00060525 00060320
[   38.050663] sof-audio-acpi 80860F28:00: 0xff31c554: 692f6c69 632e6370 00000030 00000000
[   38.050669] sof-audio-acpi 80860F28:00: 0xff31c558: c4eb6a00 86bf70da 00144800 00000000
[   38.050674] sof-audio-acpi 80860F28:00: 0xff31c55c: 80000800 00000000 e164a828 ffff8f5b
[   38.050680] sof-audio-acpi 80860F28:00: 0xff31c560: f2317800 ffff8f5b f3c0c180 ffff8f5b
[   38.050686] sof-audio-acpi 80860F28:00: 0xff31c564: 00000000 00000000 00000000 00000000
[   38.050691] sof-audio-acpi 80860F28:00: 0xff31c568: f3c0c180 ffff8f5b d59d3200 ffff8f5b
[   38.050697] sof-audio-acpi 80860F28:00: 0xff31c56c: 00000000 00000000 00000000 00000000
[   38.050704] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x0
[   38.050708] sof-audio-acpi 80860F28:00: error: mask host: pending yes complete yes raw 0x3
[   38.050713] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete no raw 0x800008000dead00a
[   38.050717] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0
[   38.050721] sof-audio-acpi 80860F28:00: error: waking up any trace sleepers
[   38.050739] sof-audio-acpi 80860F28:00: ipc tx succeeded: 0x40010000: GLB_PM_MSG: CTX_SAVE
[   38.722677] sof-audio-acpi 80860F28:00: plb: byt_remove()
[   38.722701] sof-audio-acpi 80860F28:00: plb: byt_remove() done
````

**Comment by plbossart** [comment] 2020-05-27 16:26
Actually no, updating to SOF master solves the issue. @sinahuang please try with a more recent firmware please.

Edit: https://github.com/thesofproject/sof-bin/blob/stable-v1.5/lib/firmware/intel/sof/v1.5/sof-byt-v1.5.ri works fine for me.

**Comment by sinahuang** [comment] 2020-05-28 03:27
Error only can be seen with sof-dev+FWv1.4.3, not seen with sof-dev +master and sof-dev+FWv1.5

**Comment by plbossart** [comment] 2020-06-09 18:23
firmware issue that will not be fixed, closing

**Closed as completed by plbossart** 2020-06-09 18:23 UTC
Labels: bug, won't fix, BYT
