### ISSUE TITLE
[TGL] runtime PM always in active on TGL chromebook/I2S mode

### ISSUE THREAD

**Issue by keqiaozhang** [thesofproject/linux#2053] opened 2020-04-26 06:36 UTC
**Describe the bug**
We found this issue on TGL chromebook and only happens with I2S mode. looks like there’s a dependency between SDW driver and runtime PM. if no SDW drivers loaded, runtime PM will always be active.
I also tried to disable SDW in kconfig, but got same results.

**To Reproduce**
Check runtime PM status when sof is idle for more than 3 seconds.
```
$cat /sys/bus/pci/devices/0000\:00\:1f.3/power/runtime_status
```
**Reproduction Rate**
10/10

**Expected behavior**
runtime PM will be suspended after sof is idle for more than 3 seconds.

**Environment**
Driver: fce7f934f + https://github.com/thesofproject/linux/pull/1971 + https://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git/commit/?h=for-next&id=914f674bec6efe42f9d6b036850a618fd1698290
Firmware:
SOF branch:  tgl-005-drop-stable Commit: 277a9717
TPLG: sof-tgl-max98373-rt5682.tplg 

[dmesg.txt](https://github.com/thesofproject/linux/files/4534738/dmesg.txt)
[logger.txt](https://github.com/thesofproject/linux/files/4534739/logger.txt)

**Comment by plbossart** [comment] 2020-04-27 13:37
@keqiaozhang please revisit this. If you still have an issue without SoundWire support, then it's not an issue due to SoundWire.

**Comment by keqiaozhang** [comment] 2020-04-28 09:35
> @keqiaozhang please revisit this. If you still have an issue without SoundWire support, then it's not an issue due to SoundWire.

The interesting thing is that I have 2 TGL Chromebook, these TGL devices support both I2S codec(RT5682I+MAX98373) and SDW codec(RT5682+MAX98373), since coreboot is not yet supported, so we need to override the acpi table for both codecs.
On device-1. we only overrode the acpi table for I2S codec. 
On device-2, we overrode the acpi table for both I2S and SDW codecs.
Both devices are connected with I2S codec. then I found that with same kernel(with or without SoundWire support), runtime PM always failed to suspend on device-1 but works well on device-2.

**Comment by plbossart** [comment] 2020-04-28 14:02
@keqiaozhang I am not able to parse your description, sorry. can you please use terms like

configuration a): rt5682 in I2S mode, MAX.. in I2S mode, pointer to acpi override table, results.
configuration b),...

thanks

**Comment by keqiaozhang** [comment] 2020-04-29 07:41
@plbossart  I'm sorry to confuse you.
I will try to make this issue clearly.
First, we found this issue in 5.6.0-rc6+, because latest sof-dev has a regression, kernel 5.7.0 failed to boot on chrome device. please refer to issue https://github.com/thesofproject/linux/issues/2063.

Let's back to this issue.  I did some debugging today and found that this issue only related to DSM, if we set the max98373 codec to feedback mode for DSM pipelines , then runtime PM will always be active.  @keyonjie  is doing further debugging.

**Comment by plbossart** [comment] 2020-04-29 15:14
@keqiaozhang @keyonjie There was a know issue on KBL where the team had to play with the speaker pin to let the amplifier suspend when DSM was used.

@sathya-nujella does this ring a bell?

**Comment by sathya-nujella** [comment] 2020-04-29 20:40
> @keqiaozhang @keyonjie There was a know issue on KBL where the team had to play with the speaker pin to let the amplifier suspend when DSM was used.
> 
> @sathya-nujella does this ring a bell?


KBL issue was there, but it was related to loading of DSM parameters from UCM.
But here in Kequiao's test, it is not UCM.. so not sure same.. but issue details and UCM fix for our reference:
=
Soraka: Move DSM param loading to Speaker Enable

Loading DSM params from Default Enable prevented
audio pci device from entering RTD3.
Moved the DSM param loading loagically to the speaker
enable section. This ensures Audio device enters RTD3
https://chromium-review.googlesource.com/c/chromiumos/overlays/board-overlays/+/930346/

**Comment by keyonjie** [comment] 2020-04-30 01:46
Thanks for sharing @plbossart @sathya-nujella, that's really good information, looks the speaker switch is the culprit, I am working on understand how it impact to the PCI device.

**Comment by naveen-manohar** [comment] 2020-04-30 02:23
Adding @sathyap-chrome

**Comment by keyonjie** [comment] 2020-04-30 04:36
So this is actually the expected behavior, we need to add setting/clearing the switch "Left/Right Spk Switch" to the Speaker enable/disable sequence to fix this.

**Comment by plbossart** [comment] 2020-04-30 13:29
> So this is actually the expected behavior, we need to add setting/clearing the switch "Left/Right Spk Switch" to the Speaker enable/disable sequence to fix this.

where would we add this? In the past it was added in the machine driver so that we wouldn't be adding more things in UCM.

**Comment by keyonjie** [comment] 2020-04-30 14:39
> > So this is actually the expected behavior, we need to add setting/clearing the switch "Left/Right Spk Switch" to the Speaker enable/disable sequence to fix this.
> 
> where would we add this? In the past it was added in the machine driver so that we wouldn't be adding more things in UCM.

They are still the ones in the machine driver sof_rt5682.c. If everything works well, those switch should be automatic switched on/off when the corresponding stream is started/stopped, right? but the experiment result here is different, we need to use 'amixer cset' to explicit set/clear those switchs. 

@plbossart do you know why this happen? Maybe we need to debug into the DAPM walking details.

```
static const struct snd_kcontrol_new sof_controls[] = {
...
	SOC_DAPM_PIN_SWITCH("Spk"),
	SOC_DAPM_PIN_SWITCH("Left Spk"),
	SOC_DAPM_PIN_SWITCH("Right Spk"),

};
```

**Comment by plbossart** [comment] 2020-04-30 16:13
I am pretty sure the Chrome folks changed the pin state to avoid playing with mixers, but I can't recall which KBL driver implemented this. @sathya-nujella @naveen-manohar any memories of this.

**Comment by sathya-nujella** [comment] 2020-05-01 15:08
> I am pretty sure the Chrome folks changed the pin state to avoid playing with mixers, but I can't recall which KBL driver implemented this. @sathya-nujella @naveen-manohar any memories of this.


sorry @plbossart  for late.. I was trying to see what was the change done.. yes, I see kernel change. Thanks for your recollection.
===
https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/1411892/

ASoC: Intel: Boards: kbl_da7219_max98927: add dai_trigger function

speaker amplifier feedback is not modeled as being dependent on any
active output. Even when there is no playback happening, parts of the graph,
specifically the IV sense->speaker protection->output remains active and
this prevents the DSP from entering low-power states.

This patch suggest a machine driver level approach where the speaker
pins are enabled/disabled dynamically depending on stream start/stop
events. DPAM graph representations show the feedback loop is indeed
disabled and low-power states can be reached.

**Comment by keyonjie** [comment] 2020-05-06 03:03
@sathya-nujella thanks, that makes sense, we might need to add similar widget enable/disable to sof_rt5682 machine driver.

@RDharageswari can you help on this?

**Comment by RDharageswari** [comment] 2020-05-06 03:20
yup

**Comment by xiulipan** [comment] 2020-05-09 04:15
@keqiaozhang Could you if the PM is enabled by check
```
$ cat /sys/bus/pci/devices/0000:00:1f.3/power/control
```
I found some similar issue https://github.com/thesofproject/linux/issues/2073 is caused by PM not enabled.

**Comment by RDharageswari** [comment] 2020-05-15 23:20
The following mixer settings can be set to off before the SPK playback and will be turned on when the usecase TRIGGER_START happens.
amixer -c0 cset name='Left Spk Switch' off
amixer -c0 cset name='Right Spk Switch' off
Following patch fixes the runtime issue:
https://github.com/thesofproject/linux/pull/2123

**Comment by YvonneYang2** [comment] 2020-06-02 04:00
Tested with #2123 on tgl chromebook/i2s mode, runtime pm still always in active. And the default Left/Right Spk Switch value is on. then i tried to turn them off manually, the pm runtime can be in suspended status.  

[dmesg.log](https://github.com/thesofproject/linux/files/4714664/dmesg.log)

**Comment by keyonjie** [comment] 2020-06-02 07:24
> Tested with #2123 on tgl chromebook/i2s mode, runtime pm still always in active. And the default Left/Right Spk Switch value is on. then i tried to turn them on manually, the pm runtime can be in suspended status.
> 
> [dmesg.log](https://github.com/thesofproject/linux/files/4714664/dmesg.log)

Yvonne, have you removed below amixer settings from shell script or UCM file?
amixer -c0 cset name='Left Spk Switch' off
amixer -c0 cset name='Right Spk Switch' off

**Comment by ClarexZhou** [comment] 2020-06-02 10:14
Verified #2123 again. Behaviors as below:  Pusleaudio is already disabled.
1. boot up system, runtime PM keeps active.
"Left Spk Switch" and "Right Spk Switch" is on, amixer is here
[amixerContents.txt](https://github.com/thesofproject/linux/files/4716366/amixerContents.txt)
2. Trigger headset playback and stop to check, headset audio output works ok. But runtime PM keeps active, 
3. Trigger 373-spk playabck and stop to check, runtime PM auto enter suspended successfully.
4. Trigger headset playback again,  Headset audio output quality is very bad (1 channel output both 2 channels output, and the sound is harsh), but runtime PM can auto enter suspended after stop stream. Amixer contents is here 
[amixerContents_afterRuntimePmSuspend.txt](https://github.com/thesofproject/linux/files/4716401/amixerContents_afterRuntimePmSuspend.txt)
dmesg and sof logger as below:
[dmesg.txt](https://github.com/thesofproject/linux/files/4716410/dmesg.txt)
[full_soflogger_afterPMsuspended.txt](https://github.com/thesofproject/linux/files/4716415/full_soflogger_afterPMsuspended.txt)

Difference except "Left Spk Switch" and "Right Spk Switch" is as below:
numid=83,iface=MIXER,name='Left ADC PVDD'  is changed from 0 t 183
numid=84,iface=MIXER,name='Left ADC TEMP' is changed from 0 to 49
numid=27,iface=MIXER,name='Right ADC PVDD' is changed form 0 to 183
numid=28,iface=MIXER,name='Right ADC TEMP' is changed from 0 to 49
And can't set back to 0 via cset. No any message in dmesg when run cset
```
ubuntu@TGL-Volteer-01:~/pmlog$ amixer cset numid=83,iface=MIXER,name='Left ADC PVDD' 0
numid=83,iface=MIXER,name='Left ADC PVDD'
  ; type=INTEGER,access=rw------,values=1,min=0,max=255,step=0
  : values=183
ubuntu@TGL-Volteer-01:~/pmlog$ amixer cset numid=84 0
numid=84,iface=MIXER,name='Left ADC TEMP'
  ; type=INTEGER,access=rw------,values=1,min=0,max=255,step=0
  : values=49
```
No difference for 5682 register, check via  /sys/kernel/debug/regmap/i2c-10EC5682\:00/registers 
afterboot log was caught after above step1, which runtime PM always active, and headset output is good. 
after373playback log was caught after above step3, which runtime PM works ok and headset output got issue
Loopback headset output audio are in  
[headset_output.zip](https://github.com/thesofproject/linux/files/4758500/headset_output.zip)

[5682_register_afterboot.txt](https://github.com/thesofproject/linux/files/4756354/5682_register_afterboot.txt)
[5682_register_afterboot_afterheadsetplayback.txt](https://github.com/thesofproject/linux/files/4756356/5682_register_afterboot_afterheadsetplayback.txt)
[5682_register_after373playback.txt](https://github.com/thesofproject/linux/files/4756357/5682_register_after373playback.txt)
[5682_register_after373playback_afterheadsetplayback.txt](https://github.com/thesofproject/linux/files/4756358/5682_register_after373playback_afterheadsetplayback.txt)
[5682_register_after373_duringheadsetplayback.txt](https://github.com/thesofproject/linux/files/4758490/5682_register_after373_duringheadsetplayback.txt)
[5682_register_afterboot_duringheadsetplayback.txt](https://github.com/thesofproject/linux/files/4758491/5682_register_afterboot_duringheadsetplayback.txt)

**Comment by keyonjie** [comment] 2020-06-02 12:20
Thanks for the detail information @ClarexZhou .
@RDharageswari I think you have tested this on Chrome environment, can you provide UCM file then we can port it to Ubuntu and align for the testing?

**Comment by YvonneYang2** [comment] 2020-06-09 07:05
> Verified #2123 again. Behaviors as below: Pusleaudio is already disabled.
> 
> 1. boot up system, runtime PM keeps active.
>    "Left Spk Switch" and "Right Spk Switch" is on, amixer is here
>    [amixerContents.txt](https://github.com/thesofproject/linux/files/4716366/amixerContents.txt)
> 2. Trigger headset playback and stop to check, headset audio output works ok. But runtime PM keeps active,
> 3. Trigger 373-spk playabck and stop to check, runtime PM auto enter suspended successfully.
> 4. Trigger headset playback again,  Headset audio output quality is very bad (1 channel output both 2 channels output, and the sound is harsh), but runtime PM can auto enter suspended after stop stream. Amixer contents is here
>    [amixerContents_afterRuntimePmSuspend.txt](https://github.com/thesofproject/linux/files/4716401/amixerContents_afterRuntimePmSuspend.txt)
>    dmesg and sof logger as below:
>    [dmesg.txt](https://github.com/thesofproject/linux/files/4716410/dmesg.txt)
>    [full_soflogger_afterPMsuspended.txt](https://github.com/thesofproject/linux/files/4716415/full_soflogger_afterPMsuspended.txt)
> 
> Difference except "Left Spk Switch" and "Right Spk Switch" is as below:
> numid=83,iface=MIXER,name='Left ADC PVDD' is changed from 0 t 183
> numid=84,iface=MIXER,name='Left ADC TEMP' is changed from 0 to 49
> numid=27,iface=MIXER,name='Right ADC PVDD' is changed form 0 to 183
> numid=28,iface=MIXER,name='Right ADC TEMP' is changed from 0 to 49
> And can't set back to 0 via cset. No any message in dmesg when run cset
> 
> ```
> ubuntu@TGL-Volteer-01:~/pmlog$ amixer cset numid=83,iface=MIXER,name='Left ADC PVDD' 0
> numid=83,iface=MIXER,name='Left ADC PVDD'
>   ; type=INTEGER,access=rw------,values=1,min=0,max=255,step=0
>   : values=183
> ubuntu@TGL-Volteer-01:~/pmlog$ amixer cset numid=84 0
> numid=84,iface=MIXER,name='Left ADC TEMP'
>   ; type=INTEGER,access=rw------,values=1,min=0,max=255,step=0
>   : values=49
> ```

Tested it latest topic/sof-dev(d8ac95aa4) as #2123 was merged, same behavior as above.

**Comment by keyonjie** [comment] 2020-06-10 08:12
@YvonneYang2 @ClarexZhou those mixers are for maxim98373 read only registers, that's why you can't 'set' them.

**Comment by ClarexZhou** [comment] 2020-06-11 01:38
The headset output issue isn't related with below mixers after runtime PM works.
numid=83,iface=MIXER,name='Left ADC PVDD' 
numid=84,iface=MIXER,name='Left ADC TEMP' 
numid=27,iface=MIXER,name='Right ADC PVDD' 
numid=28,iface=MIXER,name='Right ADC TEMP' 

There is one time i tried steps in https://github.com/thesofproject/linux/issues/2053#issuecomment-637440089,  above mixers are not changed after runtime PM works and headset output still got issue.
afterboot log was caught after system boot up, which runtime PM always active, and headset output is good.
after373playback log was caught after 373 playback, which runtime PM works ok and headset output got issue
[5682_register_afterboot_duringheadsetplayback.txt](https://github.com/thesofproject/linux/files/4762048/5682_register_afterboot_duringheadsetplayback.txt)
[amixer_afterboot.txt](https://github.com/thesofproject/linux/files/4762050/amixer_afterboot.txt)
[amxier_after373play.txt](https://github.com/thesofproject/linux/files/4762051/amxier_after373play.txt)
[dmesg.txt](https://github.com/thesofproject/linux/files/4762052/dmesg.txt)
[5682_register_after373_duringheadsetplayback.txt](https://github.com/thesofproject/linux/files/4762053/5682_register_after373_duringheadsetplayback.txt)

**Comment by ClarexZhou** [comment] 2020-06-12 05:42
Split headset audio output issue and track in https://github.com/thesofproject/linux/issues/2190

**Comment by RanderWang** [comment] 2020-06-15 09:25
The spk switch is restored by alsactrl in user mode. Please disable it in /var/lib/alsa/asound.state
````
        control.121 {
                iface MIXER
                name 'Left Spk Switch'
                value false
                comment {
                        access 'read write'
                        type BOOLEAN
                        count 1
                }
        }
        control.122 {
                iface MIXER
                name 'Right Spk Switch'
                value false
                comment {
                        access 'read write'
                        type BOOLEAN
                        count 1
                }
        }

````

**Comment by ClarexZhou** [comment] 2020-06-16 06:53
Runtime PM works ok after changed in /var/lib/alsa/asound.state

**Comment by ClarexZhou** [comment] 2020-06-16 06:56
Close issue

**Closed as completed by ClarexZhou** 2020-06-16 06:56 UTC
Labels: bug, P1, TGL, Chrome, I2S, machine driver
