### ISSUE TITLE
[BUG]Can't open codec intel-hdmi-hifi2: -16 when aplay HDMI/DP after plug in HDMI/DP

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1537] opened 2019-11-22 09:17 UTC
**Describe the bug**
Boot up without HDMI/DP external port connected, then plug in HDMI/DP when system in idle status. Amixer contens shows HDMI/DP is connected. But Aplay HDMI/DP, dmesg shows "can't open codec intel-hdmi-hifi2: -16." 

 It seems a regression, integration/soundwire-latest commit: 4cd6497 (ww47.3 daily kernel version) cannot reproduce the issue. But code rebased, I cannot do bisect.

**Console** 
```
ubuntu@ubuntu-Latitude-11:~$ aplay -Dhw:0,6 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i
aplay: main:788: audio open error: Device or resource busy
``` 

**dmesg**
```
[  118.768334] sof-audio-pci 0000:00:1f.3: ipc tx: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  118.768390] sof-audio-pci 0000:00:1f.3: ipc tx succeeded: 0x40020000: GLB_PM_MSG: CTX_RESTORE
[  118.774657] snd_hda_codec_hdmi ehdaudio0D2: ASoC: can't open codec intel-hdmi-hifi2: -16
[  118.774661]  iDisp2: ASoC: BE open failed -16
[  118.774662]  HDMI2: ASoC: failed to start some BEs -16
[  118.775001] sof-audio-pci 0000:00:1f.3: snd_sof_runtime_idle
[  118.775004]  HDMI2: ASoC: BE playback disconnect check for iDisp2
[  118.775005]  HDMI2: freed DSP playback path HDMI2 -> iDisp2
[  119.265602] sof-audio-pci 0000:00:1f.3: ipc rx: 0x90020000: GLB_TRACE_MSG
[  119.265634] sof-audio-pci 0000:00:1f.3: ipc rx done: 0x90020000: GLB_TRACE_MSG
```
**To Reproduce**
1. Boot up without HDMI/DP external port connected.
2. Plug in HDMI or DP external port.   
3. Aplay HDMI/DP via "aplay -Dhw:0,6 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i"

**Reproduced rate**
100%
Only reboot can recover the issue. Boot up with HDMI/DP external connected cannot reproduce the issue.
 
**Expected result**
Aplay successfully

**Actual result**
Dmesg shows "can't open codec intel-hdmi-hifi2: -16" 

Test recipe:
kernel: https://github.com/thesofproject/linux/tree/integration/soundwire-latest commit: 68cadd8
FW: https://github.com/thesofproject/sof/commits/master  commit: 9b5dc8c
tplg: Same with FW branch, sof-cml-rt711-rt1308-mono-rt715.tplg
platform: CML Laptop with ALC711+ ALC1308+ ALC715

[dmesg.log](https://github.com/thesofproject/linux/files/3878804/dmesg.log)

**Comment by YvonneYang2** [comment] 2019-11-22 09:18
@kv2019i 
Could you please have a look?  Thanks ~

**Comment by kv2019i** [comment] 2019-11-22 12:39
@YvonneYang2 ack, will take a look

**Comment by bardliao** [comment] 2019-11-22 12:58
@YvonneYang2 Is this a regression? I am not sure if it is caused by below commits
https://github.com/thesofproject/linux/commit/1fb485e261083daa536ca93e5eae984447126642
https://github.com/thesofproject/linux/commit/20d42110c579771ef1d7e9d615bb16fd8ac32435
https://github.com/thesofproject/linux/commit/12b286a2bf4b38c0fd9d7f24c23b912bf3fc1d82

**Comment by dengyangchao** [comment] 2019-11-25 06:00
Issue can reproduce on:
GLK Chrome with onboard codec DA7219 in I2S mode
CML Chrome with onboard codec RT5682 in I2S mode
ICL RVP with onboard codec ALC700 in HDA mode
CFL-S RVP with onboard codec ALC700 in HDA mode
APL UP2 with codec  PCM512x in I2S mode


Firmware: d6fe2b13 https://github.com/thesofproject/sof/commits/master
Kernel: b090cc8a https://github.com/thesofproject/linux/commits/topic/sof-dev

**Comment by kv2019i** [comment] 2019-11-26 17:28
Ok, managed to reproduce this and rootcause to following commit in upstream:

9c32fea836928d7a25a83b337f268e533cfc5c3d
ALSA: hda - Add DP-MST support for non-acomp codecs

We did test this in our CI before merging, but didn't catch the issue. I'll submit a fix to upstream tomorrow.

**Comment by kv2019i** [comment] 2019-11-27 11:48
Fix submitted upstream https://mailman.alsa-project.org/pipermail/alsa-devel/2019-November/159242.html

**Comment by kv2019i** [comment] 2019-11-27 19:05
Patch merged upstream:
https://mailman.alsa-project.org/pipermail/alsa-devel/2019-November/159265.html

@YvonneYang2 Can you verify with PR1557?

**Comment by dengyangchao** [comment] 2019-11-28 05:49
@kv2019i Verified on GLK Chrome with onboard codec DA7219 in I2S mode, after applied #1557 , issue can't reproduce.

**Comment by kv2019i** [comment] 2019-11-28 12:00
> @kv2019i Verified on GLK Chrome with onboard codec DA7219 in I2S mode, after applied #1557 , issue can't reproduce.

Thanks @dengyangchao , that's good news! Let's wait until we get the patch to sof-dev via next upstream merge and we can then close this.

**Comment by aiChaoSONG** [comment] 2019-12-04 02:41
tried with 709427e, issue not reproduced on cml with ALC3204

**Comment by dengyangchao** [comment] 2019-12-04 09:02
After upstream #1576 merged, issue can't reproduce, close.

**Closed as completed by dengyangchao** 2019-12-04 09:02 UTC
Labels: bug, P1, APL, GLK, ICL, CML, CFL, upstream
