### ISSUE TITLE
Early wake from DSP when running hotword pipeline with FW debug enabled

### ISSUE THREAD

**Issue by sathyap-chrome** [thesofproject/linux#3034] opened 2021-07-09 05:21 UTC
When we open wov stream and then try soix, there is early wake from DSP

see attached logs:
https://github.com/thesofproject/linux/files/6783689/soix.txt

Resume caused by IRQ 179, AudioDSP

But when wov stream is closed, the soix entry and exit is fine.

In kernel config,i had enabled FW debug and other options for debug purpose: (everything under SOF_DEBUG)
+CONFIG_SND_SOC_SOF_DEBUG=y
+CONFIG_SND_SOC_SOF_DEBUG_ENABLE_DEBUGFS_CACHE=y
+CONFIG_SND_SOC_SOF_DEBUG_ENABLE_FIRMWARE_TRACE=y
+CONFIG_SND_SOC_SOF_DEBUG_FORCE_IPC_POSITION=y
+CONFIG_SND_SOC_SOF_DEBUG_IPC_FLOOD_TEST=y
+CONFIG_SND_SOC_SOF_DEBUG_RETAIN_DSP_CONTEXT=y
+CONFIG_SND_SOC_SOF_DEBUG_VERBOSE_IPC=y
+CONFIG_SND_SOC_SOF_DEBUG_XRUN_STOP=y
+CONFIG_SND_SOC_SOF_DEVELOPER_SUPPORT=y

**Comment by ranj063** [comment] 2021-07-09 15:40
@sathyap-chrome thank you for reporting this. Im not sure if this is  kernel issue or a FW issue yet. In the driver, we set the flag to disable trace when entering D0i3 in S0ix. But maybe the FW is not acting on it. Need to check

**Comment by libinyang** [comment] 2021-07-26 10:58
@sathyap-chrome I tried it on my Brya. My Brya can't enter S0ix from reading the residencies. Is there anything I should do to make the OS enter S0ix? My platform is Brya proto1 SKU1. BTW: if I run `echo "freeze" > state`, the display will be off, and if I clap, the WoV will waken the display.

**Comment by libinyang** [comment] 2021-08-03 07:02
some updates:
1 can't enter S0ix is because the coreboot is too old.
2 Based on the phenomenon, we suspect that fw is sending the log to host, which cause early wake from S0ix. After some debug, this assumption is precluded.
3. And I also found, if I disable dma trace either in driver or fw, this bug won’t happen.
4. After study the code, I guess maybe DMA should be disabled to enter S0ix on ADL.

**Comment by ranj063** [comment] 2021-08-03 16:56
@libinyang we do send the TRACE_DISABLE flag along with the PM_GATE IPC when we enter D0i3 during system suspend, right? Are you saying that more needs to be done from the host? Or is the FW not acting on it?

**Comment by libinyang** [comment] 2021-08-04 13:14
After some debug, this issue is caused when dma is triggered. So it seems this is an ADL specific issue. I will prepare a patch for this issue.

**Comment by libinyang** [comment] 2021-08-04 13:19
> @libinyang we do send the TRACE_DISABLE flag along with the PM_GATE IPC when we enter D0i3 during system suspend, right? Are you saying that more needs to be done from the host? Or is the FW not acting on it?

@ranj063 Yes, we send the flag, but it didn't work. I have checked even there is no any log sent from fw, but if we triggered start the dma, pc10 won't be entered on ADL.

**Comment by libinyang** [comment] 2021-08-16 06:30
This bug can be fixed by https://github.com/thesofproject/linux/pull/3099.

However, we still have an open: why WoV dma needn't be stopped in S0ix.

**Comment by kv2019i** [comment] 2021-12-10 20:18
I can confim with SOF1.9.1 and kernel with dma-stop fixes, this still happens. System logs show system not cleanly entering S0ix in this case. Disabling the FW trace helps to solve the issue.

**Comment by mwasko** [comment] 2021-12-13 09:44
What is the reproduction rate of this issue?

**Comment by kv2019i** [comment] 2021-12-13 09:51
@mwasko This is 100% reproducible. The fact that we leave DMA programmed for trace, prevents S0ix entry although on TGL it works just fine.

**Comment by keqiaozhang** [comment] 2022-01-10 02:38
PR #3332 can fix this issue, so this bug can be closed.

**Closed as completed by keqiaozhang** 2022-01-10 02:38 UTC
Labels: bug, P1, Keyword Detection, S0ix, ADL
