### ISSUE TITLE
[bug][tgl]System freezed  after wake up from S2idle with HDMI playback.

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1701] opened 2020-01-13 09:41 UTC
**Describe the bug**
System freezed  after wake up from S2idle with HDMI playback.

Wait about 6min-8mins, HDMI can aplay successfully and can pause and resume successfully，but aplay again, it failed and can not be released, Only unplug/plugin power supply to reboot can recover

**To Reproduce**
1.sudo reboot with HDMI connected
2. open a terminal:aplay -Dhw:0,4 -r48000 -c2 -fs16_le wav/48California_Dreaming.wav -vv -i
3.open another terminal: "sudo rtcwake -m mem -s 10 " from idle

**Reproduce rate**
5/5

**Expected result**
Aplay via HDMI normally after wake up from s2idle

**Actual result**
The system freezed  after wake up from S2idle 
 
no error dmesg 

 
[dmesg13.log](https://github.com/thesofproject/linux/files/4052876/dmesg13.log)
[sof_trace13.log](https://github.com/thesofproject/linux/files/4052877/sof_trace13.log)

Platform: TGL-U RVP with onboard codec ALC711 in HDA modeFirmware: 418c77e6 https://github.com/thesofproject/sof/commits/master
Kernel: 5e7259be https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by Liviali155** [comment] 2020-01-13 10:09
Bi-sect result: Caused by kernel commit:03c657c[https://github.com/thesofproject/linux/commit/03c657c26ccb9fd8de65c5596f252f81c2557978](https://github.com/thesofproject/linux/commit/03c657c26ccb9fd8de65c5596f252f81c2557978)

**Comment by Liviali155** [comment] 2020-01-14 01:24
@ranj063,please check it

**Comment by Liviali155** [comment] 2020-01-14 05:52
Error only seen in s2idle mode,not seen in deep mode

**Comment by ranj063** [comment] 2020-01-14 16:05
@Liviali155 @mengdonglin I have no TGL boards to debug this.

**Comment by Liviali155** [comment] 2020-02-11 07:29
Tried with PR #1767[](https://github.com/thesofproject/linux/pull/1767),error not seen

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: a573a2cd https://github.com/thesofproject/sof/commits/master
Kernel: 0c7dcfee8 https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by sinahuang** [comment] 2020-02-11 12:27
Issue can't be reproduce on TGL-U RVP with soundwire-latest (commit: 0c7dcfe) when aplay DP/HDMI after wake up from s2idle.

Test recipe

Kernel:https://github.com/thesofproject/linux/commits/topic/sof-dev commit:0c7dcfe
FW: https://github.com/thesofproject/sof/commits/master commit: a573a2c
Tplg: Same with FW branch, rename sof-tgl-rt711-i2s-rt1308.tplg to sof-tgl-rt711-rt1308.tplg
Platform:TGL-U RVP with codec ALC711 in SDW mode and RT1308 in I2S mode

**Comment by kv2019i** [comment] 2020-02-13 09:49
Ack @Liviali155 and @sinahuang , this looks good. We will soon get the fix in #1767 via upstream merge to sof-dev and I think we can close this issue then.

**Comment by Liviali155** [comment] 2020-02-14 11:23
Error not seen on TGL-U on 20200214,but  PR #1767 has not been merged

Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 4d17d0de https://github.com/thesofproject/sof/commits/master
Kernel: daf71dce https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by kv2019i** [comment] 2020-02-14 12:56
-> https://github.com/thesofproject/linux/issues/1651#issuecomment-586275716

**Comment by mengdonglin** [comment] 2020-02-16 12:39
Close this issue since fix of PR #1767 was actually merged via upstream rebase. @keyonjie @xiulipan @Liviali155 I think we have a good code base to test WoV now :)

**Closed as completed by mengdonglin** 2020-02-16 12:39 UTC
Labels: bug, P1, TGL, suspend resume
