### ISSUE TITLE
[BUG] Delay in data transfer to audio dsp

### ISSUE THREAD

**Issue by softwarecki** [thesofproject/linux#4408] opened 2023-06-02 11:36 UTC
For some time I suspected that we have a problem with the linux audio driver. It concerns the thread that is responsible for exchanging data via dma with audio dsp. (I don't know if this was implemented via a thread, I didn't look at the sources). It seems we have a significant delay in handling transfer when only one stream is active.

In the case of the DMIC problem (https://github.com/thesofproject/sof/issues/7506), it looks like the receiving thread started too late, after starting a capture pipeline. This problem was temporarily circumvented by this commit: https://github.com/thesofproject/sof/commit/5ad5da5bc7571ea25dd711c591fcaef54fdc2d18. Interestingly, it also solves these issues: https://github.com/thesofproject/sof/issues/7603 and https://github.com/thesofproject/sof/issues/7646

In case of playback problems with deepbuffering (https://github.com/thesofproject/sof/issues/7663), it seems that the linux driver usually takes 2-4ms to load the data into the buffer. Sometimes the delay is even longer, which exhausts the available data to read from the host's dma before a new portion of data is written by the driver. This problem was temporarily circumvented by this commit:  https://github.com/thesofproject/sof/commit/8ddd262530042b10a5e566062433b5f2c294dd98

Interestingly, the following problems disappear when we start a second playback at the same time. Please have someone from the linux audio driver look at the problem and measure it to make sure everything is working properly. In the meantime, I will try to prepare measurements of the time that elapsed between the confirmation of reading data by the firmware and placing the next chunk by the linux driver. I would like to compare this delay when one stream is played with the delay when we have two streams.

Relates issues:
- https://github.com/thesofproject/sof/issues/7663
- https://github.com/thesofproject/sof/issues/7646 (Internal Intel issue number 14019405287)
- https://github.com/thesofproject/sof/issues/7506
- https://github.com/thesofproject/sof/issues/7603

@yongzhi1 @kv2019i @juimonen @marc-hb @abonislawski

**Comment by plbossart** [comment] 2023-06-02 14:47
I don't think anyone can proceed with such a broad description of what the issue might be on the Linux side.

We can also flip the argument and state that the second stream forces the DSP firmware to behave differently and work better.
We've seen this problem on the LNL test platform where a second SSP stream fixed DMIC issues, otherwise with a single stream the capture is too slow.

The one thing we could do though is disable SPIB support. That will force the DSP to be free-running instead of being dependent on an update from apps.

**Comment by ranj063** [comment] 2023-06-02 15:10
@plbossart I was also wondering about SPIB this morning when I saw this issue but it doesnt look like we even enable SPIB in our tests. We enabled SPIB only when hda_dsiable_rewinds is set. But this is dependent on a Kconfig that doesnt seem to exist anymore

static bool hda_disable_rewinds = IS_ENABLED(CONFIG_SND_SOC_SOF_HDA_DISABLE_REWINDS);

**Comment by plbossart** [comment] 2023-06-02 15:17
Good catch @ranj063, we need to remove this default init and keep zero as the implied value.

But that adds to my point that the HDaudio DMA does not wait for the Linux threads to do anything at the moment, even if the apps are completely stuck the DMA will keep looping forever so the notion that there's something blocking is invalid.

**Comment by marc-hb** [comment] 2023-06-02 19:39
> I don't think anyone can proceed with such a broad description of what the issue might be on the Linux side.

The description is broad and speculative but it has a collection of links to specific test failures. Maybe intermittent and hard to reproduce but specific. My 2 cents.

**Comment by mwasko** [comment] 2023-06-05 10:10
> > I don't think anyone can proceed with such a broad description of what the issue might be on the Linux side.
> 
> The description is broad and speculative but it has a collection of links to specific test failures. Maybe intermittent and hard to reproduce but specific. My 2 cents.

Why do you say it is speculative? There is a deep buffer scenario where FW waits with DMA update till there is less then 4 periods (power optimization) and in this scenario it is observed the SW driver sporadically fails to catch-up and produce new data within those 4ms.

We can of course remove this power optimization in FW, but please then explain why SW driver fails to produce data within 4ms?

**Comment by kv2019i** [comment] 2023-06-05 13:57
It would sound like this is related to L1 exit not happing correctly (DMA transfers are programmed, but do not progress as DMI is in L1). Does this patch in mtl-005 branch help in the setups where this happens https://github.com/thesofproject/sof/commit/010746170da9707ca73b0663747a44d0e08ca8db ? On this platform, host driver can no longer control L1SEN, so the control of L1 exits is FW/HW driven.

**Comment by marc-hb** [comment] 2023-06-05 14:11
> Why do you say it is speculative? 

Because every paragraph says "it seems" or "it looks".

**Comment by abonislawski** [comment] 2023-06-05 15:52
> Does this patch in mtl-005 branch help in the setups where this happens [thesofproject/sof@0107461](https://github.com/thesofproject/sof/commit/010746170da9707ca73b0663747a44d0e08ca8db) ? On this platform, host driver can no longer control L1SEN, so the control of L1 exits is FW/HW driven.

I didnt test it now but previously it was done for mtl-003 to help in similar case.
Maybe delay is not long enough? (L1 exit time)
https://github.com/thesofproject/zephyr/commit/f117365a2bcec7fea9f68af213eb6f1386e0826a

**Comment by plbossart** [comment] 2023-06-05 16:50
@mwasko you've worked on Linux before and you should know that dealing with 4ms hard real-time requirements will not work without more priority given to audio. Why do you think most solutions use a 10ms period?

Also we see these HDaudio DMA freezes with regular capture, the deep-buffer is a completely different case where the 4ms does not even apply if you have a large buffer in the firmware.

**Comment by mwasko** [comment] 2023-06-06 09:41
> @mwasko you've worked on Linux before and you should know that dealing with 4ms hard real-time requirements will not work without more priority given to audio. Why do you think most solutions use a 10ms period?

@plbossart that is fair and I understand performance & priority limitations, but I don't understand why in such case there are submitted issues on FW, while the actual problem is lying at SW Driver not being able to provide/consume data on time. That is the reason why this SW issue was submitted by @softwarecki at first place and linked to submitted issues.

> 
> Also we see these HDaudio DMA freezes with regular capture, the deep-buffer is a completely different case where the 4ms does not even apply if you have a large buffer in the firmware.

The thing is that those problems are observed with Linux E2E scenario, as far as I can tell we don't have this problem in python testing.

**Comment by plbossart** [comment] 2023-06-06 13:14
@mwasko you are starting from the hypothesis that the " SW Driver is not able to provide/consume data on time"

All my experiments show that the host DMA is stuck as a result of some power management issues that is NOT controlled by the host driver. I can get rid of all issues by forcing the DDR to remain active with the RDDRP bit set by the cSOF firmware.

In addition, the host driver did not configure the SPIB bit, so the DMA will not wait for anything and keep looping.

That's two arguments pointing to 'something else' as the root cause for the DMA delays.

I don't mind if you prefer to the 'linux' bugs but it's a system issue, not one squarely owned by the 'driver' team.

**Comment by plbossart** [comment] 2023-08-15 15:08
@softwarecki @mwasko There's been no update for 2 months so I don't think this qualifies as a P1 issue. Closing for now, you may re-open it if you think there is new data to review.

**Closed as completed by plbossart** 2023-08-15 15:08 UTC
Labels: bug, P1, MTL
