### ISSUE TITLE
[BUG][tgl] Jack detection is off  in amixer contents after reboot with HDMI connected

### ISSUE THREAD

**Issue by Liviali155** [thesofproject/linux#1792] opened 2020-02-14 13:06 UTC
**Describe the bug**
Jack detection is off  in amixer contents after reboot with HDMI/DP connected,and no sound output,but monitor display is normally
Unplug/plug HDMI/DP  again can recovery 

**To Reproduce**
1.sudo reboot with HDMI/DP connected
2.amixer contents to check jack detection

**Reproduction Rate**
10/10

**Expected behavior**
HDMI/DP jack detection is on in amixer contents 

**Actual result**
HDMI/DP jack detection is off in amixer contents 

```
numid=8,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=14,iface=CARD,name='HDMI/DP,pcm=4 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=20,iface=CARD,name='HDMI/DP,pcm=5 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=7,iface=CARD,name='Headphone Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
numid=6,iface=CARD,name='Mic Jack'
```
Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware: 4d17d0de https://github.com/thesofproject/sof/commits/master
Kernel: daf71dc https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: tools/topology/sof-hda-generic-4ch.tplg same as firmware
[dmesg0214.log](https://github.com/thesofproject/linux/files/4204558/dmesg0214.log)
[sof_trace0214.txt](https://github.com/thesofproject/linux/files/4204559/sof_trace0214.txt)

**Comment by Liviali155** [comment] 2020-02-14 13:16
Bi-sect result:
caused by kernel commit  #[https://github.com/thesofproject/linux/commit/8c0050f1207942265db85a65173cd685ab64f1bc](https://github.com/thesofproject/linux/commit/8c0050f1207942265db85a65173cd685ab64f1bc)

**Comment by kv2019i** [comment] 2020-02-14 15:30
@Liviali155 wrote:
> Bi-sect result:
> caused by kernel commit #[8c0050f](https://github.com/thesofproject/linux/commit/8c0050f1207942265db85a65173cd685ab64f1bc)

Thanks, this a good lead. I will take a look at this next week.

**Comment by sinahuang** [comment] 2020-02-26 11:17
Issue also can be reproduced on TGL-U RVP with codec ALC711 in SDW mode and  RT1308 in I2S mode if reboot with HDMI connected.

**Comment by Liviali155** [comment] 2020-02-27 03:34
On latest sof/dev +master,issue can only be reproduced with HDMI,DP is normal,tested on TGL HDA
Platform: TGL-U RVP with onboard codec ALC711 in HDA mode
Firmware:  21f13448 https://github.com/thesofproject/sof/commits/master
Kernel: 8d47294d https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology file: tools/topology/sof-hda-generic-4ch.tplg same as firmware

**Comment by kv2019i** [comment] 2020-02-27 17:42
Tested today with TGL RVP and HDMI, but could not reproduce. @Liviali155 can you take log of the case with i915 traces enabled:

modprobe conf.d:
options drm debug=0x1e

OR with kernel cmdline:
drm.debug=0x1e

**Comment by Liviali155** [comment] 2020-02-28 07:40
> modprobe conf.d:
> options drm debug=0x1e
> 
> OR with kernel cmdline:
> drm.debug=0x1e

log as attachment
[drm.log](https://github.com/thesofproject/linux/files/4265784/drm.log)

**Comment by kv2019i** [comment] 2020-03-03 09:48
@Liviali155 The DRM log is so verbose that it fills the dmesg buffer very quickly and e.g. this log is missing lot of events from the early boot. You can overcome by increasing the dmesg size. "log_buf_len=1M" should be sufficient. You can add this e.g. with following to to /etc/default/grub:

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash log_buf_len=1M"

**Comment by Liviali155** [comment] 2020-03-03 13:41
On my tgl-u,after update to A6 Silicon,issue can not be reproduced when reboot with HDMI, but DP can not work
Update to A2 Silicon,issue can not be reproduced when reboot with HDMI,but issue can be reproduced when reboot with DP

**Comment by Liviali155** [comment] 2020-03-05 01:18
> @Liviali155 The DRM log is so verbose that it fills the dmesg buffer very quickly and e.g. this log is missing lot of events from the early boot. You can overcome by increasing the dmesg size. "log_buf_len=1M" should be sufficient. You can add this e.g. with following to to /etc/default/grub:
> 
> GRUB_CMDLINE_LINUX_DEFAULT="quiet splash log_buf_len=1M"

I have increased the dmesg size,drm log as attachment
[drm0305.log](https://github.com/thesofproject/linux/files/4290425/drm0305.log)

**Comment by kv2019i** [comment] 2020-03-05 18:18
@Liviali155 Thank you! This helps a lot. This is starting to look like a i915 issue.

There's a monitor connected and the monitor ELD is found:
[    2.019369] [drm:drm_add_edid_modes [drm]] ELD size 36, SAD count 1
[    2.019384] [drm:drm_add_display_info [drm]] non_desktop set to 0

But when audio driver asks at boot, which monitors are connected, valid ELD is not returned for any monitor. This is a bit cryptic to parse from default traces but in log segment:

[    2.703028] [drm:i915_audio_component_get_eld [i915]] Not valid for port A
[    2.703068] [drm:i915_audio_component_get_eld [i915]] Not valid for port A
[    2.703102] [drm:i915_audio_component_get_eld [i915]] Not valid for port A
...
[    2.703684] [drm:i915_audio_component_get_eld [i915]] Not valid for port I
[    2.703708] [drm:i915_audio_component_get_eld [i915]] Not valid for port I
[    2.703732] [drm:i915_audio_component_get_eld [i915]] Not valid for port I

... there should be at least one port, where there is less than three "Not valid for port" traces (as no trace is printed when a valid ELD is returned). It means audio is going through all possible ports, and no data is returned -> no monitors are connected.

I'll double check tomorrow and compare once more with #1687 , and if the theory holds, can move this to i915 bug tracker.

**Comment by kv2019i** [comment] 2020-03-10 09:56
I did not file a new GFX but as this is probably related to this existing bug:
https://gitlab.freedesktop.org/drm/intel/issues/1363
... let's close if GFX side confirms it is theirs.

**Comment by kv2019i** [comment] 2020-03-17 16:07
A candidate patch is available, now under testing. I'll post a link here once it is available.

**Comment by kv2019i** [comment] 2020-03-18 09:38
@Liviali155 Can you give a test to the fix candidate #1904 ?

**Comment by Liviali155** [comment] 2020-03-18 10:40
> @Liviali155 Can you give a test to the fix candidate #1904 ?

Tried with PR #1904 ,tips“Failed to start load kernel Modules”

<img width="375" alt="Capture" src="https://user-images.githubusercontent.com/56707932/76952308-dbd53900-6947-11ea-88b9-c0c9112075ec.PNG">

**Comment by mamarley** [comment] 2020-03-18 12:44
Not sure what's happening for Livia, but for me it works fine.  HDMI/DP audio now works fine immediately on boot.  Thanks!

**Comment by mamarley** [comment] 2020-03-18 13:15
After further usage, however, it seems this introduces a strange issue where even small amounts of GPU load cause the mouse cursor to move jerkily and "drop frames".  It seems weird, but reverting the patch causes it to work normally again.

**Comment by kv2019i** [comment] 2020-03-18 16:25
Thanks @mamarley ! Follow-up is currently discussed on intel-gfx list and I passed your findings to the folks working on the patch now.

**Comment by mamarley** [comment] 2020-03-18 17:20
I'm probably just being dense, but I can't seem to locate the thread.  Could you please link to it?  Thanks!

**Comment by kv2019i** [comment] 2020-03-18 17:44
@mamarley 
> I'm probably just being dense, but I can't seem to locate the thread. Could you please link to it? Thanks!

Sure, no prob. It is here: https://lists.freedesktop.org/archives/intel-gfx/2020-March/233802.html

**Comment by mamarley** [comment] 2020-03-18 18:14
That patch is different from the one you linked earlier.  When I tried the one from the list (it took a bit of massaging to get it to apply to 5.6-rc6), the audio works on boot and the cursor behaves normally.

**Comment by Liviali155** [comment] 2020-03-19 02:48
> > @Liviali155 Can you give a test to the fix candidate #1904 ?
> 
> Tried with PR #1904 ,tips“Failed to start load kernel Modules”
> 
> <img alt="Capture" width="375" src="https://user-images.githubusercontent.com/56707932/76952308-dbd53900-6947-11ea-88b9-c0c9112075ec.PNG">


The kern.log as attachment,It should has  2 times power on log,first is power on failed log
[kern.log](https://github.com/thesofproject/linux/files/4352421/kern.log)

**Comment by kv2019i** [comment] 2020-03-19 07:27
@mamarley wrote:
> That patch is different from the one you linked earlier. When I tried the one from the list 
> (it took a bit of massaging to get it to apply to 5.6-rc6), the audio works on boot and 

Yes, true, they modified the implementation in the first version sent out on the list. Thanks a lot for the report. There are now additional validation rounds done on the patch sent to the list and if all goes well, the patch will get merged. Thanks a lot for testing!

@Liviali155 I'll check the log separately, this might something else.

**Comment by mamarley** [comment] 2020-03-23 03:03
I hadn't noticed this before since I didn't test my Broadwell laptop with an eDP display with the patched kernel, but the patch from the ML re-regresses https://gitlab.freedesktop.org/drm/intel/issues/1151.

**Comment by kv2019i** [comment] 2020-03-24 18:26
@mamarley Can you report this in the gitlab issue 1363? The gfx folks are not following this bug tracker.
UPDATE: aa, you already did, thanks!

**Comment by mamarley** [comment] 2020-03-24 18:28
[Already done](https://gitlab.freedesktop.org/drm/intel/issues/1363#note_443619) :)

**Comment by Liviali155** [comment] 2020-03-27 06:18
Tried with #1939,error not seen

**Comment by kv2019i** [comment] 2020-03-27 08:40
@Liviali155 wrote:
> Tried with #1939,error not seen

Excellent news, thanks a lot for the quick testing. The patch is merged upstream and I'll now proceed to merge this in sof-dev as well, so we get the fixing immediately to the audio tree.

**Closed as completed** 2020-03-27 10:19 UTC
Labels: bug, P1, GFX, TGL
