### ISSUE TITLE
Underruns while pausing/resuming HDMI playback on GLK

### ISSUE THREAD

**Issue by wwittbrx** [thesofproject/linux#761] opened 2019-03-29 11:55 UTC
### Description

Rapidly pausing and releasing playback over HDMI will cause underruns on GLK. What is interesting to me is that we don't see any errors in dmesg or sof-logger, only from aplay window. Please try to reproduce the issue and check if you can gather more meaningful logs.

### Recipe

**ChromeOS**
75.0.3746.0 (Platform 12000.0.0)

**Kernel**
https://github.com/thesofproject/linux/tree/topic/cros-sof-v4.14-rebase
d4d2c3b

**FW and TPLG**
https://github.com/thesofproject/sof/commits/master
a10e69d
sof-glk-da-7219.tplg

### Reproduction steps

1. Connect platform to monitor with HDMI
2. aplay -D hw:0,6 test.wav -i
3. Keep pressing space rapidly (or hold it) to pause and release playback

### Logs and files

[aplay-interactive.txt](https://github.com/thesofproject/linux/files/3022472/aplay-interactive.txt)
[dmesg.log](https://github.com/thesofproject/linux/files/3022473/dmesg.log)
[sof-logger.log](https://github.com/thesofproject/linux/files/3022474/sof-logger.log)

**Comment by xiulipan** [comment] 2019-04-01 03:08
@wwittbrx 
If you see some xrun in the terminal, then it is some issue cased by ALSA.
Please reference from https://github.com/thesofproject/sof/issues/231 https://github.com/thesofproject/sof/issues/506
This is some ALSA warning and ALSA handling when some XRUN happen to the buffer that controlled by ALSA. This should be caused by user space memory to kernel space memory copy issue.

You can try to reproduce it without pause/resuem but by some debug injection:
https://github.com/thesofproject/sof/issues/506#issuecomment-448918297

**Comment by mengdonglin** [comment] 2019-04-03 05:15
@wwittbrx Close the issue based on above comments. Will reopen if this impact audio quality in the future

**Closed as completed by mengdonglin** 2019-04-03 05:15 UTC
Labels: bug, P2, GLK
