### ISSUE TITLE
nuc11 has no audio 

### ISSUE THREAD

**Issue by snj33v** [thesofproject/linux#3301] opened 2021-11-30 05:43 UTC
kernel: 5.15.4-201.fc35.x86_64

forcing sof drivers makes audio devices unavailable on NUC11PAHi5

```
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 1: sofhdadsp [sof-hda-dsp], device 0: HDA Analog (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sofhdadsp [sof-hda-dsp], device 1: HDA Digital (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: sofhdadsp [sof-hda-dsp], device 3: HDMI1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: so
```
```
sof-audio-pci-intel-tgl 0000:00:1f.3: enabling device (0000 -> 0002)
[    3.898338] sof-audio-pci-intel-tgl 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if 0x040380
[    3.898398] sof-audio-pci-intel-tgl 0000:00:1f.3: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    3.904813] sof-audio-pci-intel-tgl 0000:00:1f.3: use msi interrupt mode
[    3.953207] sof-audio-pci-intel-tgl 0000:00:1f.3: hda codecs found, mask 5
[    3.953210] sof-audio-pci-intel-tgl 0000:00:1f.3: using HDA machine driver skl_hda_dsp_generic now
[    3.953213] sof-audio-pci-intel-tgl 0000:00:1f.3: DMICs detected in NHLT tables: 0
[    3.954156] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:9:2-e096c
[    3.954158] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    3.954159] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    3.954164] sof-audio-pci-intel-tgl 0000:00:1f.3: unknown sof_ext_man header type 3 size 0x30
[    4.048418] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware info: version 1:9:2-e096c
[    4.048420] sof-audio-pci-intel-tgl 0000:00:1f.3: Firmware: ABI 3:20:0 Kernel ABI 3:18:0
[    4.048421] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: FW ABI is more recent than kernel
[    4.064413] sof-audio-pci-intel-tgl 0000:00:1f.3: Topology: ABI 3:20:0 Kernel ABI 3:18:0
[    4.064415] sof-audio-pci-intel-tgl 0000:00:1f.3: warn: topology ABI is more recent than kernel
[    4.084055] sof-audio-pci-intel-tgl 0000:00:1f.3: ASoC: Parent card not yet available, widget card binding deferred
[    4.111378] snd_hda_codec_realtek ehdaudio0D0: autoconfig for ALC256: line_outs=1 (0x21/0x0/0x0/0x0/0x0) type:hp
[    4.111381] snd_hda_codec_realtek ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    4.111382] snd_hda_codec_realtek ehdaudio0D0:    hp_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    4.111382] snd_hda_codec_realtek ehdaudio0D0:    mono: mono_out=0x0
[    4.111383] snd_hda_codec_realtek ehdaudio0D0:    inputs:
[    4.111384] snd_hda_codec_realtek ehdaudio0D0:      Internal Mic=0x13
[    4.111384] snd_hda_codec_realtek ehdaudio0D0:      Internal Mic=0x12
[    4.151218] snd_hda_codec_realtek ehdaudio0D0: ASoC: sink widget AIF1TX overwritten
[    4.151222] snd_hda_codec_realtek ehdaudio0D0: ASoC: source widget AIF1RX overwritten
[    4.165281] snd_hda_codec_hdmi ehdaudio0D2: Monitor plugged-in, Failed to power up codec ret=[-13]
[    4.176357] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input13
[    4.176389] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input14
[    4.176409] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input15
[    4.176429] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card0/input16
```

**Comment by plbossart** [comment] 2021-11-30 14:45
@snj33v can you please upload the results of 'alsa-info' and provide a link to the results?

Also can you be more specific on what the problem is? Your 'aplay -l' log does show a set of devices exposed to userspace, what do you mean by 'forcing sof drivers makes audio devices unavailable'?

**Comment by snj33v** [comment] 2021-12-01 13:42
by forced load, i meant `snd_intel_dspcfg.dsp_driver=3` on kernel params

for alsa-info, https://gist.github.com/snj33v/c851bb87df395a415b73740fffb93493

**Comment by plbossart** [comment] 2021-12-01 14:10
there's nothing in the log file that hints at a problem with the SOF driver.

Can you please describe what the problem is
a) streaming to internal speakers (HDA analog) is broken
b) streaming works but no sound can be heard
c) sound can be heard but with an audible distortion.

We can't help you if you don't describe details that might help us root-cause the issue on your device.

**Comment by snj33v** [comment] 2021-12-01 14:18
>there's nothing in the log file that hints at a problem with the SOF driver.
Can you please describe what the problem is
a) streaming to internal speakers (HDA analog) is broken
b) streaming works but no sound can be heard
c) sound can be heard but with an audible distortion.

except there is no audio profiles which shows up at pulseaudio/pipewire, hence i can't select anything

might related to #2829

**Comment by snj33v** [comment] 2021-12-01 14:22
wierd thing there are mic(they are DMICs as per product sheet) that are found when legacy driver is used, but it does not up for SOF since its presence is not found in NHLT
 never able to get headphone jack work in both driver

**Comment by plbossart** [comment] 2021-12-01 14:54
@snj33v 'digital microphones' is a misleading term. You can have such digital microphones attached to the HDaudio codec or directly to the Intel PCH chipset. Only in the latter case would you have a need for NHLT (to describe the details in platform firmware) or the SOF driver to manage the microphones.

I think you should first start from the legacy driver, and figure out why the headset detection does not work. This is an HDaudio codec driver issue, not an SOF one. A working headset detection is really a prerequisite for PulseAudio/PipeWire to work.

Alternatively, you can also use the command line and direct access to hardware devices to see if the hardware works with the SOF driver (which would point to a userspace configuration isssue)

````
alsaucm -c sof-hda-dsp set _verb HiFi set _enadev Speaker (or Speakers, don't remember)
speaker-test -Dhw:0,0 -c2 -r48000
````

if no sound comes out you'll probably have to check with alsamixer if something was missed in the UCM files.

**Comment by snj33v** [comment] 2021-12-01 15:38
```
alsaucm -c sof-hda-dsp set _verb HiFi set _enadev Headphones
speaker-test -Dhw:0,0 -c2 -r48000
```
i can hear sound from above commands 😀

>. You can have such digital microphones attached to the HDaudio codec or directly to the Intel PCH chipset. Only in the latter case would you have a need for NHLT (to describe the details in platform firmware) or the SOF driver to manage the microphones.

this is this block diagram from nuc 11
![block](https://user-images.githubusercontent.com/1472475/144264640-0a3b69b7-3aeb-485c-adbb-ff371f54d460.png)

**Comment by plbossart** [comment] 2021-12-01 16:30
I checked with my Intel colleagues and the mic array is connected to the ALC256 HDaudio codec, The dotted line to the PCH does not exist in practice.

So basically I think your problem is that because headset detection does not work, neither PulseAudio nor PipeWire enable the profile. Enabling the profile by hand works.

I see this in the kernel code (sound/pci/hda/patch_realtek.c)

````c
ALC256_FIXUP_INTEL_NUC10,

	[ALC256_FIXUP_INTEL_NUC10] = {
		.type = HDA_FIXUP_PINS,
		.v.pins = (const struct hda_pintbl[]) {
			{ 0x19, 0x01a1913c }, /* use as headset mic, without its own jack detect */
			{ }
		},
		.chained = true,
		.chain_id = ALC269_FIXUP_HEADSET_MODE
	},
````

Maybe we need the same for NUC11?

This is a bit beyond my area of expertise, we'll likely have to ask @tiwai and/or the Realtek team. @shumingfan can you point us to the ALC256 support. It think it's Kailang but I can't find the github user name.

**Comment by snj33v** [comment] 2021-12-01 16:54
>Maybe we need the same for NUC11?

think its  similar and mostly a userspace configuration issue, but thanks for looking into this 

few observations, 
1. able to do speaker-test, on all outputs such as jack, HDMI audio sources,
2. microphone[all four mic array, not the headphones] actually works if directly use it from alsa,

**Comment by plbossart** [comment] 2022-06-29 20:22
HDaudio codec issue and no update since December 2021, closing

**Closed as completed by plbossart** 2022-06-29 20:22 UTC
Labels: codec, Community
