### ISSUE TITLE
[FEATURE] Add support for virtualised Audio

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/linux#1023] opened 2019-06-11 12:58 UTC
@lyakh This ones for you, after IPC and IRQ. It's a big ticket item, where parts will be used in generic ALSA VM support.

The SOF driver should be able to play and capture audio in a VM. i.e. consider a hypervisor topology with 4 VMs made up of 3 guest VMs (Guest OS - GOS) and 1 Service VM (Service OS - SOS). Each GOS and the SOS must be able to have a unique topology and play/capture audio without interference from the other VMs.

The  SOS VM has access to the physical HW and hence it's SOF driver (called the SOF Virtual Back End - VBE) will perform all IO with the DSP directly (as it does today on non VM systems). The GOS VMs have no access to HW, so their SOF drivers (called Virtual Front End) will use a virtual mailbox and doorbell to send all IPC to the SOF VBE driver instead of the DSP. The SOF VBE driver will then validate and forward the VFE IPC to the DSP.

The SOF VBE driver will only create virtual HW for a generic mailbox and doorbell in order for GOS VFE to perform IPC to/from. There will be no virtualised DMA, DAIs, codecs, etc.

There will also be zero copy audio data between GOS and SOS HW. This will be achieved by each GOS VFE allocating DMA buffers and then passing the PHY SG pages to the SOS for programming into DMA HW. Buffer management should also allow for cache writeback or invalidation where needed. i.e. on ARM systems.

There is already some working concept code on SOF linux repository, but this needs cleaned up and forward ported to HEAD.

Additionally, VFE SOF drivers and VBE SOF driver should also be able to support non audio uses via MFD. See https://github.com/thesofproject/linux/issues/1032

**Comment by lyakh** [comment] 2019-09-20 14:39
Update:
Status: playback working, but multiple low to moderate severity workarounds and shortcuts have been used.
Code: https://github.com/lyakh/linux/tree/virtio-wip-5_3 https://github.com/lyakh/sof/tree/virtio-wip with a patch for the ACRN hypervisor [acrn.gitdiff.txt](https://github.com/thesofproject/linux/files/3636409/acrn.gitdiff.txt)
Remaining work:
- implement capture
- remove ACRN APIs, port to pure VirtIO
- clean up and upstream

**Comment by lyakh** [comment] 2019-11-04 07:54
Update:
Status: playback and capture now working, using only VirtIO and vhost APIs, no additional ACRN dependencies. So far only used on top of ACRN. Zero-copy with vhost doesn't seem to be working with ACRN, therefore this implementation transfers data over virtual queues.

**Comment by lyakh** [comment] 2019-12-16 13:30
Status: playback and capture now working on top of QEMU / KVM with supporting patched for QEMU. Many improvements and fixes, the current work is tracked in https://github.com/thesofproject/linux/pull/1501 and is being actively reviewed for an upstream submission.

HowTo test:
- Create a VM on any machine. The easiest way to create a VM is by using the
  virt-manager. Just use the GUI to create a new Linux VM and install Ubuntu on
  it. You can do it on any machine because you'll only need the hard-drive image
  to run QEMU from the command line.

- To run SOF on the new VM the QEMU has to be patched and recompiled from the
  upstream tree: https://git.qemu.org/git/qemu.git

  I used the v4.1.0 tag. Patches are attached. I actually also ran the "make
  install" step locally on the host, so, I had to build QEMU natively on the
  device, in my case the Up^2.

- The qemu "./configure" command line, from a separate build directory:
```
../qemu/configure --target-list=x86_64-softmmu --enable-kvm --enable-vhost-kernel --enable-vhost-dsp --enable-vhost-net --enable-system --enable-spice --enable-usb-redir --enable-libusb --audio-drv-list=oss,alsa,pa --enable-libssh --enable-gnutls --enable-replication --enable-seccomp --prefix=/usr
```
- The exact set of Ubuntu packages, required to build and run QEMU is at the
  moment unknown, because for initial deployment QEMU and virt-manager were
  installed on the target system from packages, which brought a lot of
  auxiliary packages with them. It is helpful to have the libvirt-daemon
  package installed. On the test system it also installs dnsmasq and
  automatically configures a "virtbr0" bridge and a "virbr0-nic" tap interfaces
  on start up, otherwise commands to create such interfaces manually can be
  added to the script.

- Patch and build the firmware and a host and a guest topology images. The
  firmware tree is based off commit decd2064607d74106dc176bfd04a4f4a4e584eba,
  but newer commits should work too. The used topology files are:
```
cp sof-apl-pcm512x-sos.tplg /lib/firmware/intel/sof-tplg/sof-apl-pcm512x.tplg
cp sof-apl-pcm512x-uos.tplg /lib/firmware/intel/sof-tplg/sof-apl-uos0.tplg
```
- Use https://github.com/lyakh/linux/tree/virtio-core for both the host and the
  guest kernels. Sample configurations are attached.

- Build and install a new kernel for the host.

- Boot the VM from the command line, using the attached script.

- Build and install a new kernel for the guest. This is done in exactly the same
  way as natively: install a bzImage under /boot/, install kernel modules under
  /lib/modules/, create an initramfs image and update the grub2 configuration.

- Boot the guest with the new kernel. From this moment both the host and the
  guest should each have a single playback and a single capture PCM and be
  able to play and record audio.

- You can connect to the VM's UI from your development PC over VNC, e.g. by
  using
```
gvncviewer <up2-ip-address>:1
```
[virtio-sof.zip](https://github.com/thesofproject/linux/files/3968255/virtio-sof.zip)

**Comment by lgirdwood** [comment] 2019-12-16 13:34
@lyakh I'm not seeing the attached script or kconfigs here.

**Comment by lyakh** [comment] 2019-12-16 13:39
@lgirdwood now there is one

**Comment by lyakh** [comment] 2019-12-18 14:01
Update: an updated version of Linux patches has been pushed today. Among multiple improvements it removes changes to bxt_pcm512x.c which also requires removing respective changes from the firmware. Therefore I'm attaching a new archive to this update. Otherwise firmware changes can also be tracked on https://github.com/lyakh/sof/tree/virtio-wip but the branch lacks an additional uncommitted diff, included with the attached archive. Similarly an SOF QEMU tree is available at https://github.com/lyakh/qemu/tree/sof-wip 
[virtio-sof.zip](https://github.com/thesofproject/linux/files/3978691/virtio-sof.zip)

**Comment by lyakh** [comment] 2020-02-21 17:19
Update: attaching an archive with prebuilt qemu, firmware and topology images, 2 kernel configuration files and a QEMU launch script
[sof-virtio.zip](https://github.com/thesofproject/linux/files/4237222/sof-virtio.zip)

**Comment by plbossart** [comment] 2020-02-21 19:08
@lyakh Can you provide an updated host-defconfig and guest-defconfig that are incremental fragments? We don't want an entire defconfig, just what's needed on top of the baseline. Thank you!

**Comment by lgirdwood** [comment] 2020-02-26 14:07
@lyakh any chance you can create a sof-docs page describing all the steps needed to get things up and running (i.e. that were used to get your zip file demo working).

**Comment by lyakh** [comment] 2020-02-27 11:24
> @lyakh Can you provide an updated host-defconfig and guest-defconfig that are incremental fragments? We don't want an entire defconfig, just what's needed on top of the baseline. Thank you!

@plbossart https://github.com/thesofproject/kconfig/pull/26

**Comment by lyakh** [comment] 2020-02-27 11:31
> @lyakh any chance you can create a sof-docs page describing all the steps needed to get things up and running (i.e. that were used to get your zip file demo working).

@lgirdwood I never used my .zip for creating a VirtIO SOF configuration from scratch. In fact I never tried that after I've created my original working one. We anyway need someone else to reproduce my result and during that he or she would test and update the documentation and possibly the .zip. Alternatively I can propose the following: I don't want to "virtualise" my second Up2 too nor to break the currently working one to test the process. Instead I could try to repeat the process on my Mantis laptop. In the process I'll probably need to at least adjust the host topology, but since my current topology is minimal the change should be small too. Should I do that or do we want someone else to test? @plbossart wanted to test but last time we talked about that was a few days back...

**Comment by lgirdwood** [comment] 2020-02-27 21:07
@lyakh I mean a set of instructions that should be carried out to for anyone to use or test your code. e.g.
```
1) Build host kernel with config xxx
2) build guest kernel with config xxx
3) build qemu with config xxx
4) etc ......
```

**Comment by lyakh** [comment] 2020-02-27 21:37
> @lyakh I mean a set of instructions that should be carried out to for anyone to use or test your code. e.g.
> 
> ```
> 1) Build host kernel with config xxx
> 2) build guest kernel with config xxx
> 3) build qemu with config xxx
> 4) etc ......
> ```

@lgirdwood I understand what you mean. The only problem is - to write such a list I have to do all those steps myself again. The initial development process, of course, wasn't linear. You do 1, then you do 2a, then you see that that doesn't work, so you try 2b, etc. So, I have written an *approximate* such sequence on this exact page: https://github.com/thesofproject/linux/issues/1023#issuecomment-566061624 but to make an official document it has to be exact. That's why I'm considering what's best: either I take a new system and actually recreate a linear flow to achieve the desired state, or someone, who anyway tests my work, can just use those approximate notes and my interactive help to reproduce the result and simultaneously to document it.

**Comment by lgirdwood** [comment] 2020-03-02 11:06
@lyakh interactive help doesn't scale. There are 3 main things to build
1) Guest kernel
2) Host kernel
3) Qemu.
The VM disc image and installing guest kernel can be left out (since it can differ depending on guest).
The only other important things are
4) host kernel config (where to install host/guest topologies).
5) Qemu command line.
That should be all that's needed. I'm not asking for command line on how to install a kernel, or build a disc image, we just need the steps above. e.g. command lines for 1 above
```
1.1) Clone kconfig repo.
1.2) copy config X from kconfig repo to Linux dir
1.3) build kernel binaries
```
You can then state that the kernel should then be installed on guest VM.
And so on....

**Comment by lyakh** [comment] 2020-03-03 15:08
@lgirdwood also the firmware and 2 topologies. And yes all that is described on this page. There's also a .zip with QEMU, topology and firmware binaries to make the kick off easier. Also there's a qemu launch script. The command line is long with many options and you also have to prepare network bridging on the system.
Sure, I can do an .rst but it won't work anyway - you don't want references to open PRs or my private branches there and as long as
https://github.com/thesofproject/sof/pull/2376
https://github.com/thesofproject/kconfig/pull/26
https://github.com/thesofproject/linux/pull/1501
https://github.com/thesofproject/sof/pull/2428
aren't merged, you cannot build from SOF sources.

**Comment by lyakh** [comment] 2020-03-03 17:15
@lgirdwood done https://github.com/thesofproject/sof-docs/pull/190

**Comment by plbossart** [comment] 2022-07-25 23:55
There's no real plans to push this further, closing.

**Closed as not planned by plbossart** 2022-07-25 23:55 UTC
Labels: enhancement, Notable
