### ISSUE TITLE
"Kernel Panic" run 'soft/kmod_scripts/sof_bootone.sh', the second time will cause kernel panic on BYT with nocodec tplg

### ISSUE THREAD

**Issue by ghost** [thesofproject/linux#73] opened 2018-08-10 06:57 UTC
System Environment:
Kernel repo: topic/sof-dev:  2de67aacaa795ed216b176dbee799f0ec18d6403
soft repo: topic/master: cfff9e0b0402f0f7dd2bd9ba915fd6d1599b2fc8
using tplg: test-ssp2-mclk-0-I2S-volume-s16le-s16le-48k-19200k-nocodec.tplg

Reproduce step:
run the "soft/kmod_scripts/sof_bootone.sh" script, that means do the module reload one time.
the first time, it is ok after with the PR #72 .
but the second time. this kernel will hit panic.

before the 219f401431628b1c330bcae61bfc84a17543fc2e commit and with PR#72
there is no panic during the 100 reload module test.

[dmesg.txt](https://github.com/thesofproject/linux/files/2276894/dmesg.txt)

**Comment by ghost** [comment] 2018-08-14 02:19
the PR #80 can fix part of them. there still has panic after merge the PR #80 and PR #72 .

**Comment by ghost** [comment] 2018-08-14 09:05
the PR #80 and PR #72 can fix this kind of kernel panic issue already.

**Comment by mengdonglin** [comment] 2018-09-18 07:14
@ZhendanYang Could you help to check if this issue can still be reproduced?
Per Zhigang's comment, the fixes were merged.

**Comment by ZhendanYang** [comment] 2018-09-19 06:42
Can't reproduce on BYT with latest code base. Will add test into daily test and reopen this issue once reproduce.

**Closed as completed by ZhendanYang** 2018-09-19 06:42 UTC
Labels: bug, P3, BYT
