### ISSUE TITLE
[BUG][BYT] IPC error on playback

### ISSUE THREAD

**Issue by plbossart** [thesofproject/linux#2499] opened 2020-10-12 18:25 UTC
report from @jwrdegoede

"I plugged in a headset and ran GNOME's control panel sound test,
that worked. Then I tried playing back the earlier recording from
the internal mic to test if was proper stereo (same sound on both
channels) or if one channel was silent, so I played it inside
gnome-sound-recorder and then tried playing it again after removing
on of the ear-pieces from my ear so that I could check both samples
separately. When I tried to play the recording a second time
gnome-sound-recorder seems to hang and in dmesg I see [this log]
"

````
[  498.439725] sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60050000 size 12
[  498.439757] sof-audio-acpi 80860F28:00: info: preventing DSP entering D3 state to preserve context
[  498.439844] sof-audio-acpi 80860F28:00: error: unexpected fault 0x600a0001 trace 0x00000000
[  498.439871] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x8000000000000000
[  498.439894] sof-audio-acpi 80860F28:00: error: mask host: pending no complete no raw 0x0
[  498.439917] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete yes raw 0x600a0001
[  498.439940] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0
[  498.439962] sof-audio-acpi 80860F28:00: error: waking up any trace sleepers
[  498.439991] sof-audio-acpi 80860F28:00: ASoC: error at snd_soc_pcm_component_trigger on 80860F28:00: -110
[  498.440014]  Low Latency: ASoC: trigger FE cmd: 0 failed: -110
[  498.943980] sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60030000 size 12
[  498.944012] sof-audio-acpi 80860F28:00: info: preventing DSP entering D3 state to preserve context
[  498.944099] sof-audio-acpi 80860F28:00: error: unexpected fault 0x600a0001 trace 0x00000000
[  498.944228] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x8000000000000000
[  498.944255] sof-audio-acpi 80860F28:00: error: mask host: pending no complete no raw 0x0
[  498.944278] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete yes raw 0x600a0001
[  498.944301] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0
[  498.944323] sof-audio-acpi 80860F28:00: error: waking up any trace sleepers
[  498.944361] sof-audio-acpi 80860F28:00: ASoC: error at snd_soc_pcm_component_hw_free on 80860F28:00: -110
[  499.463749] sof-audio-acpi 80860F28:00: error: ipc timed out for 0x60050000 size 12
[  499.463781] sof-audio-acpi 80860F28:00: info: preventing DSP entering D3 state to preserve context
[  499.463867] sof-audio-acpi 80860F28:00: error: unexpected fault 0x600a0001 trace 0x00000000
[  499.463894] sof-audio-acpi 80860F28:00: error: ipc host -> DSP: pending no complete no raw 0x8000000000000000
[  499.463918] sof-audio-acpi 80860F28:00: error: mask host: pending no complete no raw 0x0
[  499.463941] sof-audio-acpi 80860F28:00: error: ipc DSP -> host: pending no complete yes raw 0x600a0001
[  499.463963] sof-audio-acpi 80860F28:00: error: mask DSP: pending no complete no raw 0x0
[  499.463985] sof-audio-acpi 80860F28:00: error: waking up any trace sleepers
[  499.464013] sof-audio-acpi 80860F28:00: ASoC: error at snd_soc_pcm_component_trigger on 80860F28:00: -110
[  499.464037]  Low Latency: ASoC: trigger FE cmd: 0 failed: -110 
````

**Comment by jwrdegoede** [comment] 2020-10-13 12:38
Small correction, my testing went like this:

1. Install fresh Fedora 33 + home-build latest 5.9-rc8 kernel with SOF enabled for Bay Trail devices.
2. Fix a Kconfig related issue, reboot, now the mono-speaker works.
3. Make a recording of the internal mic. with gnome-sound-recorder seems to work.
4. Turn machine off
5. Later that day boot machine again to run more tests.
6. Open gnome control-panel sound capplet, plug in headset, watch default output/input change to headset
7. Test headphones part of headset with control-panel speaker test function.
7. Now that I have stereo output capability, check if mic. recording is correctly recorded on both channels (I have seen cases where there is only audio recorded in the left channel). Open gnome-sound-recorder listen to recording with headphones
8. Ok sounds stereo, but not 100% sure, try listening one earpiece at a time. Remove 1 earpiece from my ears, press play on recording in gnome-sound-recorder for a second time.
9. Pressing play does not work, get above dmesg messages

Notice that the machine was turned off between the recording and the playback, so the issue is not with playback after recording, it is likely an issue with playback in general.

**Comment by jwrdegoede** [comment] 2020-10-13 12:38
p.s. could it be that Fedora 33 does not have the latest SOF firmware files for BYT ? How do I check this ?

**Comment by plbossart** [comment] 2020-10-13 15:18
thanks @jwrdegoede for the updated explanation.

In theory dmesg provides a log of the firmware version, but I can't recall if this is only with dynamic debug. You may need

````
options snd_sof_intel_byt dyndbg=+p
options snd_sof dyndbg=+p
options snd_sof_acpi dyndbg=+p
options snd_intel_dspcfg dyndbg=+p
````

**Comment by plbossart** [comment] 2020-10-13 15:19
if you have sof-logger installed, the first trace also dumps all the information, e.g. on a CHT machine

````
sof-logger -l /etc/sof/sof-cht.ldc 
         TIMESTAMP              DELTA C# COMPONENT          LOCATION                      CONTENT
[49949879003.906250] (             nan) c0 dma-trace             src/trace/dma-trace.c:327  ERROR FW ABI 0x3012000 DBG ABI 0x5002001 tag v1.5-rc1-778-ge5d17f3c10f3 src hash 0xa3b71c81 (ldc hash 0xa3b71c81)
[49949879003.906250] (        0.000000) c0 dma-trace             src/trace/dma-trace.c:327  ERROR FW ABI 0x3012000 DBG ABI 0x5002001 tag v1.5-rc1-778-ge5d17f3c10f3 src hash 0xa3b71c81 (ldc hash 0xa3b71c81)
root@Zotac:~/sof-test/test-case# 

````

**Comment by jwrdegoede** [comment] 2020-10-14 10:57
So I checked what version the Fedora alsa-sof-firmware packages have and they are based on the 1.5 release.

Where as:
https://github.com/thesofproject/sof-bin/

Has a 1.5.1 release out, as well as a 1.6 release, although that is marked as 1.6-rc3 in the commit adding the binaries, which I find somewhat confusing:
https://github.com/thesofproject/sof-bin/commit/b03c48b12bfb025d2415529667f038d4cfa22f4d

I guess that for the BYT/CHT testing I'm doing it will be best to use the 1.6 binaries, so I will switch to those. I will also install sof-logger so that I can get a trace if I hit another hang.

**Comment by plbossart** [comment] 2020-10-14 19:52
@jwrdegoede it's quite possible indeed that you saw a bug that existed in a previous version, there were quite a few fixes added by @lyakh over the Summer.

Based on initial results I believe however that it's not realistic to switch to SOF in the coming weeks, we have to test more to avoid impacting users.

**Closed as completed** 2022-06-29 19:50 UTC
Labels: bug, won't fix, P3, BYT
