### ISSUE TITLE
[BUG][GLK]Shows I/O error when pause arecord then resume. 

### ISSUE THREAD

**Issue by YvonneYang2** [thesofproject/linux#1022] opened 2019-06-11 07:48 UTC
**Describe the bug**
System shows I/O error when pause arecord then resume. All arecord can reproduce the issue.

**To Reproduce**
1.Arecord via "arecord -Dhw:0,1 -r48000 -c2 -fs16_le 1.wav -vv -i"
2.Pause arecord
3.Resume asrecord

**frequency**

100%

**Expected result**
Arecord resumed normally.

**Actual result**
Shows I/O error "arecord:pcm_read:2103:read error:Input/Output error"

**Environment**
Firmware: c0c858c https://github.com/thesofproject/sof/commits/master
Kernel: a50a20a https://github.com/thesofproject/linux/commits/topic/sof-dev
Topology: file: tools/topology/sof-glk-da7219.tplg same as firmware
platform： GLK

**dmesg**
```
[    0.767937] hub 1-0:1.0: 9 ports detected
[    0.768371] xhci_hcd 0000:00:15.0: xHCI Host Controller
[    0.768424] xhci_hcd 0000:00:15.0: new USB bus registered, assigned bus number 2
[    0.768428] xhci_hcd 0000:00:15.0: Host supports USB 3.0  SuperSpeed
[    0.768476] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.02
[    0.768477] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.768479] usb usb2: Product: xHCI Host Controller
[    0.768480] usb usb2: Manufacturer: Linux 5.2.0-rc1-daily-20190611 xhci-hcd
[    0.768481] usb usb2: SerialNumber: 0000:00:15.0
[    0.769093] hub 2-0:1.0: USB hub found
[    0.769112] hub 2-0:1.0: 7 ports detected
[    0.780974] checking generic (b0000000 300000) vs hw (b0000000 10000000)
[    0.780975] fb0: switching to inteldrmfb from EFI VGA
[    0.781003] Console: switching to colour dummy device 80x25
[    0.781096] i915 0000:00:02.0: vgaarb: deactivate vga console
[    0.832141] [drm] couldn't get memory information
[    0.832142] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    0.832143] [drm] Driver supports precise vblank timestamp query.
[    0.832189] i915 0000:00:02.0: vgaarb: changed VGA decodes: olddecodes=io+mem,decodes=io+mem:owns=io+mem
[    0.832642] [drm] Finished loading DMC firmware i915/glk_dmc_ver1_04.bin (v1.4)
[    0.846239] [drm] Initialized i915 1.6.0 20190417 for 0000:00:02.0 on minor 0
[    0.848682] fbcon: i915drmfb (fb0) is primary device
[    0.861103] Console: switching to colour frame buffer device 170x57
[    0.877273] mmc0: Command Queue Engine enabled
[    0.877278] mmc0: new HS400 MMC card at address 0001
[    0.878289] mmcblk0: mmc0:0001 hC8aP> 58.2 GiB 
[    0.878387] mmcblk0boot0: mmc0:0001 hC8aP> partition 1 4.00 MiB
[    0.878484] mmcblk0boot1: mmc0:0001 hC8aP> partition 2 4.00 MiB
[    0.878525] mmcblk0rpmb: mmc0:0001 hC8aP> partition 3 16.0 MiB, chardev (245:0)
[    0.880112]  mmcblk0: p1 p2
[    0.880450] i915 0000:00:02.0: fb0: i915drmfb frame buffer device
[    0.899820] random: fast init done
[    0.903196] systemd-udevd (144) used greatest stack depth: 13048 bytes left
[    0.903398] systemd-udevd (142) used greatest stack depth: 13000 bytes left
[    0.903577] systemd-udevd (146) used greatest stack depth: 12552 bytes left
[    1.090743] usb 1-4: new high-speed USB device number 2 using xhci_hcd
[    1.106597] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.217831] usb 1-4: New USB device found, idVendor=05e3, idProduct=0608, bcdDevice=85.36
[    1.217833] usb 1-4: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    1.217834] usb 1-4: Product: USB2.0 Hub
[    1.218451] hub 1-4:1.0: USB hub found
[    1.218721] hub 1-4:1.0: 4 ports detected
[    1.227298] systemd[1]: systemd 237 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    1.239856] systemd[1]: Detected architecture x86-64.
[    1.241149] systemd[1]: Set hostname to <test-Bobba>.
[    1.278137] systemd-gpt-auto-generator[206]: Failed to dissect: Input/output error
[    1.280575] systemd[199]: /lib/systemd/system-generators/systemd-gpt-auto-generator failed with exit status 1.
[    1.286067] systemd[1]: File /lib/systemd/system/systemd-journald.service:36 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[    1.286072] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[    1.334738] usb 1-7: new high-speed USB device number 3 using xhci_hcd
[    1.346799] random: systemd: uninitialized urandom read (16 bytes read)
[    1.347066] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    1.347131] random: systemd: uninitialized urandom read (16 bytes read)
[    1.347143] systemd[1]: Reached target User and Group Name Lookups.
[    1.347158] random: systemd: uninitialized urandom read (16 bytes read)
[    1.347292] systemd[1]: Created slice User and Session Slice.
[    1.347402] systemd[1]: Created slice System Slice.
[    1.369389] EXT4-fs (mmcblk0p2): re-mounted. Opts: errors=remount-ro
[    1.433518] systemd-journald[218]: Received request to flush runtime journal from PID 1
[    1.434882] Adding 2097148k swap on /swapfile.  Priority:-2 extents:6 across:2260988k SS
[    1.441267] systemd-journald[218]: File /var/log/journal/ff7b7499f99742c5b2c0cc58e322156f/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    1.470254] usb 1-7: New USB device found, idVendor=04f2, idProduct=b567, bcdDevice=32.69
[    1.470256] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.470258] usb 1-7: Product: HD WebCam
[    1.470260] usb 1-7: Manufacturer: Chicony Electronics Co.,Ltd.
[    1.526742] usb 1-4.1: new high-speed USB device number 4 using xhci_hcd
[    1.594176] proc_thermal 0000:00:00.1: Creating sysfs group for PROC_THERMAL_PCI
[    1.597384] Intel(R) Wireless WiFi driver for Linux
[    1.597386] Copyright(c) 2003- 2015 Intel Corporation
[    1.621796] usb 1-4.1: New USB device found, idVendor=0b95, idProduct=7720, bcdDevice= 0.01
[    1.621799] usb 1-4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    1.621800] usb 1-4.1: Product: AX88772A
[    1.621802] usb 1-4.1: Manufacturer: ASIX Elec. Corp.
[    1.621803] usb 1-4.1: SerialNumber: 00044E
[    1.634975] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-46.ucode failed with error -2
[    1.634994] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-45.ucode failed with error -2
[    1.635003] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-44.ucode failed with error -2
[    1.635012] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-43.ucode failed with error -2
[    1.635021] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-42.ucode failed with error -2
[    1.635030] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-41.ucode failed with error -2
[    1.635039] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-40.ucode failed with error -2
[    1.635047] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-39.ucode failed with error -2
[    1.635056] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-38.ucode failed with error -2
[    1.635065] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-37.ucode failed with error -2
[    1.635074] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-36.ucode failed with error -2
[    1.635082] iwlwifi 0000:00:0c.0: Direct firmware load for iwlwifi-9000-pu-b0-jf-b0-35.ucode failed with error -2
[    1.646965] iwlwifi 0000:00:0c.0: loaded firmware version 34.0.0 op_mode iwlmvm
[    1.650917] sof-audio-pci 0000:00:0e.0: PCI DSP detected
[    1.651166] sof-audio-pci 0000:00:0e.0: DSP detected with PCI class/subclass/prog-if 0x040100
[    1.651221] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0xc00
[    1.651223] sof-audio-pci 0000:00:0e.0: found ML capability at 0xc00
[    1.651227] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x800
[    1.651228] sof-audio-pci 0000:00:0e.0: found DSP capability at 0x800
[    1.651231] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x500
[    1.651232] sof-audio-pci 0000:00:0e.0: found GTS capability at 0x500
[    1.651235] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x1f00
[    1.651236] sof-audio-pci 0000:00:0e.0: found DRSM capability at 0x1f00
[    1.651239] sof-audio-pci 0000:00:0e.0: checking for capabilities at offset 0x700
[    1.651240] sof-audio-pci 0000:00:0e.0: found SPIB capability at 0x700
[    1.651247] sof-audio-pci 0000:00:0e.0: DMA mask is 64 bit
[    1.651251] sof-audio-pci 0000:00:0e.0: hda global caps = 0x1006701
[    1.651253] sof-audio-pci 0000:00:0e.0: detected 6 playback and 7 capture streams
[    1.651309] sof-audio-pci 0000:00:0e.0: use msi interrupt mode
[    1.651310] sof-audio-pci 0000:00:0e.0: using HDA IRQ 128
[    1.657639] iwlwifi 0000:00:0c.0: Detected Intel(R) Dual Band Wireless AC 9560, REV=0x318
[    1.684985] sof-audio-pci 0000:00:0e.0: using IPC IRQ 128
[    1.685986] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000044
[    1.685988] sof-audio-pci 0000:00:0e.0: PP capability, will probe DSP later.
[    1.686002] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000040 at  00000048
[    1.686005] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000048
[    1.690966] sof-audio-pci 0000:00:0e.0: codec_mask = 0x4
[    1.690986] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000048
[    1.690989] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000040 at  00000048
[    1.691054] sof-audio-pci 0000:00:0e.0: bound 0000:00:02.0 (ops vgt_balloon_space [i915])
[    1.691056] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power on
[    1.695502] sof-audio-pci 0000:00:0e.0: hda codecs found, mask 4
[    1.695642] sof-audio-pci 0000:00:0e.0: HDA codec #2 probed OK: response: 8086280d
[    1.696183] sof-audio-pci 0000:00:0e.0: Turning i915 HDAC power off
[    1.710514] sof-audio-pci 0000:00:0e.0: loading firmware
[    1.711464] iwlwifi 0000:00:0c.0: base HW address: 48:a4:72:af:23:50
[    1.721821] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000002 at  00000048
[    1.721827] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000000 at  00000048
[    1.721831] sof-audio-pci 0000:00:0e.0: Debug PCIR: 00000000 at  00000044
[    1.721834] sof-audio-pci 0000:00:0e.0: Debug PCIW: 00000004 at  00000044
[    1.721835] sof-audio-pci 0000:00:0e.0: booting DSP firmware
[    1.721892] sof-audio-pci 0000:00:0e.0: period_bytes:0x0
```
[Arecord_IOError_dmesg.log](https://github.com/thesofproject/linux/files/3275287/Arecord_IOError_dmesg.log)
[Arecord_IOError_logger.log](https://github.com/thesofproject/linux/files/3275288/Arecord_IOError_logger.log)

**Comment by Jiangxinx** [comment] 2019-06-11 08:23
This issue also exist in BYT rt5651 and nocodec platform.

**Comment by fredoh9** [comment] 2019-06-13 01:04
I have same problems on all of capture pipeline. Pause command worked but when resume command is issued this error returned.
>arecord: pcm_read:2143: read error: Input/output error
no error in kernel dmesg.

**Comment by fredoh9** [comment] 2019-06-17 22:26
I am able to reproduce the same error in BYT NOCODEC mode also.
For the other platforms on HDA mode(CFL and ICL), I don't see this error.

**Comment by ranj063** [comment] 2019-06-18 06:05
@Jiangxinx are you sure this problem still exists on BYT with rt5651? I couldnt reproduce it with the latest sof-dev and sof master

**Comment by ranj063** [comment] 2019-06-18 06:13
I can reproduce it after a few pause/releases on BYT. It looks like a overrun issue in the FW.

**Comment by Jiangxinx** [comment] 2019-06-18 06:14
@ranj063 Yes, I can still reproduce this issue on BYT rt5651.
Please keep pressing the tab key (Pause/Resume) while do arecord testing, then, you can see the "Input/Output error".

**Comment by ranj063** [comment] 2019-06-18 06:19
@Jiangxinx this should be a FW issue. Could you please close this one and re-open as a SOF issue?

**Comment by ranj063** [comment] 2019-06-18 17:33
replaced with https://github.com/thesofproject/sof/issues/1578

**Closed as completed by ranj063** 2019-06-18 17:33 UTC
Labels: bug, P1, BYT, GLK
